### ISSUE TITLE
Official systemd support

### ISSUE THREAD

**Issue by HLFH** [ngoduykhanh/PowerDNS-Admin#1]
Hi,

It would be great to get official systemd support with a powerdns-admin.service file.
Really nice WebUI btw.

Thanks in advance,
HLFH

**Comment by ngoduykhanh** [comment]
Hi @HLFH ,

You can run it in several ways. I would recommend using `systemd` or `supervisord`. For `systemd` script, please find the example below

`$ sudo vim /etc/systemd/system/powerdns-admin.service`
```
[Unit]
Description=PowerDNS-Admin
After=network.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/opt/web/powerdns-admin/run.py
WorkingDirectory=/opt/web/powerdns-admin
Environment="PATH=/opt/web/powerdns-admin"

[Install]
WantedBy=multi-user.target
```

**Comment by HLFH** [comment]
Thanks!

**Comment by c0fe** [comment]
Confirmed working on Ubuntu 16.04
