### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by blackyzero** [ngoduykhanh/PowerDNS-Admin#100]
Hello,

I am getting stuck at create_db step, error as below:
`./pdnsa/create_db.py 
/var/www/pdns.oios.org/flask/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
/var/www/pdns.test.com/flask/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
INFO: Wait for database server`

Check database, tables exists, but not sure if they are created correctly.
`Database changed
MariaDB [powerdnsadmin]> show tables;
+-------------------------+
| Tables_in_powerdnsadmin |
+-------------------------+
| domain                  |
| domain_setting          |
| domain_user             |
| history                 |
| role                    |
| setting                 |
| user                    |
+-------------------------+
7 rows in set (0.00 sec)

MariaDB [powerdnsadmin]> select * from role;
+----+---------------+---------------+
| id | name          | description   |
+----+---------------+---------------+
|  1 | Administrator | Administrator |
|  2 | User          | User          |
+----+---------------+---------------+
2 rows in set (0.00 sec)

MariaDB [powerdnsadmin]> select * from setting;
+----+---------------------------+-------+
| id | name                      | value |
+----+---------------------------+-------+
|  1 | maintenance               | False |
|  2 | fullscreen_layout         | True  |
|  3 | record_helper             | True  |
|  4 | login_ldap_first          | True  |
|  5 | default_record_table_size | 15    |
|  6 | default_domain_table_size | 10    |
+----+---------------------------+-------+
6 rows in set (0.00 sec)

MariaDB [powerdnsadmin]> select * from domain;
Empty set (0.00 sec)

MariaDB [powerdnsadmin]> select * from domain_setting;
Empty set (0.00 sec)

MariaDB [powerdnsadmin]> select * from history;
Empty set (0.00 sec)

MariaDB [powerdnsadmin]> select * from user;
Empty set (0.00 sec)

MariaDB [powerdnsadmin]>`

Please advise how to fix the issue.
Thank you.

**Comment by ngoduykhanh** [comment]
@blackyzero : as I can see from your output, they are just warning message. The tables were created properly. Let go a head with signing up step.

**Comment by blackyzero** [comment]
thanks @ngoduykhanh 
I tried to add new domain, and receive following error:

`/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
INFO: Wait for database server
ERROR: Couldn't connect to database server
root@blue:/var/www/testdomain.com/adns# ./create_db.py 
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
INFO: Wait for database server
root@blue:/var/www/testdomain.com/adns# ./run.py 
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
[INFO]  * Running on http://192.168.200.57:9393/ (Press CTRL+C to quit)
[INFO]  * Restarting with stat
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
/var/www/testdomain.com/adns/flask/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
[WARNING]  * Debugger is active!
[INFO]  * Debugger pin code: 283-231-269
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET / HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/plugins/iCheck/square/blue.css HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/dist/css/AdminLTE.min.css HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/plugins/jQuery/jQuery-2.2.0.min.js HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:27:56] "GET /static/adminlte2/plugins/iCheck/icheck.min.js HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:01] "GET /static/adminlte2/plugins/iCheck/square/blue@2x.png HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:01] "GET /static/adminlte2/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:01] "GET /favicon.ico HTTP/1.1" 302 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:01] "GET /error/404 HTTP/1.1" 404 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:05] "GET /register HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:28:47] "POST /login HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "POST /login HTTP/1.1" 302 -
[ERROR] Can not update domain table.While fetching http://192.168.200.57:8081/servers/localhost/zones: 
[ERROR] Can not get server statistics.
[DEBUG] Traceback (most recent call last):
  File "/var/www/testdomain.com/adns/app/models.py", line 1090, in get_statistic
    jdata = utils.fetch_json(urlparse.urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/%s/statistics' % self.server_id), headers=headers, method='GET')
  File "/var/www/testdomain.com/adns/app/lib/utils.py", line 73, in fetch_json
    assert('json' in r.headers['content-type'])
Exception: While fetching http://192.168.200.57:8081/servers/localhost/statistics: 

[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /dashboard HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/datatables/dataTables.bootstrap.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/dist/css/skins/_all-skins.min.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/all.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/multiselect/css/multi-select.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/custom/css/custom.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/minimal/_all.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/square/_all.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/flat/_all.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/line/_all.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/polaris/polaris.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:41] "GET /static/adminlte2/plugins/iCheck/futurico/futurico.css HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:45] "GET /admin/manageuser HTTP/1.1" 200 -
[ERROR] Can not update domain table.While fetching http://192.168.200.57:8081/servers/localhost/zones: 
[ERROR] Can not get server statistics.
[DEBUG] Traceback (most recent call last):
  File "/var/www/testdomain.com/adns/app/models.py", line 1090, in get_statistic
    jdata = utils.fetch_json(urlparse.urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/%s/statistics' % self.server_id), headers=headers, method='GET')
  File "/var/www/testdomain.com/adns/app/lib/utils.py", line 73, in fetch_json
    assert('json' in r.headers['content-type'])
Exception: While fetching http://192.168.200.57:8081/servers/localhost/statistics: 

[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:48] "GET /dashboard HTTP/1.1" 200 -
[INFO] 192.168.200.177 - - [09/Aug/2016 09:29:51] "GET /admin/domain/add HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/var/www/testdomain.com/adns/app/models.py", line 595, in add
    jdata = utils.fetch_json(urlparse.urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
  File "/var/www/testdomain.com/adns/app/lib/utils.py", line 73, in fetch_json
    assert('json' in r.headers['content-type'])
Exception: While fetching http://192.168.200.57:8081/servers/localhost/zones: 

[ERROR] Cannot add domain testdomain.com
[DEBUG] While fetching http://192.168.200.57:8081/servers/localhost/zones: 
[INFO] 192.168.200.177 - - [09/Aug/2016 09:31:16] "POST /admin/domain/add HTTP/1.1" 400 -

`
<img width="1265" alt="screen shot 2016-08-09 at 8 31 20 pm" src="https://cloud.githubusercontent.com/assets/4286063/17518123/bac1e690-5e70-11e6-9779-4abd3b648d88.png">

**Comment by blackyzero** [comment]
after correcting config.py and initialize the db, i still get the issue.
from console, it shows
"[ERROR] Cannot add domain testdomain.com.
[DEBUG] While fetching http://192.168.200.57:8081/api/v1/servers/localhost/zones: 500 Server Error: Internal Server Error
"

i am running Ubuntu 16.04 and pdns version 4.0.0-alpha2

**Comment by trenb** [comment]
@blackyzero are you using replication at all? If so, you need to add
`binlog_format=row`
to your my.cnf

I ran into this myself, and this resolved it for me.

**Comment by blackyzero** [comment]
Thanks @trenb 
At moment, no. i am testing only, but i will follow this instruction here for replication.
https://www.digitalocean.com/community/tutorials/how-to-configure-dns-replication-on-a-slave-powerdns-server-on-ubuntu-14-04

do i need to enable this feature for replication as you mentioned?

Thanks!

**Comment by trenb** [comment]
I'd recommend reviewing https://doc.powerdns.com/3/authoritative/backend-generic-mypgsql/ - It lists the changes necessary for replication. 

Do you have the binary log enabled on your mysql?

**Comment by blackyzero** [comment]
thanks @trenb 
You're right. After enabling that option in my.conf. i am able to create domain, but still getting error from console.

**Comment by blackyzero** [comment]
This ticket answered my question ;)
https://github.com/ngoduykhanh/PowerDNS-Admin/issues/47
