### ISSUE TITLE
Typo on line 1316 on powerdnsadmin/routes/admin.py

### ISSUE THREAD

**Issue by mzamora87** [ngoduykhanh/PowerDNS-Admin#1006]
Line says:

    NSS_PATTERN = re.compile(fr'^({NSS_PCHAR})({NSS_PCHAR}|/|\?)*$', re.IGNORECASE)

But should be 

    NSS_PATTERN = re.compile(r'^({NSS_PCHAR})({NSS_PCHAR}|/|\?)*$', flags=re.IGNORECASE)

Not used to make changes on code, sorry if this is not the correct way to fix it

**Comment by KostasMparmparousis** [comment]
The f-tag before the string is needed, because inside the string the variable "NSS_PCHAR" is referenced. 
Furthermore, according to the python3 documentation, stating explicitly that the 2nd argument used is the "flags" argument is not necessary.

**Comment by zoeller-freinet** [comment]
Kostas is right, closing.
