### ISSUE TITLE
Salt reuse for API key?

### ISSUE THREAD

**Issue by wdoekes** [ngoduykhanh/PowerDNS-Admin#1014]
In https://github.com/ngoduykhanh/PowerDNS-Admin/blob/993e02b635ed271f855e02aeab3e2f8c18d0554f/powerdnsadmin/models/api_key.py#L90-L91 it looks like a predefined SALT is reused for all generated API keys.

Shouldn't that use `bcrypt.gensalt()` instead?

**Comment by RGanor** [comment]
Thank you for bringing this to my attention!
Indeed it seems like this is the right thing to do. Im researching about this topic more and i'll create a fix for it soon.

**Comment by RGanor** [comment]
The point of salt is to create different hash for similar values:
https://en.wikipedia.org/wiki/Salt_(cryptography)#Example_usage

Because API Keys are unique, their hash values are already different, so having the same salt is not a problem.

**Comment by wdoekes** [comment]
I know what a salt is for ;) The point is _not_ -- as you say -- to create a different hash for the same value. The point is to make precomputing hashes harder/impossible. If I know the salt beforehand, I can start precomputing now.

Using a fixed salt is far better than using no salt at all. But here I see no reason here why the salt would have to be fixed/predefined.

**Comment by zoeller-freinet** [comment]
I was going to suggest adding a comment explaining why this kind of usage is OK in this case -
on the other hand using `bcrypt.gensalt()` wouldn't hurt either and would help avoiding similar confusion in the future.

The value of `current_app.config['SALT']` is also used by ItsDangerous to sign tokens for
    email address verification if the `signup_enabled` setting is True. [[1]](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/v0.2.4/powerdnsadmin/services/token.py#L7) By default it's a bcrypt-formatted string as output by `bcrypt.gensalt()`. This is a bit strange as the `salt` parameter serves a different purpose there (see [ItsDangerous Documentation (1.1.x)](https://readthedocs.org/projects/itsdangerous/downloads/pdf/1.1.x/), section 3.2.1 "The Salt"), but it doesn't look like that should cause trouble currently.

> The point is _not_ [...] to create a different hash for the same value.

Making different instances of the same password result in different hashes is of course among the purposes of a salt as used in the context of password hashing.

**Comment by wdoekes** [comment]
> making different instances of the same password result in different hashes is of course among the purposes of a salt as used in the context of password hashing.

Yeah. So I was being pedantic. We mean the same thing. But I'll explain my reasoning:

- we don't want precomputed hashes, because we do not want password lookup tables (the goal, the purpose)
- we change the result of the hash (outcome of the solution, the means)

If the goal was to make the hash _different_, then code would be available to _assert_ that no two salts are the same. You rarely (if ever) find such code. Generally the salt is just random. Ergo, the conclusion must be that avoiding dupe hashes is _not_ the ultimate goal. The ultimate goal is avoiding precomputation.

As a different example, take (random) iteration counts. You wouldn't call the point of those to change the hash either, even though they do. There, the point is to increase computation time. (Same outcome with respect to hash differences, but different goal.)

> As it stands, a constant salt must be used here as `ApiKey.is_validate()` would have no way of retrieving the key from the database otherwise, and thus no way to check if any given key is valid. Perhaps an explanatory comment could be added to help avoid confusion in the future?

Thank you for looking into this. I haven't checked if this is is necessarily the best way to look up these api keys. But at least this explains it.

Adding a comment that this non-random salt is intentational (because of the reasons you mention), would indeed be an appropriate fix :+1:

**Comment by zoeller-freinet** [comment]
You're welcome!

Here is a PR adding a respective comment: https://github.com/ngoduykhanh/PowerDNS-Admin/pull/1037.

> We mean the same thing.

Semantic nitpicking aside, I'd add that making different instances of the same password result in different cryptographically random* hash values - which proper salting achieves - also prevents the following scenario (i.e. is also a goal):

Imagine some service experienced a database leak. If that database stored different instances of the same password in a way that leaves similarities between their hash values, an attacker could identify sets of users sharing the same password. Moreover, if the attacker has an account on that service, they could identify users that use the same password as them, and that password could also have been reused on another service.

\* I took for granted that something like `deadbeef+1`, `deadbeef+2`, ... `deadbeef+n` is out of the question.

**Comment by RGanor** [comment]
> As it stands, a constant salt must be used here as `ApiKey.is_validate()` would have no way of retrieving the key from the database otherwise, and thus no way to check if any given key is valid. Perhaps an explanatory comment could be added to help avoid confusion in the future?

As @zoeller-freinet mention here, currently it is not possible to just change the salt as it will break the API Key functionality.
Merged #1037 for future reference.
Thanks!
