### ISSUE TITLE
How can I run PowerDNS-Admin with SSL (HTTPS)

### ISSUE THREAD

**Issue by trinv** [ngoduykhanh/PowerDNS-Admin#1022]
How can I run PowerDNS-Admin with SSL (HTTPS)
I've been created Certificate & config in NGINX,
but still can not start with HTTPS:
This site can’t provide a secure connection

**Comment by RGanor** [comment]
Hey @trinv.
Can you please elaborate more on the issue? share some configuration files and error logs?

**Comment by bcsanford** [comment]
@trinv 
if you are using nginx then the config on this page should work for you

[Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx
)

at the bottom there is a toggle for an SSL Config

i use this with a few minor tweaks for IPv6
