### ISSUE TITLE
OIDC Account provisioning is creating duplicate User <-> Account Mappings

### ISSUE THREAD

**Issue by cbxnet-ali** [ngoduykhanh/PowerDNS-Admin#1024]
~~For one of our users the List of domains shows only a small (like 3 or less) number of Items if 10 item pagination is selected. That leads to a high number (over 100) of pages.~~

~~Is there anything wrong with the table plugin or the way the domains are filtered per user?~~

The Problem was a different one. With OIDC Account Provisioning set up, every time a user logs in another Account <-> User mapping is creating in the account_user table. that confuses all querys and counts later on

**Comment by RGanor** [comment]
Hey @cbxnet-ali,
I didn't quite understand the issue. Can you please elaborate the problem and give steps to reproduce?

**Comment by cbxnet-ali** [comment]
We have an OIDC Setup with a Keycloak Provider. Whenever the User logs in, a new Account <-> User Mapping in the table is created (a duplicate). That duplicate causes multiply the domaincount and makes the table view broken.

To reproduce we just need to setup "Autoprovision Account Name property" and "Autoprovision Account Description property" in the Advanced tab of the OIDC Authentication Page

**Comment by RGanor** [comment]
Okay, thank you for your explanation.
I will look into soon.

**Comment by benshalev849** [comment]
Can you send what table you are selecting from.
What the DB looks like when you are querying it etc?...

**Comment by cbxnet-ali** [comment]
The table is "account_user"

for example normally there is one line like this:

id account_id user_id
10	4	10

after logging in via sso with "Autoprovision Account" enabled
it looks like this

id account_id user_id
10	4	10
11	4	10

and after a third login like this

id account_id user_id
10	4	10
11	4	10
12	4	10

and so on

**Comment by benshalev849** [comment]
> The table is "account_user"
> 
> for example normally there is one line like this:
> 
> id account_id user_id 10 4 10
> 
> after logging in via sso with "Autoprovision Account" enabled it looks like this
> 
> id account_id user_id 10 4 10 11 4 10
> 
> and after a third login like this
> 
> id account_id user_id 10 4 10 11 4 10 12 4 10
> 
> and so on

What is the claim you use for the autoprovision account name property?

**Comment by cbxnet-ali** [comment]
I think it was preferred_username, so the account name is like the user name (in our usecase)

**Comment by benshalev849** [comment]
> I think it was preferred_username, so the account name is like the user name (in our usecase)

https://github.com/benshalev849/PowerDNS-Admin/tree/oidc-list-accounts

This fork fixed some things for OIDC.

You can try it and it might solve the problem.
It should be pushed to master here soon.

Let me know if it doesn't fix it still.
