### ISSUE TITLE
Unable to set password for local database for docker container

### ISSUE THREAD

**Issue by yngmike** [ngoduykhanh/PowerDNS-Admin#1028]
This is for the powerdns-admin Docker container (Latest)

There doesn't seem to be any way to set the SQL password for the local PowerDNS-Admin Docker container.
Under the docker_config.py: SQLA_DB_PASSWORD = 'changeme' does not seem to be changeable.

I would like to see this added as a docker run environment variable if possible.

Thanks,
-Mike

**Comment by RGanor** [comment]
Hey!
Are you using external database? If so try to pass `SQLALCHEMY_DATABASE_URI` as environment variable instead of changing the configuration file.
