### ISSUE TITLE
SQLALCHEMY_DATABASE_URI 

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [ngoduykhanh/PowerDNS-Admin#1036]
Hello, 

New issue found today : 

When using SQLALCHEMY_DATABASE_URI  for Mysql : 

i.e : ### DATABASE - MySQL
SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+':'+'/'+SQLA_DB_NAME

if password contains special caracters like # or @ .. db connection fails

B. R.

**Comment by zoeller-freinet** [comment]
You need to escape the password (and possibly the username too) using `urllib.parse.quote_plus` (see [SQLAlchemy docs](https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls)).

Note that `powerdnsadmin/default_config.py` shouldn't be edited - if you use docker-compose or a container directly, it should be possible to run the password/username through `urllib.parse.quote_plus` and use the result of that within the `SQLALCHEMY_DATABASE_URI` environment variable. If you don't use a containerized deployment, the docs recommend using `FLASK_CONF` (see e.g. [here](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian#running-powerdns-admin))

**Comment by WhatshallIbreaktoday** [comment]
Thank you for your help.

Side note  regarding second point : 
wiki page : [Running PowerDNS Admin with Systemd, Gunicorn and Nginx](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx) states : 
`Please note, for this to work as expected, you have to have your database configuration in powerdnsadmin/default_config.py file and FLASK env variables are no longer valid.`

Anyway, maybe it's still worth modifying default_config.py:
```
adding:
import urllib.parse

and replacing : SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME

by SQLALCHEMY_DATABASE_URI = 'mysql://'+urllib.parse.quote_plus(SQLA_DB_USER)+':'+urllib.parse.quote_plus(SQLA_DB_PASSWORD)+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME
````
so that default example file adds more security best practice.

What do you think?
Best regards,

**Comment by zoeller-freinet** [comment]
> Please note, for this to work as expected, you have to have your database configuration in powerdnsadmin/default_config.py file and FLASK env variables are no longer valid.

Thanks - missed that! I still think not editing `powerdnsadmin/default_config.py` if possible would be preferable: I'd consider that file as part of the application code. This way, conceptually, you don't lose any configuration as defined by the application itself which might provide a safe/working fallback in case you miss anything in the configuration file that you're editing as an admin.

Currently I see no reason why using `FLASK_CONF` wouldn't work in principle in a (non-containerized) PowerDNS-Admin + Gunicorn + Nginx + systemd scenario. I may give this a try when I find the time. Perhaps it'd make sense to edit the wiki page to that effect - opinions?

> maybe it's still worth modifying default_config.py

Fair enough, I created a PR to that end: https://github.com/ngoduykhanh/PowerDNS-Admin/pull/1040

**Comment by zoeller-freinet** [comment]
Finally got around to testing this, it works as expected. I [edited](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx/_compare/25a6e64bbd1809573e97ba73d5f5e3dc5afff1ad...710cc3567352993c615d9b1f2a94dc95bf360bea) the wiki page accordingly.

#1040 has been merged as well, thanks for bringing this issue up!
