### ISSUE TITLE
Linking imported domains to users

### ISSUE THREAD

**Issue by mabeltron** [ngoduykhanh/PowerDNS-Admin#1038]
I have several hundred bind zone files imported with zone2sql but they need associating with users. Is there an API call for this?

**Comment by RGanor** [comment]
Hey @mabeltron !
Here is a link to PowerDNS-Admin API Swaggers:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/swagger-specv2.yaml

At first it indeed doesn't seems to support this kind of operation but under `POST /servers/{server_id}/zones` you can update the account.
Please let me know if this solution helped you :)

**Comment by jbe-dw** [comment]
Be aware that zones are not associated to users but to accounts. As I already said, the "account" term and concept is confusing for users.
From a pure PDNS perspective, a domain belongs to an "account" (defaults to admin). So PDA sticks to this by managing accounts that can "own" domains. Then for the permission policy, a regular user may be linked to several accounts to be allowed to manage the owned domains.

I'm actually using this accounts as groups (meaning that accounts are "groups" in which I associate users and grant administration permission on domains to these accounts ~ groups). Accounts are basically not groups but PDA simulate this in that way. Users already asked it to be renamed as group. It would not stick to PDNS account terminology anymore but it can make PDA closer to the audience conception of groups and permissions.

That said, you can use the API to:
- Create all the accounts you need (like groups)
- Create local users
- Associate users to the accounts
- Update domains to set the desired account

If you use external auth, PDA creates an external account in the DB that can be managed when a user logs in. You can create users through the api though, I'm not 100% sure but I think they are updated if a user logs in via an external provider.

Currently, the API is split in two parts:
- Any endpoint managing PDA in /pdnsadmin is authenticated via a basic user auth
- Any endpoint managing PDNS is authenticated with an API Key

It is not possible to update the domain account via /pdnsadmin endpoint. You will need an apikey for this task.

The swagger file can be a good starting point for the API, it lacks documentation. 

You can ask in this topic if you have any issue using the API.
