### ISSUE TITLE
DNS masking

### ISSUE THREAD

**Issue by fatihbm** [ngoduykhanh/PowerDNS-Admin#1050]
Hi there,
Could there be a way to mask the DNS records the same as a Cloudflare orange network?
If that's possible, it might be a good idea to return a default IP address for each domain name to everyone in the outside world. This IP address can work as a proxy server. In this way, we can temporarily change the DNS response with a single action.

![image](https://user-images.githubusercontent.com/4369033/142742025-96d96662-2383-4a9f-9a02-87bbea30702a.png)

**Comment by RGanor** [comment]
Im not really familiar with cloudflare, what do you mean masking dns record?

**Comment by fatihbm** [comment]
> Im not really familiar with cloudflare, what do you mean masking dns record?

for example, there is the www.example.com record. 
Suppose it's ip address is x.x.x.x. This ip address points to the webserver. But one day we may want to have a waf service between the web server and the client. 
For this, we need to change the webserver ip address in the dns record with the waf ip address. Sometimes it may be necessary to undo this change. 
Cloudflare provides a way to do this easily. In the picture above, the yellow cloud image shows that the waf ip address is active. In order to do this, the original webserver ip address must be kept in a table and the webserver ip address must be updated as waf in the pdns service.

i hope i could explain :)

**Comment by jbe-dw** [comment]
From a pure PDNS perspective it can be done, by setting a record in a RRSET as disabled. You can test through the API, if it is working as you wish (ie use the PDA API servers/zone/zone_id endpoint to have a RRSET with one record disabled and toggle).

If the DNS behaviour is what you expect, you can request a function to have a per record toggle button to disable the entry in the zone edit page, or push a PR to add it.

**Comment by arbaldin** [comment]
But in the zone edit page we are able to disable an entry. It is not a
button, but a drop down menu called Status the the options Active or
Disabled.


[]´s
Audrey

**Comment by fatihbm** [comment]
I will make a development for this. I'm closing this issue for now. Thanks.

**Comment by jbe-dw** [comment]
> But in the zone edit page we are able to disable an entry. It is not a
button, but a drop down menu called Status the the options Active or
Disabled.

You are right. I was tired ! You can enable record quick edit to just have to click on the record to change the status. If it is not visible enough you can develop something but you'll still need to click on the apply button anyway.
