### ISSUE TITLE
New install error 400 when adding new domain

### ISSUE THREAD

**Issue by ChayneC** [ngoduykhanh/PowerDNS-Admin#1067]
Hi all 

I have installed Powerdns on Debian 11 with the admin GUI

I can manually add dns entries but get the 400 error when trying to add via GUI

I was able to find this error in my logs
If possible could someone help guide me towards the solution.
i have been searching for answers for what feels like years

[webserver] b34710e7-0903-44bb-8b3d-efe1a21c9e66 HTTP ISE for "/api/v1/servers/localhost/zones": Exception: GSQLBackend unable to list keys: Could not prepare statement: select cryptokeys.id, flags, active, published, content from domains, cryptokeys where cryptokeys.domain_id=domains.id and name=?: Unknown column 'published' in 'field list'
Dec  3 14:33:30 PowerDNS gunicorn[498]: [2021-12-03 14:33:30,721] [domain.py:252] ERROR - Cannot add domain temp.superman.com. Error while fetching http://192.168.20.230:8081/api/v1/servers/localhost/zones. Returned status 500 and content Internal Server Error

added info 

mysql> show tables;
+------------------------+
| Tables_in_powerdns     |
+------------------------+
| account                |
| account_user           |
| alembic_version        |
| apikey                 |
| comments               |
| cryptokeys             |
| domain                 |
| domain_apikey          |
| domain_setting         |
| domain_template        |
| domain_template_record |
| domain_user            |
| domainmetadata         |
| domains                |
| history                |
| records                |
| role                   |
| setting                |
| supermasters           |
| tsigkeys               |
| user                   |
+------------------------+
21 rows in set (0.00 sec)

**Comment by RGanor** [comment]
Can you share the alembic version from alembic_version?

**Comment by zoeller-freinet** [comment]
Hi @ChayneC,

PowerDNS (not PowerDNS-Admin, this reporitory here!) introduced a DB schema change from version `4.2.X` to `4.3.0` which added the `published` column to the `crypokeys` table. [1] [2]

It looks like you need to migrate your PowerDNS database by executing [2].

It also seems you have put both PowerDNS and PowerDNS-Admin's tables into one MySQL database - I'd recommend you put both into a separate database.

---
[1] https://doc.powerdns.com/authoritative/upgrading.html#x-to-4-3-0
[2] https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql

**Comment by ChayneC** [comment]
@zoeller-freinet 
thank you so much.
Running that one command [2] has repaired my installation and I can now successfully add domains and add records to that.
I have been pulling my hair out for days(and I don't have much to begin with )

This is my first experience with powerdns I have installed it on a test VM so i can become comfortable with it. Your suggestion about splitting the databases is greatly received and I will do this when I do my next build.

I cannot thank you enough.
Have a fantastic weekend
