### ISSUE TITLE
Enhancement request: Add hovering bar to manage domain page

### ISSUE THREAD

**Issue by michielvisser** [ngoduykhanh/PowerDNS-Admin#108]
If there are many DNS records in a domain it is sometimes difficult to see which set of buttons (Edit, Delete) belongs to which record. Is it possible to have the row of the table over which the mouse is hovering highlighted? This would make it easier to link the actions to the correct record.

**Comment by jallakim** [comment]
Isn't the alternating row-color/shade enough? Or maybe they are not that visible on screens having too much contrast?

**Comment by michielvisser** [comment]
@jallakim: the alternting row colors are barely visible on my screen, it also depends on the screen I'm using - on my laptop it is more visible than through my Virtual Desktop (which uses a browser based RDP session).

A hover bar would be of much help to improve the visibility in managing domain records, thanks.

**Comment by ngoduykhanh** [comment]
Now you can click on the record's row to switch to edit mode directly. No need to click on Edit button.
