### ISSUE TITLE
Enhancement request: Ability to navigate through the hosted domains via the sidebar

### ISSUE THREAD

**Issue by michielvisser** [ngoduykhanh/PowerDNS-Admin#109]
At this moment the only way to manage a domain is by going to the dashboard and then select the domain. I think it would be practical to have the hosted domains in the sidebar on the left hand side, so you can select between them quickly.

**Comment by ngoduykhanh** [comment]
I don't think moving the list of domain into the left sidebar for navigation is a good idea because the list may be long; depends on user's pdns infrastructure, they may have hundred of domain.

**Comment by jallakim** [comment]
I wouldn't like it that way even with few domains. Even when editing a lot of domains, the overhead of going via the dashboard isn't that much.

**Comment by ngoduykhanh** [comment]
Closing the issue since it isn't useful.
