### ISSUE TITLE
Differences between pdns 3.4.2 and 3.4.1?

### ISSUE THREAD

**Issue by alexkiousis** [ngoduykhanh/PowerDNS-Admin#112]
README mentions this project needs pdns 3.4.2 or newer.
Debian Jessie comes with pdns-server v3.4.1. From a look at the settings the (experimental) API this project needs is there on that version. Are you aware of some other incompatibilty that wouldn't let this project work with 3.4.1?

**Comment by ngoduykhanh** [comment]
There is a change with `priority` key as we discussed at #44 . You can also look at pdns changelog.

**Comment by alexkiousis** [comment]
Thanks, that covers it.
