### ISSUE TITLE
Feature request: Support OpenID Connect for auth

### ISSUE THREAD

**Issue by pschiffe** [ngoduykhanh/PowerDNS-Admin#114]
I see you added github oauth as an option for authentication, which is great, but would it be possible to also add support for generic OpenID Connect [1]? It's an extension for oauth, and basically a standard today for SSO. With OpenID Connect, for example, it's possible to use Keycloak [2] as an auth provider.

[1] http://openid.net/connect/
[2] http://www.keycloak.org/

**Comment by ngoduykhanh** [comment]
Oh, I missed this FR. Actually it was implemented some time ago. Please check out the latest source code.
