### ISSUE TITLE
Reset search field on "add record" event

### ISSUE THREAD

**Issue by adrpp** [ngoduykhanh/PowerDNS-Admin#115]
Hello,

not really a bug, but might confuse a bit. Inside of domain where existent RR's are shown, when entering a search string into the search field and afterwards clicking on "add record" shows 'nothing'.

This is by design, as the newly created (empty) RR field doesn't match the search string.
Maybe want to reset search field after clicking on "add record" button to workaround this behavior ?

Rgds,
Adrian

**Comment by jallakim** [comment]
Hi,

This is related to #94. Your suggestion would fix the issue I described (if you have an active search), but would not fix the problem if you've altered the sorting of the rows (as OP of #94 describes).

Both these issues should probably be addressed in the same fix, hence, I'm not sure clearing the search field on "Add record" would be enough...

**Comment by ngoduykhanh** [comment]
This issue was fixed by @jallakim . Please get the latest code. Thanks.
