### ISSUE TITLE
Support uWSGI

### ISSUE THREAD

**Issue by pschiffe** [ngoduykhanh/PowerDNS-Admin#116]
In production deployments, python web server is usually not facing users. For performance and stability reasons, there is usually an nginx proxy with uWSGI in front of a python app.

Couple of useful links:
https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-applications-using-uwsgi-web-server-with-nginx
http://flask.pocoo.org/docs/0.11/deploying/uwsgi/

**Comment by jallakim** [comment]
Not sure what this "issue" is for? *WSGI is already supported -- you just have to make the Apache/nginx-configuration yourself.

Should probably be some examples/instructions/documentation, but the support itself is already there.

**Comment by jallakim** [comment]
Example setup with Apache 2.4 with mod_wsgi;

```
<VirtualHost *:443>
        ServerName superawesomedns.foo.bar
        ServerAlias [fe80::1]
        ServerAdmin webmaster@foo.bar

        SSLEngine On
        SSLCertificateFile /some/path/ssl/certs/cert.pem
        SSLCertificateKeyFile /some/path/ssl/private/cert.key

        ErrorLog /var/log/apache2/error-superawesomedns.foo.bar.log
        CustomLog /var/log/apache2/access-superawesomedns.foo.bar.log combined

        DocumentRoot /srv/vhosts/superawesomedns.foo.bar/

        WSGIDaemonProcess pdnsadmin user=pdnsadmin group=pdnsadmin threads=5
        WSGIScriptAlias / /srv/vhosts/superawesomedns.foo.bar/powerdnsadmin.wsgi

        <Directory "/srv/vhosts/superawesomedns.foo.bar/">
                WSGIProcessGroup pdnsadmin
                WSGIApplicationGroup %{GLOBAL}

                AllowOverride None
                Options +ExecCGI +FollowSymLinks
                SSLRequireSSL
                AllowOverride None
                Require all granted
        </Directory>
</VirtualHost>
```

Content of `/srv/vhosts/superawesomedns.foo.bar/powerdnsadmin.wsgi`;

```
#!/usr/bin/env python3
import sys
sys.path.insert(0, '/srv/vhosts/superawesomedns.foo.bar')

from app import app as application
```

**Comment by pschiffe** [comment]
Great. I wasn't sure because there was no info/doc about it. Thanks for the examples. Feel free to close this, or use it for documentation update PR.

**Comment by jallakim** [comment]
I don't have much WSGI-experience, so there are no guarantees that the above examples can be classified as "best practice" (-:

But yeah, an example of nginx should probably also be added together with the above, and put into the documentation for future reference.

**Comment by pschiffe** [comment]
Ah, there is a wiki..
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/uWSGI-example
