### ISSUE TITLE
history.detail should be JSON encoded instead of str()

### ISSUE THREAD

**Issue by fangli** [ngoduykhanh/PowerDNS-Admin#1187]
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/82f03a4de2f1ca54c678ea08e79d5a48f5b1a8cf/powerdnsadmin/routes/domain.py#L547

This issue leads to 500 internal server error in dashboard page.

**Comment by jbe-dw** [comment]
Related to #1181

**Comment by jbe-dw** [comment]
Hello,

Thanks for reporting, we're working on a patch to upgrade the db and fix the code.

Regards

**Comment by jbe-dw** [comment]
Could you try #1182
