### ISSUE TITLE
When trying to login with a user after the first user is created it fails.

### ISSUE THREAD

**Issue by seitzbg** [ngoduykhanh/PowerDNS-Admin#12]
When trying to login with a user after the first user is created it fails.
If I delete the first user from the DB (after ldap login created it), I can login with a different user and it will create this user in the DB.  I cannot however login with another user where it would be the second user in the DB.  Please advise.

**Comment by ivanfilippov** [comment]
Hi @seitzbg!

If you're able to, can you try the same thing with local non-LDAP users and let me know if it breaks?

**Comment by ivanfilippov** [comment]
I think this issue might be related to a broken DB after the manual fix applied in issue #11. Since I can't replicate this issue via Active Directory or OpenLDAP and the reporting user hasn't returned I recommend this issue be closed.
