### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by pschiffe** [ngoduykhanh/PowerDNS-Admin#120]
When trying to use python 3, I get:

```
# pip3 install -r requirements.txt
...
Collecting python-ldap==2.4.21 (from -r requirements.txt (line 7))
  Using cached python-ldap-2.4.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g1iucx4s/python-ldap/setup.py", line 53
        print name + ': ' + cfg.get('_ldap', name)
                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g1iucx4s/python-ldap
```

Unfortunately, `python-ldap` doesn't support python 3, but there are at least 2 alternatives that do:
https://github.com/cannatag/ldap3
https://github.com/pyldap/pyldap

**Comment by ngoduykhanh** [comment]
I only did tests with Python2. Except python-ldap, not sure if other components will work with Python3.

**Comment by pschiffe** [comment]
I understand, replacing ldap library is probably only a beginning of python 3 support, but I think it's worth it in the end. Linux distros are in the process of slowly deprecating python 2, so installing pdns-admin on latest distro means installing legacy stuff (for example, latest Fedora docker image has only python3 installed).

**Comment by ngoduykhanh** [comment]
Understand. I will consider this issue as a enhancement for PowerDNS-Admin to fullly support Python3 in my next works. Any contribution is welcome also ;).

**Comment by kaechele** [comment]
https://github.com/kaechele/PowerDNS-Admin/tree/python3

**Comment by ngoduykhanh** [comment]
checkout `development` branch which support python3. Waiting to merge to master.
