### ISSUE TITLE
Feature request: add option to configure TTL values

### ISSUE THREAD

**Issue by pschiffe** [ngoduykhanh/PowerDNS-Admin#123]
Like the `RECORDS_ALLOW_EDIT` config option, it would be nice to have similar config option for TTL values dropdown, with possibility to select the default option.

**Comment by mathieumd** [comment]
+1, and a "Custom" choice should let the user choose any value she wants. By default it would be seconds, but it would be possible to append a simple unit: **s**econds, **m**inutes, **h**ours and **d**ays.

**Comment by andreyhammer** [comment]
+1
Need to have ability to set any TTL in seconds. 
Please implement this feature

**Comment by tmuncks** [comment]
Looks like this is solved by #409 and #755 ?

**Comment by zoeller-freinet** [comment]
As mentioned, the TTL dropdown's values can be customized using the `ttl_options`setting as implemented by #409.
Specific seconds-based values can be achieved using the same feature.

For a "custom" choice as part of the resource record editing table where a seconds value could be entered directly, or customization of the default choice, if needed, I suggest creating a separate issue or MR.
