### ISSUE TITLE
cant run create.py for DB creation

### ISSUE THREAD

**Issue by direktorn** [ngoduykhanh/PowerDNS-Admin#126]
Hi, 
Whatever I do the DB script will not connect to the MySQL (MariaDB) Backend: 
(flask) PowerDNS-Admin# ./create_db.py
INFO: Wait for database server
ERROR: Couldn't connect to database server

However Pdns works fine with the same backend, I can run mysql -u with the username and password in my config-file and it works fine. 

Ubuntu 16.04 
mysql  Ver 14.14 
PowerDNS  4.0.0-alpha2  (Intrestingly an alpha build comes with Ubuntu 16.04) 
Latest PowerDNS-Admin from git. 

DATABASE CONFIG
#You'll need MySQL-python
SQLA_DB_USER = 'powerdnsadmin'
SQLA_DB_PASSWORD = 'xxxxxx'
SQLA_DB_HOST = 'xxx.xxx.xxx.xxx'
SQLA_DB_NAME = 'powerdnsadmin'

#MySQL
SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME

I have tried binding the script to both localhost and to other IPs but no success.

**Comment by michielvisser** [comment]
I had the same issue with this, CentOS 7 with MariaDB. The following solved this for me:
yum install MySQL-python
pip install python-mysql

Somehow these are not part of the installation of the requirements. After that, all went well...

**Comment by direktorn** [comment]
I have followed the installation guide here and mysql-phyton should be installed.

**Comment by direktorn** [comment]
It there any guide(s) available that can help me go trough the steps of isntalling PDNS-Admin on an vanilla Centos or Ubutu? I have not been successful following an guides :(

**Comment by alythemonk** [comment]
Into this problem, I don't know if this is the right thing to do, BUT I inserted mysql-python at the end of my requirements.txt and re-ran it ... I again could be off base but that worked for me ?

**Comment by direktorn** [comment]
@alythemonk That did the trick, it also showed that i was missing the mysql-developer package. Perhaps it could be good to update the requirements.txt file. 

Now everything works as expected: )

**Comment by ngoduykhanh** [comment]
The mysql developer package was removed from requirements.txt file in PR #104 . It should be optional since user can use difference kind of DB backend. Please reference to README, WIKI for more information.

**Comment by tahiro86j** [comment]
Intended to run it on Raspbian Stretch and ran into the same problem today.
