### ISSUE TITLE
Support for PowerDNS 4.x

### ISSUE THREAD

**Issue by TacoScheltema** [ngoduykhanh/PowerDNS-Admin#13]
Hi,

Will you be supporting PowerDNS 4.x? I got it to work nicely on version 3 but on 4 I can only see the domains, not the records under a domain (I get a 500 error then).

Cheers,
Taco

**Comment by ngoduykhanh** [comment]
PowerDNS 4 still in Alpha release. But I will start working on this to make sure PowerDNS-Admin can work with the new version of PowerDNS.

**Comment by Trozz** [comment]
any movement on this?

**Comment by ivanfilippov** [comment]
I've started a very naive implementation of pdns 4 support in a new branch. You'll need to add `/api/v1/` to the end of your PDNS_STATS_URL in `config.py` when configuring the new code.

It works in my test environment with pdns 4.0.0-alpha1, but I would appreciate feedback from others.

The branch can be found here: https://github.com/ivanfilippov/PowerDNS-Admin/tree/pdns4-support

**Comment by ivanfilippov** [comment]
Spoke too soon, this will need quite a bit more work to work properly with pdns4.

**Comment by ngoduykhanh** [comment]
@ivanfilippov : I've pushed some adjustments to support pdns v4.x.x in our `new_ui` branch.
Features are working:
- Add a domain
- Show domain/record table
- Adding a records.

Still have problem with multiple records adding which described at https://github.com/ngoduykhanh/PowerDNS-Admin/issues/5#issuecomment-181637576 in my adjustment.

Let me know if you have any idea/adjustment.

**Comment by ivanfilippov** [comment]
@ngoduykhanh I fixed the multiple record adding issue in this commit: https://github.com/ngoduykhanh/PowerDNS-Admin/commit/812aa055f858c09e4324ad043e8172821264df4d

During testing I noticed that the new PDNS API won't accept MX or SRV records unless they are suffixed by a '.'. This looks like it's part of the spec for MX and SRV records, so I'll work on adding that in as well just for the new API code.

**Comment by ivanfilippov** [comment]
@ngoduykhanh I fixed the '.' issue with MX and SRV records I mentioned above, but I'm not sure that the way I fixed it is the best way. Can you review it? Commit here: https://github.com/ivanfilippov/PowerDNS-Admin/commit/b9f57e8cfec5addc0e278f9228904c610ee2cf38

**Comment by ngoduykhanh** [comment]
@ivanfilippov : I am OK with your change. But it looks like we need more than `MX` and `SRV` here. `CNAME`, `NS` also requires trailing dot in their content.

p/s: pdns v4.x.x requires to add a trailing dot in the records `name` and `content`, but the trailing dots aren't saved in the pdns's database actually :)

**Comment by ivanfilippov** [comment]
@ngoduykhanh I noticed that the pdns database does not save the dots as well, but pdns itself must add them when responding to queries. I wonder why they decided to do that.

We'll need to add CNAME and NS to this line: https://github.com/ivanfilippov/PowerDNS-Admin/commit/b9f57e8cfec5addc0e278f9228904c610ee2cf38#commitcomment-17781503

Go ahead and add those two in if you're free, I won't have a chance to look at it until tomorrow. :smile:

**Comment by ngoduykhanh** [comment]
@ivanfilippov : I see. I will take care of adding those two in. thanks Ivan.

**Comment by ngoduykhanh** [comment]
Pushed commit aad9d920389d675f19dd7f28b41c53ccb6f2d12c for those changes.

**Comment by ivanfilippov** [comment]
@ngoduykhanh 

Thanks!

By the way, I'm going to remove my own `new_ui` branch and push directly to the one in your repo, having my own branch and keeping it in sync is becoming a pain. :smile:

**Comment by ngoduykhanh** [comment]
@ivanfilippov 
Yes, you should do that. Thanks buddy :)

**Comment by ngoduykhanh** [comment]
PDNS 4.x.x is supported now with PR #50 . Feel free to open issues related to PDNS 4.x.x compatibilities.
