### ISSUE TITLE
I suggest to move Dockerfile from winggundamth/docker-base to ngoduykhanh/PowerDNS-Admin

### ISSUE THREAD

**Issue by harobed** [ngoduykhanh/PowerDNS-Admin#135]
I suggest to move Dockerfile from https://github.com/winggundamth/docker-base/tree/master/powerdns-admin to https://github.com/ngoduykhanh/PowerDNS-Admin in `docker` folder.

**Comment by pschiffe** [comment]
If you are looking for more of a prod version of pdns-admin Docker image, check my repo: https://github.com/pschiffe/docker-pdns
