### ISSUE TITLE
LDAP login problem with sensitive case.

### ISSUE THREAD

**Issue by Scrowny** [ngoduykhanh/PowerDNS-Admin#136]
Hello,

I have a LDAP authentication problem with sensitive case. 

Exemple :  The login "test" and "Test" are considered like two different account

( Sorry about my bad english :dancers: )

**Comment by bergzand** [comment]
Is this problem caused by LDAP not being case sensitive with the login, but PowerDNS-Admin handling ldap logins case sensitive?

**Comment by Scrowny** [comment]
Hi,

PowerDNS-Admin create an account for every case sensitive login : 

Example : bergzand, Bergzand, BeRgZaNd, bergzanD

4 differents logins are created in the login database.

Regards,

**Comment by ngoduykhanh** [comment]
They should be difference. `bob` and `Bob` should be difference user likes what we have in *nix system.

**Comment by Scrowny** [comment]
Oh ok ... ! Thanks ;)

**Comment by bergzand** [comment]
Isn't this caused by ldap matching bob and Bob to a single ldap account possibly named bOb. Since a lot of ldap attributes are matched case insensitive.

I would suggest lower casing the stored database login name in lower case if the account is from LDAP
