### ISSUE TITLE
Impossible to apply changes to a zone with a txt entry

### ISSUE THREAD

**Issue by hlidotbe** [ngoduykhanh/PowerDNS-Admin#137]
Hi,

When using PDNS-Admin with PowerDNS 3.4 I can't apply changes to a zone with a txt entry.

Here's the error received:

{ "msg": "Record mg.epic-sys.io/TXT v=spf1 include:mailgun.org ~all: Parsing record content: Data field in DNS should start with quote (\") at position 0 of 'v=spf1 include:mailgun.org ~all'", "status": "error" }

The field is quoted in the DNS and the changed record is unrelated. The json sent includes the quotes so it must be somewhere between the app and PowerDNS but my python is not good enough to track it.

**Comment by willfurnell** [comment]
Are you sure you are quoting using " marks rather than ' marks? I've found " marks work.

**Comment by ngoduykhanh** [comment]
You have to quote your txt record with double quotes ""

**Comment by hlidotbe** [comment]
Found the issue while looking into the database. Some unrelated records where not quoted. It was not obvious because the error was for another but yeah. Fixed the database and now everything works. Thanks
