### ISSUE TITLE
Basic settings reference

### ISSUE THREAD

**Issue by dahamsta** [ngoduykhanh/PowerDNS-Admin#1399]
Is there a reference for the basic settings anywhere? I've search the repo and I've been able to find some explanations in tickets, but a lot of them are hard to understand. I can create a doc similar to the [environment variables reference](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/configuration/Environment-variables.md) and fill in what I can, but I wonder if that will end up the same way as that reference, fairly devoid of info. :)

**Comment by AzorianMatt** [comment]
@dahamsta albeit not the most complete or helpful, this has been started some time ago.

Updates to this are certainly a welcome PR. Check this out: https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/configuration/Environment-variables.md
