### ISSUE TITLE
Issues with how the History view works with large domains

### ISSUE THREAD

**Issue by trenb** [ngoduykhanh/PowerDNS-Admin#140]
When doing a single record update in a zone containing a large number of records (over 800 in this case), it seems like PDA is submitting the ENTIRE ZONE, instead of the deltas. This isn't necessarily an issue, however we get NOTHING back when we click "Info" in the history view (literally nothing, the button doesn't do anything).

In addition, if you are running MySQL/MariaDB with "STRICT_TRANS_TABLES" SQL Mode, you'll get a 1406 error `DataError: (_mysql_exceptions.DataError) (1406, "Data too long for column 'detail' at row 1")` - I had to disable this mode to even be able to submit updates.

Would it be possible to have updates to the domain ONLY show the records that were modified? Otherwise, this feature is useless as there's no way to pick out which record was updated. Or failing that, can we disable the history?

This is using mariadb on CentOS 7. Please let me know if you need more information.

Thanks!

**Comment by jallakim** [comment]
The Proper™ way to solve this would be, as you describe, to only submit the actual changes made to the zone. In stead of doing a comparison (e.g. compare with the previous values when submitting the zone), we could probably solve this somewhat "easy" by setting some kind of "edited"-flag on a record whenever you "save" it (regardless if you actually changed it). Only records having the edit-flag would be submitted.

**Comment by trenb** [comment]
The Proper™ way is always preferable, but at this point, I'd be happy with anything ;-) The history view was a big plus for us and in its current implementation is not useable. 

Thanks for responding right away to this. I was concerned I was doing something wrong, but glad to hear it's something that needs improvement.

Let me know if you have any code you want tested! :-D

**Comment by jallakim** [comment]
Well, the culprit isn't really the history-view -- it's actually working as intended (the whole zone is submitted, and thus, the whole zone is also displayed in the history).

The MySQL/MariaDB-error is specific to those databases, as the `text` data type in PostgreSQL supports `strings of any length` (i.e. unlimited amounts of text).

**Comment by jallakim** [comment]
After thinking two more seconds about it, I don't think it's as easy as I thought, as the pdns API wants all records for the same FQDN in the same RRset -- all the other records not present are deleted/removed. E.g. if you have `foo IN A 10.10.10.10` and `foo IN A 10.20.20.20`, and you only change the first (hence, only the first gets the "edited" flag), the second record will be removed upon saving the zone (unless you edit that record as well).

**Comment by trenb** [comment]
Hmm. Okay, I'm not sure how we handle this then. The Info button is dead for any updates I've committed that are truncated due to size. And even if the Info button worked, it'd show the entire zone. I'm not sure how useful the Info button is for domain edits. Unless I'm misunderstanding how this feature is expected to work?

And regarding the issues with "Text" field type in MySQL, it looks like it only supports a max of 64KB. I found these notes:

> TEXT can store 65,535 characters (approx 64KB)
MEDIUMTEXT = 16,777,215 characters (approx 16 MB) 
LONGTEXT = 4,294,967,295 chars (approx 4GB)

I'll try altering the detail column in the history table to "LONGTEXT" from "TEXT" to see if this helps.

**Comment by trenb** [comment]
`ALTER TABLE history MODIFY detail LONGTEXT;` 

The above did the trick. Now I have no issues with the Info button working, and the updates are pushing as they should. 

Still doesn't help highlight what record out of the 800+ was actually edited though :-( I'm not sure what can be done about that though.

It might be worth altering the schema for MySQL with this change so others with large domains won't have this issue.

**Comment by ngoduykhanh** [comment]
To me, there is no way to ONLY keep the records that were modified in  the history. By using the pdns api, you won't know exactly which record is modified/added/deleted. My original ideal about keeping history of record's JSON data is for another feature likes Version Control so we can revert our changes if need.

**Comment by trenb** [comment]
Ah! Then I did misunderstand the purpose of the history. Thanks for the explanation. This make sense and I see the value. 

Do you agree with the mysql schema change for the history table? If so after that change, this ticket can be closed.

**Comment by ngoduykhanh** [comment]
`MEDIUMTEXT = 16,777,215 characters (approx 16 MB)`: This should be enough i think. 

Changing to `detail = db.Column(db.Text(16777215))` works well with mysql db backend, it create mediumtext column type but seems not working for Postgresql.

**Comment by ngoduykhanh** [comment]
It looks like `text` in [PostgreSQL](https://www.postgresql.org/docs/9.1/static/datatype-character.html) is unlimited. I applied the change for MySQL at commit d2bbc04d5b73a775c27e6a948fb223a0b042bd79
