### ISSUE TITLE
considering flask coding guidelines[1] and app renaming

### ISSUE THREAD

**Issue by cstruck** [ngoduykhanh/PowerDNS-Admin#145]
Hey Khanh Ngo,

great work you're doing here.

I have 2 suggestions to make.
- Usage of relative imports.
- And Renaming the "app" (by this I mean the app folder) to something more self explaining like powerdnsadmin or powerdns-admin

Best regards

Struck

[1] http://exploreflask.com/en/latest/conventions.html

**Comment by ngoduykhanh** [comment]
I didn't have much time to look at this issue. However, the project has been refactored recently. The app was renamed and restructured. Not sure whether it is perfect. But it looks good to me for now...
