### ISSUE TITLE
'_ldap' extension build failure

### ISSUE THREAD

**Issue by bjo81** [ngoduykhanh/PowerDNS-Admin#148]
building '_ldap' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/Modules

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.21 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -I/usr/include/python2.7 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-2.7/Modules/LDAPObject.o

In file included from Modules/LDAPObject.c:9:0:

Modules/errors.h:8:18: fatal error: lber.h: No such file or directory

 #include "lber.h"

```
              ^
```

compilation terminated.

**Comment by jallakim** [comment]
This is a computer/Python/non-PowerDNS-Admin issue. Google is your friend.

E.g. http://stackoverflow.com/questions/4768446/i-cant-install-python-ldap

**Comment by ivanfilippov** [comment]
Thanks @jallakim 

Closing due to this not being a PDNS-A issue.
