### ISSUE TITLE
How to set the timezone for the CST?

### ISSUE THREAD

**Issue by dzhyw** [ngoduykhanh/PowerDNS-Admin#149]
hi,all
  I am a Chinese, I use powerdns-admin ,when use Dashboard, Recent History Time is UTC? how to change it. thanks!

The following is my local system Settings:

  mysql 5.6.31
  mysql> SHOW VARIABLES LIKE '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | CST    |
| time_zone        | SYSTEM |
+------------------+--------+
2 rows in set (0.00 sec)

(flask) [root@pdnstest PowerDNS-Admin]# date
Wed Oct 12 10:35:46 CST 2016

**Comment by jallakim** [comment]
Timezones <3

**Comment by dzhyw** [comment]
how to solve this problem?

**Comment by ngoduykhanh** [comment]
Recent History Time is in UTC at the moment. Depends on the user's browser timezone, we can convert and display in proper time. Patches are welcome :)
