### ISSUE TITLE
Error 500 : Internal Server Error when creating new domain

### ISSUE THREAD

**Issue by saldru** [ngoduykhanh/PowerDNS-Admin#152]
Hi all,

When I want to create new domain in the PowerDNS-Admin GUI, I have a 400 error. 
If I look in the debugger, I see this : 

`Traceback (most recent call last):`

 `File "/opt/PowerDNS-Admin/app/models.py", line 586, in add
    jdata = utils.fetch_json(urlparse.urljoin(PDNS_STATS_URL, API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)`

  `File "/opt/PowerDNS-Admin/app/lib/utils.py", line 64, in fetch_json
    r = fetch_remote(remote_url, method=method, data=data, params=params, headers=headers, accept='application/json; q=1')`

  `File "/opt/PowerDNS-Admin/app/lib/utils.py", line 56, in fetch_remote
    r.raise_for_status()`

  `File "/opt/PowerDNS-Admin/flask/local/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)`

`RuntimeError: While fetching http://127.0.0.1:8081/api/v1/servers/localhost/zones: 500 Server Error: Internal Server Error`

`[ERROR] Cannot add domain test.local.`

`[DEBUG] While fetching http://127.0.0.1:8081/api/v1/servers/localhost/zones: 500 Server Error: Internal Server Error`

`[INFO] 10.10.1.25 - - [16/Oct/2016 16:13:42] "POST /admin/domain/add HTTP/1.1" 400 -`

I don't know the source of the problem. Can I have some help please ? (Sorry for my language, I'm French)
Thank you.
Saldru

**Comment by ngoduykhanh** [comment]
Are you able to create a new domain via curl to powerdns api? 
https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones

**Comment by jallakim** [comment]
@ngoduykhanh, maybe go through some of the issues lacking a reply, and close them? They "clutter" up the issue list somewhat.

**Comment by ivanfilippov** [comment]
No response from original submitter. Closing.

**Comment by dzervas** [comment]
I have the same problem, but I can't see any errors (I use [this](https://github.com/dzervas/powerdns-docker/blob/master/padmin/Dockerfile) docker container). The entry is created normaly on pdns.
