### ISSUE TITLE
PowerDNS installation DB issue

### ISSUE THREAD

**Issue by nidotech** [ngoduykhanh/PowerDNS-Admin#157]
problem: cannot connect to database when running create_db.py

Env: Centos 7.2
MariaDB: 5.5.50
Python: 2.7.5
pip install -r requirements.txt: all satisfied

// run create_db.py
(flask) [root@localhost PowerDNS-Admin-master]# ./create_db.py 
INFO: Wait for database server
ERROR: Couldn't connect to database server

//config.py
SQLA_DB_USER = 'powerdnsadmin'
SQLA_DB_PASSWORD = 'password'
SQLA_DB_HOST = 'localhost'
SQLA_DB_NAME = 'powerdnsadmin'

//i'm able to login using the same user
(flask) [root@localhost PowerDNS-Admin-master]# mysql -u powerdnsadmin -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 31
Server version: 5.5.50-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use powerdnsadmin;
Database changed
MariaDB [powerdnsadmin]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| powerdnsadmin      |
+--------------------+
2 rows in set (0.00 sec)

MariaDB [powerdnsadmin]>

**Comment by petersipos** [comment]
Hello @nidotech 

In https://github.com/ngoduykhanh/PowerDNS-Admin/pull/102/files#diff-04c6e90faac2675aa89e2176d2eec7d8
this modification @dorion corrected the README.md. Based on this correction you need to install mysql-python via pip to enable the mysql support in python:
`pip install MySQL-python`

**Comment by nidotech** [comment]
alright, thanks. I need to install mysql-devel first before running 'pip install MySQL-python' under virtualenv since mysql_config is missing.

**Comment by ivanfilippov** [comment]
Looks like this is solved.
