### ISSUE TITLE
Strange SOA for new zone

### ISSUE THREAD

**Issue by nidotech** [ngoduykhanh/PowerDNS-Admin#158]
I've everything set up and running with supermaster. However, wheneverI create a master new zone with powerdns-admin, it will add a strange string in SOA. Though I can modify the SOA string manually, it is a bit inconvenient for this. Anyone got any idea how did this happen?

;; ANSWER SECTION:
test.com.               3600    IN      SOA     a.misconfigured.powerdns.server. hostmaster.test.com. 2016112335 10800 3600 604800 3600

**Comment by jallakim** [comment]
If you are referring to the `a.misconfigured.powerdns.server` part, it's not PowerDNS-Admin related at all (the string itself is a good hint for where you should look).

A quick Google search would yield you the answer, but I'll give you a tip; configure your PowerDNS server properly -- more specifically https://doc.powerdns.com/md/authoritative/settings/#default-soa-name .

**Comment by nidotech** [comment]
oh, thanks. I thought it should be a parameter when creating a new zone in the UI.

**Comment by hcsaustrup** [comment]
The **default-soa-name** option is being deprecated in PowerDNS 4.4.0, so perhaps this needs some attention? :-)

**Comment by dmarteau** [comment]
> The default-soa-name option is being deprecated in PowerDNS 4.4.0, so perhaps this needs some attention? :-)

Indeed, so what is the alternative: nothing in the documentation suggest how to set the default SOA name in since 4.2 (since when default-soa-name is a noop setting)

**Comment by aki-ks** [comment]
@hcsaustrup  PowerDNS 4.4 added `default-soa-content` which seems to combine `default-soa-mail`, `default-soa-name` and others into one config options.
