### ISSUE TITLE
Apache WSGI error

### ISSUE THREAD

**Issue by madpsy** [ngoduykhanh/PowerDNS-Admin#160]
I'm trying to launch pdns admin via WSGI with Apache but seeing the following...

```
[Wed Nov 30 10:47:32.393179 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456] mod_wsgi (pid=60446): Target WSGI script '/var/www/html/pdns-admin/powerdnsadmin.wsgi' cannot be loaded as Python module.
[Wed Nov 30 10:47:32.393286 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456] mod_wsgi (pid=60446): Exception occurred processing WSGI script '/var/www/html/pdns-admin/powerdnsadmin.wsgi'.
[Wed Nov 30 10:47:32.393372 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456] Traceback (most recent call last):
[Wed Nov 30 10:47:32.393407 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456]   File "/var/www/html/pdns-admin/powerdnsadmin.wsgi", line 5, in <module>
[Wed Nov 30 10:47:32.393410 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456]     from app import app as application
[Wed Nov 30 10:47:32.393416 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456]   File "/var/www/html/pdns-admin/app/__init__.py", line 1, in <module>
[Wed Nov 30 10:47:32.393419 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456]     from werkzeug.contrib.fixers import ProxyFix
[Wed Nov 30 10:47:32.393441 2016] [wsgi:error] [pid 60446] [remote 10.10.0.10:39456] ImportError: No module named 'werkzeug'
```

Having never used WSGI before (nor confident with Python) I'm wondering if anyone knows off the top of the head what may cause this? My config looks sane (used the sample provided in #116).

My initial thought was it's to do with the virtualenv stuff but not convinced.

Running './run.py' directly in /var/www/html/pdns-admin/ works just fine. Any thoughts on how to debug would be greatly appreciated.

**Comment by madpsy** [comment]
Alright so this is indeed to do with virtualenv as after installing python3-werkzeug (Ubuntu 16.04) that error went away and moved on to Flask.

I suspect the best way to fix this is to get WSGI to use virtualenv, which is what I'm figuring out now.

**Comment by TacoScheltema** [comment]
Hi Madsppy,

I'm using the following in my setup:

powerdnsadmin is installed in /opt/powerdnsadmin

The file /opt/powerdnsadmin/powerdnsadmin.wsgi contains the following:

```
activate_this = '/opt/powerdnsadmin/flask/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
sys.path.insert(0, '/opt/powerdnsadmin')

from app import app as application
```

In my apache (2.4) vhost I have this:

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    WSGIDaemonProcess pdnsadmin user=pdnsadmin group=pdnsadmin threads=5
    WSGIScriptAlias / /opt/powerdnsadmin/powerdnsadmin.wsgi

#    uncomment the following if using a reverse proxy with ssl termination in front of this server
#    RequestHeader set X-Forwarded-Proto "https"

    <Directory /opt/powerdnsadmin>
        WSGIProcessGroup pdnsadmin
        WSGIApplicationGroup %{GLOBAL}
        Order allow,deny
        Allow from all
        Require all granted
    </Directory>
</VirtualHost>
```

This works for me.

**Comment by madpsy** [comment]
Thanks!

I was clearly missing:

```
activate_this = '/opt/powerdnsadmin/flask/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))
```

Working now, appreciate that.

**Comment by mchlrv** [comment]
I've just set it up like this, but I still do the following Apache  output:
`[Fri May 25 13:19:28.039503 2018] [:error] [pid 28912] [remote 127.0.0.1:152] mod_wsgi (pid=28912): Target WSGI script '/opt/powerdnsadmin/powerdnsadmin.wsgi' cannot be loaded as Python module.
[Fri May 25 13:19:28.039548 2018] [:error] [pid 28912] [remote 127.0.0.1:152] mod_wsgi (pid=28912): Exception occurred processing WSGI script '/opt/powerdnsadmin/powerdnsadmin.wsgi'.
[Fri May 25 13:19:28.039587 2018] [:error] [pid 28912] [remote 127.0.0.1:152] Traceback (most recent call last):
[Fri May 25 13:19:28.039624 2018] [:error] [pid 28912] [remote 127.0.0.1:152]   File "/opt/powerdnsadmin/powerdnsadmin.wsgi", line 7, in <module>
[Fri May 25 13:19:28.039676 2018] [:error] [pid 28912] [remote 127.0.0.1:152]     from app import app as application
[Fri May 25 13:19:28.039703 2018] [:error] [pid 28912] [remote 127.0.0.1:152]   File "/opt/powerdnsadmin/app/__init__.py", line 1, in <module>
[Fri May 25 13:19:28.039745 2018] [:error] [pid 28912] [remote 127.0.0.1:152]     from werkzeug.contrib.fixers import ProxyFix
[Fri May 25 13:19:28.039782 2018] [:error] [pid 28912] [remote 127.0.0.1:152] ImportError: No module named werkzeug.contrib.fixers`

I've followed all the above configuration settings, including setting up a separate user and group. Does anybody know how to debug this?
