### ISSUE TITLE
Dyndns Updates Not Working

### ISSUE THREAD

**Issue by madpsy** [ngoduykhanh/PowerDNS-Admin#165]
Let me state from the start there is a good chance this is my fault. I can't seem to get dyndns updates working. I've tried:

GET https://user:pass@host/nic/update?domain=sub.domain.com
GET https://host/nic/update?domain=sub.domain.com (with base64 encoded Authorizaion header)
GET https://host/nic/update?user=user&password=password&domain=sub.domain.com

plus a few others, with no luck - they all return 'badauth'. I've checked that the user/pass is correct and the user has permission for the zone.

Does anyone have a fully working example for cURL or a client such as inadyn ?

Thanks

**Comment by ivanfilippov** [comment]
PDNS-Admin actually needs the domain to be in the `hostname` parameter. This should work for you
```
curl "http://user:pass@host/nic/update?hostname=sub.domain.com&myip=1.1.1.1"
```
When implementing this feature I followed the DynDNS docs almost exactly (there are a few missing features, such as updating multiple A records at once, but for the most part its fully compatible) and I don't see the `domain` parameter in there. You can see those docs [here](https://help.dyn.com/remote-access-api/perform-update/). Do you have an example of another provider or tool that uses that parameter? It should not be hard to add if there is a need.

Let me know if this helped. 😄

**Comment by madpsy** [comment]
Thanks but no joy. Here's what I'm running:

`curl "https://user:pass@blah.com/pdns-admin/nic/update?hostname=dyntest.mydomain.com&myip=1.1.1.1"`

The result is 'badauth'

I've double checked the user:pass and they're correct (copy/pasted etc).

If there's anything I can do to debug I'm more than happy to do it. This isn't critical for me, just a bit frustrating :)

**Comment by trenb** [comment]
Works fine for me. I use via /etc/sysconfig/ddclient on centos type boxen.
```
DDCLIENT_OPTIONS="-daemon 300 -nossl -options nossl,wildcard=no,login=DYNDNS,password=PASSWORD,use=web,web=1.2.3.4:9393/nic/checkip.html,server=1.2.3.4:9393,script=/nic/update -host whatever.you.want.com"
```

Hope that helps!

**Comment by trenb** [comment]
Have you created a user in powerdns-admin and assigned it access to the domain you're trying to do dyndns with? Creating a user isn't enough, unless it's an admin user which gets access to all domains.

**Comment by madpsy** [comment]
Yeah and I can log in to the UI with the credentials and edit the zone etc. Very strange.

**Comment by ngoduykhanh** [comment]
@madpsy : You have to grant user (including Administrators) access to that domain to be able to edit the record via DynDNS. Let double check your "Domain Access Control" page.

**Comment by madpsy** [comment]
I think I've done it right.. see screenshot.

![domainpriv](https://cloud.githubusercontent.com/assets/13963858/21044379/91e4f252-bdf3-11e6-9da9-7d65dd438251.png)

**Comment by petersipos** [comment]
Uhmm you need to check in the "Allow on-demand creation of records via DynDNS updates?", don't you?

**Comment by madpsy** [comment]
I thought that was if the record you were 'updating' didn't already exist, thus gets created... in my test case the record already exists and is a true 'update'.

**Comment by ngoduykhanh** [comment]
"Allow on-demand creation of records via DynDNS updates?" is for creating new record only. In update case we don't need it.

@madpsy : can you try with another user with new credential? Your issue looks weird.

**Comment by madpsy** [comment]
No joy either...

I'm beginning to wonder if this is because it's running under WSGI and maybe the basic auth stuff isn't being passed.

**Comment by madpsy** [comment]
That solved it. Missing 'WSGIPassAuthorization On' from Apache config. Hopefully useful to someone else.

Thanks for everyone's time & help.

**Comment by jallakim** [comment]
Thanks for the info, @madpsy. I added it to the [https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/WSGI-Apache-example](WSGI Apache example) wiki page.

**Comment by sourcenux** [comment]
Is there any nginx-alternative to "WSGIPassAuthorization On" on apache? This issue persists, when using nginx+powerdnsadmin+ddns

**Comment by bryanpedini** [comment]
I've currently deployed PowerDNS-Admin via Docker container on CentOS 7 with Nginx as reverse proxy.
I don't use any subdirectory or subdomain, the hostname of the machine is the domain name of the web console, which is configured on root `/` on Nginx.
Result is `badauth`, I don't use Apache on the host machine, and I expect this to be already correctly configured in the Docker container provided by this repo itself.

Any clue?
Thanks in advance.

**Comment by sourcenux** [comment]
What Application did you use to test this? After investigating the issue I found out, that the problem only occured when using an webbrowser that was using the authentication string directly within the called URL (https://user:pass@pdnsserver). Did you check if the user has access to the specific domain (domain acl)?

**Comment by bryanpedini** [comment]
Well, I tested with `curl -u "myuser:mypassword" "http://127.0.0.1/nic/update?hostname=test.dynamic.bjphoster.com&myip=1.1.1.1"` directly from the console of the server... pretty much defeats the reverse proxy from Nginx as a cause...

My current deployment is `x.x.x.x:80 nginx: master` -> `x.x.x.x:443 nginx: master` (ssl) -> (proxy) `127.0.0.1:80 docker-proxy` (as per `netstat -tupln`)
Nginx v1.16.1
Docker v19.03.12
PowerDNS Authoritative v4.1.11
MariaDB v5.5.65

Also, this is my domain setup on PowerDNS-Admin:
![Screenshot from 2020-08-17 12-40-08](https://user-images.githubusercontent.com/45012292/90387903-4a4d2d00-e087-11ea-9d9f-968a9511f49f.png)
![Screenshot from 2020-08-17 12-40-55](https://user-images.githubusercontent.com/45012292/90387919-52a56800-e087-11ea-9744-4f74802d7eef.png)
![Screenshot from 2020-08-17 12-41-34](https://user-images.githubusercontent.com/45012292/90387937-5933df80-e087-11ea-9fc2-67c7a9c2f262.png)
