### ISSUE TITLE
powerdns 4.0.0 and admin.

### ISSUE THREAD

**Issue by pnunn** [ngoduykhanh/PowerDNS-Admin#166]
I can see the domains configured in pdns but when I try and access or manage any of them I get an error 

[ERROR] Cannot fetch domain's record data from remote powerdns api

any ideas why this might be?

**Comment by pnunn** [comment]
Just discovered that the reverse domain and one of the three configured do work with the api, the other two throw an Internal Server Error when I try and query the api with curl so looks as though its a database error from upgrading earlier versions or so such thing.

**Comment by ngoduykhanh** [comment]
so the problem solved? The error meant you have problem in the pdns api configuration.

**Comment by ivanfilippov** [comment]
No response from original reporter since December 2016. Closing issue.
