### ISSUE TITLE
Ability to add comments to records

### ISSUE THREAD

**Issue by pentiumoverdrive** [ngoduykhanh/PowerDNS-Admin#167]
We have lots of records being added to different zones.
Can we somehow make these records somewhat traceable by adding an optional comment field for each record?
There you can add ticket number/identification for each added record.

Powerdns does have a comment table in the database at least, but not sure if this is for zones only.

Thanks

**Comment by leuchtdiode** [comment]
+1. Such a field would be great. Like a comment or "tags" stored in one field for each record, so we can bulk update our records based on this comment field.

**Comment by ngoduykhanh** [comment]
Feature already implemented in the linked PR.
