### ISSUE TITLE
enabling/disabling Two Factor Authentication doesn't work 

### ISSUE THREAD

**Issue by gianbisso** [ngoduykhanh/PowerDNS-Admin#169]
I'm trying PowerDNS-Admin but OTP activation didn't work i fixed it in this way:
```
--- templates/user_profile.html.old	2016-12-21 16:05:25.235741833 +0100
+++ templates/user_profile.html	2016-12-21 16:11:13.320239331 +0100
@@ -165,8 +165,7 @@
                 'enable_otp' : enable_otp
             }
         };
-        applyChanges(postdata, $SCRIPT_ROOT + '/user/profile');
-        location.reload();
+        applyChanges(postdata, $SCRIPT_ROOT + '/user/profile',false,true);
     });
 </script>
 {% endblock %}
```

**Comment by goldyfruit** [comment]
@gianbisso Thanks for the patch, it works for me 👍

**Comment by ngoduykhanh** [comment]
Added your patch to `development` branch. See commit 4d88d829d59056ddb2e1700f23b2634f2f9b5c1e. Thanks for your contribution.

**Comment by robetus** [comment]
The commit was added incorrectly. You need to also remove the line: `location.reload();` in order for the fix to work. Tried it myself. Thank you! @gianbisso
