### ISSUE TITLE
Deployment issues with Ubuntu 22.04 LTS and FreeBSD

### ISSUE THREAD

**Issue by Externalnet** [ngoduykhanh/PowerDNS-Admin#1694]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

root@powerdns:/var/www/html/pdns# pip install -r requirements.txt
Usage: pip [options]

ERROR: Invalid requirement: --use-feature=no-binary-enable-wheel-cache lxml==4.9.0
pip: error: option --use-feature: invalid choice: 'no-binary-enable-wheel-cache' (choose from '2020-resolver', 'fast-deps', 'in-tree-build')

root@powerdns:/var/www/html/pdns# source ./flask/bin/activate
(flask) root@powerdns:/var/www/html/pdns# export FLASK_APP=powerdnsadmin/__init__.py
(flask) root@powerdns:/var/www/html/pdns# flask db upgrade
Error: While importing 'powerdnsadmin', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/var/www/html/pdns/powerdnsadmin/__init__.py", line 4, in <module>
    from flask_mail import Mail
ModuleNotFoundError: No module named 'flask_mail'

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

### Expected Behavior

Able to install PowerDNS Admin by following instuction/documentation

### Observed Behavior

root@powerdns:/var/www/html/pdns# pip install -r requirements.txt
Usage: pip [options]

ERROR: Invalid requirement: --use-feature=no-binary-enable-wheel-cache lxml==4.9.0
pip: error: option --use-feature: invalid choice: 'no-binary-enable-wheel-cache' (choose from '2020-resolver', 'fast-deps', 'in-tree-build')

root@powerdns:/var/www/html/pdns# source ./flask/bin/activate
(flask) root@powerdns:/var/www/html/pdns# export FLASK_APP=powerdnsadmin/__init__.py
(flask) root@powerdns:/var/www/html/pdns# flask db upgrade
Error: While importing 'powerdnsadmin', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/var/www/html/pdns/powerdnsadmin/__init__.py", line 4, in <module>
    from flask_mail import Mail
ModuleNotFoundError: No module named 'flask_mail'

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

**Comment by Pammetje** [comment]
I used this instruction but also other instructions fail: https://www.howtoforge.com/how-to-install-powerdns-on-ubuntu-22-04/

**Comment by Metrax** [comment]
Please use the official instructions:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/tree/master/docs/wiki/install

In 0.4.1 there is a dependency problem in some distributions.
If you run in to an error because of "pg_config", you need to install libpg-dev (Debian/Ubuntu)
If you run in to an error because of "cython", change the Version Number of "PyYAML" to 6.0.1 in requirements.txt

I was installing PDA today at Ubuntu 22.04 and ran into these problems.

**Comment by Pammetje** [comment]
Thanks for all the quick replies, I will try the official instructions and come back her with the results.

**Comment by sonnh-uit** [comment]
I met same error on CentOS7. I follow instruction wiki above. Have any one figure out method to fix, please share for me.

**Comment by Pammetje** [comment]
Ok I used the official wiki instuction to install PowerDNS-Admin on my favorite OS FreeBSD v13
The first step in the instuction is:

"sudo pkg install git python3 curl node12 yarn-node12"

result:

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'node12' have been found in the repositories
pkg: No packages available to install matching 'yarn-node12' have been found in the repositories

So this instuction is also not valid, what do I do next?

**Comment by Metrax** [comment]
@Pammetje i have no clue about FreeBSD but sounds like the howto was written for an older FreeBSD version. Please check if these packages are available with new versions, but i'm not sure if newer yarn versions are working.

@sonnh-uit please post a full description of your problem with the steps you've done and the output of the errors.

**Comment by Pammetje** [comment]
There is a node-16, node-18 and a yarn-node16, yarn-node18 package on FreeBSD but not a node-12 and yarn-node12 package. So wich version should I install, version 16 of version 18 ?

**Comment by 662KDV** [comment]
> Please use the official instructions: https://github.com/PowerDNS-Admin/PowerDNS-Admin/tree/master/docs/wiki/install
> 
> In 0.4.1 there is a dependency problem in some distributions. If you run in to an error because of "pg_config", you need to install libpg-dev (Debian/Ubuntu) If you run in to an error because of "cython", change the Version Number of "PyYAML" to 6.0.1 in requirements.txt
> 
> I was installing PDA today at Ubuntu 22.04 and ran into these problems.

I was seeing the same error as OP in Ubuntu 22.04
I can confirm the "cython" fix solved the error for me.

**Comment by sirEgghead** [comment]
I am on Ubuntu 22.04.  I began with OP's problem using the same guide as OP.

I changed to using https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/install/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md when pointed to it by a comment above and ran into the error regarding wheel not building correctly.

Following another comment, changing the version number of PyYAML to 6.0.1 in requirements.txt fixed that issue.  I seem to be finished with the installation.

**Comment by AzorianMatt** [comment]
This is not a bug, but a deployment issue. While the documentation is almost certainly not up-to-date for FreeBSD deployments, the instructions for Debian / Ubuntu still seem pretty close if not usable as I have no issues running the project in my Ubuntu 22.04 environment.

I'm converting this to a discussion.
