### ISSUE TITLE
cannot get systemd working...

### ISSUE THREAD

**Issue by andreasalberta** [ngoduykhanh/PowerDNS-Admin#171]
i get "run.py: /usr/bin/env: python: No such file or directory"

this is the same error message i get if i try to start run.py manually (/opt/PowerDNS-Admin/run.py).
run.py only work if i first execute "source /opt/PowerDNS-Admin/flask/bin/activate"
but how can i start a service with this extra command first?

(i'm on centos7 with sqlite)

**Comment by anddah** [comment]
/bin/bash -a -c 'source /opt/PowerDNS-Admin/flask/bin/activate && exec  /opt/PowerDNS-Admin/run.py'

**Comment by andreasalberta** [comment]
excellent, working thanks!
