### ISSUE TITLE
List recently edited zones in the left column

### ISSUE THREAD

**Issue by mathieumd** [ngoduykhanh/PowerDNS-Admin#172]
The left column should contain a list of the N zones recently edited. The navigation would be faster, because currently you have to go to the dashboard first before switching zones.

It could look like this:
![list_zones.png](https://cloud.githubusercontent.com/assets/2104679/21753588/76323744-d5f0-11e6-8943-6a71e47f413c.png)

**Comment by ngoduykhanh** [comment]
Doesn't look good to me. If we have to have history if recently edited zone. It should be located some where else, not main navigation.

**Comment by mathieumd** [comment]
You closed this issue because you don't want an history? Or merely because of my poor design suggestion?
