### ISSUE TITLE
CSS: Emphasis on zone name

### ISSUE THREAD

**Issue by mathieumd** [ngoduykhanh/PowerDNS-Admin#173]
The page "Manage domain" should have a title which put emphasis on the zone name. Something like this:
![better css](https://cloud.githubusercontent.com/assets/2104679/21753649/04b26dd0-d5f2-11e6-8ea9-c16e530cf17e.png)

In the same way, the HTML `<title>` should start with the zone name:
- NOW: `<title>DNS Control Panel - DOMAIN</title>`
- BETTER: `<title>example.com - DNS Control Panel</title>`

**Comment by ngoduykhanh** [comment]
Thanks for suggestion. See 670805459164b140dd3149a57bbaaa9e59c61ae5
