### ISSUE TITLE
Editing NS records

### ISSUE THREAD

**Issue by SBC-MvS** [ngoduykhanh/PowerDNS-Admin#179]
In the default configuration the record type NS for domains is not included. As those record types are required to be set if you create a new domain through the webinterface the first you have to do is to update the configuration to include them or else you can't add a new domain and configure it completely through the webinterface. This is a minor problem that should be changed in the config_template.py. But there is a second problem that is more critical. For PTR zones the app/views.py overrides the RECORDS_ALLOW_EDIT list and then only the record type PTR is available. This should be expanded to PTR and NS.

**Comment by jallakim** [comment]
Explicitly having to "enable" NS record editing is good as it is, IMHO. 

Regarding the issue with PTR zones, that was introduced in [b8848f3](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/b8848f315b7c9935ed5a6463b577f375faafa685#diff-b5099d1f0106025f31781ccbe0a59d13) -- and yes, that should be changed.

**Comment by SBC-MvS** [comment]
Maybe check if the RECORDS_ALLOW_EDIT contains 'PTR' and then add it in the overwrite in the views.py.

**Comment by jallakim** [comment]
Or just add `PTR_RECORDS_ALLOW_EDIT` or similar, where you can control it for PTR zones. There are several allowed record types for PTR zones (PTR, NS, CNAME, TXT, etc).

**Comment by yohannprigent** [comment]
I think it should also copy original NS with auto_ptr

**Comment by carragom** [comment]
Ran into this issue today. The root of the problem here seems to be that the criteria for Reverse zones are different than for Forward zones. Maybe an option could be to have two lists:

    FORWARD_RECORD_TYPES = ('SOA', 'NS', 'A', 'CNAME', etc)
    REVERSE_RECORD_TYPES = ('SOA', 'NS', 'PTR')

Then change [this](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L1131) line to something like:

    if zone.is_reverse:
        return self.type in set(REVERSE_RECORD_TYPES).intersection(app.config['RECORDS_ALLOW_EDIT'])
    else:
        return self.type in set(FORWARD_RECORD_TYPES).intersection(app.config['RECORDS_ALLOW_EDIT'])

But I see no way how to determine if the zone is Forward or Reverse in the context of that specific line.
