### ISSUE TITLE
Unable to grant admin access if users are not on first page

### ISSUE THREAD

**Issue by githuhb** [ngoduykhanh/PowerDNS-Admin#180]
Running latest PowerDNS-Admin with pdns 4.0.1

I am unable to grant admin access to a powerdnsadmin user (LDAP users) if the users are not on first page (more than 10 users), the tick box appears different on the second page and has no effect.

**Comment by iXL7** [comment]
Same Issue here.
I've updated manually the role_id in the mysql database for my user.
Anyone got a better solution ? Maybe increase the amount of user listed on the pages ?

**Comment by ngoduykhanh** [comment]
Fixed and more adjustment in commit e1f12c8f1614e4f624d26032ac5b67bbd0b522d9
