### ISSUE TITLE
Issue with adding A record

### ISSUE THREAD

**Issue by k0nsl** [ngoduykhanh/PowerDNS-Admin#185]
I don't know why this is an issue, but it is.

Let me explain:

Adding an A entry for `subdomain.domain.tld` works perfectly fine, but if I try to add an entry for the actual `domain.tld` it doesn't work. In the admin interface it shows that the entry has been added, sure. But it does not resolve. So I can only add various subdomains, e.g `something.domain.tld`, `something.else.domain.tld`, and so on and so forth.

Any idea why this is happening?

**Comment by ivanfilippov** [comment]
When you try to add an A record for `domain.tld` are you leaving the Name field blank (or with an @ sign)? Can you attach a screenshot of your interface?
