### ISSUE TITLE
Powerdns Issue

### ISSUE THREAD

**Issue by srinijreddy** [ngoduykhanh/PowerDNS-Admin#187]
Hi Khanh,

I am trying to install powerdns on my existing DNS server, set following error.  This is my existing DNS server. Can you please help.

compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for python-ldap
  Running setup.py clean for python-ldap
Failed to build python-ldap

Modules/common.h:10:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/root/flask/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nvHstK/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-AHMlxD-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/flask/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-build-nvHstK/python-ldap/

**Comment by trenb** [comment]
This isn't an issue with PDA, you don't have your python development libraries installed. On a RHEL compatible system, it'll be python-devel.

**Comment by srinijreddy** [comment]
Thanks Issue is resolved.
