### ISSUE TITLE
MySQL connection problem

### ISSUE THREAD

**Issue by Zuko** [ngoduykhanh/PowerDNS-Admin#189]
Hi, I move PowerAdmin database from local host to another host (Galera Cluster) and I experience too many ```2006, 'MySQL server has gone away'``` errors.

It's possible to just reconnect rather than putting ```error 500```?

Or maybe it's possible to set connection timeout?

**Comment by unclev0va** [comment]
Try,
SQLALCHEMY_POOL_RECYCLE = 600
in config.py

**Comment by Zuko** [comment]
Thanks
