### ISSUE TITLE
Support CAA Records

### ISSUE THREAD

**Issue by techhelper1** [ngoduykhanh/PowerDNS-Admin#192]
It would be nice if the UI would support CAA records.

**Comment by jallakim** [comment]
Just add it to ```RECORDS_ALLOW_EDIT```, and it should work just fine.

**Comment by bitsofinfo** [comment]
How do you do this? where is this property defined? file?

**Comment by jallakim** [comment]
@bitsofinfo, in ```config.py```.

**Comment by ngoduykhanh** [comment]
ref: #197
