### ISSUE TITLE
Show DNSSEC details of a zone

### ISSUE THREAD

**Issue by HLFH** [ngoduykhanh/PowerDNS-Admin#2]
Hi,

Do you support DNSSEC?
If no, please support it.

Thanks in advance,
HLFH

**Comment by TacoScheltema** [comment]
+1 for DNSSEC support

**Comment by ngoduykhanh** [comment]
@HLFH do you mean support creating domain with DNSSEC enabled? If yes, we are not able to do it from front-end yet because the PowerDNS RestAPI doesn't support enabling `dnssec` yet.
https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones

**Comment by HLFH** [comment]
@ngoduykhanh Yes, it would be great to support it when PowerDNS RestAPI will support `dnssec`. At least, for this moment, [like nsedit](https://github.com/tuxis-ie/nsedit), it would be cool to be able to "show the DNSsec details of a zone".

**Comment by ngoduykhanh** [comment]
@HLFH : pushed commit 990bbe5 to support showing DNSsec detail of a zone

**Comment by HLFH** [comment]
@ngoduykhanh Thanks a lot!! Issue solved.
