### ISSUE TITLE
Running as a background service

### ISSUE THREAD

**Issue by howsonwhocodes** [ngoduykhanh/PowerDNS-Admin#200]
Hi,

I've tried running PowerDNSAdmin wtih gunicorn and using supervisor. The wiki examples using supervisor don't seem to work on Debian 8. Please can you advise how to run it as a service? 

Thanks for making a great tool. Running it in the background is all i'm struggling with. 

Thanks,

Tom

**Comment by olkitu** [comment]
Do you have tried?

`  sudo ./run.py &
`
