### ISSUE TITLE
requirement.txt misses dependancy to psycopg2

### ISSUE THREAD

**Issue by tobiasstein** [ngoduykhanh/PowerDNS-Admin#203]
Hi,
When using `uwsgi` with a `virtualenv` the dependancy to `pyscopg2` is missing in `requirements.txt`.
Would be great if you added it. Latest (currently) 2.7.1 seems to be working.

```
…
dbapi = dialect_cls.dbapi(**dbapi_args)
File "/opt/pdns/pdns-admin/flask/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 579, in dbapi
    import psycopg2
ImportError: No module named psycopg2
```

Thanks for powerdns-admin!

**Comment by ngoduykhanh** [comment]
We use MySQL by default in the example of config file. Installing psycopg2 should be mentioned in manual / wiki pages.
