### ISSUE TITLE
problem when creating DB

### ISSUE THREAD

**Issue by mdomore** [ngoduykhanh/PowerDNS-Admin#204]
hi,

i ha ve some trouble creating the databases with the create_db.py

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: u'\nCREATE TABLE migrate_version (\n\trepository_id VARCHAR(250) NOT NULL, \n\trepository_path TEXT, \n\tversion INTEGER, \n\tPRIMARY KEY (repository_id)\n)\n\n']

Any one can help me with that ?

**Comment by Hansfreddy** [comment]
I just wanted to add that I'm experiencing the exact same problem. I'm on Ubuntu 16.04 BTW

**Comment by mdomore** [comment]
i just switch to psql, but its a on going problem with mysql and inodb.

**Comment by colbin8r** [comment]
I'm having the same issue with MariaDB.

```sh
$ flask db upgrade
...
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1709, 'Index column size too large. The maximum column size is 767 bytes.') [SQL: 'CREATE UNIQUE INDEX ix_domain_template_name ON domain_template (name)'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

I've already set these variables in MariaDB:
```
innodb_file_format                          | Barracuda
innodb_large_prefix                         | ON
```

**Comment by Rico29** [comment]
Same problem for me
