### ISSUE TITLE
GitHub Wiki

### ISSUE THREAD

**Issue by ivanfilippov** [ngoduykhanh/PowerDNS-Admin#21]
Hi @ngoduykhanh!

I've started a wiki in my fork, but I'm not sure how to set up a wiki PR to the main repo (based on my quick search, it might not even be possible...). Take a look to see if you'd like to integrate it into the main repo. I'd like to fill it up with guides about installation on various systems, integrating AD, LDAP, DynDns, etc.

The wiki is [here](https://github.com/ivanfilippov/PowerDNS-Admin/wiki).

**Comment by ngoduykhanh** [comment]
Hi @ivanfilippov ,

I've created initial Wiki page and public it. It is editable now. You can copy the wiki from your repo into it. (so your name will marked there :-) )

Thank you for great contribution!.

**Comment by ivanfilippov** [comment]
HI @ngoduykhanh 

Awesome, thanks! I host the screenshots in the wiki as well, and I can't publish those via the GitHub editor:

![screenshot](http://i.imgur.com/EaXGtv3.png)

Since I don't have contributor access can you merge my wiki repo into the main wiki repo? The repo is here: https://github.com/ivanfilippov/PowerDNS-Admin.wiki.git

**Comment by ngoduykhanh** [comment]
@ivanfilippov , I've merged your wiki into the main repo. Thank you.

I am not sure about the permission when using Github editor. I've changed Wiki access permission follow [this instruction](https://help.github.com/articles/changing-access-permissions-for-wikis/) already. Let try to use command line instead, you can check [this guide line](https://gist.github.com/larrybotha/10650410).

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh

That's actually the guide I was following, it says that the owner of the main repo has to do the merges themselves. :disappointed: 

I'll try to batch up a few edits into my repo before sending you more merge requests, so you're not doing it all the time.
