### ISSUE TITLE
Support for LDAP_GROUP_SECURITY

### ISSUE THREAD

**Issue by vitalka200** [ngoduykhanh/PowerDNS-Admin#211]
Hi do you have any plans on adding the functuanality described by @ivanfilippov in
https://github.com/ngoduykhanh/PowerDNS-Admin/issues/11
It's very useful especially in large ldap/ad deployments when you want users/roles separation. 

Actually having LDAP_USER_GROUP and LDAP_ADMIN_GROUP will allow controlling wich specific users from the domain can have read or write permissions without giving to all domain users ability to login

**Comment by maysara** [comment]
I second that, thank you for pointing out that @vitalka200, I wrote a quick hack to make LDAP authenticated users admins by default, I shall replace it with work of @ivanfilippov
