### ISSUE TITLE
Powerdns-admin service path 

### ISSUE THREAD

**Issue by yasmeen2017** [ngoduykhanh/PowerDNS-Admin#212]
Greetings,

I followed up the example you mentioned here "PowerDNS-Admin/wiki/Systemd-example" and i think  there is no need to write this line " Environment="PATH=/opt/web/powerdns-admin" in the script,  as its not  running with it because this path breaks the user path

**Comment by rhaamo** [comment]
The WIKI page have been edited some times ago, if this is OK can you close the issue ?

**Comment by ngoduykhanh** [comment]
I agree. Environment isn't needed to be in systemd config.
