### ISSUE TITLE
postgresql?

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#22]
Hello,

could you please provide install instructions for use with postgresql?

I got the app running (via uwsgi/nginx), also I got it to run under postgresql, unfortunately it does not show any dns records at all. I have to assume that the db setup I did is somehow wrong.

pdns logs say it transmits the json data.

Many thanks

**Comment by ngoduykhanh** [comment]
hi @piwats ,

It looks like that you completed the setup for running PowerDNS-Admin with Posgresql. Your issue is a bug actually. I've fixed it at commit f1b38b1. Please checkout the new code and let me know if it fixes your issue.

**Comment by piwats** [comment]
Hello there,

unfortunately I still cannot see any records.

**Comment by piwats** [comment]
Could it be because I run in a subdirectory? e.g. server.com/pdns?

**Comment by ngoduykhanh** [comment]
It works for me on Ubuntu 14.04 and Postgresql 9.4. What are you environment? I don't think the subdirectory can cause this issue, but have you tried to removing it?
Can you show me your `config.py` file also ?

**Comment by piwats** [comment]
```
import os
basedir = os.path.abspath(os.path.dirname(__file__))

# BASIC APP CONFIG
WTF_CSRF_ENABLED = True
SECRET_KEY = 'verylongsecret'
#PORT = 9393

# TIMEOUT - for large zones
TIMEOUT = 10

# LOG CONFIG 
LOG_LEVEL = 'DEBUG'
LOG_FILE = '/var/log/dns/logfile.log'

# Upload
UPLOAD_DIR = os.path.join(basedir, 'upload')

# DATABASE CONFIG
SQLALCHEMY_DATABASE_URI = 'postgresql://pdns:nothing-to-see-here@localhost/pdns'
SQLALCHEMY_MIGRATE_REPO = os.path.join(basedir, 'db_repository')
SQLALCHEMY_TRACK_MODIFICATIONS = True

# LDAP CONFIG
#LDAP_URI = 'ldaps://your-ldap-server:636'
#LDAP_USERNAME = 'cn=dnsuser,ou=users,ou=services,dc=duykhanh,dc=me'
#LDAP_PASSWORD = 'dnsuser'
#LDAP_SEARCH_BASE = 'ou=System Admins,ou=People,dc=duykhanh,dc=me'
#LDAP_TYPE = 'ldap' // or 'ad'
LDAP_URI = ''                                                                                                                                                           
LDAP_USERNAME = ''                                                                                                                                                      
LDAP_PASSWORD = ''                                                                                                                                                      
LDAP_SEARCH_BASE = ''                                                                                                                                                   
LDAP_TYPE = ''                                                                                                                                                          
                                                                                                                                                                        
                                                                                                                                                                        
# POWERDNS CONFIG                                                                                                                                                       
PDNS_STATS_URL = 'http://127.0.0.1:8081/'                                                                                                                               
PDNS_API_KEY = 'whao,some,secret,key,in,here'

# RECORDS ALLOWED TO EDIT
RECORDS_ALLOW_EDIT = ['A', 'AAAA', 'CNAME', 'SPF', 'PTR', 'MX', 'TXT']
```
I'm on gentoo wit pgsql-9.5.2, to be precisely.

**Comment by piwats** [comment]
Ah, I forgot to mention, that I also tried to run it in /. Same behavior, no changes.

**Comment by piwats** [comment]
Could you please change the create_db.py script so I can try it with postgresql?

Last time I had to create the db structure by hand, maybe I did something wrong?

**Comment by ngoduykhanh** [comment]
@piwats : didn't `create_db.py` work for you? I works fine for me with Postgresql. Can you create new bank database and rerun the script?

**Comment by piwats** [comment]
I've got it now:

Somehow the app won't work if the venv (aka 'flask' directory) is not inside of PowerDNS-Admin...

**Comment by ivanfilippov** [comment]
Hi @piwats 

The flask directory contains all the dependencies (Flask, SQLAlchemy, etc), but you can install the dependencies into your system Python packages without the `virtualenv` and avoid needing it there. :smile:

**Comment by ivanfilippov** [comment]
I should mention that `virtualenv` is the recommended way of doing it, unless you're building a docker image or something that will only ever run PowerDNS-Admin.

**Comment by piwats** [comment]
My initial setup as described in #23 was:

../PowerDNS-Admin
../venv

Now it is 

../PowerDNS-Admin
../PowerDNS-Admin/flask

where venv = flask, meaning ```virtualenv flask```

**Comment by ngoduykhanh** [comment]
For you description #23, they are:
```
pythonpath = /the_place_of/PowerDNS-Admin/
virtualenv = /the_place_of/venv/
```
Yes. you need the `env` (flask) directory in inside `PowerDNS-Admin` to make it work.

**Comment by piwats** [comment]
That I have already changed. I think it is safe to close this issue.
