### ISSUE TITLE
Project will be updated

### ISSUE THREAD

**Issue by TheGr8Wonder** [ngoduykhanh/PowerDNS-Admin#221]
All,

I was recently given access to mod the project, so for those subscribed to this project (or those who lurk on issues), over the next few weeks or so, I will be combing through all of the backlog issues and PRs, and will close/merge as needed. It's been a year since anything has been committed, and that has caused some disparity within all of the forks. So if you have a awesome feature that you've added in your custom fork, but haven't submitted a PR because you thought the project was no longer being maintained, please submit the issue/PR, and it will be addressed in the near future! 

Thanks!!

**Comment by thomasDOTde** [comment]
I've already merged a lot of recent PRs and implemented some new functionality.
Thats also including some new bug fixes from other contributors.
https://github.com/thomasDOTde/PowerDNS-Admin

**Comment by pasikarkkainen** [comment]
Nice! Good to see activity related to this project :)

**Comment by TheGr8Wonder** [comment]
@thomasDOTde can you please shoot me an email (can be found on my profile). Would like to have a conversation offline regarding this project

**Comment by JeroenBo** [comment]
@TheGr8Wonder @thomasDOTde  Is possible to keep my updated about your plans? In the next few weeks we (my company) like to do some dedicated development on the project.

**Comment by thomasDOTde** [comment]
I‘d love to see python3 support and I’m going to merge translation and a global search on my fork.

**Comment by JeroenBo** [comment]
Our goal for now is to implement the PDNS 4.1 API with full support for DNSSEC and creating new docker images for testing against PDNS version 3.x en 4.x.

We will work with the fork from @thomasDOTde,  I would be nice to have only one project, but i don't know how active @ngoduykhanh still is within the project.

**Comment by TheGr8Wonder** [comment]
I have reached out to @thomasDOTde to discuss the best possible merger of this project, solely for those who may not be aware of his and the great work he has done with it. @JeroenBo please stand by while we solidify these discussions.

**Comment by fenice2** [comment]
I'm looking forward to seeing what you both have planned for this project. :)

**Comment by blackyzero** [comment]
+1
Would be great to have new updates in near future.

**Comment by jsenecal** [comment]
It would be great if the work done by @thomasDOTde could be merged into the main repo - it would also be great to have him be promoted to a maintainer to this project as well. @JeroenBo could then contribute to the now up-to-date code to add dnssec functionality.

Anyhow, keep up the very good work :)

**Comment by fenice2** [comment]
@jsenecal I wholeheartedly agree with those comments. It's about time that PowerDNS had a more modern management interface. :)

**Comment by maysara** [comment]
Please keep us posted; If the repo will be based on the work of @thomasDOTde, let us also know so we can submit pull requests against that repo

**Comment by fenice2** [comment]
It's been a few months since it was announced that this project is going to be updated and also mentioned that the PRs and additional functionality from thomasDOTde might get merged into this project. I'm having problems getting either of the projects to build or work on my CentOS7 server.

This isn't a criticism but just an enquiry. :) Are you likely to be publishing a timeline or roadmap of when things might be happening with these improvements? I think that some feedback on the current status and/or future plans would go a long way to getting this software adopted by other PowerDNS users.

**Comment by ngoduykhanh** [comment]
Hi guys,

I have been inactive in this project for a long time. Now i will start looking all the PRs again and merge them.

I've created `developement` branch with first commits to adopt python3 which suggested in #143 . Added simple docker compose file as well.

Let me know if you have suggestions, bug need to be fixed.

Regards,

**Comment by bemanuel** [comment]
Do you want something about the translate PR?

Em sex, 30 de mar de 2018 03:58, Khanh Ngo <notifications@github.com>
escreveu:
