### ISSUE TITLE
Need Installation help for NGINX webserver

### ISSUE THREAD

**Issue by satya876** [ngoduykhanh/PowerDNS-Admin#222]
Kindly provide detailed steps to install the application on Debian over NGINX Webserver. Thank You !!

**Comment by rhaamo** [comment]
What's your issue exactly ?
There is https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/uWSGI-example and by using something like https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Systemd-example it's a simple "proxy pass".

**Comment by satya876** [comment]
Thank you for the help. However I am not able to run it on local, I followed the native installation steps provided on the home page of the project. But not successful in the installation, is there any trick ?

**Comment by rhaamo** [comment]
Ok, on which step are you blocked ?
Creating the database or running the app ?
Can you provide a traceback error to debug ?

**Comment by satya876** [comment]
I am getting issue from the below steps onward:

pip install -r requirements.txt

I will share the logs shortly.

Wanted to know if any dependency module is required apart from mentioned in the installation steps.

Thank You !!

**Comment by satya876** [comment]
Attached is the error I am getting. GCC compilation is installed. If needed I can share server login credentials if you would like to check.
[1.txt](https://github.com/ngoduykhanh/PowerDNS-Admin/files/1551234/1.txt)

**Comment by satya876** [comment]
Thanks for the help, I am able to install and it is not running on below url:
http://216.158.238.59:9393
This is for testing.
Kindly let me know how I can create a Admin account and please explain me the below configuration from the  file config.py
# POWERDNS CONFIG
PDNS_STATS_URL = 'http://172.16.214.131:8081/'
PDNS_API_KEY = 'you never know'
PDNS_VERSION = '3.4.7'

What is this "PDNS_STATS_URL" URL for ?

Thanks for the help.

**Comment by rhaamo** [comment]
Try to avoid publishing public IPs/URLs to avoid security issues.

```PDNS_STATS_URL``` is the URL to your PowerDNS Webserver API, for a PowerDNS with config:
```
--webserver=yes --webserver-address=0.0.0.0 --webserver-port=8000 --api=yes --api-key=someapikey42 --webserver-allow-from=ip.where.is.installed.powerdns-admin
```
Your ```PDNS_STATS_URL``` will be ```http://ip.where.is.installed.powerdns:8000/```
```PDNS_API_KEY``` Will be "someapikey42"
```PDNS_VERSION``` Set to the version of the installed PowerDNS.

Then after restarting PowerDNS-Admin, you will be able to use the link on the index page to Create an Account.

**Comment by satya876** [comment]
Thanks for your help. I will try and let you know if needed any further help. 
Also I truly agree to avoid posting any public IP, however I mentioned because that is my Test Environment.
Thanks a lot.

**Comment by decramy** [comment]
I had some troubles with Python 2.x vs 3.x. I needed python3-dev and python3-pip, and used 'pip3 install'...
