### ISSUE TITLE
UWSGI : Invalid permissions for vassal powerdns-admin.ini

### ISSUE THREAD

**Issue by betawi** [ngoduykhanh/PowerDNS-Admin#223]
PowerDNS-Admin up and running via ./run.py

now i want to serve it via NGINX using uWSGI

followed: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/uWSGI-example

uwsgi running too,but serving 0 vassal
journalctl -u uwsgi show : 

`uwsgi[18185]: [emperor-tyrant] invalid permissions for vassal powerdns-admin.ini`

uwsgi.ini  :
```
[uwsgi]
#uid = uwsgi
#gid = uwsgi
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
#stats = /run/uwsgi/stats.sock
stats = /tmp/uwsgi-stats.sock
#chmod-socket = 660
emperor-tyrant = true
cap = setgid,setuid
```

/uwsgi.d/powerdns-admin.ini
```
[uwsgi]
plugins = python27

uid=nginx
gid=nginx

chdir = /var/www/python/PowerDNS-Admin/ 
pythonpath = /var/www/python/PowerDNS-Admin/
virtualenv = /var/www/PowerDNS-Admin/flask 

mount = /pdns=run.py
manage-script-name = true
callable = app 

vacuum = true
harakiri = 20
post-buffering = 8192
socket = /run/uwsgi/app/%n/%n.socket
chown-socket = nginx
pidfile = /run/uwsgi/app/%n/%n.pid 

daemonize = /var/log/uwsgi/app/%n.log
enable-threads
```

on CentOS 7 NGINX running as `nginx` , so i set uid and gid as `nginx` which the owner `/var/www/html`

**Comment by peshmerge** [comment]
Change the permission of /etc/uwsgi.d/ to uwsgi and it wil work! I spent 3 days searching and re-configuring. 
`chown -R uwsgi:uwsgi /etc/uwsgi.d/` 
I have Centos 7,  uwsgi is installed system-wide and my_site.ini was placed under /etc/uwsgi.d/my_site.ini. 
In my_site.ini I had the gid en uid as follows: 
`uid=svc.flexface`
`gid=nginx`
