### ISSUE TITLE
python 2 support broken

### ISSUE THREAD

**Issue by tracernz** [ngoduykhanh/PowerDNS-Admin#232]
b5b3b77acbf404585bbaf75ad41e29cf89e676a2 broke python 2 (urllib.parse doesn't exist in python 2). Python 3 doesn't work with pgsql so now I'm stuck with neither working on master branch.

**Comment by ngoduykhanh** [comment]
Hi,

What os the problem with postgres sql python module in Python3 env?

**Comment by ngoduykhanh** [comment]
To be discussed in #233. For python 2, are we still want to support it ? It going to retire soon... :)
https://pythonclock.org/

**Comment by tracernz** [comment]
I am okay with dropping python 2 as long as python 3 works well. :+1: I was initially disappointed when things didn't work under python 3 (I assumed it wasn't supported since it looked like a bytes/str issue :wink: ).
