### ISSUE TITLE
PostgreSQL broken under Python 3

### ISSUE THREAD

**Issue by tracernz** [ngoduykhanh/PowerDNS-Admin#233]
When creating the first user, insert fails, saying a value doesn't fit in varying(64). The password hash is bytes rather than str so I think that is the issue without delving any deeper.

**Comment by ngoduykhanh** [comment]
ok, i will try to reproduce your issue with PostgreSQL and fix it.

**Comment by tracernz** [comment]
I setup my admin user by checking out a previous version and running under Python 2. Now I set up a py3 venv to get the full error message. This is what I get when creating a regular user:

sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(64) [SQL: 'INSERT INTO "user" (username, password, firstname, lastname, email, avatar, otp_secret, role_id) VALUES (%(username)s, %(password)s, %(firstname)s, %(lastname)s, %(email)s, %(avatar)s, %(otp_secret)s, %(role_id)s) RETURNING "user".id'] [parameters: {'username': 'test', 'password': b'$2b$12$5ipkzYGyiX24fIV9BjUyKeDhGhHzUNMApqwP.0vNq/mGrkgWI2ce6', 'firstname': 'testy', 'lastname': 'tester', 'email': 'testy@tester.com', 'avatar': None, 'otp_secret': None, 'role_id': 2}] (Background on this error at: http://sqlalche.me/e/9h9h)

Note the password hash is type bytes, not str.

**Comment by ngoduykhanh** [comment]
Please try again with commit fc4e9dc9a057f826a99d1a620fa95c62b6db3c4a

**Comment by tracernz** [comment]
fc4e9dc fixes this issue. Thanks very much for promptness! :grin:
