### ISSUE TITLE
Setting up a domain

### ISSUE THREAD

**Issue by c0fe** [ngoduykhanh/PowerDNS-Admin#24]
Ok so I have a dummy domain, adivix.org where my registrar points to my IP address as the place to check for all DNS records. So how do I properly setup the records where the DNS records are setup to point to specific servers on the local network.

Let's take this for example:

192.168.1.100 - IP Address of my DNS server
192.168.1.101 - IP Address of my website host (A record)
192.168.1.102 - IP Address of my mail server (MX record)

So how would I properly set this up so it would properly resolve to local servers on my network (all this is behind a NAT/Firewall/Router) in PowerDNS-Admin?

**Comment by ngoduykhanh** [comment]
Hi @c0fe ,

I don't understand your question. Are you asking about creating records or setting up pdns service? PowerDNS-Admin is just a Web-UI. You can create records with internal ip addresses if you want and make sure that clients are able to connect to dns server (pdns) via port 53, that's all.

**Comment by c0fe** [comment]
I just want to correctly setup the domain via webUI where if someone externally enters "adivix.org" or sends an email what IP addresses should I enter? Public IP or the internal IP?

**Comment by c0fe** [comment]
Maybe I am doing something wrong but I keep getting 404 errors:

https://www.youtube.com/watch?v=4_8CWDmZQjw&feature=youtu.be&hd=1

**Comment by ngoduykhanh** [comment]
@c0fe , Do you have any error message from logfile / console ?

**Comment by c0fe** [comment]
Nope, log is blank

**Comment by ivanfilippov** [comment]
Hi @c0fe,

Try running PowerDNS-Admin directly while we're troubleshooting instead of as a service, that will give you console access and you'll be able to show us any errors.

My guess is that PowerDNS-Admin can't connect to the PowerDNS API and that's causing the 400 error, but the console logs will show for sure.

**Comment by ivanfilippov** [comment]
We haven't heard from @c0fe in over a month, I think we should close this issue. What do you think @ngoduykhanh?

**Comment by ngoduykhanh** [comment]
@ivanfilippov : Yes, I think so. Closing the issue.
