### ISSUE TITLE
Support for not running in root of domain

### ISSUE THREAD

**Issue by decramy** [ngoduykhanh/PowerDNS-Admin#240]
Hey,

Currently I'm running PowerDNS-admin using supervisor at 0.0.0.0:9393. But I want to get the service in a "subdir" of a DNS domain, like https://tools.example.com/PowerDNS-admin/

When I 'just' try to reverseproxy the application at a certain URL, it redirects me to /dashboard, forgetting the subdir.
I did see some hints for 'script_root', but it has not been explained how to use this. I tried setting it in config.py and as entry in the `setting` table, but none worked...

Any ideas?

Tjerk Jan

**Comment by xTrekStorex** [comment]
I am no python dev nor have I ever worked with flask myself but this should solve your issue https://mrl33h.de/post/15

**Comment by joshuaboniface** [comment]
Why close this issue without explanation? This is a very valid feature request that I too would like.
