### ISSUE TITLE
domain_template_record schema definition

### ISSUE THREAD

**Issue by decode13** [ngoduykhanh/PowerDNS-Admin#241]
Hello,

We are using DomainKeys to sign emails and hold the public key in dns.
Please modify the column **data** in domain_template_record to varchar(65535) because large public key text does not fit. 
I recommend 65535 inherited from PowerDNS table structure.

Thanks

**Comment by ngoduykhanh** [comment]
Thanks for your suggestion. I changed data type to TEXT to support longer record data. See commit 8b7653ad4a95f20487886916328bb0745e07e3da.

Tested on MySQL and Postgres latest stable version.
