### ISSUE TITLE
auto_ptr record update throws 'filter' object is not subscriptable.

### ISSUE THREAD

**Issue by aloforte** [ngoduykhanh/PowerDNS-Admin#247]
I'm getting an issue with the auto_ptr record update.
Domains are generated properly, but PTR entries creation fails with logged error:

` [ERROR] Cannot update auto-ptr record changes to domain ******************. DETAIL: 'filter' object is not subscriptable. `

# Env details:
- Debian 9 x86_64
- Python 3.5.3
master HEAD release as of yesterday
running as flask app.
libraries from pip as for requirements.txt BUT SQLAlchemy==1.2.6 (1.2.5 download got broken yesterday).

**Comment by ngoduykhanh** [comment]
This issue has happened since we support python3 recently. Fixed it.
Thanks for raising the issue.
