### ISSUE TITLE
create_db.py: ImportError: No module named 'migrate'

### ISSUE THREAD

**Issue by TCB13** [ngoduykhanh/PowerDNS-Admin#249]
I was following the Step-by-step installation on how to install this, however after running `./create_db.py` I get this error:

```
(flask) root@mcl1:/webroot/powerdns-admin# ./create_db.py
Traceback (most recent call last):
  File "./create_db.py", line 8, in <module>
    from migrate.versioning import api
ImportError: No module named 'migrate'
```

Some system info:
```
python --version
Python 2.7.13
pip --version
pip 10.0.0 from /web/powerdns-admin/flask/local/lib/python2.7/site-packages/pip (python 2.7)
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

How can I fix this? Thank you.

**Comment by ngoduykhanh** [comment]
`./create_db.py` is supposed to run with python3, not python2. How did create your flask virtualenv and install the package in requirements.txt?

**Comment by TCB13** [comment]
@ngoduykhanh yes I did, no errors there.

**Comment by TCB13** [comment]
Using python 3 fixes this. `virtualenv --python=/usr/bin/python3 flask`
