### ISSUE TITLE
Centos 7 and pwdns 4.1 supported?

### ISSUE THREAD

**Issue by santxus** [ngoduykhanh/PowerDNS-Admin#251]
Hi All

This project looks amazing but not sure if is supporting Centos 7 and the new versions of pwdns. I see that the project is not dead and wll be updated, could someon confirm if is going to add this functionality ?

I'm not developer but i can help testing or translating to spanish for example.

Thanks in advance

**Comment by ngoduykhanh** [comment]
Yes, PowerDNS-Admin supports that. As long as you can run python3 and installed all requirements library, you can run it.

**Comment by santxus** [comment]
Could I find any step by step or manual to install PowerDNS-Admin on CentOS 7?
Thank you so much

**Comment by xTrekStorex** [comment]
It's literally all over the wiki. https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Install-PowerDNS-Admin-in-Fedora-23

But in short:

- cd to path of your choice (I'd use /opt)
- git clone <this repository>
- cp config{_template,}.py
- <add your settings to config.py>
- install python3, virtualenv, python3-dev (incl pip3) via package manager of your choice
- virtualenv flask (or name of your choosing)
- source ./flask/bin/activate (loads virtualenv)
- pip3 install -r requirements.txt (important AFTER virtualenv otherwise you install python package for system env)
- ./create_db.py
- ./run.py to start it

all .py files should default to python3 but to be sure you can also execute them via python3 <file> - do NOT use python2.

to run it as a service e.g. with systemd:
- vi /etc/systemd/system/pdnsadmin.service according to this https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Systemd-example

**Comment by santxus** [comment]
Thanks guys, I'm doind the steps, but i have the next eerror

(flask) [root@testdns1 PowerDNS-Admin]# pip3 install -r requirements.txt
Collecting Flask==0.12.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 18.3MB/s 
Collecting Flask-WTF==0.14.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Flask-Login==0.4.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz
Collecting Flask-OAuthlib==0.9.4 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/0e/8a/775cd729baec72ce388c175e7aa0cba3a7a0b7740c5a5803d335235d38df/Flask-OAuthlib-0.9.4.tar.gz
Collecting Flask-SQLAlchemy==2.3.2 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting SQLAlchemy==1.2.5 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7e/57/435347429f4ff5016b72c9b179c70a6cc67e5f9b4d3f3e9b51362c40b356/SQLAlchemy-1.2.5.tar.gz (5.6MB)
    100% |████████████████████████████████| 5.6MB 7.5MB/s 
Collecting sqlalchemy-migrate==0.10.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/83/c8/c9b30792222210e0c19c7dfc26ea3b777382417ea48ae9d9d02619de81ac/sqlalchemy-migrate-0.10.0.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 33.2MB/s 
Collecting mysqlclient==1.3.12 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 34.2MB/s 
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9lrn1v4t/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-9lrn1v4t/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-9lrn1v4t/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9lrn1v4t/mysqlclient/

Could someone help me?

**Comment by xTrekStorex** [comment]
You are missing the mysql dev libs.
on debian those packages are called libmysqlclient-dev/libmariadbclient-dev/libmariadb-dev.
(or you can install a full mysql-server which includes the libs but thats totally wrong for a pure DB client node)

so for CentOS it's probably something like libmysqlclient-devel
