### ISSUE TITLE
Reload after apply changes

### ISSUE THREAD

**Issue by zepich** [ngoduykhanh/PowerDNS-Admin#253]
In the commit 84d4bfa (https://github.com/ngoduykhanh/PowerDNS-Admin/commit/52b6966c83a1c0d53557af2362c6d2cd8c1549df / Fix for #183) you've added a new javascript function 'applyRecordChanges'. Compared with the 'applyChanges' function, the parameter 'refreshPage' is missing.

The problem now is, that it is not possible to apply changes multiple times. If i add a new record i can apply the changes and PowerDNS sends the notifications to the slaves. But if i add another record without refreshing the page, the record got saved (and the serial gets increased) but no notification will be sent to the slaves.

I tried to find the root of this problem but i wasn't able to find it. My solution is to add the 'refreshPage' parameter and refresh the page after the changes got applied. With this easy solution it is working perfectly, but i don't know if you maybe have a better solution to fix this problem. 

If you would like i can send you a pull request for this fix (my change: https://github.com/zepich/PowerDNS-Admin/commit/81214840164bd1fb594e407304855c81c10acae6).

**Comment by ngoduykhanh** [comment]
Although refresh flag is available in `applyChanges` function but it wasn't used before i made that change. We don't do the page refresh to get the applying result (FAIL / SUCCESS message). See [this line](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/17a892b18d1c502928c535c346723b129ff253f1#diff-db810e8f2e3155d61e926d78e5eae5fbR203).

However, your issue looks weird to me, i can't see any reason why refreshing the page can solve your problem.

**Comment by zepich** [comment]
I'm sorry. I didn't read the code carefully enough and misinterpreted the 'true' at the end of the function (i was a little bit tired yesterday ;)).

I've reverted my changes and tried to find the problem again. I recognized that the serial wasn't increased after the second apply of the changes (i didn't checked that carefully enough yesterday). But if i edit the SOA record and increase the serial manually (to the serial from the first 'apply changes'), the changes got applied and transfered to the slaves.

I tried to add a solution do this automatically. You can find my changes here (i deleted the previous fork): https://github.com/zepich/PowerDNS-Admin/commit/301c3bbad6d97edef46757863a3bac713a5a12c6

For me it's a dirty fix because the fix rely on a class name. If you have a better idea how we can do this please let me know.

With this change, everything works as expected. Compared with my earlier solution it makes sense: with the refresh of the page the SOA record in the table got the new serial and an additional 'apply changes' call sent the right serial to PowerDNS.
