### ISSUE TITLE
Systemd service creation

### ISSUE THREAD

**Issue by cyrilcros** [ngoduykhanh/PowerDNS-Admin#259]
Hi,  here are a few comments:

- please mention clearly that this is a Python 3 project (some Linux flavors use Python 2 by default)
- about systemd service files: you can use the example systemd file from the Wiki but only after running `useradd --system --user-group powerdnsadmin` to create an user for the service, and creating a log file owned by this group with `touch YOURLOGFILE` / `chown powerdnsadmin:powerdnsadmin YOURLOGFILE`.

Thanks for this great project!

**Comment by ngoduykhanh** [comment]
Thanks for the suggestion. I am going to update the WIKI and README.
