### ISSUE TITLE
BUG: "Home" in the breadcrum is linked to /

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#26]
When operating in a subdirectory the "Home"-Link in the breadcrumb should not point to /.

Instead it should point to the /subdirectory it is running in.

**Comment by ivanfilippov** [comment]
Hi @piwats 

Do you mean when you proxy PowerDNS-Admin behind a subdirectory like:

http://example.com/powerdnsadmin

**Comment by piwats** [comment]
The Setup I am using is described in #23.

**Comment by ivanfilippov** [comment]
I've replicated your environment here and made a fix that works for me. Would you be able to test with my branch?

You'll need to add a new remote, fetch my branches and switch to the branch with the fix:
`git remote add ivanfilippov https://github.com/ivanfilippov/PowerDNS-Admin.git`
`git fetch ivanfilippov`
`git checkout breadcrumb_fix`

After that, restart uWSGI and see if that will work for you, if it does then I'll submit a PR to have that code in the main repo and if it's approved you can switch back to the main repo.

**Comment by piwats** [comment]
Thank you! Seems to work 👍

**Comment by ngoduykhanh** [comment]
@ivanfilippov : Your changes look good to me. Please submit a PR. Thank you!
