### ISSUE TITLE
Someone has working on CentOS 7?

### ISSUE THREAD

**Issue by santxus** [ngoduykhanh/PowerDNS-Admin#261]
Hi guys 

Is someone has pdns 4.1 and powerdns admin working on centos 7 and can help me with the installation steps?

Than you so much guys

**Comment by ngoduykhanh** [comment]
Following is the guide to install PDA on Centos 7.
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7

For pdns 4.1 service, please take a look at their official website. Basically you will need to use their repository and install `pdns` + db backend package.

**Comment by santxus** [comment]
selinux and firewall disabled

**Comment by santxus** [comment]
I did a step by step guide for Centos 7, pdns + recursor + DNS-admin, if interesting i can send to you
