### ISSUE TITLE
SOA-EDIT-API setting invalid

### ISSUE THREAD

**Issue by tmuncks** [ngoduykhanh/PowerDNS-Admin#262]
I've spent some time figuring out why I couldn't get the various `SOA-EDIT-API` options listed in PowerDNS-Admin, to make a difference in behaviour.

As it turns out, it's because the options that PowerDNS-Admin presents (and sets in the database) are actually the options for `SOA-EDIT`, which is a vastly different setting (although it sounds very similar).

The proper list of options usable for `SOA-EDIT-API` are the ones specified for `SOA-EDIT-DNSUPDATE` and are as follows:

* `DEFAULT`: Generate a soa serial of YYYYMMDD01. If the current serial is lower than the generated serial, use the generated serial. If the current serial is higher or equal to the generated serial, increase the current serial by 1.
* `INCREASE`: Increase the current serial by 1.
* `EPOCH`: Change the serial to the number of seconds since the EPOCH, aka unixtime.
* `SOA-EDIT`: Change the serial to whatever SOA-EDIT would provide. See Domain metadata
* `SOA-EDIT-INCREASE`: Change the serial to whatever SOA-EDIT would provide. If what SOA-EDIT provides is lower than the current serial, increase the current serial by 1.

For PowerDNS-Admin, I suspect the `SOA-EDIT` and `SOA-EDIT-INCREASE` options are probably too advanced and requires some knowledge of the underlying DNS and is not for the average DNS admin. Perhaps it makes sense to exclude those from PowerDNS-Admin.

References are here:
https://doc.powerdns.com/md/httpapi/api_spec/#zones (Specifies that `SOA-EDIT-API` options are the same as for `SOA-EDIT-DNSUPDATE`)
https://doc.powerdns.com/md/authoritative/dnsupdate/#soa-serial-updates (Provides the options list for `SOA-EDIT-DNSUPDATE`)

**Comment by ngoduykhanh** [comment]
Thank you for raising the issue. The options in SOA-EDIT-API were taken from PowerDNS manual and haven't been updated for a long time. Some options are deprecated in PowerDNS 4.1 so we need to update them.

I agree with you about `SOA-EDIT` and `SOA-EDIT-INCREASE`. Let's do it as your opinion and reconsider in the feature if needed.

I am looking to your PR. Thanks.
