### ISSUE TITLE
Please add a per-domain comment

### ISSUE THREAD

**Issue by tmuncks** [ngoduykhanh/PowerDNS-Admin#267]
There are several times where a comment for a domain would be useful.

In my case, we handle a lot of different domains, for a lot of different customers. Having a per-domain comment (and having it visible in the dashboard), would make it much easier to track/remember which domain belongs to which customer, who at the customer site normally manages the domain etc.

The PowerDNS API allows a comment to be set per-record, and perhaps setting this comment on the SOA record would be a great way of storing that information for the domain.

What do you think?

**Comment by tmuncks** [comment]
Having looked at the API a bit more closely, PowerDNS has a built-in per-domain `account` parameter, that would be perfect for this. It is stored with the domain in the database and designed for local use.

https://doc.powerdns.com/md/httpapi/api_spec/#zones - see parameters here.

**Comment by ngoduykhanh** [comment]
Yes, this feature has been mentioned before but i still haven't had time for it yet. I will try to implement it when i have time :).

**Comment by tmuncks** [comment]
I can try to do a PR for it...

**Comment by tmuncks** [comment]
Pull request #269 fixes this in a slightly more elaborate way.

**Comment by tmuncks** [comment]
@ngoduykhanh feel free to close this issue, unless you feel a different type of per-domain comment would make sense, in addition the Account stuff.
I can see the use case for a per domain "free text" comment, but my initial idea with this issue, was to keep track of domain ownership, which the Account stuff takes care of.
