### ISSUE TITLE
Make width 100%

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#27]
It would be great, if you could change the width to 100%. Else the space is not used.

**Comment by ivanfilippov** [comment]
I like this idea as well, I've put up a sample implementation here https://github.com/ivanfilippov/PowerDNS-Admin/tree/width_fix for review

**Comment by ivanfilippov** [comment]
I somehow broke my branch and made an empty commit. I've now fixed that for review.

**Comment by ivanfilippov** [comment]
This is fixed in the `new_ui` branch. This is a new branch with a new template and I'm still testing it so I don't recommend it for daily use. Once merged into master this issue can be closed.

**Comment by ngoduykhanh** [comment]
We can set the width 100% now with PR  #50
