### ISSUE TITLE
Record edit and delete buttons disappear when record name is "adserv"

### ISSUE THREAD

**Issue by xTrekStorex** [ngoduykhanh/PowerDNS-Admin#270]
For whatever reason (couldn't find anything in the source code) when I set a DNS record named "adserv" the edit and delete buttons disappear. No matter what kind of record or what value.

I also tried different variations of "ad", "adservnet", "serv", "dserv" etc but it only applies to "adserv".
On existing records you can still edit via clicking on the record but you can't delete it that way.

![image](https://user-images.githubusercontent.com/3179810/40908415-fbc6ff1e-67e6-11e8-80d7-de281b82efba.png)

**Comment by saschaludwig** [comment]
Could this be an adblocker gone wild? :-D (just a wild guess)

**Comment by xTrekStorex** [comment]
I didn't even think of that... spot on. Turning uBlock off fixes it 🙈
