### ISSUE TITLE
Calling the zone-sync script from within a cronjob

### ISSUE THREAD

**Issue by rodehoed** [ngoduykhanh/PowerDNS-Admin#278]
Hi,

It seems there is some work in progress moving the "zone-sync" to a BG process. Which is a  good first step! We are serving around 10K zones and the sync process could be a real pain sometimes :-) 

But maybe it would be good too, to be able run this process from a cron (or cli as you want). This way we can have an up2date list even when people do not login.

**Comment by ngoduykhanh** [comment]
It is your choice. The route is available so you call it via a script in cronjob.
We can also implement queue/worker for this task. However, it looks overkill to me for this project :).

**Comment by rodehoed** [comment]
I made a python script which can be called directly on the CLI. Are you interested in a PR? 

I think it's wise that BG_DOMAIN_UPDATES is on true. So this makes it harder that AND the CLI version AND the auto-update function are running on the same time. What do you think?

**Comment by rodehoed** [comment]
I created a PR request https://github.com/ngoduykhanh/PowerDNS-Admin/pull/281

**Comment by tmuncks** [comment]
Maybe a matter of personal taste, but I actually like a "curl" solution better - something like:

curl https://user:pass@dns.example.com/dashboard-domains-updater

It's simpler, easier and cleaner to me and while I haven't tested it, should just work. Also, this approach can be easily extended to other housekeeping jobs, without the need additional local scripts, when the functionality we need is already there.

It also saves setting up the virtualenv/flask stuff and risking log files becoming owned by root and such.

Just my few cents. :)

**Comment by rodehoed** [comment]
@ctp-tsteenholdt ye maybe it is for you :-)  As a policy we don't run potentially long running tasks thru a webserver. Just to get rid of possible webserver limits (timeouts etc) .... so for us a cron is the best way. 

I'm presuming people who are using this software are not your averages-Joe's and know how to properly make use of a cron (non-root).
