### ISSUE TITLE
migrations need to be in source control

### ISSUE THREAD

**Issue by jsenecal** [ngoduykhanh/PowerDNS-Admin#285]
As per [Flask-Migrate documentation](http://flask-migrate.readthedocs.io/en/latest/#example), the contents of this folder (migrations) need to be added to version control along with your other source files.

Otherwise, starting a new installation with an already populated db yields errors such as `alembic.script.revision.ResolutionError: No such revision or branch '25468bf02131'`

Basically, what you are doing in [docker/PowerDNS-Admin/entrypoint.sh#L5-L14](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docker/PowerDNS-Admin/entrypoint.sh#L5-L14) breaks if the DB already has data in it.

**Comment by tmuncks** [comment]
Makes sense to me that the various scheme versions and the way you migrate between versions should be controlled by the project, not by the user, in order to be successful.

**Comment by ngoduykhanh** [comment]
Agree. I removed it from .gitignore file and add the first version of migration script to [master](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/d2a5adc027f81407612451c2eb1394181870dd2f). Let me know if it have any issue :).

**Comment by jsenecal** [comment]
@ngoduykhanh  you could also adapt [/docker/PowerDNS-Admin/entrypoint.sh#L5-L14](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docker/PowerDNS-Admin/entrypoint.sh#L5-L14) to only do the migrations

I'll test soon and let you know :)

**Comment by jsenecal** [comment]
Wait - I realized in https://github.com/ngoduykhanh/PowerDNS-Admin/commit/d2a5adc027f81407612451c2eb1394181870dd2f that you are also inserting default data there - I guess it makes sense but it will break existing installations if not careful 

Also, for existing installations a manual operation is required to "fake" the initial migration - using `flask db stamp 787bdba9e147` should work in most cases

**Comment by sschamp** [comment]
Instead of flask db stamp 787bdba9e147
I did:

INSERT INTO alembic_version (version_num) VALUES ('787bdba9e147');


That would also be correct, no?
