### ISSUE TITLE
Add the ability to disable the "quick record edit" feature in config/settings

### ISSUE THREAD

**Issue by jsenecal** [ngoduykhanh/PowerDNS-Admin#288]
Currently, when clicking on a record text, the UI automagically behaves as if one clicked on the `Edit` button of that record.

This behavior prevents one from copy/pasting data from another record whilst editing/creating one.
It also breaks the UI because a _pending_ edit remains and it is now impossible to either create another Record or access that _current_ record.

Let me know if you need help on reproducing this issue.

**Comment by tmuncks** [comment]
I have a fix ready for this, pending #287 merge (I'm utilizing the infrastructure provided in #287 to provide the setting functionality). If that PR gets merged, I can easily do a new PR to fix this.
