### ISSUE TITLE
Systemd wiki example error(?)

### ISSUE THREAD

**Issue by fenice2** [ngoduykhanh/PowerDNS-Admin#297]
I've just created a new install of PowerDNS-Admin on a new centos7 server (fully updated to the current version).

When I create the systemd service as shown in the wiki article it fails to start with permission errors unles the owner:group is change on the following files:

chown -R powerdnsadmin:powerdnsadmin  /opt/web/powerdns-admin/app

Is this a bug or have I missed something?

**Comment by ngoduykhanh** [comment]
`powerdnsadmin` is just an example username for systemd config. You have to make sure that user has write permission to the PowerDNS-Admin directory to write log files.

**Comment by fenice2** [comment]
So the answer was yes, I missed something!  My mistake and sorry for the noise. :)
