### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by itcultus** [ngoduykhanh/PowerDNS-Admin#299]
I really struggle to make the application usable. All the documents in the Wiki are focused mainly for development and nothing is comprehensive. There is no end-to-end document (the only one that is **close** to that is the Fedora's one). 
There is no mention about the PowerDNS database (do we simply modify the PowerDNS database, or the Admin DB is a different one?), there is no clear explanation about other PowerDNS backends (do they even work?)

Generally, I do like the application. But the lack of documentation means that we cannot suggest it to the DNS admins.

**Comment by xTrekStorex** [comment]
The DB used by PDA is a dedicated one that holds roles, users, 2FA secrets, history and a synched state of the domain table of the actual PowerDNS DB (refreshed when loading the dashboard or applying changes). 
Roles and users can be outsourced to other authentication services.

PDA does not use any PowerDNS backends so there is no need to list compatible ones.
All it does is communicate with the PDNS service via its JSON API.

About the quality of documentation: I agree there is none. But this project is changing so much all the time that all docs would have been useless by now anyways. The migration from python2 to python3 alone changed the entire process. Also depending on the OS the virtualenv approach with flask can be quite daunting. Especially when you usually don't run python apps and don't know uWSGI.

I personally run PDA for over a year now as a Puppet deployed virtualenv. But with the latest changes tp flask, the DB, pip3 modules etc that deployment process started to struggle. So I am considering to just use Docker as that is what devs seem to push the most and actually test. Not that I really want to...

Btw you can add any docs yourself if you feel like it.. I did so for the undocumented DDNS feature - pulled from the code.

**Comment by itcultus** [comment]
Exactly. 
I plan to write a detailed Wiki for the CentOS 7 integration, step by step. My experience with Python apps is non-existent (I was a PHP dev before going to Linux Engineering roles), so, I needed detailed documentation. I managed to complete my installation with the help of a python dev, so, after everything is in place, I will contribute to the docs.

**Comment by ngoduykhanh** [comment]
What @xTrekStorex is true.

Also, there are several ways to deploy PowerDNS-Admin, we cannot cover all, just give common examples of deployment.

If you find any useful info need to add, WIKI contribution is welcome :)
