### ISSUE TITLE
Display records in a verbatim font (monospace)

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#30]
Would it be possible to display the records in a font that is fixed-width or non-proportional, like monospace or equivalent?

**Comment by ivanfilippov** [comment]
:+1: 

I like this change, it makes comparing records much quicker.
Default:
![default](http://i.imgur.com/xE7G4Yl.jpg)
Monospaced:
![monospaced](http://i.imgur.com/OvcY959.jpg)

I have a sample implementation at https://github.com/ivanfilippov/PowerDNS-Admin/tree/fonts 

@ngoduykhanh if you're interested in this change, I'll submit a PR.

**Comment by ngoduykhanh** [comment]
@ivanfilippov Yes, this font looks much more better than the default one. Feel free to submit the PR

**Comment by ivanfilippov** [comment]
Submitted PR #32

**Comment by piwats** [comment]
Thank you all very much 👍

**Comment by piwats** [comment]
Related: #35
