### ISSUE TITLE
Break lines when displaying records, which are very long (Issue #28)

### ISSUE THREAD

**Issue by ntinti** [ngoduykhanh/PowerDNS-Admin#302]
Hi

it seems the code which fixed that issue is gone in the actual version (no "table-editable.js" anymore)? Long DKIM code makes edting a domain painfull if there is no 30" monitor in front becouse the buttons to save a record are unreachable on normal browser width. Also a horizontal scrollbar would help.

Nicola

**Comment by ngoduykhanh** [comment]
I was removed long time ago because we changed the UI. I did push another commit to add `length-break` class for data column.
