### ISSUE TITLE
Upgrade procedure for existing install

### ISSUE THREAD

**Issue by akront** [ngoduykhanh/PowerDNS-Admin#305]
Hello,

Sorry this might be basic, but what is the right procedure to upgrade an old install?

I have PowerDNS-Admin running for a few months on Ubuntu 16 LTS

Thank you

**Comment by ngoduykhanh** [comment]
There are several changes in the code and db schema / migration steps. I suggest you to clone the latest code and follow the [WIKI guide](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-16.04---Ubuntu-18.04) to run PowerDNS-Admin. All pdns domains will be loaded automatically in the first time you access the dashboard. For the users and permission you have to check and migrate manually.
