### ISSUE TITLE
pdns 4.1.3 install issues

### ISSUE THREAD

**Issue by sergiopcesar** [ngoduykhanh/PowerDNS-Admin#306]
I am new with pdns looking to manage it a little easier.
I was able to install pdns_server and the recursor on a ubuntu 16.04, imported all data from bind and it is responding to queries OK.
Try to follow the flask howto  and after a few hiccups I was able create a admin user, login and created an account, 
unfortunately none of my domains show to be managed.

I try to add one manually but got error 400.
Is there a document that describe how this all is supposed to work? configure powerdns-admin to play with pdns latest release, how to create templates etc.
thanks
sc

**Comment by ngoduykhanh** [comment]
Have you specified pdns version and its API key in the `config.py` file ?

**Comment by sergiopcesar** [comment]
yes, 
I see this in the logfile:
2018-07-09 17:07:53,390 - app.models - ERROR - Config Option "api-config-dir" must be set
I did not find an entry in the config file for this, I added 
API_CONFIG_DIR = "/var/www/powerdns-admin"
no more errors and nothing on domain list. still not able to add a domain error 400.
and ignorant on how to create a template.
