### ISSUE TITLE
Install with Docker 

### ISSUE THREAD

**Issue by mike-norris** [ngoduykhanh/PowerDNS-Admin#309]
docker-compose up is throwing the following
powerdns-admin          | ===> Waiting for powerdns-admin-mysql MySQL service
powerdns-admin          | DNS fwd/rev mismatch: powerdns-admin-mysql != powerdns-admin-mysql.powerdnsadminmaster_default
powerdns-admin          | powerdns-admin-mysql [172.18.0.2] 3306 (mysql) open
powerdns-admin          | ===> DB management
powerdns-admin          | ---> Running DB Migration
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/bin/flask", line 11, in <module>
powerdns-admin          |     sys.exit(main())
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 513, in main
powerdns-admin          |     cli.main(args=args, prog_name=name)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 380, in main
powerdns-admin          |     return AppGroup.main(self, *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
powerdns-admin          |     rv = self.invoke(ctx)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
powerdns-admin          |     return ctx.invoke(self.callback, **ctx.params)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
powerdns-admin          |     return f(get_current_context(), *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 256, in decorator
powerdns-admin          |     with __ctx.ensure_object(ScriptInfo).load_app().app_context():
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 237, in load_app
powerdns-admin          |     rv = locate_app(self.app_import_path)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 90, in locate_app
powerdns-admin          |     __import__(module)
powerdns-admin          |   File "/powerdns-admin/app/__init__.py", line 25, in <module>
powerdns-admin          |     logging = logger('powerdns-admin', app.config['LOG_LEVEL'], app.config['LOG_FILE']).config()
powerdns-admin          |   File "/powerdns-admin/app/lib/log.py", line 32, in config
powerdns-admin          |     file_log_handler = logging.FileHandler(self.logfile)
powerdns-admin          |   File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
powerdns-admin          |     StreamHandler.__init__(self, self._open())
powerdns-admin          |   File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
powerdns-admin          |     return open(self.baseFilename, self.mode, encoding=self.encoding)
powerdns-admin          | PermissionError: [Errno 13] Permission denied: '/powerdns-admin/logs/log.txt'
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/bin/flask", line 11, in <module>
powerdns-admin          |     sys.exit(main())
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 513, in main
powerdns-admin          |     cli.main(args=args, prog_name=name)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 380, in main
powerdns-admin          |     return AppGroup.main(self, *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
powerdns-admin          |     rv = self.invoke(ctx)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
powerdns-admin          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
powerdns-admin          |     return ctx.invoke(self.callback, **ctx.params)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
powerdns-admin          |     return callback(*args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
powerdns-admin          |     return f(get_current_context(), *args, **kwargs)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 256, in decorator
powerdns-admin          |     with __ctx.ensure_object(ScriptInfo).load_app().app_context():
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 237, in load_app
powerdns-admin          |     rv = locate_app(self.app_import_path)
powerdns-admin          |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 90, in locate_app
powerdns-admin          |     __import__(module)
powerdns-admin          |   File "/powerdns-admin/app/__init__.py", line 25, in <module>
powerdns-admin          |     logging = logger('powerdns-admin', app.config['LOG_LEVEL'], app.config['LOG_FILE']).config()
powerdns-admin          |   File "/powerdns-admin/app/lib/log.py", line 32, in config
powerdns-admin          |     file_log_handler = logging.FileHandler(self.logfile)
powerdns-admin          |   File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
powerdns-admin          |     StreamHandler.__init__(self, self._open())
powerdns-admin          |   File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
powerdns-admin          |     return open(self.baseFilename, self.mode, encoding=self.encoding)
powerdns-admin          | PermissionError: [Errno 13] Permission denied: '/powerdns-admin/logs/log.txt'
powerdns-admin          | ===> Assets management
powerdns-admin          | ---> Running Yarn
powerdns-admin          | chown: changing ownership of '/powerdns-admin/app/static/custom/css/custom.css': Permission denied
powerdns-admin          | chown: changing ownership of '/powerdns-admin/app/static/custom/css': Permission denied
powerdns-admin          | chown: changing ownership of '/powerdns-admin/app/static/custom/js/custom.js': Permission denied
powerdns-admin          | chown: changing ownership of '/powerdns-admin/app/static/custom/js': Permission denied
powerdns-admin          | chown: changing ownership of '/powerdns-admin/app/static/custom': Permission denied
powerdns-admin exited with code 1

**Comment by mike-norris** [comment]
Docker version 1.13.1, build 584d391/1.13.1
OS: Centos 7

**Comment by ngoduykhanh** [comment]
Docker stuff has been updated several times. The latest one works fine for me.
