### ISSUE TITLE
flask assets build failes 

### ISSUE THREAD

**Issue by ptselios-inmarsat** [ngoduykhanh/PowerDNS-Admin#310]
I downloaded the latest master (today) on a CentOS 7 box. I run it as a WSGI application (after installing the appropriate mod_wsgi to support python 3.4). 
The installation was OK up to the point of creating the static files with flask: 
```
(flask) -bash-4.2$  flask assets build
uilding bundle: generated/main.css
[INFO] Building bundle: generated/main.css
Traceback (most recent call last):
  File "/srv/www/powerdns-admin/flask/bin/flask", line 11, in <module>
 ...
....
FileNotFoundError: [Errno 2] No such file or directory: '/srv/www/powerdns-admin/app/static/node_modules/bootstrap/dist/css/bootstrap.css'
```

I followed the instructions in the CentOS 7 Wiki. From the commit comments (July 5, July 6) it looks like it's not needed anymore. Is that true? If it is, where are the static files? 
 
Based on the fact that the application results to error 500 and the log files have a lot of file not found error (like the following), are we sure that the latest version is complete?

`FileNotFoundError: [Errno 2] No such file or directory: '/srv/www/powerdns-admin/app/static/node_modules/bootstrap/dist/css/bootstrap.css'`

**Comment by kanisae** [comment]
Any updates on this issue? I have followed the same steps in the wiki for installing CentOS 7 for a new server and it is failing with the same errors.

**Comment by ptselios-inmarsat** [comment]
This is what I did. I don't remember if there are other steps/minor fixes involved, but this is what I have in my notes:

```
su -
curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
yum install -y httpd-devel python34-setuptools \
    python34-virtualenv python34 python-pip \
    python34-devel python-pip gcc mariadb-devel \
    openldap-devel xmlsec1-devel libtool-ltdl-devel \
    yarn
 
yum install -y policycoreutils-python policycoreutils-pythonsystemc 

pip install pip3
easy_install-3.4 pip
 
mod_wsgi-express install-module > /etc/httpd/conf.modules.d/02-wsgi.conf
mv /etc/httpd/conf.modules.d/10-wsgi.conf /etc/httpd/conf.modules.d/10-wsgi

mkdir -p /srv/www/powerdns-admin/wsgi
chcon -t httpd_sys_rw_content_t /srv/www/powerdns-admin/wsgi/
useradd -s /bin/nologin -M -d /srv/www/powerdns-admin/wsgi -r pdnsadmin

curl -sL https://github.com/ngoduykhanh/PowerDNS-Admin/archive/master.zip -o /tmp/master.zip
cd /tmp
unzip ./master.zip
cp -r ./PowerDNS-Admin-master/* /srv/www/powerdns-admin/
rm -r ./PowerDNS-Admin-master/*
rm ./master.zip
 
cd /srv/www/powerdns-admin/
virtualenv-3 -p python3 flask
. ./flask/bin/activate
pip install -r requirements.txt
 
cp config_template.py config.py
```
Then, configure your installation. 

And finally: 

```
export FLASK_APP=app/__init__.py
flask db upgrade
flask db migrate -m "Init DB"
yarn install --pure-lockfile
flask assets build
deactivate
chown pdnsadmin:pdnsadmin /srv/www/powerdns-admin/ -R
```

**Comment by madmath03** [comment]
I do not know if that will help, but I encountered a similar error message when building a docker container for pdns-admin.

The error `No such file or directory: '/srv/www/powerdns-admin/app/static/node_modules/bootstrap/dist/css/bootstrap.css'` would happen when executing `flask assets build`.

Since yarn install actually installs node modules in a different directory, I simply fixed this by adding a symlink : 
```
yarn install --pure-lockfile
ln -sf "$(pwd)/node_modules" ./app/static/node_modules
flask assets build
```

For those interested in complete code, docker container available here : https://github.com/Monogramm/docker-powerdns-admin
