### ISSUE TITLE
Cannot change passwords

### ISSUE THREAD

**Issue by denschub** [ngoduykhanh/PowerDNS-Admin#324]
Apparently, changing passwords from the profile view is broken. On submitting the form, it correctly submits a `POST /user/profile`, which the server responds to with a 200. However, the change does not seem to reach the database, as the old password still has to be used to login.

I am running on 501b8178081246c21246ae62cc5ed337088d7da6, and there is no information in the log.

**Comment by denschub** [comment]
Hmm, interesting.

I run gunicorn, basically following [this](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-16.04---Ubuntu-18.04) setup. I run on Ubuntu 16.04, with Postgres 9.5.

**Comment by denschub** [comment]
... after hitting submit, I remembered I could enable Postgres info logging. And sure enough...

```
2018-08-07 04:29:36 CEST [5672-1] pdns-admin@pdns-admin ERROR:  value too long for type character varying(64)
2018-08-07 04:29:36 CEST [5672-2] pdns-admin@pdns-admin STATEMENT:  UPDATE "user" SET password='[foo]'::bytea WHERE "user".id = 1
```

**Comment by ngoduykhanh** [comment]
I guess the created password hash was longer than 64 characters for some reasons. You can try to extend the current limit of password column on your Postgresql db or print the password hash after [this line](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L342) to verify it.
