### ISSUE TITLE
rebuild PowerDNS-admin to change configration

### ISSUE THREAD

**Issue by MohamadBrham** [ngoduykhanh/PowerDNS-Admin#327]
I have installed powerDNS-admin on Centos server with pgsql database inside python virtual environment, and gunicorn to run as a service.
I want to change some configurations in the config.py file, but how to reflect those changes to powerDNS-admin??
for ex. disabling SignUp ?

**Comment by ngoduykhanh** [comment]
You can make changes directly to `config.py` and reload your web application. For disabling SingUp, you can use `SIGNUP_ENABLED` config. Not sure if i understand your question correctly....

**Comment by ngoduykhanh** [comment]
Almost configuration is migrated to DB now. We can make changes in _Setting_ menu from PDA UI.
