### ISSUE TITLE
[RFE] Logout button not easily visible

### ISSUE THREAD

**Issue by tjyang** [ngoduykhanh/PowerDNS-Admin#332]
I spent sometime and finally found the logout button.

![image](https://user-images.githubusercontent.com/378638/44001456-2790d22c-9df8-11e8-8933-000add1b18a6.png)

Is it possible to have both buttons in color other than existing white ?

**Comment by tmuncks** [comment]
Would something like this work for you?

![screenshot from 2018-08-12 14-12-51](https://user-images.githubusercontent.com/9822186/44003968-e62d1588-9e39-11e8-84d2-326194919a80.png)

**Comment by tjyang** [comment]
@tmuncks 
Above color scheme is ok to me, at least "Log out" and "My profile" are more visible to me. 
But I think from (IMO) GUI design view, the two buttons' should have light blue backgroup, like the "User Usersen".

**Comment by splog123** [comment]
Orange logout button? Yes please!
