### ISSUE TITLE
AD integration

### ISSUE THREAD

**Issue by tavaresrick** [ngoduykhanh/PowerDNS-Admin#335]
Hello, I'm trying to integrate the app with my local AD services.

I've created an group on the AD and I want all users in this group to have access to the application and automatically became Admins, my current config is this:

# AD CONFIG
LDAP_TYPE = 'ad'
LDAP_URI = 'ldaps://foo.corp:636'
LDAP_USERNAME = 'cn=svc_powerdns,ou=Services_TI,ou=sao_paulo,ou=usuarios,dc=foo,dc=corp'
LDAP_PASSWORD = 'p@ssword'
LDAP_SEARCH_BASE = 'ou=usuarios,dc=foo,dc=corp'
# You may prefer 'userPrincipalName' instead
LDAP_USERNAMEFIELD = 'sAMAccountName'
# AD Group that you would like to have accesss to web app
LDAP_FILTER = '(memberof=cn=gs_powerdns_admin,ou=Grupos,ou=sao_paulo,ou=usuarios,dc=foo,dc=corp)'

Is it possible to do that?

**Comment by ngoduykhanh** [comment]
Let's discuss on #337 . Closing this one.
