### ISSUE TITLE
IndexError viewing one domain

### ISSUE THREAD

**Issue by MaxDiOrio** [ngoduykhanh/PowerDNS-Admin#343]
I recently upgraded pdns from 3.something to 4.1.3.  Everything is working perfectly after updating the API version in pdns-admin - except for viewing the records in a single domain.

When I go to view the records, I receive an error 500, and the following is logged:

>Aug 28 08:51:12 la-1pbind01 gunicorn: [DEBUG] http://127.0.0.1:8081 "GET /api/v1/servers/localhost/zones/dev.clientservices HTTP/1.1" 200 1074
Aug 28 08:51:12 la-1pbind01 gunicorn: [2018-08-28 08:51:12,310] ERROR in app: Exception on /domain/dev.clientservices [GET]
Aug 28 08:51:12 la-1pbind01 gunicorn: Traceback (most recent call last):
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
Aug 28 08:51:12 la-1pbind01 gunicorn: response = self.full_dispatch_request()
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
Aug 28 08:51:12 la-1pbind01 gunicorn: rv = self.handle_user_exception(e)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
Aug 28 08:51:12 la-1pbind01 gunicorn: reraise(exc_type, exc_value, tb)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
Aug 28 08:51:12 la-1pbind01 gunicorn: raise value
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
Aug 28 08:51:12 la-1pbind01 gunicorn: rv = self.dispatch_request()
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
Aug 28 08:51:12 la-1pbind01 gunicorn: return self.view_functions[rule.endpoint](**req.view_args)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/flask/lib/python3.4/site-packages/flask_login/utils.py", line 261, in decorated_view
Aug 28 08:51:12 la-1pbind01 gunicorn: return func(*args, **kwargs)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/app/decorators.py", line 27, in decorated_function
Aug 28 08:51:12 la-1pbind01 gunicorn: return f(*args, **kwargs)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/app/views.py", line 560, in domain
Aug 28 08:51:12 la-1pbind01 gunicorn: zone_info = r.get_record_data(domain.name)
Aug 28 08:51:12 la-1pbind01 gunicorn: File "/opt/web/powerdns-admin/app/models.py", line 1290, in get_record_data
Aug 28 08:51:12 la-1pbind01 gunicorn: rrset['content'] = rrset['records'][0]['content']
Aug 28 08:51:12 la-1pbind01 gunicorn: IndexError: list index out of range

The domain records themselves look fine:

>MariaDB [pdns]> select * from records where domain_id=9
    -> ;
+----+-----------+----------------------+------+-----------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| id | domain_id | name                 | type | content                                                                                       | ttl  | prio | change_date | disabled | ordername | auth |
+----+-----------+----------------------+------+-----------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| 36 |         9 | *.dev.clientservices | A    | 10.85.164.26                                                                                  |  600 |    0 |        NULL |        0 | NULL      |    1 |
| 37 |         9 | dev.clientservices   | SOA  | la-1pbind01.internal.ieeeglobalspec.com admin.ieeeglobalspec.com 2018071601 900 600 86400 300 |  600 |    0 |        NULL |        0 | NULL      |    1 |
| 38 |         9 | dev.clientservices   | NS   | la-1pbind01.internal.ieeeglobalspec.com                                                       |  600 |    0 |        NULL |        0 | NULL      |    1 |
+----+-----------+----------------------+------+-----------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
3 rows in set (0.00 sec)

Any thoughts?

**Comment by ngoduykhanh** [comment]
The schema itself looks OK. However, the returned `rrset['records']` didn't have any value i guess. In order to do the further debugging, you can query directly to the PDNS API to see the return value

`http://your-api-host/api/v1/servers/localhost/zones/your-domain`

**Comment by MaxDiOrio** [comment]
Here's the result from the API.

[[LAColo-Prod] root@la-1pbind01 ~]# curl -H 'X-API-KEY: k8s' http://localhost:8081/api/v1/servers/localhost/zones/dev.clientservices | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1074  100  1074    0     0  96809      0 --:--:-- --:--:-- --:--:--  104k
```
{
  "account": "",
  "api_rectify": false,
  "dnssec": false,
  "id": "dev.clientservices.",
  "kind": "Native",
  "last_check": 0,
  "masters": [],
  "name": "dev.clientservices.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "*.dev.clientservices.",
      "records": [
        {
          "content": "10.85.164.26",
          "disabled": false
        }
      ],
      "ttl": 600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "dev.clientservices.",
      "records": [
        {
          "content": "la-1pbind01.internal.ieeeglobalspec.com. admin.ieeeglobalspec.com. 2018071601 900 600 86400 300",
          "disabled": false
        }
      ],
      "ttl": 600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "dev.clientservices.",
      "records": [
        {
          "content": "la-1pbind01.internal.ieeeglobalspec.com.",
          "disabled": false
        }
      ],
      "ttl": 600,
      "type": "NS"
    },
    {
      "comments": [
        {
          "account": "Max",
          "content": "My first API-created zone",
          "modified_at": 1531761520
        }
      ],
      "name": "dev.clientservices.",
      "records": [],
      "ttl": 0,
      "type": "TYPE0"
    }
  ],
  "serial": 2018071601,
  "soa_edit": "",
  "soa_edit_api": "INCEPTION-INCREMENT",
  "url": "/api/v1/servers/localhost/zones/dev.clientservices."
}
```

**Comment by ngoduykhanh** [comment]
The error came from this piece json. `records` is empty and `type` looks weird. How did you create this data?
```
    {
      "comments": [
        {
          "account": "Max",
          "content": "My first API-created zone",
          "modified_at": 1531761520
        }
      ],
      "name": "dev.clientservices.",
      "records": [],
      "ttl": 0,
      "type": "TYPE0"
    }
```

**Comment by MaxDiOrio** [comment]
It was created using the API and the following:

{
    "comments": [
        {
            "account": "Max",
            "content": "My first API-created zone",
            “name”: “dev.clientservices.”,
            “type”: “Zone”
        }
    ],
    "kind": "Native",
    "masters": [],
    "name": "dev.clientservices.",
    "nameservers": [
        "la-1pbind01.internal.ieeeglobalspec.com"
    ],
   “soa_edit_api”: “INCEPTION-INCREMENT”,
    "records": [
        {
            "content": "10.85.164.26",
            "disabled": false,
            "name": "*.dev.clientservices",
            "ttl": 600,
            "type": "A",
            “set-ptr”: true
        }
    ]
}

**Comment by ngoduykhanh** [comment]
According to https://github.com/PowerDNS/pdns/issues/2130, `TYPE0` indicates that you have unsupported record type in your zone. I guess pdns removed that type in your current version.

**Comment by MaxDiOrio** [comment]
That was it - looks like they got rid of the zone type.  I deleted the zone and re-created it via API without that type and it's coming up fine now.  Thanks!
