### ISSUE TITLE
[BUG] Delte Entrys from Template

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#346]
Hi :-)

I've created from a domain a template and have to delete all the useless records from that template.

If you delete entrys from a template (more as 1 or 2 before you "Apply changes") it happens about 50% of a time, that it deletes some other entrys too... Seems like a bug...

Just that you can test too:
Add an Template from a domain with 15 or more entrys... Than go into that Template and delete 5 entrys or so, you will see, that its going to delete some other things too :-)

If you delete entrys from a domain itself (not a template) everything is perfect, just happens with Templates...

The only one bug ive found :-)

Thank you for your work, i love this admin panel!!!!

Cheers :-)

**Comment by ngoduykhanh** [comment]
I believe this bug was fixed for the record editing in an actual domain (52b6966c) but hasn't applied for the domain template yet. Will be fixed in #345 as well.

**Comment by Ramalama2** [comment]
Thanks!! :-)

Gonna close this :-)
