### ISSUE TITLE
[BUG] Delete a Domain (Doesnt redirect to Dashboard)

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#347]
Hi again :-)

Found another bug :-)

If you delete a domain (in Firefox), you will stay on that "Manage Domain" Site and not get redirected to Dashboard again.

domain.com -> Admin -> Detele Domain -> (Redirected to Dashboard)
(Maybe with a notification, like "Domain was successfull deleted" or sth like that)

Cheers :-)

**Comment by Ramalama2** [comment]
I have 3 Zones, in dashboard xD
And the whole Powerdns-admin site is freaking fast here for me, feels faster as light :-)

Im using nginx 1.15 with http2 and ssl... here is my config:

```
server {
        listen                  213.213.213.213:80 default_server;
        server_name             "";
        return 301 https://$http_host$request_uri;
}

server {
        listen                  213.213.213.213:443 ssl http2 default_server;
        server_name             _;
        include                 conf.d/ssl/ssl.inc;
        index                   index.html index.htm;
        error_log               /var/log/nginx/error_powerdnsadmin.log error;
        access_log              off;

        client_max_body_size            10m;
        client_body_buffer_size         128k;
        proxy_redirect                  off;
        proxy_connect_timeout           90;
        proxy_send_timeout              90;
        proxy_read_timeout              90;
        proxy_buffers                   32 4k;
        proxy_buffer_size               8k;
        proxy_set_header                Host $host;
        proxy_set_header                X-Real-IP $remote_addr;
        proxy_set_header                X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_headers_hash_bucket_size  64;

        location ~ ^/static/  {
                include  /etc/nginx/mime.types;
                root /opt/web/powerdns-admin/app;
                location ~*  \.(jpg|jpeg|png|gif)$ { expires 365d; }
                location ~* ^.+.(css|js)$ { expires 7d; }
        }

        location / {
                proxy_pass              http://unix:/opt/web/powerdns-admin/powerdns-admin.sock;
                proxy_read_timeout      120;
                proxy_connect_timeout   120;
                proxy_redirect          off;
        }
}
```

The only error i get with firefox debugging is the:

> Fehler beim Laden der folgenden Adresse: Could not load the source for blob:https://dns.domain.tld/27ab570d-9adb-43b6-9c64-c07f8fdf2219.
> [Exception... "Failed to open input source 'file:////dns.domain.tld/27ab570d-9adb-43b6-9c64-c07f8fdf2219'"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 645"  data: yes]
> Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:645:5
> _getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:410:27
> Line: 645, column: 0

AAAHHHH i found it, it has todo with SSL
The problem is, all your links refers to HTTP not HTTPS
Here is the error ive get:
`Laden von gemischten aktiven Inhalten "http://dns.domain.tld/dashboard" wurde blockiert.`

That means, mixed content loading was blocked...

Can you make a variable in Config.py for http/https switching?
or simply remove http:// from all links? that should work too...

Cheers :-)

**Comment by Ramalama2** [comment]
Ive just looked into the code, seems not that easy to edit it, because it gets generated automatically from flask...

i know a way, based on a sub_filter for nginx, the allows rewriting the code on the fly like:
sub_filter     http://$host    https://$host;

But the problem is with this plugin, you need to compile nginx instead installing from repo...

I hope there is any other way to solve this :-)

**Comment by ngoduykhanh** [comment]
Well, i have a website with ssl nginx config just like your case, but cannot reproduce the issue. Wanna see my config to compare?

**Comment by ngoduykhanh** [comment]
Looks same to me

```
server {
  listen *:80;
  server_name               mydomain.com;
  return                    301 https://mydomain.com$request_uri;
}

server {
  listen                    *:443 ssl http2;
  server_name               mydomain.com www.mydomain.com;

  ssl                       on;

  ssl_certificate           /etc/nginx/ssl/mydomain.com/ssl-bundle.pem;
  ssl_certificate_key       /etc/nginx/ssl/mydomain.com/domain.key;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
  ssl_prefer_server_ciphers on;
  ssl_dhparam  /etc/nginx/ssl/mydomain.com/dhparam.pem;

  index                     index.html index.htm index.php;
  root                      /opt/web/mydomain.com;
  access_log                /var/log/nginx/mydomain.com.access.log combined;
  error_log                 /var/log/nginx/mydomain.com.error.log;

  client_max_body_size    10m;
  client_body_buffer_size 128k;
  proxy_redirect          off;
  proxy_connect_timeout   90;
  proxy_send_timeout      90;
  proxy_read_timeout      90;
  proxy_buffers           32 4k;
  proxy_buffer_size       8k;
  proxy_set_header        Host $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_headers_hash_bucket_size 64;

  location ~ ^/static/  {
    include  /etc/nginx/mime.types;
    root /opt/web/mydomain.com/app;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location ~ ^/upload/  {
    include  /etc/nginx/mime.types;
    root /opt/web/mydomain.com;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location / {
    proxy_pass http://unix:/opt/web/mydomain.com/mydomain.com.sock;
    proxy_read_timeout    120;
    proxy_connect_timeout 120;
    proxy_redirect        off;
  }

}
```

**Comment by Ramalama2** [comment]
yep
But can you check if your links are pointing to http istead of https too? (with the debugger)

**Comment by ngoduykhanh** [comment]
No, all links are https. The debugger is clean.

**Comment by Ramalama2** [comment]
Im using the gunicorn... Systemd script...

```
[Unit]
Description=PowerDNS-Admin
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/opt/web/powerdns-admin
ExecStart=/opt/web/powerdns-admin/flask/bin/gunicorn --workers 2 --bind unix:/opt/web/powerdns-admin/powerdns-admin.sock app:app

[Install]
WantedBy=multi-user.target
```

Thats really strange, ive checked the whole site (this time with the Microsoft Edge debugger)
Everything is https,
except if i click on "Delete Domain" it try to load http://...dashboard
Thats the only one thing that trys to load http, lol xD

I can simply rewrite this block to my link
```
$(document.body).on('click', '.delete_domain', function() {
    var modal = $("#modal_delete_domain");
    var domain = $(this).prop('id');
    var info = "Are you sure you want to delete " + domain + "?";
    modal.find('.modal-body p').text(info);
    modal.find('#button_delete_confirm').click(function() {
        $.get($SCRIPT_ROOT + '/admin/domain/' + domain + '/delete', function() {
            window.location.href = '/dashboard';
        });
        modal.modal('hide');
    })
    modal.modal('show');
    
});
```

But i want to find where it comes from, lol :-)

**Comment by Ramalama2** [comment]
I have found a new Bug.
Dunno if i should open for this a new Issue, since im already dominating the issues xD

If you make a new domain (that already exists)
you get a error 400 :-)
So now i dont know if its meant that way or not xD
![400](https://user-images.githubusercontent.com/6314556/44958374-a12fbb00-aedf-11e8-8f8d-60fae460f05b.JPG)

Cheers :-)

**Comment by tmuncks** [comment]
We can fix that to provide a proper error message... 👍🏻

**Comment by Ramalama2** [comment]
@ngoduykhanh 
Just by the way
ssl                       on;
is depricated since nginx version (whatever), it should be only in "listen *:443 ssl http2;"
and "listen *:443 ssl http2" is useless too, its enough if you write "listen 443 ssh http2"

Just because i know always everything better xD lol....

**Comment by tmuncks** [comment]
So does that mean, it's the Javascript that causes that http:// URL? That shouldn't happen I believe.

**Comment by Ramalama2** [comment]
Yes, thats exact that block ive posted 4? comments above...

Im still fighting with that, give me time, since its working for you, the fault should be somewhere on my side.
So give me little bit time.

Cheers :-)

**Comment by Ramalama2** [comment]
Solved, look at the solution 2 Posts above.

**Comment by tmuncks** [comment]
Awesome!
