### ISSUE TITLE
[Reguest] Bring the "Edit_OnClick" Setting back

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#348]
Hi :-)

In the last versions, there was a setting (i dont remember how its called exactly) Edit_onclick or sth like that...

You had the possibility to turn off (Edit entrys if you just click them)... So you had to click on edit before you can change an entry...

After the Update (All the settings to database) some comments ago, it was removed :-(

Cheers :-)

**Comment by ngoduykhanh** [comment]
Oops, it was called `allow_quick_edit` but missing setting value in the DB. Bring it back in commit 615413ae90da109309a2d94066c203eb76a5ea11 of #345

**Comment by tmuncks** [comment]
@ngoduykhanh the setting was missing from the initial database on purpose, as it makes little sense to have to handle both database contents AND code for implementing a setting.

The revamped settings "infrastructure" handles the database side of things for you, so all you need is the code changes. Defaults are assigned in the code and any the setting is automatically written to database when toggled.

See #287

**Comment by Ramalama2** [comment]
Nice, thanks!

Can i close this then?

**Comment by Ramalama2** [comment]
Solved, fixes are already in upstream....

Cheers :-)
