### ISSUE TITLE
Javascript blob Error

### ISSUE THREAD

**Issue by ntinti** [ngoduykhanh/PowerDNS-Admin#349]
I've installed latest version and hoped this error is gone. But it also persists since weeks.
I have this Javascript error on all PowerDNS-Admin sites - seen in the Firefox debugger
```
Fehler beim Laden der folgenden Adresse: 
Could not load the source for blob:http://pdns.domain.tld/101ae5e4-8162-0040-bd3d-0aa47b31485a.
Error: Failed to fetch blob:http://pdns.domain.tld/101ae5e4-8162-0040-bd3d-0aa47b31485a. Code 2152857618.
Stack: onResponse@resource://devtools/shared/base-loader.js ->
resource://devtools/shared/DevToolsUtils.js:558:23
onStopRequest@resource://gre/modules/NetUtil.jsm:126:17
Line: 558, column: 23
```

But all things work fine with  the exception of saving templates, which also persits since weeks. Don't know if there is a correlation.

**Comment by Ramalama2** [comment]
Confirmed here too
`Fehler beim Laden der folgenden Adresse: Could not load the source for blob:https://dns1-syb.sybcom.net/259549e5-343d-462a-81af-42d352906080.
[Exception... "Failed to open input source 'file:////dns.domain.tld/259549e5-343d-462a-81af-42d352906080'"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 645"  data: yes]
Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:645:5
_getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:410:27
Line: 645, column: 0`

But saving Templates working here...
Cheers :-)

**Comment by Ramalama2** [comment]
Still happens...
If you open the firefox debugger
Sources (Tab) -> blob -> your.server.org -> longuuid
(look at my Picture)
`Fehler beim Laden der folgenden Adresse: Could not load the source for blob:https://my.server.org/2f49d425-50c1-4bf3-9b1f-c826bd4b179f.
[Exception... "Failed to open input source 'file:////my.server.org/2f49d425-50c1-4bf3-9b1f-c826bd4b179f'"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 645"  data: yes]
Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:645:5
_getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:410:27
Line: 645, column: 0`

![unbenannt](https://user-images.githubusercontent.com/6314556/45312763-3c064600-b52d-11e8-8afd-9bd65a5e5276.JPG)

Cheers :-)

**Comment by Ramalama2** [comment]
Forgot: Im on Commit 565 not the actual 567
But i can test with 567 if you want...

Cheers :-)
