### ISSUE TITLE
[BUG] Create Domain from Template (SOA Serial)

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#351]
Hi,
if you Create a domain from template, you get a SOA Serial of YYYYMMDDnn
(where nn is random, i dont see any logic there)

If you Create a domain without template its perfect, you get YYYYMMDD01

Cheers :-)

**Comment by tmuncks** [comment]
I think `nn` will end up matching the number of operations the create process is going through, so should probably never be more than `02` or perhaps `03` in some special case. Which numbers are you seeing?

When creating from template, the domain is created first, then data is added. This should give `02`.

I've seen `03` myself, but not sure why. Adding a custom SOA to the template might cause an extra operation to happen, to replace the one created with the domain.

**Comment by Ramalama2** [comment]
AAH !!! Makes sense!!!
Sry, ive didnt seen it from this point!!!

Ive see sometimes 04 and seen once 06 (but cant reproduce 06)
its 99% 03 or 04.

But yes, it creates the domain with 01 and applys the template 02,03,04 ...

So not a bug, its just how it works....
Thanks!!!

Can i close this then?
