### ISSUE TITLE
[Request] History Improvements

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#354]
I know its like my issue Nr. 6 in 2 days xD

However is it possible to improve the history?
1.) For example, an user delete a "A" entry from domain blabla.de

I get in history:
(UserName) -- Apply record changes to domain blabla.de

If i click on the "INFO" button, i got just the new records from the whole domain instead of whats added or deleted....
Here would be nice, if you can do a "diff (old entrys) (new entrys)" and list only the changes...
like with a + (for anything added) or - (deleted)

That would be awesome, there rest i write from now, is not really important, but would be cool too:

2.) If you add a new "A" record to any domain (which has auto_PTR enabled)
The new PTR records will be created automatically = perfect!
But there is no history for this at all :-)

If you do this manually, you get same result as with from 1.) (without diff) :-)

Everything else is not important in the history :-)

Cheers :-)

**Comment by Ramalama2** [comment]
Ah sry, readed just now the other issue :-)

I would help here with code changes, but i dont understand anything about flask and python xD
However, maybe i can help just need to ask our developers... but can i get a tip where i need to look exactly in the code to?

Cheers :-)

**Comment by Ramalama2** [comment]
Ive spoken with our developers, they will do the history improvements, and maybe a small email system (where you can mail the changes everytime someone changes a zone)

Cheers :-)

**Comment by Rico29** [comment]
hello, any news about that  @Ramalama2 ?

**Comment by Ramalama2** [comment]
Yeah... They are busy:-((

But i solved it myself...
I maked an nginx proxy, between pdns-api and powerdns-admin
Which i use only for logging "PATCH" action to a logfile.
And a tail script with a loop, which does compares the difference, sends the differences via mail and wipe pdns-recursor zone...

But anyway, our devs maybe need another 2-3 weeks to implement this... The problem is, powerdns-admin sends the whole zone to the pdns-api, not only the changes.

**Comment by Rico29** [comment]
just talking about powerdns admin "history", it would be very useful to be able to make a diff between 2 history items. I'll ask the webdev guy at my job if it's easily doable.
