### ISSUE TITLE
[Request] Upload Profile picture into MySQL DB

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#355]
Hi :-)

Background:
I have here a Mariadb (Galera-Cluster) running,
where every server uses same database (for pdns and powerdns-admin)

This works absolute amazing, if anyone is interested in doing this too... (Just from my side, its an absolute perfect solution, works extremely well, with powerdns and this powerdns-admin)

The thing is, everything you do on the admin panel on server1, you have synced on admin panel server2 too... so it doesnt matter on which server you do what...

The benefit is, if one server fails, you can throw it away and it doesnt care, just adding another server to the cluster and its synced... However :-)

Problem:
This brings side effects, if anything is stored on the drives xD
So if you upload a picture for the profile, you need to do that on both servers xD
If we can have that profile pictures in Database (they are just 5kb small) that problem is eliminated :-)

If its not going to happen any time, its not a problem, just need to do that on both servers then :-)
Or i need to make an script, that syncs the upload folders :-)
(Based on an filesystem based cron, like incron)

Cheers :-)

**Comment by ngoduykhanh** [comment]
If i were you, i would use the shared storage (NFS or whatever),  or file synchronization :D. I think it is better to manage the static files on the filesystem than binary database rows. Also, the current code doesn't take care of the images size i think, have to adjust that if we really want to store them into DB.

**Comment by Ramalama2** [comment]
Thanks :-) than i make an simply incron script :-)

Should i share or can i close? :-)

**Comment by ngoduykhanh** [comment]
Can close this one :).
