### ISSUE TITLE
[Request] Statistics Page like in Dashboard (Not important)

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#356]
Hi,

1. An iframe Page would do that too, then i will make sth and write an howto...
(Sth like an optional Iiframe tab, which you can enable in settings with link to destination... and we can do that with nginx proxy location)

However, my Idea is
We have already (in api) something like:

rd-queries = all questions to our server
latency = general latency for answers
real-memory-usage = in bytes i quess?
tcp6-queries  -- tcp6-answers
tcp4-queries  -- tcp4-answers
udp6-queries  -- udp6-answers
udp4-queries -- udp4-answers

Something like that :-)

However thats not important in any way, just maybe an idea for sth in the future :-)
Maybe i can do something graphite like, that we can integrate via iframe with nginx proxy...

Cheers :-)

**Comment by tmuncks** [comment]
Great idea in theory, but I suspect very few installations uses the pdns instance that PDA talks to, as the only server for the real workload? 

I've been thinking about something similar, but I have zero queries to my local pdns instance and a geo-dispersed cluster of actual nodes that does the actual work.

What do you think?

**Comment by Ramalama2** [comment]
you have right, we are using the pdns-auth server (for the world) and it theoretically makes no sense to monitor it...
However, forget it... or just wait, maybe anyone get a better idea :-)

In theory everyone who access your site, asks your pdns instance before (if the ttl is not to big)
So its a simple way to monitor your users xD

However, this is really the last thing thats important xD

Cheers :-)

**Comment by Ramalama2** [comment]
Hi, i have news!!! :-))))

Ive got working grafana/graphite-api/carbon :-)
And im Receiving querys directly from PowerDNS (auth and recursor)

The possibilitys are absolutely awesome, you can combine alle your auth or all recursor or both to one graph (nice if you have a cluster)
And much more, will post Pictures if i have it done.

If anyone is interrested in a HowTo, i will do one here!

Cheers :-)

**Comment by tmuncks** [comment]
Cool. Carbon and Graphana are great for this sort of thing. The people over at PowerDNS even has a public carbon graphing service if you want to avoid a local setup.

**Comment by ngoduykhanh** [comment]
We already had the basic statistics which queried from PDNS api. I don't think we should have any kind of detail statistics, graphs in PDA. It will requires the integration with time series database which is better to be handled in monitoring tools.

Btw, grafana is a good tool for data visualization. You can use it as a part of your monitoring system :).

**Comment by Ramalama2** [comment]
I Closng this!
You have fully right, this has nothing todo with powerdns-admin :-)

Thanks ngoduykhanh :-)

**Comment by Ramalama2** [comment]
The actual status of grafana :-)
Cheers :-)

![unbenannt](https://user-images.githubusercontent.com/6314556/45255049-fc4f2b00-b381-11e8-822d-8db5f266a18e.png)
