### ISSUE TITLE
[Request] Execute a Python/Bash script after editing zone.

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#357]
Hi, this is one of the most important things for me, i searched like a week to get to this solution...

Is it possible to make an option for executing something?
or maybe at least create an empty file in any folder with the domain/zone name that was modified??
(So i can do here an incron script too)

Basically i want
rec_control wipe-cache example.net (pdns recursor) or
unbound-control flush_zone example.net (unbount)

In my example:
I have fullowing constellation (3 server cluster) but each of them with:
powerdns-auth = launching on one ip (for the world)
recursor = launching on another ip (managed by iptables/firewalld for allowed networks)

If we update our Zone (mydomain.com)
for example (bla.mydomain.com A 1.1.1.1 to 1.1.1.2)
We need to wait for the TTL of that entry.... (Cached in recursor)... thats painfull if you have 86400 (1d)...

ipconfig /flushdns (would not help, because recursur has will resend from cache)

So here basically where you could fix that completely with
rec_control wipe-cache mydomain.com
and after ipconfig /flushdns, you have the new record...

he benefit is, if we simply restart the recursor, the whole cache will be gone... and that we need to avoid too...

I hope you understand me, i know its maybe not rfc... or you can use dnsdist for specific zones...
But in my opinion (didnt tested dnsdist) this will add latency...
And you need to find a way, to write with a script or sth all your domains to dnsdist... painfull too, since we have huge :-)

Cheers :-)

**Comment by ngoduykhanh** [comment]
Hi,

I don't think PDA should take care of that situation. It should be taken care by pdns itself if really needed, so the goal can be achieved if there are changes from PDA or whatever 3rd software. However, that's how DNS TTL works, why don't you want to wait 😜?

**Comment by Ramalama2** [comment]
Really, i dont know how other does this :-)
The thing is, a ttl of 300 (5min) is bad for caching, and an ttl of 84600 is good for caching, but yes, with the above problem :-)

I cant believe that no one have a propper solution for this :-)

With our actual nameservers (tinydns with ldap2dns backend) we yust restart our dnscache... but thats really everything else as optimal xD

However, if there will be a possibility to even create a empty file with the zonename in any directory, would be welcome :-) Or any other way, dunno :-) but any at all :-)

Cheers :-)

**Comment by Ramalama2** [comment]
no, thats to not flexible enough, im going to use dnsdist then, with some sort of a script, to load-balance my own zones to the auth server... seems like its the only way.
If the auth answers my own zones instead of the recursor...

However, sry that i wasted your time!

Cheers :-)

**Comment by tmuncks** [comment]
Makes sense - for local zones that's exactly what I do here.

**Comment by Ramalama2** [comment]
Im sry, ive reopened...

But its not possible with dnsdist or better to say (it is possible but with side effects)
Ive discussed in the official irc channel about that, the problem is:
if you redirect your zones to the auth, the auth does not return "A" records for cnames, that are not defined in your zone... same for RR records...
Because the auth cant resolve cnames, where the recursor does...

So the only clean way is with
rec_control wipe-cache mydomain.com

Cheers :-)

**Comment by tmuncks** [comment]
Just to be clear - The problem here, is actually that the DNS standards doesn't work for you, right? :-)

I don't really feel this is something that should be solved in PDA, so unless there is some more universal use for being able to call an external script on update, I really think it should be solved elsewhere.

That said, there are many ways to achieve what you're trying to pull off - Most of them will probably have kind of a hacky feel to them, but they can be made to work just fine.

You could run something like this on the recursor every minute:

```
if test "$(dig +short SOA mydomain.com @<recursor_ip> | awk '{ print $3 }')" -ne "$(dig +short SOA mydomain.com @<auth_ip> | awk '{ print $3 }')"; then
    echo "flushing cache" >> /var/log/super_flusher.log
    rec_control wipe-cache mydomain.com
fi
```

Super simple - And it would allow you to BOTH have the advantage of a long TTL of 86400s, while effectively reducing the ttl to <= 60s on updates. 

It doesn't solve the caches on the individual clients, but nothing will.

**Comment by Ramalama2** [comment]
You are genius! That with clients i know to xD but thats their problem xD

Never thinked of such an simple idea, lolz :-)

Okay, let this issue still open if its okay, i try to speak tomorrow with our developers, if they can implement something like an option to execute script afterwards...
if you are willing even to take the changes to upstream xD
However, first they need to make the diff changes for the history, (see other issue)

Cheers :-)
