### ISSUE TITLE
Be able to select how many records are shown permamently

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#36]
Use case:

Domain with >150 records.
At the moment one has to select how many records are to be displayed from the standard setting of 15 to something convenient, like 20 or 'All'.

An default option to set how many records are to be shown would be nice.

(How about infinite scrolling/autoload? e.g. https://github.com/pklauzinski/jscroll)

**Comment by ivanfilippov** [comment]
I've added this feature into the `new_ui` branch. It will be in mainline once that's merged.
