### ISSUE TITLE
How the PNDS  API is configured

### ISSUE THREAD

**Issue by m1911** [ngoduykhanh/PowerDNS-Admin#367]
config.py file, you do not see the option to configure the PNDS  API.

**Comment by ngoduykhanh** [comment]
The PDNS is now managed in the DB. So, at the first time you login into the web ui, you will be redirected to config page.

**Comment by m1911** [comment]
@ngoduykhanh 
Thanks for the answer.
How to use sed to replace Sqla_db_user = ' PDA '

**Comment by m1911** [comment]
@ngoduykhanh 
This libxmlsec1-openssl installation package centos7 hint does not exist.
