### ISSUE TITLE
Consider using MEDIUMTEXT for history.detail column

### ISSUE THREAD

**Issue by Kaelnor** [ngoduykhanh/PowerDNS-Admin#368]
Hi,

I stumbled upon an error message while applying changes to a zone. After reading the logs, the changes are applied correctly through powerdns API but an exception is raised while inserting the history record.

**Problem:**

This is the extract from the application logs:

[powerdnsadmin_history_sql_error.txt](https://github.com/ngoduykhanh/PowerDNS-Admin/files/2410469/powerdnsadmin_history_sql_error.txt)

As you can see the query is trying to insert a large text in history.detail (200k+ chars).
The problem is that this column is created as TEXT limited to 65,535 characters (using MariaDB 10.2.17)

**Solution:**

I converted the column to MEDIUMTEXT: alter table history modify detail MEDIUMTEXT;

The error message no longer appears in the GUI nor the logs. The history entry is successfully created.

**Comment by ngoduykhanh** [comment]
I believe it can be fixed by using [this one](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L1752). However, that option will cause problem on other DB like Sqlite, Postgresql (or migration script i don't remember exactly).

**Comment by Kaelnor** [comment]
> I believe it can be fixed by using [this one](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L1752). However, that option will cause problem on other DB like Sqlite, Postgresql (or migration script i don't remember exactly).

Thank you for answering so quickly. From what I see in sqlalchemy docs, this seems like a good solution. I'll try to test it on a fresh install when I have some time.

Can I edit the "Prepare MySQL or MariaDB Database for PowerDNS-Admin" wikipage to put a note regarding this issue ?

**Comment by ngoduykhanh** [comment]
Please feel free, WIKI pages are open to everyone for contributing.

**Comment by scop** [comment]
The "this one" link doesn't seem to point to the correct line any more, but I suppose it's supposed to be the with_variant longer length commented out one.

FWIW here's another approach to the same problem from elsewhere, perhaps it'd work?
https://github.com/openstack/nova/blob/01c33c584f7209ae02bc537adea85502d52f1c22/nova/db/sqlalchemy/models.py#L38
