### ISSUE TITLE
SOA issues

### ISSUE THREAD

**Issue by m1911** [ngoduykhanh/PowerDNS-Admin#371]
Create an SOA record within the domain template.
The new domain selection template does not take effect.
template：[https://imgchr.com/i/iMUoY6](https://imgchr.com/i/iMUoY6)
domain：[https://imgchr.com/i/iMUXmd](https://imgchr.com/i/iMUXmd)

**Comment by Ramalama2** [comment]
Your pictures doesnt work....

However i found sth different: (belongs to SOA too)
-> if you add/modify a record --> Serial gets updated
-> if you just delete a record  --> Serial doesnt update

Cheers :-)
