### ISSUE TITLE
[BUG] SOA Serial doesnt update always

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#375]
Hi,  dont know if this comes from Powerdns-Admin or pdns itself.

The problem is, that SOA Serial doesnt update quite often.
(Almost 80-90% of the time)

You can check yourself, just make any example domain/zone and edit some settings and apply...
You will see, maybe the soa updates, maybe not...
if you change 10times something, 8times the Serial will be same...

Cheers :-)

**Comment by batmac** [comment]
you can force pdns to increase the serial after every api call.
for instance:
` pdnsutil set-meta <zone.tld> SOA-EDIT-API INCEPTION-INCREMENT`

**Comment by batmac** [comment]
1. only on patch yes sorry. ( https://doc.powerdns.com/authoritative/domainmetadata.html#soa-edit-api )
2. yes I think so. (not a problem for my configuration neither)

**Comment by Ramalama2** [comment]
Thx!
So seems for me a perfect solution...

The question is now, what do we do with this Thread/Issue?
I mean, we have a good workaround, but the bug is still there xD

Cheers :-)

**Comment by T313C0mun1s7** [comment]
If I understand correctly this would need to be done separably to every domain, is that right?

I have 933 domains, this should be a default, not something that needs to be changed 933 times. What about new domains? Would you need to make this change for every new domain you create?

**Comment by tmuncks** [comment]
When you create a new domain from inside PowerDNS-Admin, the SOA updates automatically as defined by the DEFAULT setting (or whatever non-OFF setting you choose during zone creation). If the zone is imported from elsewhere or by other means created without the SOA-EDIT-API metadata setting, it will not update automatically.

I've only had an issue with this on imported domains, and it's easy enough to set this bit of metadata from a script, something like this:
```
for ZONE in $(pdnsutil list-all-zones); do 
    pdnsutil set-meta $ZONE SOA-EDIT-API DEFAULT
done
```
