### ISSUE TITLE
About TXT recording issues

### ISSUE THREAD

**Issue by m1911** [ngoduykhanh/PowerDNS-Admin#380]
Adding a TXT record requires adding  "" to automatically add  "" when the TXT record is Selected.

**Comment by Ramalama2** [comment]
It absolutely normal that you need to quote txt records...
whats the problem?

**Comment by Ramalama2** [comment]
i dont get, why double quotes, do you have a better example?

**Comment by m1911** [comment]
@Ramalama2 
The correct usage is This.
![domian](https://user-images.githubusercontent.com/10194213/46513509-68db1e00-c88b-11e8-821b-ceb5a213e2d3.png)
I mean the user doesn't need to manually enter the quotes around 123.
Automatically added by the Program.

**Comment by tmuncks** [comment]
To me it makes sense, that if you create a record of type TXT, the user don't need to provide the "'s himself, but can simply type the actual text. It's a DNS technicality, that the user really shouldn't need to worry about.

**Comment by m1911** [comment]
@tmuncks 
yes, so I hope the author can Improve.

**Comment by ngoduykhanh** [comment]
Hi. I've added a record helper for this type of Record. Use the text area instead of textbox. Quotes will be automatically added if user doesn't include them.
