### ISSUE TITLE
Suspected bugs

### ISSUE THREAD

**Issue by m1911** [ngoduykhanh/PowerDNS-Admin#382]
I used the updated version 4 days ago, deleting the domain name cannot jump to Dashboard.

**Comment by Ramalama2** [comment]
OMG....

https://github.com/ngoduykhanh/PowerDNS-Admin/issues/347

https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx
--> look at Sample Nginx-Configuration for SSL

Cheers

**Comment by m1911** [comment]
@Ramalama2 
Thanks a lot, it's really good.
I didn't notice the SSL example because of my carelessness.
