### ISSUE TITLE
don't support mysql-community-server-8.0, compile error

### ISSUE THREAD

**Issue by pengliaoye** [ngoduykhanh/PowerDNS-Admin#383]
/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o -m64
    _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:1894:3: error: unknown type name ‘my_bool’
       my_bool recon = reconnect;
       ^
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of mysqlclient
Command "/opt/web/powerdns-admin/flask/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovpxhr3d/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-q8hcr7ts/install-record.txt --single-version-externally-managed --compile --install-headers /opt/web/powerdns-admin/flask/include/site/python3.6/mysqlclient" failed with error code 1 in /tmp/pip-install-ovpxhr3d/mysqlclient/

**Comment by Ramalama2** [comment]
this has nothing todo with powerdns-admin...

mysqlclient-python doesnt support mysql 8.0 atm.
https://github.com/farcepest/MySQLdb1/issues/140
https://github.com/PyMySQL/mysqlclient-python/issues/218 (exactly your error)

Cheers

**Comment by BeckYeh** [comment]
I tried to install from "pip install git+https://github.com/PyMySQL/mysqlclient-python.git" and remove mysqlclient in requirement.txt
It works fine. 

The new mysqlclient version is 1.4.2.post1

**Comment by ngoduykhanh** [comment]
The new version of mysqlclient is included in requirements.txt
