### ISSUE TITLE
Change the default web interface URL

### ISSUE THREAD

**Issue by breaked01** [ngoduykhanh/PowerDNS-Admin#386]
Hello. I want to use a PowerDNS-admin on a different PORT on my server, I have successfully configured nginx, and all works just fine, but, when I login or logout from web-interfaces I have redirected to the default 80 port. How can I configure a redirect url to a different port?

Thanx in advance, may you understand my bad english.

**Comment by ngoduykhanh** [comment]
It is matter of your nginx configuration. Please take a look at WIKI page for the example.

**Comment by r3d-f0x** [comment]
docker-compose can change ports and you can also set up a proxy with a different domain and the standard port.

**Comment by wwender** [comment]
I struggled with the same problem and found a solution.  (As ngoduykhanh wrote it is just nginx configuration) Maybe this will help somebody like me as I also found this github thread. 

Please just change your nginx .conf file. In the server section you have a block with "proxy_" configuration. 

There just replace the line: 

proxy_set_header                  Host $host;
with 
proxy_set_header                  Host $host:$server_port;

everything works as expected :).
