### ISSUE TITLE
Feature: Add local Users

### ISSUE THREAD

**Issue by fredericmohr** [ngoduykhanh/PowerDNS-Admin#39]
The WebUI has a section "manage users", which is great but it lacks the option to add new users. This would be a great additional feature. I disabled registration after I created the first admin user, so nobody can register and mess with my dns records.

**Comment by ivanfilippov** [comment]
Hi @fredericmohr 

New users created via the registration system don't get access to any domains until an admin level user grants them access, so you shouldn't need to worry about that. :smile: 

Your suggestion to add the ability to create users in the admin section is a great idea. I'll work on getting this implemented, but it might not show up until we've merged the new templating system (which is soon I hope, depending on testing).

**Comment by fredericmohr** [comment]
Thanks, good to know. In our case, we only need two admin accounts (for
now) so I just added another via mysql directly.

**Comment by ivanfilippov** [comment]
Hi @fredericmohr 

I've added the create user functionality into the `new_ui` branch. You're welcome to try it out here:
https://github.com/ivanfilippov/PowerDNS-Admin/tree/new_ui

I'm almost done with this branch and we will most likely be integrating it into the `master` soon.
