### ISSUE TITLE
Login fails with "Method not allowed" on some URLs

### ISSUE THREAD

**Issue by ymage** [ngoduykhanh/PowerDNS-Admin#403]
Hi,

When accessing on some routes ('/domain/<path:domain_name>', '/template/<path:template>/edit, ....) and session is expired, the login view is displayed without redirection to "/login" route.
So far so good.
But when you get logged in, these route do not allow POST method so error occurs.

Two way to fix that :
1. Allow POST method on each route which is protected
    - PROS : easy to fix
    - CONS : the current redirection to /dashboard lose the user current route
2. Make a real redirection to /login route with a **next** param to get redirected on the previous route after logged in
    - PROS : a better user experience I think
    - CONS : need to change the login view and add redirection on protected views

Any hints ?

**Comment by ngoduykhanh** [comment]
I prefer the second way for better user experience. There are routes that don't allow GET method, so we need to handle the redirection properly so user won't see "Method not allowed" error.
