### ISSUE TITLE
LDAP_GROUP_SECURITY w/ groupOfNames groups no longer working/supported?

### ISSUE THREAD

**Issue by garettharnish** [ngoduykhanh/PowerDNS-Admin#414]
I'm running commit [004b211fdc679a3e6b97740ac13745906454a6dd](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/004b211fdc679a3e6b97740ac13745906454a6dd).  It appears in commit [9ed09e92fcc799533f8364b8cf4401ad6cb0c955](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/9ed09e92fcc799533f8364b8cf4401ad6cb0c955#diff-413e9aa8961126d20e2d90befa13e0f1), how non-AD LDAP security groups are verified was radically changed (either intentionally or accidentally). 

In the original release code, groupOfNames groups were supported.  

The command looked like this:
`
self.ldap_search('(member=%s)' % ldap_user_dn, LDAP_ADMIN_GROUP)
`

Now, it looks like the user account itself must be in the DN path for the group. 

The command looks like this:
`
self.ldap_search(searchFilter, LDAP_ADMIN_GROUP)
`

The searchFilter is defined as such:
`
searchFilter = "(&({0}={1}){2})".format(LDAP_FILTER_USERNAME, self.username, LDAP_FILTER_BASIC)
`

which in my case have these parameters:
`
LDAP_FILTER_USERNAME = uid
LDAP_FILTER_BASIC = (objectClass=inetorgperson)
`

I know some people do thing this way, but that isn't optimal for security for PowerDNS since only a subset of my users are allowed to log into PowerDNS and these groups are defined for them.

So here is my quick workaround.

I redefined searchFilter before the checks:
`
searchFilter = "(member=%s)" % ldap_username
`

If the current behaviour is intentional, is there anyway to make this a more permanent option?  Like a I'm using groupOfNames groups checkbox to enable a workaround like the above?

Thanks,
Garett

```
diff --git a/app/models.py b/app/models.py
index 7e87d08..0de0adb 100644
--- a/app/models.py
+++ b/app/models.py
@@ -243,6 +243,7 @@ class User(db.Model):
                     if LDAP_GROUP_SECURITY_ENABLED:
                         try:
                             if LDAP_TYPE == 'ldap':
+                                searchFilter = "(member=%s)" % ldap_username
                                 if (self.ldap_search(searchFilter, LDAP_ADMIN_GROUP)):
                                     role_name = 'Administrator'
                                     logging.info('User {0} is part of the "{1}" group that allows admin access to PowerDNS-Admin'.format(self.username, LDAP_ADMIN_GROUP))
```

**Comment by ngoduykhanh** [comment]
There are setups that user's `memberof` or group's `member` attribute is missing. I think we should let the Administrators have ability to configure these options.

Also, currently OpenLDAP is requiring administrator credential for the querying. Not sure if we should keep it.

**Comment by nickmaleao** [comment]
@garettharnish Thanks for your fix!! i'm using the ldap server of FreeIPA and with the current branch i couldn't match the user group. It should be possible do define a custom searchfilter for the user group.

**Comment by kokel** [comment]
I'm also wondering why this behaviour changed. Using groupOfNames is a standard LDAP way to define groups of users. When configuring groupOfNames in LDAP the member attribute is mandatory, so I cannot really comprehend that in some setups the member attribute is missing. People have to configure their groups accordingly.

I would really appreciate the use of groupOfNames again. The current code did not make any sense to me.

The fact, that currently non-AD LDAP is requiring administrator credential isn't related to this issue in my opinion.

**Comment by johnwarburton** [comment]
I've created a PR (#512) to add groupOfNames support. Please let me know if it works for you

**Comment by mjkantowski** [comment]
I made the adjustments in here, but pdns admin still complains that I'm not part of any of the three security groups.  So I've had to disable Group Security again.

**Comment by johnwarburton** [comment]
Hi @mjkantowski 

Are you sure your LDAP queries are working? Please turn on debugging in config.py and restart the service
```LOG_LEVEL = 'DEBUG'```

When I log in via LADP, and I set admin & operator group to our ITOps groups, I get log entries like:
2019-05-21 10:18:15,333 - root - DEBUG - Ldap searchFilter (&(uid=john.warburton)(objectClass=posixAccount))
2019-05-21 10:18:15,344 - root - DEBUG - Ldap search result: [[('uid=john.warburton,ou=people,dc=REDACTED,dc=REDACTED', {'uidNumber': [b'10202'], 'gidNumber': [b'10005'], 'cn': [b'john.warburton'], 'description': [b'User account'], .......
2019-05-21 10:18:15,351 - root - INFO - groupSearchFilter is (&(member=uid=john.warburton,ou=people,dc=REDACTED,dc=REDACTED)(objectclass=groupOfNames))
2019-05-21 10:18:15,359 - root - INFO - User john.warburton is part of the "cn=ITAdmin,ou=groups,dc=REDACTED,dc=REDACTED" group that allows admin access to PowerDNS-Admin
```

**Comment by nickbouwhuis** [comment]
We're also struggling to get get group security to work

@johnwarburton I don't see the groupSearchFilter in my logs, even though log level is set to debug. How were you able to get that to show up in the logs? Did you ever get group security working?

**Comment by johnwarburton** [comment]
Hi @nickmaleao , group security is working *for me, with OpenLDAP, with my patch* in PR #512, and that's where the debug line is. You won't find it in mainline, until I try and find some time to work out why HTML elements aren't working as expected (see PR)

**Comment by ngoduykhanh** [comment]
#639 got merged. closing the issue.
