### ISSUE TITLE
REST-API to manage Zone Records by Accounts - Feature Request

### ISSUE THREAD

**Issue by StevieBowman** [ngoduykhanh/PowerDNS-Admin#416]
Found a similar feature on powerdns-auth-proxy and DjangoPowerDNS. It would be great if PowerDNS-Admin would expose it's own API key for each zone so that multiple teams could update their own zone records programmatically.

List Records in a zone
Create a New Record
View a specific Record
Edit a specific Record
Delete a specific Record

![powerdnsadmin](https://user-images.githubusercontent.com/24257638/49300404-0e8cc100-f4ba-11e8-9843-689bbf376f90.png)

**Comment by ngoduykhanh** [comment]
I think we can integrate with flask-restplus which has Swagger to expose needed API.

**Comment by StevieBowman** [comment]
Hi,

I wander if this has been accepted as a road map item?  Thanks
