### ISSUE TITLE
[BUG] Manage domain - Doesnt change account

### ISSUE THREAD

**Issue by arigal** [ngoduykhanh/PowerDNS-Admin#417]
Unable to change the account of a domain already created since the administration of the domain. When I change the account in the drop-down list (as Administrator) and I click on "Change account example.com", nothing happens.

**Comment by ngoduykhanh** [comment]
Hmm, I am able to make a change. Can you describe a bit more about the issue? How to reproduce it.

**Comment by arigal** [comment]
Hello,
Here are the screenshots of my problem.

The account created:
[http://image.noelshack.com/fichiers/2018/49/3/1543995759-screen01.png](url)
Access to the administration of the domain concerned:
[http://image.noelshack.com/fichiers/2018/49/3/1543995767-screen02.png](url)
Account change and validation :
[http://image.noelshack.com/fichiers/2018/49/3/1543995770-screen03.png](url)
Result, the account has not changed:
[http://image.noelshack.com/fichiers/2018/49/3/1543995775-screen04.png](url)

Thanks :)

**Comment by markusmilkereit** [comment]
We currently have the same issues - we can create domains with accounts attached, but changing accounts is not possible. The change does not get saved, does not matter if there was no account (our old domains) or if we created the domain with an account in PDNSadmin. There is a cryptic error message in the logs: "app.models - ERROR - Key 'kind' not present or not a String"

**Comment by ngoduykhanh** [comment]
The changing account action will call the PDNS API also. Base on your error, it looks like the PDNS itself has the problem. Are you able to set the account directly via API?

Example:
```
curl -X PUT --data '{"account": "staff"}' -v -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org
```

**Comment by markusmilkereit** [comment]
We tried setting the account directly by using the API call as suggested, it is also not working, with the same {"error": "Key 'kind' not present or not a String"} error message. When we set the value in the (DNS) DB directly, it works, and is nicely propagated back to the PDNS admin interface. Of course direct access to the DB should be the last way to do it, we just wanted to test every angle :)

**Comment by ngoduykhanh** [comment]
So it would be a bug in the pdns or your db schema isn't correct i guess.

**Comment by vipera** [comment]
I ran into the same issue using the latest PowerDNS-Admin master and pdns from the Debian stable package.

I updated to pdns 4.2.x using [their repos](https://repo.powerdns.com/) and that fixed the issue, so it's definitely a bug in the api for older pdns versions, and not related to PowerDNS-Admin.
