### ISSUE TITLE
DynDNS2 / docker

### ISSUE THREAD

**Issue by ghost** [ngoduykhanh/PowerDNS-Admin#420]
not sure im following, the api url is for the web interface, however pdns states 8081 though its not exposed in the docker compose, so how does dyndns work exactly when you state

Usage: http://user:pass@yournameserver.yoursite.tld/nic/update?hostname=record.domain.tld&myip=127.0.0.1

wheres my poweradmin interface url is http://poweradmin.domain.com:9191

**Comment by ngoduykhanh** [comment]
Just need to put the port in your URL, isn't it enought?

Also, The docker stuff is only for the development purpose. In the Prod environment you might have a reverse proxy for the PowerDNS-Admin UI so you can remove the port.

**Comment by outbackdingo** [comment]
ok, so still confused as your not answering the question, again... the api url is for the web interface, however pdns states 8081 though its not exposed in the docker compose, so how does dyndns work exactly when you state

Usage: http://user:pass@yournameserver.yoursite.tld/nic/update?hostname=record.domain.tld&myip=127.0.0.1

wheres my poweradmin interface url is http://poweradmin.domain.com:9191

My web interfface is located at 9191 .... however powerdnsadmin config states

PDNS Settings
PDNS API URL￼
http://pdns-server:8081
PDNS API KEY￼
••••••••••
PDNS VERSION￼
4.1.1
￼Update

**Comment by ngoduykhanh** [comment]
Still i don't understand what is the issue here.

> Usage: http://user:pass@yournameserver.yoursite.tld/nic/update?hostname=record.domain.tld&myip=127.0.0.1
When you do this query, its will ask the PowerDNS-Admin to do Dyndns update via its API, not PDNS API which exposing to 8081.

The PowerDNS-Admin container talks to PDNS container by using the name, we don't need to expose that 8081 port.

**Comment by outbackdingo** [comment]
ahhhh so the 8081 port is the powerdns pdnsd api interface ?

that clarifies it for me.
