### ISSUE TITLE
Crash opening zone if comments exist with V4.0.3 PowerDNS

### ISSUE THREAD

**Issue by firthmj** [ngoduykhanh/PowerDNS-Admin#421]
PowerDNS V4.0.3 has an issue where if comments are added to a record, then the API gives a malformed second instance of the zone (see issue at https://github.com/PowerDNS/pdns/issues/6204)

As PowerDNS-Admin doesn't support comments (yet?), it should just ignore these dummy records.

However, because there is an array indirection in app/models.py into the 'records' section of the RR that doesn't check there are any records, PowerDNS-Admin crashes when opening a zone with a comment associated with any record.

Changing (at line 1321 in the current version of app/models.py):

`                rrset['name'] = r_name`
`                rrset['content'] = rrset['records'][0]['content']`
`                rrset['disabled'] = rrset['records'][0]['disabled']`
`            return {'records': rrsets}`

To:

`                rrset['name'] = r_name`
`                if len(rrset['records']) > 0:`
`                    rrset['content'] = rrset['records'][0]['content']`
`                    rrset['disabled'] = rrset['records'][0]['disabled']`
`            return {'records': rrsets}`

Fixes the crash, and the record with a comment appeared to be displayed correctly. Not sure if the dummy/duplicate RR causes any other issues internally.

**Comment by ngoduykhanh** [comment]
Thanks for reporting. I will take a look at this issue.  Time to have comment feature also... 😬

**Comment by ngoduykhanh** [comment]
The comment feature is implemented so PDA now can display records that have comments.
