### ISSUE TITLE
Auto PTR

### ISSUE THREAD

**Issue by olfway** [ngoduykhanh/PowerDNS-Admin#43]
Please, add support for ptr records auto generation, probably with "Create PTR" checkbox

ie if i added "foo.bla.com. A 10.0.0.1" record and have domain "0.0.10.in-addr.arpa" configured,
then create "1.0.0.10.in-addr.arpa PTR foo.bla.com" too

**Comment by jallakim** [comment]
https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzoneszone95id

> set-ptr: If set to true, the server will find the matching reverse zone and create a PTR there. Existing PTR records are replaced. If no matching reverse Zone, an error is thrown. Only valid in client bodies, only valid for A and AAAA types. Not returned by the server. Only valid for the Authoritative server.

**Comment by dorion** [comment]
https://github.com/ngoduykhanh/PowerDNS-Admin/pull/102

**Comment by petersipos** [comment]
or an another solution is: #156
