### ISSUE TITLE
RRset on apply changes deletes record

### ISSUE THREAD

**Issue by jaap3** [ngoduykhanh/PowerDNS-Admin#432]
I tried to change an `A` record to a `CNAME `and apply this change, but in this particular case that wasn't possible. The UI shows an error "`RRset foo.example.com. IN CNAME: Conflicts with pre-existing non-CNAME RRset`".

When reloading the page I noticed that the record was gone completely and I wasn't able resolve that domain anymore.

I had some other pending changes at the same time, they weren't applied and instead these records seemed to be reset to their original values.

**Comment by ngoduykhanh** [comment]
Can you show the steps with sample data to reproduce the issue? I tried but couldn't reproduce it.
btw, the error `RRset foo.example.com. IN CNAME: Conflicts with pre-existing non-CNAME RRset` is returned from PDNS API so please let me know the version of PDNS you are using.

**Comment by jaap3** [comment]
I tried to re-create the issue, but wasn't able to. I don't want to retry on the actual record that caused the issues before and don't know the underlying version of PDNS, so I don't know to proceed from here.

I'll close the issue until I run into it again and am able to provide more information.
