### ISSUE TITLE
Missing record types

### ISSUE THREAD

**Issue by madpsy** [ngoduykhanh/PowerDNS-Admin#435]
I'm trying to enable a few record types, such as SSHFP and OPENPGPKEY but after adding them to RECORDS_ALLOW_EDIT they're not appearing in the UI when adding a record. 

There's mention of them in app/models.py but not much else. Does every record type have to be specifically coded for some reason (validation?) or can they just assume 'string' for any which don't have specific support (such as the nice splitting of fields for MX etc)?

**Comment by ngoduykhanh** [comment]
> I'm trying to enable a few record types, such as SSHFP and OPENPGPKEY but after adding them to RECORDS_ALLOW_EDIT they're not appearing in the UI when adding a record.

Are you using the latest code? The setting is now be done in the UI, not the config file anymore.

>There's mention of them in app/models.py but not much else. Does every record type have to be specifically coded for some reason (validation?) or can they just assume 'string' for any which don't have specific support (such as the nice splitting of fields for MX etc)?
No need, the specifically code is just for UX and did some validation. Technically you still able to put the record data in a textbox i believe.

**Comment by madpsy** [comment]
Thanks! I had not realised the config had moved into the UI. Found permitted record types under settings and all works well.
