### ISSUE TITLE
SSL not Secure

### ISSUE THREAD

**Issue by ghost** [ngoduykhanh/PowerDNS-Admin#436]
Hi

I have change a installation to ssl and get The error that the page is not secure. My networktraffix show me this:
http://ns1.domain.tld/error/404 as not secure on login Page. Have I forgot a setting?

**Comment by ngoduykhanh** [comment]
It is just matter of web server configuration. There is an example in [WIKI page](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx) that you can refer to.

**Comment by SandraCCH** [comment]
This works fine. Thank you for your great work.
