### ISSUE TITLE
How to configure PowerDNS w/ submount behind Nginx

### ISSUE THREAD

**Issue by johntdyer** [ngoduykhanh/PowerDNS-Admin#445]
So I have configured powerDNS w/ the example using SystemD and nginx, and its working great. Howver I would like to configure it to be under a path ( http://myserver.com/powerdns ).  Its not clear to me where I set this base path.  Any suggestions would he great

**Comment by Ramalama2** [comment]
its not possible at the moment.

I have some ideas, like a double proxy with nginx, but this will not work.
And just change the locations will dont work too, because the sites are gonna always to redirect to the root...

In my opinion, you need to work with a subdomain, thats the only clean way...
Or you can do a subdomain like pdns.myserver.com and an iframe in the index.html of myserver.com/powerdns/ directory.

Cheers :-)

**Comment by rkerr** [comment]
Totally untested, but in theory this should be pretty simple. First you need to configure nginx to mount the app on the right path, and second you need to tell flask that it is mounted there so the redirects are right. For the first part you edit the relevant location directives in the nginx config. For the second part you need to modify the gunicorn call to pass the correct path in SCRIPT_NAME:

ExecStart=/opt/web/powerdns-admin/flask/bin/gunicorn --workers 2 --bind unix:/opt/web/powerdns-admin/powerdns-admin.sock -e SCRIPT_NAME=**/app-path** app:app

**Comment by Metrax** [comment]
I had the same problem like @johntdyer .

> For the first part you edit the relevant location directives in the nginx config. For the second part you need to modify the gunicorn call to pass the correct path in SCRIPT_NAME:
> 
> ExecStart=/opt/web/powerdns-admin/flask/bin/gunicorn --workers 2 --bind unix:/opt/web/powerdns-admin/powerdns-admin.sock -e SCRIPT_NAME=**/app-path** app:app

Thanks to @rkerr , it worked fine for me.

nginx.conf of host:
```
location /powerdns-admin/ {
     proxy_pass http://127.0.0.1:9191;
}
```

changed in supervisord.conf of the docker container:
```
[program:powerdns-admin]  
command=/usr/local/bin/gunicorn -t 120 --workers 4 --bind '0.0.0.0:9191' -e SCRIPT_NAME=/powerdns-admin --log-level info app:app
```

**Comment by rodehoed** [comment]
Sorry to re-open:

> [program:powerdns-admin]  
> command=/usr/local/bin/gunicorn -t 120 --workers 4 --bind '0.0.0.0:9191' -e SCRIPT_NAME=/powerdns-admin --log-level info app:app
> ```

But when I'm starting that line (ofcourse I changed path) it says: ImportError: No module named 'app'.
