### ISSUE TITLE
Bug Found? The server refused to process your request and return a 400 error. You may return to the dashboard.

### ISSUE THREAD

**Issue by kamunhas** [ngoduykhanh/PowerDNS-Admin#449]
Hi all,

First of all mention that I am a complete newbie on this, so please excuse me if I do any mistake or "blame" the wrong people.

Scenario:

Freshly instaled Ubuntu 18.04+MariaDB+PowerDNS 4.1.1 + PowerDNS Admin

When trying to set the first domain I get this error:

The server refused to process your request and return a 400 error. You may return to the dashboard.

But when going to Dashboard I can really find the domain in there, so next step is trying to create a record ---> crashes when trying to save changes ( no descriptive error, just somewhat "contact your administrator" )

Looking into databases I was able to find the domain in both pdns and powerdnsadmin databases but (of course) not any single trace of the record...

API Key and Conection between PDNS and PDNS-Admin is working (some records are created...)

cat /var/log/syslog --->  HTTP ISE for "/api/v1/servers/localhost/zones/test.local": Exception: GSQLBackend unable to feed record: Could not prepare statement: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values (?,?,?,?,?,?,?,?,?,NULL): Unknown column 'change_date' in 'field list'

That "change_date" column was not on the oficial DB schema!!!! well.... lets try:

alter table records add change_date int default null;

Trying again... and et voilá!!! it is working !!!!

**Comment by ngoduykhanh** [comment]
PowerDNS-Admin communicate with PowerDNS using the API, not DB writing directly. According to the SQL query error, it looks like you have issue with the PowerDNS DB schema. I suggest you to double check your setup or raise an issue to PDNS repo if you find it is a bug.
