### ISSUE TITLE
Why two mysql server containers ?

### ISSUE THREAD

**Issue by francesco2013** [ngoduykhanh/PowerDNS-Admin#450]
Hello,

I was wondering, reading the docker-compose.yaml file why do you have two containers running mysql ?

powerdns-admin-mysql:
    image: mysql/mysql-server:5.7
    hostname: ${PDA_DB_HOST}
    container_name: powerdns-admin-mysql
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - 3306
    volumes:
      - powerdns-admin-mysql-data:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_DATABASE=${PDA_DB_NAME}
      - MYSQL_USER=${PDA_DB_USER}
      - MYSQL_PASSWORD=${PDA_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

 pdns-mysql:
    image: mysql/mysql-server:5.7
    hostname: ${PDNS_DB_HOST}
    container_name: ${PDNS_DB_HOST}
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - 3306
    volumes:
      - powerdns-mysql-data:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_DATABASE=${PDNS_DB_NAME}
      - MYSQL_USER=${PDNS_DB_USER}
      - MYSQL_PASSWORD=${PDNS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

Can someone please explain me the reason why two separated containers running mysql server are needed ?

**Comment by Chrzi** [comment]
It is not really needed, but easier to setup. The offical mysql and mariadb images are built for one database with one user.

You could put more databases into them, but you can not specify it in the env variables (which is desired)

**Comment by ngoduykhanh** [comment]
Ya, Chrzi is right.

Btw, the repo docker-compose file is just a reference and used for development purpose. You can always adjust it as you want.
