### ISSUE TITLE
Bug: when editing user only first word of "last name" is showed

### ISSUE THREAD

**Issue by prupert** [ngoduykhanh/PowerDNS-Admin#451]
There is a bug on the `/admin/user/edit/<username>` page. In the form field of "Last name" only the first word is shown when the last name contains multiple words.

How to reproduce?
- Create or edit user with last name "Some Last Names Have Multiple Words"
- Click "EDIT" again for this user, look at the field: only "Some" is shown
- When making other changes to this user, the last name will be saved as "Some"

**Comment by prupert** [comment]
Found the bug. The "value" should be quoted, but isn't:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/2f39512b658aae6ce229f1cc94b4205b34d25a05/app/templates/admin_edituser.html#L51

When looking at this file, it appears the bug exists for all other fields as well. All field values are missing quotes in the HTML.

**Comment by ngoduykhanh** [comment]
Thanks @prupert  for catching that. I have fixed it in bc2b57e47570c682262e52feb07393b26ebdc4e3
