### ISSUE TITLE
error when build with 'docker-compose build'

### ISSUE THREAD

**Issue by iamnumlock** [ngoduykhanh/PowerDNS-Admin#452]
Step 28/31 : ADD . /powerdns-admin/
 ---> d017574e398c
Step 29/31 : COPY ./configs/${ENVIRONMENT}.py /powerdns-admin/config.py
ERROR: Service 'powerdns-admin' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder108580002/configs/.py: no such file or directory

**Comment by rkerr** [comment]
It's failing because the ENVIRONMENT variable isn't set. There's a file ".env" that contains a bunch of environment variables you will need to set before running docker-compose build.  Easiest thing is to just `source ./.env` in your shell before running docker-compose
