### ISSUE TITLE
Prevent create users

### ISSUE THREAD

**Issue by hellEVIL-13** [ngoduykhanh/PowerDNS-Admin#453]
It is necessary to make an option in the settings so that users can not create accounts themselves

I'm talking about the main login page and links Create an account

**Comment by paescuj** [comment]
There is already an option under Settings > Authentication > General

**Comment by hellEVIL-13** [comment]
I only see these settings.
I want the users to be in the local DB, but on the main login page they could not create accounts themselves

 Local DB Authentication
Allow users to sign up

**Comment by hellEVIL-13** [comment]
wow, that's what you need, thanks
