### ISSUE TITLE
Add warning on unapplied changes when session timeout approaches

### ISSUE THREAD

**Issue by scop** [ngoduykhanh/PowerDNS-Admin#457]
It would be nice to issue a warning popup or something before session times out, if there are unapplied changes. Otherwise hitting the timeout with unapplied stuff results in loss of work.

**Comment by epipheus** [comment]
It's very annoying.  can we set the session timeout to something reasonable? Where?

**Comment by zoeller-freinet** [comment]
A warning on imminent session timeout has been implemented via #610, session timeout is configurable via the Web UI (Settings -> Basic, `session_timeout` (number is in minutes).

Indication on unsaved changes is another issue, see e.g. #92.
