### ISSUE TITLE
Bad JSON in history's detail column

### ISSUE THREAD

**Issue by dreynaud-w3line** [ngoduykhanh/PowerDNS-Admin#466]
For all history entries containing one or more double quotes in the history.detail column, a javascript error occured when we clic on the "Info" button within the "History" screen.

Double quotes must be escaped using a backslash (\") fo JSON data.

Could you update code in order to have the JSON compliant ?

Best regards.

**Comment by ngoduykhanh** [comment]
Could you please give me more information about your setup and how to reproduce this issue?

**Comment by dreynaud-w3line** [comment]
For some records, when i click, on the button "INFO" from the History View, the browser catch a JavaScript error :

VM117:1 Uncaught SyntaxError: Unexpected token v in JSON at position 30
    at JSON.parse (<anonymous>)
    at Object.prettyPrint (main.js?fe033d5e:5163)
    at HTMLButtonElement.<anonymous> (history:6259)
    at HTMLBodyElement.dispatch (main.js?fe033d5e:364)
    at HTMLBodyElement.elemData.handle (main.js?fe033d5e:350)

The database field [history.detail] contains the following data 👍 

{'record': [{'record_data': '"v=spf1 include:spf.protection.outlook.com -all"', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'TXT', 'record_name': '@'}, {'record_data': '0 innolea-fr.mail.protection.outlook.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'MX', 'record_name': '@'}, {'record_data': '100 1 443 sipdir.online.lync.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'SRV', 'record_name': '_sip._tls'}, {'record_data': '100 1 5061 sipfed.online.lync.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'SRV', 'record_name': '_sipfederationtls._tcp'}, {'record_data': 'autodiscover.outlook.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'CNAME', 'record_name': 'autodiscover'}, {'record_data': 'enterpriseenrollment.manage.microsoft.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'CNAME', 'record_name': 'enterpriseenrollment'}, {'record_data': 'enterpriseregistration.windows.net.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'CNAME', 'record_name': 'enterpriseregistration'}, {'record_data': 'webdir.online.lync.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'CNAME', 'record_name': 'lyncdiscover'}, {'record_data': 'sipdir.online.lync.com.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'CNAME', 'record_name': 'sip'}, {'record_data': '"MS=ms33008889"', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'TXT', 'record_name': '@'}, {'record_data': 'dns.w3line.fr. postmaster.w3line.fr. 2019032001 10800 3600 604800 3600', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'SOA', 'record_name': '@'}, {'record_data': 'dns.w3line.fr.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'NS', 'record_name': '@'}, {'record_data': 'ext01.w3line.fr.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'NS', 'record_name': '@'}, {'record_data': 'mail.w3line.fr.', 'record_status': 'Active', 'record_ttl': '3600', 'record_type': 'NS', 'record_name': '@'}], 'serial': '2019032001'}

Trying to parse the JSON data using http://json.parser.online.fr/ cause 143 errors.

We have making changes to the JSON data :
- searching for " (double-quotes) and replacing all by \" (json escaped double-quotes)
- searching for ' (single-quote) and replacing all by " (double-quotes)

After the changes, we have updated the SQL data field (using HeidiSQL to connect to the database) with the new JSON data and now the INFO button works fine.

It work also if we do not replace (singe-quotes) by (double-quotes) and removed all records containg a double-quotes.

My conclusion is : double-quotes are the problem.

**Comment by ngoduykhanh** [comment]
The History feature has been adjusted recently.
