### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by jiangby123** [ngoduykhanh/PowerDNS-Admin#467]
After starting with docker, the A record added on the web page cannot be saved. After adding it, there is no refresh.

**Comment by openmsk** [comment]
![image](https://user-images.githubusercontent.com/3602406/53221852-66336680-367c-11e9-81a7-ae08b3ac21e5.png)

**Comment by jiangby123** [comment]
Oh, sorry, I didn’t apply after I ordered save.
Many thanksOh, sorry, I didn’t apply after I ordered save.
Many thanks

**Comment by openmsk** [comment]
close issue please
