### ISSUE TITLE
Master & Slave NS Setup

### ISSUE THREAD

**Issue by dfiel** [ngoduykhanh/PowerDNS-Admin#47]
Hello All,

I followed the [DigitalOcean tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-dns-replication-on-a-slave-powerdns-server-on-ubuntu-14-04) to set up master and slave servers. In order for the domain to replicate, there must be 2 NS records in the domain. I don't see an option to add NS records. Am I missing something?

**Comment by ivanfilippov** [comment]
Hi @dfiel 

Thanks for trying PowerDNS-Admin! You'll need to add the NS record type into `config.py`. Find the line that says this:
`RECORDS_ALLOW_EDIT = ['A', 'AAAA', 'CNAME', 'SPF', 'PTR', 'MX', 'TXT']`
and change it to this:
`RECORDS_ALLOW_EDIT = ['A', 'AAAA', 'CNAME', 'SPF', 'PTR', 'MX', 'TXT', 'NS']`

Let me know if that helps. :smile:

**Comment by dfiel** [comment]
@ivanfilippov Yes, that worked. Now I just have to get the actual syncing of records to work. Would you know anything about that?

**Comment by ivanfilippov** [comment]
This is how you'd configure a traditional master/slave setup:
- Make sure you have `allow-axfr-ips=<your slaves IP address>` set in the masters `/etc/powerdns/pdns.conf`.
- Add a new domain as a master on the PowerDNS-Admin instance on the master
- Add the same domain as a slave on the PowerDNS-Admin instance on the slave (making sure to enter the masters IP address when you do it)
- That's it, PowerDNS will take care of replication by itself

You can also configure 'supermaster' functionality which is a very cool feature in PowerDNS. This makes the slave automatically query the master for all domains the master hosts and create slave domains for them as long as the slave is one of the configured nameservers. All you'd need to do is add the masters IP address and the current servers hostname into the supermasters database table on the slave. PowerDNS-Admin doesn't have this functionality so you'll need to do it manually via the SQL command line or a tool like phpMyAdmin. Something like:

```sql
INSERT INTO supermasters VALUES ('<your masters IP address>', '<your slaves hostname>', 'admin');
```

The DigitalOcean tutorial you linked actually uses this method so I'd recommend going with it. You also won't need a PowerDNS-Admin instance on the slave.

**Comment by dfiel** [comment]
@ivanfilippov How long does this usually take to propagate? My settings look like this:

     +---------------+------------------------+---------+
     | ip            | nameserver             | account |
     +---------------+------------------------+---------+
     | 104.XXX.61.XX | ns2.XXXXXXXXXXXXXX.xyz | admin   |
     +---------------+------------------------+---------+

The correct master IP is in the above record, and the settings in PowerDNS-Admin on the host look like this:
![image](https://cloud.githubusercontent.com/assets/7292540/15947661/c2552722-2e6a-11e6-96ae-4fc94dd7d89b.png)

Am I missing something, or are my settings wrong?

**Comment by ivanfilippov** [comment]
Your settings look good to me. To confirm, the supermaster snip you pasted above is on the slave server and the screenshot is from master, correct?

Also, have you tested to make that your slave can access and query the master? Something like running `dig ns1.yourdomain.com @yourmastersIP` on the slave should do it.

**Comment by dfiel** [comment]
@ivanfilippov Yes, the MySQL results are on the slave, and the screenshot is from my master server.

Using dig as you mention returned the correct IP as an A record.

**Comment by ivanfilippov** [comment]
Hi @dfiel 

Sorry for the delay. This may be a bit beyond my abilities, you might want to ask for help on the PowerDNS forums/github.
