### ISSUE TITLE
applying changes to large domain: "Error when applying new changes"

### ISSUE THREAD

**Issue by megabert** [ngoduykhanh/PowerDNS-Admin#479]
When I try to make changes at a large domain, I get the following error(Red Error Message window):

"Error: Error when applying new changes"

The changes are not applied into the pdns-database. The powerdns-admin interface however shows the new, not applied data.

When I look into /powerdns-admin/logs/log.txt I get the following error:

```2019-03-05 13:25:30,568 - app.views - ERROR - Cannot apply record changes. Error: (_mysql_exceptions.DataError) (1406, "Data too long for column 'detail' at row 1") [SQL: 'INSERT INTO history (msg, detail, created_by, created_on) VALUES (%s, %s, %s, %s)'] [parameters: ('Apply record changes to domain mydomain.de', '{"serial": "2019020521", "record": [{"record_data": "1.2.3.4", "record_name": "*.cluster", "record_status": "Active", "record_type": "A", "reco ... (133402 characters truncated) ...  "86400"}, {"record_data": "1.2.3.5", "record_name": "testshop", "record_status": "Active", "record_type": "A", "record_ttl": "86400"}]}', 'admin', datetime.datetime(2019, 3, 5, 13, 25, 30, 546552))] (Background on this error at: http://sqlalche.me/e/9h9h)```

The Domain holds 1000 records. (Other, smaller Domains are working perfectly).

That is obviously not the only error happening, since it states it can not insert a record into the history table (of powerdns-admin database). But there's nothing about the not accomplished/failed api call for powerdns.

Environment: 
- Docker
- MariaDB 10.3.12
- powerdns-admin version: current version from github

**Comment by p53** [comment]
this seems to be related to this https://github.com/PowerDNS/pdns/issues/5992 chunk encoding could fix it

**Comment by megabert** [comment]
Thanks for your answer p53.

As far as I see #5992 and #1469 are about curl and maximum header size/length. 

This error is a mysql error.

**Comment by Dolphi2** [comment]
I have exactly the same problem with large domains!

The colomn 'detail' in table 'history' is of type text which has a maximum of 65535 charachters. Changing it to LONGTEXT solved the problem for me.
MariaDB [pda]> describe history;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| msg        | varchar(256) | YES  |     | NULL    |                |
| detail     | text         | YES  |     | NULL    |                |
| created_by | varchar(128) | YES  |     | NULL    |                |
| created_on | datetime     | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+

A command to fix this: (using mysql command line and applying it to the powerdns-Admin database):
```
ALTER TABLE `history` MODIFY `detail` LONGTEXT;
```

After the alteration of the type to longtest, applying changes to large domains completes successfully.

**Comment by p53** [comment]
ah sorry i didn't read the data :) (too quick) but anyway we will probably hit also problem which i posted...

**Comment by p53** [comment]
try above branch, i am trimming there detail string

**Comment by Dolphi2** [comment]
I have tried the branch https://github.com/ngoduykhanh/PowerDNS-Admin/pull/492. It solved the issue in my case. Applying changes to large domain does not display an error and the domain updates successfully.

**Comment by vampik** [comment]
#492 didn't fix the issue. Well, it fixed error when applying changes. But it causes errors when viewing the history. Browser console shows errors like:
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1001 of the JSON data
SyntaxError: JSON.parse: unterminated string at line 1 column 1001 of the JSON data
SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 1001 of the JSON data

**Comment by megabert** [comment]
I just checked the patch of #492 (https://github.com/p53/PowerDNS-Admin/commit/43095f5ee0352cdde7ec3d3459a6578484a5d257.patch) against current PowerDNS-Admin version.

It fixes the reported problem for me.

**Comment by vampik** [comment]
Not really true, as I said above. It fixes applying changes, but it breaks history details. Trimmed history details cannot be viewed.

**Comment by megabert** [comment]
@vampik: Yes you're right. 

Not fixed, but for me better this kind of workaround than damaged data or inability to merge certain domains.

**Comment by pprietosanchez** [comment]
I have the same issue, as I can see, when you press "apply changes" the powerdns-admin interface modifies all register existing on domain, not only modified registries, causing to try a very large data to save in the history database, on some cases is possible to fail the insert.

As an example, if you have 1000 records in a Domain and you try to add an A record, the powerdns-admin interface tries to save in history 1000 modified record and the new record you are trying to insert.

The issue is double, because it can fails on the insert and if the system doesn't fail on the insert, yo can a lot of unnecessary entries on your history.

Regards.

**Comment by ngoduykhanh** [comment]
History detail now only contains record changes (add/delete) for the domain.
