### ISSUE TITLE
Minify JS / CSS

### ISSUE THREAD

**Issue by Trozz** [ngoduykhanh/PowerDNS-Admin#48]
Hey @ngoduykhanh 

Not sure if you would want a PR or not but on my fork I have minified the JS/CSS in efforts to increase the speed on large deployments.

Let me know if you want it and ill send a PR

**Comment by ngoduykhanh** [comment]
Hi @Trozz ,

Thank you for your idea. It is good to use minified JS/CSS files in the production environment. But we should do that in the deployment process. I prefer keeping normal JS/CSS for easy code maintenance in Github.

Regards,
