### ISSUE TITLE
File "/powerdns-admin/app/lib/utils.py", line 104, in fetch_remote

### ISSUE THREAD

**Issue by ericallenpaul** [ngoduykhanh/PowerDNS-Admin#483]
I am running docker and I get an error every time I try to create a new domain.
The domain is created but the server returns a 400 error.
The exact error is:

```
powerdns-admin          |   File "/powerdns-admin/app/lib/utils.py", line 104, in fetch_remote
powerdns-admin          |     r.raise_for_status()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
powerdns-admin          |     raise HTTPError(http_error_msg, response=self)
powerdns-admin          | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.23.171:8081/api/v1/servers/localhost/zones
powerdns-admin          |
powerdns-admin          | During handling of the above exception, another exception occurred:
powerdns-admin          |
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/powerdns-admin/app/models.py", line 1018, in add
powerdns-admin          |     urljoin(self.PDNS_STATS_URL, self.API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
powerdns-admin          |   File "/powerdns-admin/app/lib/utils.py", line 115, in fetch_json
powerdns-admin          |     accept='application/json; q=1')
powerdns-admin          |   File "/powerdns-admin/app/lib/utils.py", line 108, in fetch_remote
powerdns-admin          |     raise RuntimeError('Error while fetching {0}'.format(remote_url))
powerdns-admin          | RuntimeError: Error while fetching http://192.168.23.171:8081/api/v1/servers/localhost/zones

```
I can get to the URL (in fiddler) it lists at the end without any problem.
I tried downloading and installing everything instead of using docker, but I get the same error.
The domain adds but the page does not refresh properly and shows a 400 error.

![2019-03-13_1445](https://user-images.githubusercontent.com/847489/54305929-abbdc200-459e-11e9-817a-c7da23c9015c.png)

![2019-03-13_1442](https://user-images.githubusercontent.com/847489/54305729-3fdb5980-459e-11e9-9073-d8a3d3ae47ba.png)

Any ideas why this might be happening?

**Comment by p53** [comment]
did you check powerdns logs?

**Comment by ericallenpaul** [comment]
Yes but unfortunately now I don't remember what was in them--only that it didn't point me to a clear solution. I have already started writing my own interface and am most of the way through it at this point, but thanks for your reply. The parts of it that worked were good and it seems like a pretty slick implementation.
