### ISSUE TITLE
Can't enter multiple NS records

### ISSUE THREAD

**Issue by mortzu** [ngoduykhanh/PowerDNS-Admin#5]
If I add a second NS entry for the zone it removes the first one

**Comment by ivanfilippov** [comment]
This also affects MX records.

**Comment by ivanfilippov** [comment]
Looks like the PDNS API expects same-type records to be updated as a single 'rrset' in the JSON request (using multiple 'records') instead of over multiple 'rrsets'.  This issue will prevent the creation of any records (after the first one) that share a name type, this includes NS and MX entries as well as multiple A and AAAA entries used for round-robin.

This is what the PDNS API expects:
```javascript
{
  "rrsets": [
    {
      "name": "test.com",
      "type": "MX",
      "changetype": "REPLACE",
      "records": [
        {
          "content": "10 mx1.test.com",
          "disabled": false,
          "name": "test.com",
          "ttl": 3600,
          "type": "MX"
        },
        {
          "content": "20 mx2.test.com",
          "disabled": false,
          "name": "test.com",
          "ttl": 3600,
          "type": "MX"
        }
      ]
    }
  ]
}
```

And this is what the PowerDNS-Admin code sends:

```javascript
{
  "rrsets": [
    {
      "name": "test.com",
      "type": "MX",
      "changetype": "REPLACE",
      "records": [
        {
          "content": "10 mx1.test.com",
          "disabled": false,
          "name": "test.com",
          "ttl": 3600,
          "type": "MX"
        }
      ]
    },
	{
	  "name": "test.com",
      "type": "MX",
      "changetype": "REPLACE",
      "records": [
        {
          "content": "20 mx2.test.com",
          "disabled": false,
          "name": "test.com",
          "ttl": 3600,
          "type": "MX"
        }
      ]
	}
  ]
}
```

The code needing the fix is in 'app/models.py'.

**Comment by ivanfilippov** [comment]
I'm not a Python wizard by any means, but I've created a pull request with my solution to this problem. Anyone else wanting to fix the issue can make the code modifications listed in the pull request (https://github.com/ngoduykhanh/PowerDNS-Admin/pull/7)

**Comment by ngoduykhanh** [comment]
Thanks @mortzu for raising this issue and @ivanfilippov for the pull request. I've tried the code in your pull request, it seems not working in all case yet. There was a case that I lose all duplicate records.

I also pushed a new change for fixing this bug, see commit c94e24c98574da2595729547c9e41decce7ffa26

**Comment by ivanfilippov** [comment]
Your changes worked on my side, thanks @ngoduykhanh !

**Comment by stackexpress-kushal** [comment]
I have added two MX records , If I'm trying to add third MX record its replacing older records.

**Comment by kushalkumar101** [comment]
I have added two MX records, If I try to add third MX record it will replace older records.

**Comment by jon617** [comment]
I cannot get three MX records to add.  Only the last one is stored.

    {
      "rrsets": [
        { 
          "records": [
            { 
              "disabled": false,
              "content": "10 mailserver.com."
            }
          ],
          "changetype": "REPLACE",
          "ttl": 600,
          "type": "MX",
          "name": "me.com."
        },
        { 
          "records": [
            { 
              "disabled": false,
              "content": "20 mailserver2.com."
            }
          ],
          "changetype": "REPLACE",
          "ttl": 600,
          "type": "MX",
          "name": "me.com."
        },
        { 
          "records": [
            { 
              "disabled": false,
              "content": "30 mailserver3.com."
            }
          ],
          "changetype": "REPLACE",
          "ttl": 600,
          "type": "MX",
          "name": "me.com."
        },

Only the last one is stored.
