### ISSUE TITLE
I can not log in via domain

### ISSUE THREAD

**Issue by sIL3nTwaT3r** [ngoduykhanh/PowerDNS-Admin#503]
Hey,

I'm a little bit questioned and can not get any further. I have successfully installed PowerDNS Admin. As a web server I use a NGINX proxy.

The login works wonderfully, but only via the IP address.

About my domain, I can call PowerDNS Admin. But I can not log in because no data is detected. Have I overlooked something? I'm not so familiar with NGINX as I am with Apache.

**Comment by ngoduykhanh** [comment]
It is just a matter of Nginx configuration. You can take a look at [this example](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx).
