### ISSUE TITLE
docker-compose up example: What is the default login?

### ISSUE THREAD

**Issue by bitsofinfo** [ngoduykhanh/PowerDNS-Admin#505]
I've run the docker-compose up example. 

I go to http://localhost:9191/login and attempt logging in w/ creds in the `.env` file i sourced prior to docker compose up/build.

I can't login and have no clue what the credentials are.

**Comment by schretzi** [comment]
Did you try to register yourself? On the login page you will find a "Create an Account" Link, as the docu describes for running on ubuntu, the first user who registers is the Admin.

**Comment by bitsofinfo** [comment]
that worked, might be good to put a note there immediately following the docker compose section in the readme.
