### ISSUE TITLE
All available config options?

### ISSUE THREAD

**Issue by Kerwood** [ngoduykhanh/PowerDNS-Admin#507]
Hi.. Quick question. Where can I find all available config options for config.py?
I have an old config and I'm not sure all the options in there still are valid in the newest version of PowerDNS Admin.

Like is `BASIC_ENABLED` still a thing ?

**Comment by ngoduykhanh** [comment]
Several configs have been moved to the database. You can take a look at `config_template.py` file for the updated version of your config.py.
