### ISSUE TITLE
I had an error installing with Docker at step 27/29

### ISSUE THREAD

**Issue by r3d-f0x** [ngoduykhanh/PowerDNS-Admin#508]
`Step 27/29 : COPY ./configs/${ENVIRONMENT}.py /powerdns-admin/config.py`
`ERROR: Service 'powerdns-admin' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder305309959/configs/.py: no such file or directory`

I was in the PowerDNS-Admin/docker/PowerDNS-Admin directory and ran the command `docker-compose build`.  What went wrong here?

**Comment by r3d-f0x** [comment]
I edited the ,env file in the root PowerDNS-Admin directory for the repository and changed the passwords and the api key and set the environment to "production."

I got this error when running `docker-compose built` from the PowerDNS-Admin directory:

`Step 27/29 : COPY ./configs/${ENVIRONMENT}.py /powerdns-admin/config.py`
`ERROR: Service 'powerdns-admin' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder817878175/configs/production.py: no such file or directory`

**Comment by maxkochubey** [comment]
It is obvious that you had unset variable `${ENVIRONMENT}` (for the first time).
At second time you have no file `production.py`.

**Comment by r3d-f0x** [comment]
Thank you.  I realized that and I'm getting more familiar with Docker.  I have it running in a testing environment.
