### ISSUE TITLE
500 error when I try to manage a domain name

### ISSUE THREAD

**Issue by r3d-f0x** [ngoduykhanh/PowerDNS-Admin#510]
Everything was working out at first but after almost a day I got on the site and it said I had too many redirects and it wasn't displaying the site.  I shut down the containers and restarted them.  Now I get this error when I try to manage a domain name.

`[2019-05-14 17:53:05,370] [ERROR] | Cannot fetch domain's record data from remote powerdns api. DETAIL: HTTPConnectionPool(host='pdns-server', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones/r3df0x.srb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc060607dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by Armadill0** [comment]
Have you checked, via curl, telnet or something else, if your PDNS API is still reachable under you configured values (pdns-server:8081)?

**Comment by sshipway** [comment]
I had this error today, and it turned out to be because the pdns server was not actually running.  I would think that your pdns-server:8081 is not reachable either because it is down, firewalled, or not resolveable
