### ISSUE TITLE
Add global search

### ISSUE THREAD

**Issue by Armadill0** [ngoduykhanh/PowerDNS-Admin#515]
One of our most used features of our very old poweradmin installation was the ability to run a global search across all domains and records. I wasn't able to find such a feature in PowerDNS-Admin.
We use this e.g. to find multiple records which point to a singe IP address. If you don't know to which zone a record may belong to and you haven't setup a reverse record, it currently is nearly impossible to find forward records pointing to the IP address.

I also found an endpoint in the PowerDNS API which can provide such a feature: https://doc.powerdns.com/authoritative/http-api/search.html

Would be great if that could be added to PowerDNS-Admin, too. The search field could be placed centralized in the top bar together with a drop down list where the user can select the search type targets provided by the PowerDNS API: All, Zone, Record and Comment.

**Comment by ngoduykhanh** [comment]
It was implemented in #599. Restricted to Administrator/Operator only.
