### ISSUE TITLE
Under uwsgi, some actions lead to 404 errors.

### ISSUE THREAD

**Issue by piwats** [ngoduykhanh/PowerDNS-Admin#52]
When I want to toggle the fullscreen_layout f.e. I get the following error message inside my logs:

```
2016/06/27 15:54:35 [error] 2287#0: *7603 open() "/var/www/admin/setting/fullscreen_layout/toggle" failed (2: No such file or directory), client: XX.XX.XX.XX, server: sys.dtsi.eu, request: "POST /admin/setting/fullscreen_layout/toggle HTTP/2.0", host: "host.tld", referrer: "https://host.tld/admin/settings"
```

Nothing happens thereafter. Basically all the new settings are affected by this.

**Comment by ivanfilippov** [comment]
Hi @piwats,

Is the PDNS-Admin uWSGI at root or in a sub-folder(like: http://host/powerdns/)?

Let me know because that's likely the problem and I'll look into fixing that so that it works in both setups.

**Comment by piwats** [comment]
I have it under a subdirectory running, like host.tld/xy/pdns-admin.

**Comment by piwats** [comment]
Same happens, if I try to apply changes.

**Comment by ivanfilippov** [comment]
Hi @piwats 

Are you able to try the following branch https://github.com/ivanfilippov/PowerDNS-Admin/tree/scriptroot_fix ? I'd like to make sure I'm not missing anything.

I have applied a fix that works for me in the below four scenarios:
- directly via Flask
- Flask running behind an nginx reverse proxy
- running under uWSGI without a subfolder
- running under uWSGI with a subfolder

**Comment by piwats** [comment]
Sorry for the delay.

I tried your fixed repo and the original one. Now I get a 500 Error, too many redirects:

```
PowerDNS-Admin/app/views.py", line 47, in inject_login_ldap_first_setting
    return dict(login_ldap_first_setting=strtobool(login_ldap_first_setting.value))
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by ngoduykhanh** [comment]
@piwats : due to PR for issue #69 . Please follow my last comment there to update your db.
