### ISSUE TITLE
Exception when trying to access the page for one of the domains

### ISSUE THREAD

**Issue by r3d-f0x** [ngoduykhanh/PowerDNS-Admin#521]
I get this error when I try to access one of the domains through the web interface.  Site is accessible through http://register.rf.o through OpenNIC.

```
powerdns-admin          |
powerdns-admin          | [2019-06-04 19:38:27,437] [DEBUG] | Starting new HTTP connection (1): pdns-server:8081
powerdns-admin          | [2019-06-04 19:38:27,440] [ERROR] | Cannot fetch domain's record data from remote powerdns api. DETAIL:
TTPConnectionPool(host='pdns-server', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones/test (Caused by
wConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe9b6027b8>: Failed to establish a new connection: [Errno 111]
onnection refused',))
```

**Comment by ngoduykhanh** [comment]
It looks like the PDNS API is down or have access restriction. You should verify it first.

**Comment by wheelq** [comment]
launched via docker-compose up

**Comment by wheelq** [comment]
> I get this error when I try to access one of the domains through the web interface. Site is accessible through http://register.rf.o through OpenNIC.
> 
> ```
> powerdns-admin          |
> powerdns-admin          | [2019-06-04 19:38:27,437] [DEBUG] | Starting new HTTP connection (1): pdns-server:8081
> powerdns-admin          | [2019-06-04 19:38:27,440] [ERROR] | Cannot fetch domain's record data from remote powerdns api. DETAIL:
> TTPConnectionPool(host='pdns-server', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones/test (Caused by
> wConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe9b6027b8>: Failed to establish a new connection: [Errno 111]
> onnection refused',))
> ```

scroll up a bit to the section with:

```pdns-server_1 ```
