### ISSUE TITLE
Zone Validation

### ISSUE THREAD

**Issue by Net-Felix** [ngoduykhanh/PowerDNS-Admin#522]
Hi,

is it possible to add a zone validation before saving? For example it is possible to create a cname and another entry for the same subdomain which will break the zone.

Eg:
foo.bar.baz IN CNAME bar.baz
foo.bar.baz IN A 1.2.3.4

**Comment by ngoduykhanh** [comment]
Hi,

The PDA itself doesn't do that kind of validation. However, PowerDNS does. You would receive the error message pop up which is returned from PowerDNS API.

E.g.
`RRset foo.bar.baz. IN A: Conflicts with pre-existing RRset`
