### ISSUE TITLE
docker-compose build throws warning (error?)

### ISSUE THREAD

**Issue by ReneCD** [ngoduykhanh/PowerDNS-Admin#524]
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Maybe it runs fine with 8.1.1 but should it not use the latest pip available?

**Comment by ngoduykhanh** [comment]
We are using the default pip packages from Ubuntu 16.04 repository which might be outdated. However, the pip install command will throw a WARNING and the build process still continue without issue.

IMO, In the production env, we should use the latest stable version if possible, for all packages, not only pip :-)
