### ISSUE TITLE
id of records is changed on each update

### ISSUE THREAD

**Issue by akurach** [ngoduykhanh/PowerDNS-Admin#526]
after adding or deleting record/incrementing soa i get whole or partly updated zone. 

like 
<img width="441" alt="Screenshot 2019-06-13 at 13 04 04" src="https://user-images.githubusercontent.com/1264049/59423941-cc82f700-8ddb-11e9-8753-8387f50ed540.png">
or today the whole zone was updated after adding new record 
<img width="464" alt="Screenshot 2019-06-13 at 13 05 13" src="https://user-images.githubusercontent.com/1264049/59424032-eae8f280-8ddb-11e9-9d9e-f1c19c21a8b0.png">

in history the same thing 

<img width="426" alt="Screenshot 2019-06-13 at 13 06 20" src="https://user-images.githubusercontent.com/1264049/59424185-34394200-8ddc-11e9-8926-a94fdba16961.png">

what could it be? and may be you know how to fix it? 

for example: 
after deleting ptr of record chat.******.** i got additional 120 changes in ptr
one of them: 
deleted
```
38365	8	*******5.in-addr.arpa	PTR	student.********.**	600	0	\N	f	\N	t
```

created: 
```
49685 8 *******5.in-addr.arpa PTR student.********.** 600 0 \N f \N t
```

**Comment by Blizzke** [comment]
I have the same "issue" 

Fact is that I'm using external data to point to those records and every time I change a DNS entry I have to remap a lot of my data. 

I'm assuming it's intended behavior... It is probably just deleting all zone records and adding them again on every change? 
I mean: from a development point of view I get it, it's a lot simpler than diff'ing, but it's not really handy if you use the database for other data as well... This might force me to move away from the tool and find another one.

**Comment by Blizzke** [comment]
I guess we're not even going to get a reply then...

**Comment by akurach** [comment]
> I guess we're not even going to get a reply then...

already switched to dns-ui by opera

**Comment by ngoduykhanh** [comment]
The linked PR solves this issue by applying only changes to PDNS API. The same for History data. Not really a perfect implementation, but it is good for now I think. Will do more improvement in the future.

Btw, thanks for reporting the issue. I didn't have much time for this project :(
