### ISSUE TITLE
Serial might be larger than Integer

### ISSUE THREAD

**Issue by eht16** [ngoduykhanh/PowerDNS-Admin#529]
The `serial` and `notified_serial` columns in the `domain` table are defined as `sa.Integer()` which renders to 32bit *signed* integers on most DBMS (at least MySQL and PostgreSQL).
But per [RFC 1035](https://tools.ietf.org/html/rfc1035#section-3.3.13) the serial of a SOA record is defined as a 32bit *unsigned* integer and so can be up to 2^32-1 but the current database layout only allows 2^31-1 (because of signed int).

Even though it doesn't happen often, I'd suggest to increase the serial columns in the managed database layout to `sa.BigInteger` to be safe (MySQL has an unsigned integer type but it's not portable, other DBMS do not support unsigned integers and so BigInteger is the next best choice).

This did actually happened in our PowerDNS instance and caused warnings like:
`/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py:507: Warning: (1264, "Out of range value for column 'serial' at row 1") cursor.execute(statement, parameters)`.

**Comment by eht16** [comment]
To be clear: this is not only a warning but actually causes the domain to be updated every time as the serial differs between PowerDNS and the database as the serial in the database is truncated to 2^31-1.

**Comment by ngoduykhanh** [comment]
Thanks for raising the issue. Yes, we should increase the range of those serial fields. I am gonna submit a fix for this.

**Comment by ngoduykhanh** [comment]
I noticed that PDNS db schema also use int(11) for the notified_serial. It doesn't make sense to just update it in PDA db schema.

```
## in PDNS
mysql> desc domains;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(11)      | NO   | PRI | NULL    | auto_increment |
| name            | varchar(255) | NO   | UNI | NULL    |                |
| master          | varchar(128) | YES  |     | NULL    |                |
| last_check      | int(11)      | YES  |     | NULL    |                |
| type            | varchar(6)   | NO   |     | NULL    |                |
| notified_serial | int(11)      | YES  |     | NULL    |                |
| account         | varchar(40)  | YES  |     | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)

## in PDA
mysql> desc domain;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(11)      | NO   | PRI | NULL    | auto_increment |
| name            | varchar(255) | YES  | UNI | NULL    |                |
| master          | varchar(128) | YES  |     | NULL    |                |
| type            | varchar(6)   | NO   |     | NULL    |                |
| serial          | int(11)      | YES  |     | NULL    |                |
| notified_serial | int(11)      | YES  |     | NULL    |                |
| last_check      | int(11)      | YES  |     | NULL    |                |
| dnssec          | int(11)      | YES  |     | NULL    |                |
| account_id      | int(11)      | YES  | MUL | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
9 rows in set (0.01 sec)
```

**Comment by eht16** [comment]
According to the docs at https://doc.powerdns.com/authoritative/backends/generic-mysql.html#default-schema, the default schema defines an `unsigned int`.
It seems the `unsigned` flag was introduced in PowerDNS 4.1.1:
https://github.com/PowerDNS/pdns/commit/bd441912863b91ce0f32c8d3eac4e5ff9745e135
and https://doc.powerdns.com/authoritative/upgrading.html#to-4-1-1

**Comment by ngoduykhanh** [comment]
Oops, my PDNS schema is outdated actually. I pushed a new commit to change the data type. Thanks!
