### ISSUE TITLE
I can not add a domain to webUI

### ISSUE THREAD

**Issue by kvanleeuwen** [ngoduykhanh/PowerDNS-Admin#532]
Hello,

When I try to add a domain to the web ui, than I get this error message in de syslog:
I've set the right API details and added the base64_encoded api key to the db.

Jul  8 16:48:52 template gunicorn[22518]: [2019-07-08 16:48:52,923] [DEBUG] | Starting new HTTP connection (1): {api url}
Jul  8 16:48:52 template gunicorn[22518]: [2019-07-08 16:48:52,938] [ERROR] | Cannot add domain {domain}
Jul  8 16:48:52 template gunicorn[22518]: [2019-07-08 16:48:52,939] [DEBUG] | Traceback (most recent call last):
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jul  8 16:48:52 template gunicorn[22518]:     chunked=chunked)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Jul  8 16:48:52 template gunicorn[22518]:     six.raise_from(e, None)
Jul  8 16:48:52 template gunicorn[22518]:   File "<string>", line 2, in raise_from
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Jul  8 16:48:52 template gunicorn[22518]:     httplib_response = conn.getresponse()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Jul  8 16:48:52 template gunicorn[22518]:     response.begin()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Jul  8 16:48:52 template gunicorn[22518]:     version, status, reason = self._read_status()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 285, in _read_status
Jul  8 16:48:52 template gunicorn[22518]:     raise BadStatusLine(line)
Jul  8 16:48:52 template gunicorn[22518]: http.client.BadStatusLine: HTTP/1.0 1005 UNKNOWN
Jul  8 16:48:52 template gunicorn[22518]: During handling of the above exception, another exception occurred:
Jul  8 16:48:52 template gunicorn[22518]: Traceback (most recent call last):
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
Jul  8 16:48:52 template gunicorn[22518]:     timeout=timeout
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Jul  8 16:48:52 template gunicorn[22518]:     _stacktrace=sys.exc_info()[2])
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
Jul  8 16:48:52 template gunicorn[22518]:     raise six.reraise(type(error), error, _stacktrace)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
Jul  8 16:48:52 template gunicorn[22518]:     raise value.with_traceback(tb)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jul  8 16:48:52 template gunicorn[22518]:     chunked=chunked)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Jul  8 16:48:52 template gunicorn[22518]:     six.raise_from(e, None)
Jul  8 16:48:52 template gunicorn[22518]:   File "<string>", line 2, in raise_from
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Jul  8 16:48:52 template gunicorn[22518]:     httplib_response = conn.getresponse()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Jul  8 16:48:52 template gunicorn[22518]:     response.begin()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Jul  8 16:48:52 template gunicorn[22518]:     version, status, reason = self._read_status()
Jul  8 16:48:52 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 285, in _read_status
Jul  8 16:48:52 template gunicorn[22518]:     raise BadStatusLine(line)
Jul  8 16:48:52 template gunicorn[22518]: urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('HTTP/1.0 1005 UNKNOWN\r\n',))
Jul  8 16:48:52 template gunicorn[22518]: During handling of the above exception, another exception occurred:
Jul  8 16:48:52 template gunicorn[22518]: Traceback (most recent call last):
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/models.py", line 1023, in add
Jul  8 16:48:52 template gunicorn[22518]:     urljoin(self.PDNS_STATS_URL, self.API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 115, in fetch_json
Jul  8 16:48:52 template gunicorn[22518]:     accept='application/json; q=1')
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 100, in fetch_remote
Jul  8 16:48:52 template gunicorn[22518]:     params=params
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/api.py", line 60, in request
Jul  8 16:48:52 template gunicorn[22518]:     return session.request(method=method, url=url, **kwargs)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
Jul  8 16:48:52 template gunicorn[22518]:     resp = self.send(prep, **send_kwargs)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
Jul  8 16:48:52 template gunicorn[22518]:     r = adapter.send(request, **kwargs)
Jul  8 16:48:52 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
Jul  8 16:48:52 template gunicorn[22518]:     raise ConnectionError(err, request=request)
Jul  8 16:48:52 template gunicorn[22518]: requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.0 1005 UNKNOWN\r\n',))

Does someone have a clue?

**Comment by ngoduykhanh** [comment]
In the UI, you just need to input the raw API key, not base64 encoded one.
btw, why it is HTTP/1.0 . 🤔 
```
 requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.0 1005 UNKNOWN\r\n',))
```
