### ISSUE TITLE
ERROR: Complete output from command

### ISSUE THREAD

**Issue by ceom123** [ngoduykhanh/PowerDNS-Admin#533]
Hello,guys! im trying to install powerdns-admin via guide of Wiki.
but its give me these errors.

> 
> Building wheel for SQLAlchemy (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/7f/47/19/9d21adcd1f537063d81e00b933df6c58c9cd4d278bfb500bb5
>   Building wheel for mysqlclient (setup.py) ... error
>   ERROR: Complete output from command /opt/web/powerdns-admin/flask/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-97z6giyn/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y__v43_j --python-tag cp36:
>   ERROR: running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-3.6
>   copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.6
>   creating build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   copying MySQLdb/times.py -> build/lib.linux-x86_64-3.6/MySQLdb
>   creating build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>   running build_ext
>   building '_mysql' extension
>   creating build/temp.linux-x86_64-3.6
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -I/opt/web/powerdns-admin/flask/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o
>   unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for mysqlclient
>   Running setup.py clean for mysqlclient
>   Building wheel for configobj (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
>   Building wheel for python-ldap (setup.py) ... error
>   ERROR: Complete output from command /opt/web/powerdns-admin/flask/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-97z6giyn/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ucd14u53 --python-tag cp36:
>   ERROR: running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-3.6
>   copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.6
>   copying Lib/ldif.py -> build/lib.linux-x86_64-3.6
>   creating build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.6/ldap
>   copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.6/ldap
>   creating build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.6/ldap/controls
>   creating build/lib.linux-x86_64-3.6/ldap/extop
>   copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.6/ldap/extop
>   copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.6/ldap/extop
>   creating build/lib.linux-x86_64-3.6/ldap/schema
>   copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.6/ldap/schema
>   copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.6/ldap/schema
>   copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.6/ldap/schema
>   copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.6/ldap/schema
>   creating build/lib.linux-x86_64-3.6/slapdtest
>   copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.6/slapdtest
>   copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.6/slapdtest
>   running egg_info
>   writing Lib/python_ldap.egg-info/PKG-INFO
>   writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
>   writing requirements to Lib/python_ldap.egg-info/requires.txt
>   writing top-level names to Lib/python_ldap.egg-info/top_level.txt
>   reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   no previously-included directories found matching 'Doc/.build'
>   writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
>   creating build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
>   running build_ext
>   building '_ldap' extension
>   creating build/temp.linux-x86_64-3.6
>   creating build/temp.linux-x86_64-3.6/Modules
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.1.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include/python3.6m -I/opt/web/powerdns-admin/flask/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
>   unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for python-ldap
>   Running setup.py clean for python-ldap
>   Building wheel for cssmin (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/56/05/1e/ed779e049cd9909638d3973adb86f928ba1f6025118bd1a13e
>   Building wheel for jsmin (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/64/f4/de/9667d84f759289edf5442220997c6d4334637a6bb2a7b90f73
>   Building wheel for Flask-Seasurf (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/75/4a/8e/ca53c401e38aa1e0e6cd626c9bc3ef5230e362e385358779fb
>   Building wheel for lima (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/82/dd/62/c7a3b419315d2bc21a0f2b3404e0e8372f473a1ed43efd9557
>   Building wheel for PyYAML (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
>   Building wheel for webassets (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/eb/2a/fd/d10453a8c9ee05159da8877d083947e376caeca041988df18e
>   Building wheel for alembic (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/8b/65/b2/9837b4422d13e739c3324c428f1b3aa9e3c3df666bb420e4b3
>   Building wheel for xmlsec (setup.py) ... error
>   ERROR: Complete output from command /opt/web/powerdns-admin/flask/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-97z6giyn/xmlsec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-17sdu9p5 --python-tag cp36:
>   ERROR: running bdist_wheel
>   running build
>   running build_ext
>   building 'xmlsec' extension
>   creating build
>   creating build/temp.linux-x86_64-3.6
>   creating build/temp.linux-x86_64-3.6/tmp
>   creating build/temp.linux-x86_64-3.6/tmp/pip-install-97z6giyn
>   creating build/temp.linux-x86_64-3.6/tmp/pip-install-97z6giyn/xmlsec
>   creating build/temp.linux-x86_64-3.6/tmp/pip-install-97z6giyn/xmlsec/src
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.3 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/tmp/pip-install-97z6giyn/xmlsec/.eggs/lxml-4.3.4-py3.6-linux-x86_64.egg/lxml/includes -I/tmp/pip-install-97z6giyn/xmlsec/.eggs/lxml-4.3.4-py3.6-linux-x86_64.egg/lxml -I/tmp/pip-install-97z6giyn/xmlsec/.eggs/lxml-4.3.4-py3.6-linux-x86_64.egg/lxml/includes/libxml -I/tmp/pip-install-97z6giyn/xmlsec/.eggs/lxml-4.3.4-py3.6-linux-x86_64.egg/lxml/includes/libexslt -I/tmp/pip-install-97z6giyn/xmlsec/.eggs/lxml-4.3.4-py3.6-linux-x86_64.egg/lxml/includes/libxslt -I/usr/include/python3.6m -I/opt/web/powerdns-admin/flask/include/python3.6m -c /tmp/pip-install-97z6giyn/xmlsec/src/lxml.c -o build/temp.linux-x86_64-3.6/tmp/pip-install-97z6giyn/xmlsec/src/lxml.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
>   unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for xmlsec
>   Running setup.py clean for xmlsec
>   Building wheel for msgpack-python (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/d5/de/86/7fa56fda12511be47ea0808f3502bc879df4e63ab168ec0406
>   Building wheel for simplejson (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/5d/1a/1e/0350bb3df3e74215cd91325344cc86c2c691f5306eb4d22c77
>   Building wheel for Mako (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/cc/0e/59/0e7f24103d1ebce045037aa17b75548a8387f5e7d2d0011fdc
>   Building wheel for pycparser (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
>   Building wheel for pyrsistent (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/8a/ec/e2/3b9045d997adb0376026267ebbb641bed0f9126eb2bc615330
>   Building wheel for strict-rfc3339 (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/bb/af/c9/b6e9fb5f9b2470e4ed2a7241c9ab3a8cdd3bc8555ae02ca2e6
> Successfully built Flask-Assets Flask-Login SQLAlchemy configobj cssmin jsmin Flask-Seasurf lima PyYAML webassets alembic msgpack-python simplejson Mako pycparser pyrsistent strict-rfc3339
> Failed to build mysqlclient python-ldap xmlsec
> Installing collected packages: click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, Flask, webassets, Flask-Assets, Flask-Login, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, six, python-dateutil, alembic, Flask-Migrate, mysqlclient, configobj, pycparser, cffi, bcrypt, certifi, idna, urllib3, chardet, requests, pyasn1, pyasn1-modules, python-ldap, pyotp, qrcode, dnspython, gunicorn, pkgconfig, lxml, xmlsec, isodate, defusedxml, python3-saml, asn1crypto, cryptography, pyOpenSSL, pytz, cssmin, jsmin, Authlib, Flask-Seasurf, pytimeparse, lima, more-itertools, zipp, importlib-metadata, attrs, atomicwrites, pyparsing, packaging, py, wcwidth, pluggy, pytest, PyYAML, msgpack-python, pyrsistent, jsonpointer, rfc3987, strict-rfc3339, webcolors, jsonschema, swagger-spec-validator, simplejson, jsonref, bravado-core
>   Running setup.py install for mysqlclient ... error
>     ERROR: Complete output from command /opt/web/powerdns-admin/flask/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-97z6giyn/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_oo1f12/install-record.txt --single-version-externally-managed --compile --install-headers /opt/web/powerdns-admin/flask/include/site/python3.6/mysqlclient:
>     ERROR: running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     copying MySQLdb/times.py -> build/lib.linux-x86_64-3.6/MySQLdb
>     creating build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
>     running build_ext
>     building '_mysql' extension
>     creating build/temp.linux-x86_64-3.6
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -I/opt/web/powerdns-admin/flask/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o
>     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     ----------------------------------------
> ERROR: Command "/opt/web/powerdns-admin/flask/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-97z6giyn/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_oo1f12/install-record.txt --single-version-externally-managed --compile --install-headers /opt/web/powerdns-admin/flask/include/site/python3.6/mysqlclient" failed with error code 1 in /tmp/pip-install-97z6giyn/mysqlclient/

**Comment by ngoduykhanh** [comment]
Make sure you installed the package libraries for building requirements file:

```
sudo apt-get install -y libmysqlclient-dev libsasl2-dev libldap2-dev libssl-dev libxml2-dev libxslt1-dev libxmlsec1-dev libffi-dev pkg-config apt-transport-https virtualenv build-essential
```

**Comment by ceom123** [comment]
> 
> 
> Make sure you installed the package libraries for building requirements file:
> 
> ```
> sudo apt-get install -y libmysqlclient-dev libsasl2-dev libldap2-dev libssl-dev libxml2-dev libxslt1-dev libxmlsec1-dev libffi-dev pkg-config apt-transport-https virtualenv build-essential
> ```

Thanks bro!!!!!
