### ISSUE TITLE
Wiki cleanup

### ISSUE THREAD

**Issue by Daniel15** [ngoduykhanh/PowerDNS-Admin#536]
I recently did some cleanup of this wiki page: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx. The previous documentation said to run PowerDNS-Admin as root, which is extremely insecure.

What do you think about merging these two wiki pages together into one single page?
- https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-16.04---Ubuntu-18.04
- https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx

The first one has very little that's specific to Ubuntu, and that could be called out separately.

I'm happy to rewrite these pages, but didn't want to make very large changes to the wiki without asking first 😛

**Comment by ngoduykhanh** [comment]
Hi,

Thanks for fixing it.

The WIKI is open and contributed by several people. Yes, we can always improve it. Please feel free to submit another page with the merged content, then we can review and remove the old one.

**Comment by Daniel15** [comment]
Actually, thinking about it a bit, it probably make sense to keep them separate as the systemd/gunicorn instructions are the same across all OSes, but the Ubuntu instructions are specific to Ubuntu/Debian. I'll just clean up the wiki pages in place rather than making a new one :)
