### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by PhilsLab** [ngoduykhanh/PowerDNS-Admin#538]
Hey,

I just found out there are only third-party docker images hosted on docker hub for this software.
Is there any chance that there will be an official (and versioned) image on docker hub?

**Comment by xTrekStorex** [comment]
See https://github.com/ngoduykhanh/PowerDNS-Admin/pull/535

**Comment by PhilsLab** [comment]
@xTrekStorex thanks, didn't find that one even though I looked for similar issues...
