### ISSUE TITLE
template for new domains

### ISSUE THREAD

**Issue by TacoScheltema** [ngoduykhanh/PowerDNS-Admin#54]
A thought for a new feature:

Having an editable template to be applied when adding a new domain. Application of the template should be optional.

**Comment by piwats** [comment]
+1, also if possible to have multiple templates to choose from / and also to be able to combine them.

**Comment by ivanfilippov** [comment]
I'm working on a basic implementation of this.

**Comment by fabiorauber** [comment]
This would be really awesome.

**Comment by fabiorauber** [comment]
Would it be possible to create a DNSSEC enabled zone template?

**Comment by RoRoo1977** [comment]
Templates would be awesome.
Looking into this to replace poweradmin and their template functions is widely used here.

**Comment by madpsy** [comment]
Does anyone know if there is a way to at least automatically add the NS records when a domain is added?

I fear not and that will depend on this FR.

**Comment by Znuff** [comment]
This would be very useful. The default config values don't even allow to add NS records, which was a brief "WTF" for me.

**Comment by ngoduykhanh** [comment]
Feature is available in `developement` branch. Waiting to merge to master
