### ISSUE TITLE
Full install On CentOS7 without Dockers ? 

### ISSUE THREAD

**Issue by msalemcentrilogic** [ngoduykhanh/PowerDNS-Admin#558]
Hello, 

can we get a full detailed steps to install on CentOS7 without Dockers ? , I saw the WIKI however I would assume there are many missing steps. like MySQL and other tools.

**Comment by msalemcentrilogic** [comment]
never mind resolved :)

**Comment by kmorales026** [comment]
Hi,, could you helpe to install please?

**Comment by msalemcentrilogic** [comment]
In the Wiki, it states how to install without Dockers. usually if you are good with dockers it would be good. 

I like it old school
