### ISSUE TITLE
Automatically set version based on API's data

### ISSUE THREAD

**Issue by theel0ja** [ngoduykhanh/PowerDNS-Admin#559]
`curl -K "X-Api-Key: changeme" http://pdns:8081/api/v1/servers/localhost | jq .version` returns the version, why ask it in the admin panel?

**Comment by ngoduykhanh** [comment]
To avoid calling to that API to detect the version every time we make an API call (record applying for example). However, since the #604, I've dropped the old PDNS (3.x) support. I will need to think about a better way of handling the PDNS API version...
