### ISSUE TITLE
current version cannot insert/update any records with PDNS 4.0.0

### ISSUE THREAD

**Issue by CaptainQwark** [ngoduykhanh/PowerDNS-Admin#56]
Hi, 

It seems that I cannot make any changes to records with pdns 4.0.0 (rc2).
Is this a known issue (as there seems to be support for 4.0.0)?

I'm willing to work on this issue if it's known to be broken with 4.0.0 (and someone else isn't doing that already)

Thanks,
Alex.

**Comment by ngoduykhanh** [comment]
It works for me on version `4.0.0~alpha2-3build1` (on ubuntu 16.04). I haven't tried version 4.0.0 (rc2) yet. Can you give more detail on the error you got?

**Comment by CaptainQwark** [comment]
not much. the gui just says:
{ "msg": "There was something wrong, please contact administrator", "status": "error" }

and in the debug log:
2016-06-30 17:27:17,004 - MODEL - ERROR - Cannot apply record changes to domain While fetching http://127.0.0.1:8081/api/v1/servers/localhost/zones/test123.com: 'content-type'. DETAIL: test123.com
2016-06-30 17:27:17,007 - werkzeug - INFO - 172.20.15.252 - - [30/Jun/2016 17:27:17] "POST /domain/test123.com/apply HTTP/1.1" 400 -

**Comment by CaptainQwark** [comment]
I've tracked down the problem with pdns 4.0.0. 
the problem is that pdns doesnt return any json (or any content) if everthing went fine.  It just returns a 204 and no body.

this is easyly fixable in utils.py by adding something like:
```
   if r.status_code == 204:
        return True
```

But that needs handling in models.py as well. At least in Records.apply() but probably in other places as well. I have it working now but need to check other places. before I submit a pull request.

**Comment by CaptainQwark** [comment]
just returning an empyt dict solved the problem and didn't need further changes in models.py.
See PR #60

**Comment by ngoduykhanh** [comment]
That's a weird behavior of pdns i think. Maybe because of unstable version?
The `status_code` should be checked in the `fetch_remote` function as I commented on your PR.
btw, what is the response header did you get? I am interested in what did you get in `r.headers['content-type']`.

**Comment by CaptainQwark** [comment]
Below is the output of curl for a PATCH request. No content-type is given. Probably logical for a zero byte 204 reply :).

And this behavior is actually documented here [https://doc.powerdns.com/md/httpapi/api_spec/](url):
> URL: /api/v1/servers/:server_id/zones/:zone_id
> Allowed methods: GET, PUT, DELETE, PATCH.
> GET
>  Returns zone information.
> DELETE
>  Deletes this zone, all attached metadata and rrsets.
> PATCH
>  Modifies present RRsets and comments. Returns 204 No Content on success.

and: [https://httpstatuses.com/204](url) so returning a 204 seems quite logical here. 

curl output:
``` bash
curl -v -X PATCH --data '{"rrsets": [ { "changetype": "REPLACE", "type": "A", "name": "testing.kees.nl.", "ttl": 86400, "records": [{"content": "1.2.3.4", "disabled": false}]}]}' -H 'X-API-Key: X' http://127.0.0.1:8081/api/v1/servers/localhost/zones/kees.nl.
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PATCH /api/v1/servers/localhost/zones/kees.nl. HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8081
> Accept: */*
> X-API-Key: X
> Content-Length: 152
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 152 out of 152 bytes
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 0
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
* Server PowerDNS/4.0.0-rc2 is not blacklisted
< Server: PowerDNS/4.0.0-rc2
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
< 
* Closing connection 0
```

**Comment by ngoduykhanh** [comment]
Thanks @CaptainQwark  for figuring it out. `204` is the new http response code in pdns 4. I've commented in your PR and merged it.

**Comment by jallakim** [comment]
Works for me just fine in 4.0.0rc2.

Thanks!

**Comment by ivanfilippov** [comment]
This is resolved.
