### ISSUE TITLE
Problem with Modification not increasing SOA

### ISSUE THREAD

**Issue by tcastelle** [ngoduykhanh/PowerDNS-Admin#567]
Hello,

When I edit a domain and click on "Apply Changes" (even without any actual change), the SOA is correctly increased.

However, if i stay "inside" the domain and does several other modifications the SOA is not increased anymore.

The only way is to go back to the Dashboard Menu, and then inside the domain and click "Apply Changes".

Same behaviour with SOA-EDIT-API = DEFAULT or INCREASE.

I don't know if it's a PowerDNS or PowerDNS-Admin bug.

We are running PowerDNS 4.2.0.

Regards,

Thomas

**Comment by splog123** [comment]
That would seem to be the correct behaviour. Changes are stored up in a "queue" so to speak, and only permanently applied when you click Apply Changes, that is when the changed records are actually stored and when the SOA is updated. The name of the button tells you what the function is.

The Save button on each record does not make permanent changes, it merely tells PowerDNSAdmin you are done with that RR and want to go to another.

**Comment by tcastelle** [comment]
Thank you for your answer.

My problem is not with the « Save » button, but with the « Apply Changes ».

First « Apply Change » ==> SOA is updated and zone transfer to slaves from master works.
Every subsequent « Apply Change » ==> SOA is never updated.

The only way to make PowerDNS Admin update the SOA, is to click on « Dashboard » and then edit the zone and then click on « Apply Change ».

It seems that SOA is updated once we click on « Edit Zone », not when we click on « Apply Change ».
So, if I edit a zone, make a modification, click on « Apply Change », make another modification and click again on « Apply Change », only the 1st modification is transferred to my Slaves because SOA as only been updated with the first « Apply Change ».

Once again, I don’t know if its a PowerDNS Admin bug, or a PowerDNS bug. We are running PowerDNS Authoritative server version 4.2.1.

Regards,

Thomas

De : splog123 <notifications@github.com>
Envoyé : mardi 10 décembre 2019 15:00
À : ngoduykhanh/PowerDNS-Admin <PowerDNS-Admin@noreply.github.com>
Cc : Thomas CASTELLE <tcastelle@exaprobe.com>; Author <author@noreply.github.com>
Objet : Re: [ngoduykhanh/PowerDNS-Admin] Problem with Modification not increasing SOA (#567)


That would seem to be the correct behaviour. Changes are stored up in a "queue" so to speak, and only permanently applied when you click Apply Changes, that is when the changed records are actually stored and when the SOA is updated. The name of the button tells you what the function is.

The Save button on each record does not make permanent changes, it merely tells PowerDNSAdmin you are done with that RR and want to go to another.

**Comment by ngoduykhanh** [comment]
> However, if i stay "inside" the domain and does several other modifications the SOA is not increased anymore.

Do you mean you go to the domain page, edit the records, Save and hit Apply Changes button? I tried with my setup and see SOA is increased.

My setup:
- PDNS: 4.2.0
- Domain: SOA-EDIT-API = DEFAULT

**Comment by tcastelle** [comment]
Yes, I go to domain page, edit the records, Save and Apply Change.
First time SOA is increased.
But if I stay inside the domain, edit again another record, Save and Apply Change : SOA not increased.

Regards,

Thomas CASTELLE
Responsable de la Direction Technique
Direction des Opérations

Tel : +33 4 26 20 76 23 - Mob : +33 6 27 27 28 57
Agence de Lyon
13B avenue Albert Einstein - CS 90217 - 69623 VILLEURBANNE CEDEX
tcastelle@exaprobe.com<mailto:tcastelle@exaprobe.com> – www.exaprobe.com<http://www.exaprobe.com/>

[LOGO_EXAPROBE_ENDOSSEMENT_ECO_NEW_BLU_RVB_HD]

De : Khanh Ngo <notifications@github.com>
Envoyé : mardi 10 décembre 2019 15:34
À : ngoduykhanh/PowerDNS-Admin <PowerDNS-Admin@noreply.github.com>
Cc : Thomas CASTELLE <tcastelle@exaprobe.com>; Author <author@noreply.github.com>
Objet : Re: [ngoduykhanh/PowerDNS-Admin] Problem with Modification not increasing SOA (#567)


However, if i stay "inside" the domain and does several other modifications the SOA is not increased anymore.

Do you mean you go to the domain page, edit the records, Save and hit Apply Changes button? I tried with my setup and see SOA is increased.

My setup:

  *   PDNS: 4.2.0
  *   Domain: SOA-EDIT-API = DEFAULT

**Comment by splog123** [comment]
I can't replicate this behaviour on pdns-4.1.1 with latest PowerDNSAdmin (git) on Ubuntu-18.04.3 using SOA-EDIT-API DEFAULT
"Apply Changes" always increases the Serial if there are edited records.

How are you checking if the Serial increases? Your first mail mentioned slaves and masters so I assume PDNSAdmin updates a master pdns and that updates other nameservers (NOTIFY or perhaps native mysql). Do check both what the SOA in PowerDNSAdmin says and also "dig soa <zone> @<server>"

pdns does more work with the Serial than you'd think, there appears to be an internal serial and also an external serial that is used for dig soa. The db schema has fields for this. The pdns man pages describe it somewhat and I'm somewhat fuzzy about why they do this, but it's true enough. It has caught me and my dns admins out several times already
