### ISSUE TITLE
Feature request: Let any user do read only search on whole domains server

### ISSUE THREAD

**Issue by pprietosanchez** [ngoduykhanh/PowerDNS-Admin#568]
Hello,

We are using this app instead of poweradmin since a little days, It's very usefull and easy to install.

As we test de interface, we miss a more powerfull search features like a global search on  whole domains server, not only on where the user has permissions, like a whole server search on read only mode or, usign another approach, a more powerfull permissions system.

Thank you so much for your wonderfull work.

Best regards

Pedro

**Comment by mans39** [comment]
Hi,

I think this feature would be easily feasible because the searching method already exists with PowerDNS API (https://doc.powerdns.com/authoritative/http-api/search.html).

Regard's

**Comment by pprietosanchez** [comment]
> Hi,
> 
> I think this feature would be easily feasible because the searching method already exists with PowerDNS API (https://doc.powerdns.com/authoritative/http-api/search.html).
> 
> Regard's

Hello,

the feature I'm referring is not a whole search as it is, I mean that an unprivileged user can do a search within all domains on server, even if doesn't have permissions on them.

Regards

**Comment by zeylos** [comment]
Hi,

+1 for this feature, would be very usefull combined with LDAP users group.

Regards

**Comment by ngoduykhanh** [comment]
PR #599 for this feature. However, I make it available to Operator/Administrator only. I don't see any reason to expose it to the user as It might lead to security issues
