### ISSUE TITLE
Unix Sockets?

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [ngoduykhanh/PowerDNS-Admin#569]
Is there an undocumented configuration option for PDA that allows it to connect to MariaDB/MySQL via unix sockets?

Thanks!

**Comment by Daniel15** [comment]
Adding it like `?unix_socket=/var/run/mysqld/mysqld.sock` to the end of the config setting should work.

Like this:
```
SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+':'+str(SQLA_DB_PORT)+'/'+SQLA_DB_NAME+'?unix_socket=/var/run/mysqld/mysqld.sock'
```

Reference: https://stackoverflow.com/questions/6245813/is-it-possible-to-use-mysql-with-sqlalchemy-and-flask-if-my-mysql-socket-isnt-i

Unfortunately my installation is broken at the moment so I can't test this 😕

**Comment by MxyzptlkFishStix** [comment]
Thanks. That wasn't it, but you guided me in the right direction.

`SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME+'?unix_socket=/var/run/mysqld/mysqld.sock'`

I changed SQLA_DB_HOST from 127.0.0.1 to localhost as well.

**Comment by Daniel15** [comment]
Ah, good catch, I forgot to remove the port.
