### ISSUE TITLE
Support MySQL 8.x

### ISSUE THREAD

**Issue by HOSTED-POWER** [ngoduykhanh/PowerDNS-Admin#571]
the mysqlclient in the requirements.txt is too old to work with MySQL 8.x

   _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:1894:3: error: unknown type name ‘my_bool’; did you mean ‘bool’?
       my_bool recon = reconnect;
       ^~~~~~~
       bool

I changed requirements to: mysqlclient==1.4.4

And now it seems to work...

Any reason not using newer version anyway? :)

**Comment by almereyda** [comment]
Could you hand in a Pull Request that implements this little change?

**Comment by HOSTED-POWER** [comment]
Hello @almereyda 

I'm not very familiar with that to be honest, it would probably take a lot of time on my end.

Al that is needed is to change the requirements to at least mysqlclient==1.4.4 :)

I hope you can implement that?

**Comment by ngoduykhanh** [comment]
Looks weird, I don't have any problem with MySQL 8 container. Btw, It is good to have packages updated.  I made a change to update mysqlclient to 1.4.6
