### ISSUE TITLE
how to use the templates 

### ISSUE THREAD

**Issue by Mohamed-SM** [ngoduykhanh/PowerDNS-Admin#572]
I didn't find a good documentation on what to put in the data field of the template

**Comment by splog123** [comment]
The records in the templates are regular RRs. When you create a new zone and apply a template, the records are copied from the template to the new zone. Very useful for NS records.

So what goes in the data field? The usual content for the RR you are adding.

There can't really be good docs for this, the field contains what the DNS says that record type contains. 
Check the pdns docs for supported record types for more info
