### ISSUE TITLE
Supermaster support improvements

### ISSUE THREAD

**Issue by HOSTED-POWER** [ngoduykhanh/PowerDNS-Admin#573]
Hi,

The tool looks fantastic at first sight, however coming from poweradmin we miss supermaster features.

So unless I look over it, we really really miss following features:

- Show & Manage the supermasters (we have many many supermasters). Maybe it's there already hidden somewhere?
- On the "Manage domain", it has a button: Update from Master, unfortunately it doesn't show the current master. Since we have so many, we'd like to see this info there.
-  Ideally it would also allow to change the master from the GUI under "Manage Domain" for admin users. Sometimes domain needs new supermaster (new parent server).

**Comment by alexander-rieder** [comment]
yes, would be awesome

**Comment by ngoduykhanh** [comment]
Are you referring to the Master-Slave model? The "Update from Master" will send [axfr-retrieve API request](https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzoneszone95idaxfr-retrieve) which do RR call the masters. I've pushed small changes to show the actual Master, you can find it on the master branch now.
![Screen Shot 2019-12-11 at 13 40 40](https://user-images.githubusercontent.com/6447444/70599031-d36db380-1c1e-11ea-83ab-7c07bf8e9804.png)

I also noticed that PowerDNS itself has a table called **supermasters**  to act as a master server I guess. But there is no API to handle this.

**Comment by HOSTED-POWER** [comment]
Hi,

It would be good to just show the master ip as well without pressing sync :)

Furthermore, it would be more interesting if we could switch the master ip to another one. So a new server would become the master over it...

It's pretty cumbersome to get this done atm (we delete it and refresh zone trough named on the new master server).

Supermaster management is also missing I think, we have no idea who's in the current supermasters table :)

**Comment by ngoduykhanh** [comment]
> It would be good to just show the master ip as well without pressing sync :)

Noted. I am thinking of a place to display the domain's information. Including its masters.

> Furthermore, it would be more interesting if we could switch the master ip to another one. So a new server would become the master over it...
I think it is already there. You can go to the domain admin page, edit the zone type and reset the Masters IPs.

> Supermaster management is also missing I think, we have no idea who's in the current supermasters table :)
PDA works with PDNS over API. Currently, I don't see any API for managing the supermasters. So the feature is not achievable. Or, I am missing something?

**Comment by HOSTED-POWER** [comment]
Noted. I am thinking of a place to display the domain's information. Including its masters.
--> Mabye just in the "Update from Master"  , change it in: "Update from Master xxx.xxx.xxx.xxx"

I think it is already there. You can go to the domain admin page, edit the zone type and reset the Masters IPs.

---> that was quite hidden for us, but indeed, looks good :)

PDA works with PDNS over API. Currently, I don't see any API for managing the supermasters. So the feature is not achievable. Or, I am missing something?

--> I'm afraid that probably the case :(

PS: Thank you so much for your extensive replies!!!
