### ISSUE TITLE
Unable to access webUI from another computer on same LAN.

### ISSUE THREAD

**Issue by joshbgosh10592** [ngoduykhanh/PowerDNS-Admin#575]
I just installed PowerDNS-Admin on CentOS 7 using these directions, on top of PowerDNS being set up using: https://www.tecmint.com/install-powerdns-poweradmin-mariadb-in-centos-rhel/

But now when I go to a web browser on my local computer using the server's IP address with port 9191, I receive an error saying connection was refused.
I'm new to hosting a web server via Linux, so I have no idea where to start besides trying to curl it:

`[user@PowerDNS root]$ curl -I http://localhost:9191
HTTP/1.0 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 219
Location: http://localhost:9191/login
Set-Cookie: _csrf_token=asdf0987asdf987; Expires=Wed, 06-Nov-2019 03:53:51 GMT; Max-Age=432000; Path=/
Vary: Cookie
Set-Cookie: session=.cookiestringhere; Expires=Fri, 01-Nov-2019 04:03:51 GMT; HttpOnly; Path=/
Server: Werkzeug/0.16.0 Python/3.6.8
Date: Fri, 01 Nov 2019 03:53:51 GMT`
So, I'm assuming the webpage is running, but I just don't know how to allow other computers to access it.

**Comment by czeigler** [comment]
Do you have a firewall enabled on that server?  Chances are if you do you are blocking port 9191.  Run 

`sudo systemctl stop firewalld`

on the server and try to access the web site again from the other computer on the LAN.  If it works you'll want to figure out how to disable the firewall for just that port and turn it back on with

`sudo systemctl start firewalld`

**Comment by joshbgosh10592** [comment]
> Do you have a firewall enabled on that server? Chances are if you do you are blocking port 9191. Run
> 
> `sudo systemctl stop firewalld`
> 
> on the server and try to access the web site again from the other computer on the LAN. If it works you'll want to figure out how to disable the firewall for just that port and turn it back on with
> 
> `sudo systemctl start firewalld`

Thank you for your reply! I tried that right after I posted, no change.

**Comment by ieaster1** [comment]
Those instructions look to be for PowerAdmin, not PowerDNS-Admin.
https://github.com/poweradmin/poweradmin

Your issue sounds like httpd is binding access for 127.0.0.1 but not for 0.0.0.0.  You'll need to change that in your httpd Virtual Host configuration.  

For example:
`Listen 0.0.0.0:9191`

**Comment by joshbgosh10592** [comment]
> Those instructions look to be for PowerAdmin, not PowerDNS-Admin.
> https://github.com/poweradmin/poweradmin
> 
> Your issue sounds like httpd is binding access for 127.0.0.1 but not for 0.0.0.0. You'll need to change that in your httpd Virtual Host configuration.
> 
> For example:
> `Listen 0.0.0.0:9191`

Where would that file be? I just searched for httpd on the server and didn't come back with any results..

**Comment by vipera** [comment]
Probably in `/etc/httpd/conf/httpd.conf` or `ports.conf` in the same directory. You can try running `rgrep 'Listen' /etc/httpd` to search for it. This is of course assuming Apache is binding port 9191.

**Comment by joshbgosh10592** [comment]
> Those instructions look to be for PowerAdmin, not PowerDNS-Admin.
> https://github.com/poweradmin/poweradmin
> 
> Your issue sounds like httpd is binding access for 127.0.0.1 but not for 0.0.0.0. You'll need to change that in your httpd Virtual Host configuration.
> 
> For example:
> `Listen 0.0.0.0:9191`

I also just re-read your reply. I used the directions I linked to in order to install PowerDNS, and then used [these ](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7)steps to install PowerDNS-Admin.


> Probably in `/etc/httpd/conf/httpd.conf` or `ports.conf` in the same directory. You can try running `rgrep 'Listen' /etc/httpd` to search for it. This is of course assuming Apache is binding port 9191.

The server isn't running on Apache, but rather flask (I believe), as directed by the wiki to install onto CentOS7 [here](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7).

**Comment by ieaster1** [comment]
> I also just re-read your reply. I used the directions I linked to in order to install PowerDNS, and then used [these ](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7)steps to install PowerDNS-Admin.


Thank you, that makes things more clear.

If you followed those steps exactly, then I think you can edit `config.py` in `/opt/web/powerdns-admin`

You'll want to find the `BIND_ADDRESS` variable and set it to 0.0.0.0.
Such as:
`BIND_ADDRESS = '0.0.0.0'`

Give the powerdns-admin service a restart and you should be able to access it from remote addresses.

**Comment by joshbgosh10592** [comment]
> > I also just re-read your reply. I used the directions I linked to in order to install PowerDNS, and then used [these ](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7)steps to install PowerDNS-Admin.
> 
> Thank you, that makes things more clear.
> 
> If you followed those steps exactly, then I think you can edit `config.py` in `/opt/web/powerdns-admin`
> 
> You'll want to find the `BIND_ADDRESS` variable and set it to 0.0.0.0.
> Such as:
> `BIND_ADDRESS = '0.0.0.0'`
> 
> Give the powerdns-admin service a restart and you should be able to access it from remote addresses.

Sorry for not being clearer before, and thank you!
I made that change, now I'm still getting the same error on a remote machine, but also from the server itself, the curl -I (capital i) is now returning connection refused. I figured the web server probably isn't running, so I run ./run.py (side question, how do I automate the starting of that on reboot? I'm new to CentOS but have scripts running normally on Debian/Ubuntu servers without issue..) and the console threw out: `[josh@PowerDNS powerdns-admin]$ ./run.py 
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from app import app
  File "/opt/web/powerdns-admin/app/__init__.py", line 1, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug'
[josh@PowerDNS powerdns-admin]$ curl -I http://10.9.0.87:9191
curl: (7) Failed connect to 10.9.0.87:9191; Connection refused`

**Comment by ieaster1** [comment]
Likely have to turn off your firewall or add a rule to allow connections to 9191.

If you don't want to have to manually kill the running service, start it, etc, you would be best to set up a [systemd service](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx).

**Comment by joshbgosh10592** [comment]
> Likely have to turn off your firewall or add a rule to allow connections to 9191.
> 
> If you don't want to have to manually kill the running service, start it, etc, you would be best to set up a [systemd service](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx).

It failed to even start the service because of " ModuleNotFoundError: No module named 'werkzeug'" So the server isn't allowing connections on port 9191 because there's nothing listening for it.
I just don't know squat about pip or flask, so this is all new territory for me. Thank you so far!

**Comment by ngoduykhanh** [comment]
Do you still have problem with the setup? It looks like you haven't installed the packages requirements.txt yet, or you didn't set the virtualenv properly. Please follow the guides in the WIKI.

**Comment by joshbgosh10592** [comment]
@ngoduykhanh Hi there!
Yes I do. I followed the guide on the Wiki, but it seems some packages are either out of date, not offered anymore, or CentOS7 doesn't supports some things. I followed the guides exactly as I could.
[https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7](url)

**Comment by ngoduykhanh** [comment]
Are you able to redo the installation and post the full console log here? I am happy to help you troubleshoot. Please hide your sensitive info.

**Comment by joshbgosh10592** [comment]
I can! However, I just reinstalled my hypervisors and lost this VM (wasn't on my backup policy yet, as it wasn't in prod yet... Whoops..
What is the known-working OS and steps you used to create it?

**Comment by joshbgosh10592** [comment]
Ended up blowing it up, redoing it by combining guides from multiple places. However I'm having a flask issue now. Closing this and opening another.
