### ISSUE TITLE
HTTPConnectionPool(host='127.0.0.1', port=8081): Read timed out. (read timeout=10)

### ISSUE THREAD

**Issue by bjo81** [ngoduykhanh/PowerDNS-Admin#576]
When trying to add or modify domain, PowerDNS-Admin gets a read timeout:
`Cannot add domain testfoo.tld. HTTPConnectionPool(host='127.0.0.1', port=8081): Read timed out. (read timeout=10)`

PowerDNS Server 4.2.0

**Comment by bjo81** [comment]
Issue seems to be caused by PowerDNS, as it also has some timeouts answering to a simple curl.

**Comment by bjo81** [comment]
We have a zone with 200 records, does PowerDNS-Admin "change" every record after clicking "apply" also if only one record was changed? This could lead to the timeout, imho.

**Comment by bjo81** [comment]
Increasing timeout helped.

**Comment by tamntm03** [comment]
can i ask how to increase timeout ?
