### ISSUE TITLE
[Help] site_name ignored?

### ISSUE THREAD

**Issue by mattosem** [ngoduykhanh/PowerDNS-Admin#578]
Hi!
I have succesfully installed two different instances of PowerDNS-Admin on one web server.
It's awesome! But now I cant' recognize one from the another one without lookin at URL...
I've changed "site_name" in configuration, but nothing happen.
I'm missing a step?
I'm doing right?
How can I modify site name to recognize them easily?

Thanks!

**Comment by ieaster1** [comment]
site_name isn't ignored per se.  It is used in page titles rather than allowing you to change the branding on the login page and base page.

You could either replace it with the name you'd like or have or pull site_name to be something you can easily change.

**Comment by mattosem** [comment]
Thank you!
I haven't noticed page title because we usually have a lot of tabs opened... Our fault!
How can I modify login page and base page to be sure that they don't be overwrited when we update?

**Comment by ngoduykhanh** [comment]
You can adjust the SITE_NAME value in **Settings > Basic > site_name**. It is used for the page title. If you wish to have a different name in the login page, feel free to edit the source code [here](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/templates/login.html#L25) :-)
