### ISSUE TITLE
Info buttons on items in history do not work on pages other than the first

### ISSUE THREAD

**Issue by trenb** [ngoduykhanh/PowerDNS-Admin#58]
If I click "info" on any history items on page 1, it displays as expected. But once on page 2, the info button does nothing. 

I am on git commit 17be7ba, running on CentOS 7. Please let me know if you need more info or details.

Thanks!

**Comment by trenb** [comment]
As well, if I change the sort order in the history, the info buttons stop working.

**Comment by ivanfilippov** [comment]
Fixed in #65
