### ISSUE TITLE
Change Type (between Native / Master / Slave) after creation

### ISSUE THREAD

**Issue by ReneCD** [ngoduykhanh/PowerDNS-Admin#580]
In order to transfer domains in from other nameservers, we need to start out zones as "slave", but once they are over we want to change them to "native". 

I can't find any way to do this through the interface.  Obviously I can easily do it with a mysql update query, but I think it would be handy to be able to do it through the GUI.  

Am I missing something?

**Comment by ngoduykhanh** [comment]
You can find it on the master branch now. From UI, go to the domain's administrator page to update the type.
