### ISSUE TITLE
Integration on an existing web server

### ISSUE THREAD

**Issue by BigBen2003** [ngoduykhanh/PowerDNS-Admin#581]
Can I use PowerDNS Admin without Docker?

It is planned to run the admin website on an existing lighttp web server.

**Comment by davispuh** [comment]
Of course you can :P It's just a lot more effort configuring everything.


But basically:

1. Install all dependencies.
2. Copy `PowerDNS-Admin/configs/development.py` to `PowerDNS-Admin/config.py` and adjust accordingly.
3. Run `flask assets build` and `flask db upgrade`
4. Use Python WSGI server like Gunicorn (or uWSGI)

If you're using systemd, you can check my example #582 
I just set it up very similar as you want, just using Nginx with proxy_pass to gunicorn.

**Comment by ngoduykhanh** [comment]
Of course, you can. Please take a look at the guides in the WIKI pages.

**Comment by BigBen2003** [comment]
Hi,
sorry for the late response.
The notification mail has been lost in the many spam mails.
The installation of PowerDNS is planned for the new year.
I wish you all a merry Christmas and a happy new year.
