### ISSUE TITLE
Add explicit support for Azure OAuth2 (feature req)

### ISSUE THREAD

**Issue by sshipway** [ngoduykhanh/PowerDNS-Admin#585]
The existing generic Oauth2 support is not able to directly support Azure AAD out of the box.  Specific support for AAD could be done, or the generic configuration expanded to allow it.

Specifically, it needs
* API endpoint function in Azure is /me rather than /userinfo -- this should be a config option
* Returned attributes are userPrincipalName, givenName, surname (mail is returned but should use userPrincipalName if it is empty).  Possibly allow configuration of a list of attributes to search for and use if non-blank?
* There is no code to catch a returned 'error' attribute or error status and this can result in 502 or 404.
* Failure of account creation should raise a visible error and clear the session, rather than just returning to the login page which results in looping

**Comment by sshipway** [comment]
I have coded up most of this myself in a test branch and hope to submit a pull request to add a new AAD support option.  Some documentation on how to configure the Azure end is probably required as well since it is a little obscure what options are needed (scope User.Read and so on)

**Comment by ngoduykhanh** [comment]
Actually we can use LDAP (Active Directory) authentication option to allow users from our Azure AD to access PDA.

I saw your PR #591. Fixed and merged it. Thanks.

**Comment by sshipway** [comment]
The benefit of using SAML or Oauth over LDAP is that with SAML and OAuth you can use the Microsoft MFA and additional security protection afforded by Azure AD.  You also do not need to install an AAD-DS object (which is required to have an LDAPS endpoint).

The benefit of OAuth over SAML is that, although you lose access to the group memberships, OAuth is free but SAML requires a Premium Azure account.
