### ISSUE TITLE
python version and lima package

### ISSUE THREAD

**Issue by SergeyNosko** [ngoduykhanh/PowerDNS-Admin#587]
Documentation states python2.7 is required.
However at 

`$ pip install -r requirements.txt`
we see lima==0.5 requires python 3.3

`  Downloading https://files.pythonhosted.org/packages/6e/28/21c28adcd88cb607f33aa6be8794861da0db089058183e62cfe053d68fe0/lima-0.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/lib/PowerDNS-Admin/flask/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Aq97gA/lima/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Aq97gA/lima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-Aq97gA/lima/pip-egg-info
         cwd: /tmp/pip-install-Aq97gA/lima/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Aq97gA/lima/setup.py", line 12, in <module>
        assert sys.version_info >= (3, 3), 'Python 3.3 oder newer required.'
    AssertionError: Python 3.3 oder newer required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by ngoduykhanh** [comment]
You should use Python 3. We don't maintain the code in Python 2 anymore.
