### ISSUE TITLE
Sample-Configuration for nginx (with SSL) contains wrong socket

### ISSUE THREAD

**Issue by sourcenux** [ngoduykhanh/PowerDNS-Admin#588]
Referring to: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx

"Sample NGINX Configuration file" 
(...)
    proxy_pass            http://unix:/run/powerdns-admin/socket; <--- Working
(..)

"Sample Nginx-Configuration for SSL"
(...)
                proxy_pass              http://unix:/opt/web/powerdns-admin/powerdns-admin.sock:/; <-- Broken. (It is supposed to be the same socket-path on both configuration samples)
(...)

**Comment by Neven1986** [comment]
The config on Wiki page was modified accordingly.

**Comment by sourcenux** [comment]
Thanks
