### ISSUE TITLE
Login does not complete behind a reverse proxy

### ISSUE THREAD

**Issue by pirogoeth** [ngoduykhanh/PowerDNS-Admin#59]
For example, my BIND_ADDRESS is `10.0.0.1`, and I've got a reverse proxy serving it. When login happens and the user is redirected, for some reason, it redirects to `10.0.0.1:9393`. Is there a way to override this behaviour?

**Comment by ivanfilippov** [comment]
Hi @pirogoeth 

My primary environment is behind an nginx proxy and it seems to work for me, can you share a little bit more about your setup?

**Comment by ngoduykhanh** [comment]
I works fine for me with setup of PowerDNS-Admin+Nginx (as reverse proxy).  From my experience, this might caused by the nginx config, can you share your setting?

**Comment by pirogoeth** [comment]
Sorry for the delay -- here's my nginx config:
```
server {
    listen 80;
    listen [::]:80;

    server_name dns.maio.me;
    root /var/www/dns.maio.me;

    include letsencrypt_loc;

    return 301 https://$server_name$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;

    server_name  dns.maio.me;
    root /var/www/dns.maio.me;

    ssl_certificate      /etc/letsencrypt/live/dns.maio.me/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/dns.maio.me/privkey.pem;

    include letsencrypt_loc;

    location / {
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;

        proxy_pass http://10.0.0.1:9393/;
    }
}
```

**Comment by ivanfilippov** [comment]
@pirogoeth 

Sorry for delay. I've replicated your issue, to fix it add the below line to your `location /` block.

`proxy_set_header Host $host;`

**Comment by pirogoeth** [comment]
@ivanfilippov Not sure how I missed that / including proxy_params. Fixed, thanks!

**Comment by davekempe** [comment]
For the benefit of others, I had this problem, and it turned out the time was wrong on the pdns-admin server (running flask). The haproxy in front of it meant the session didn't work, I got a 403 immediately. 
So, if you get this error, check all the servers have the right time!
