### ISSUE TITLE
Does not show history detail info on large domain change

### ISSUE THREAD

**Issue by pprietosanchez** [ngoduykhanh/PowerDNS-Admin#590]
Hello,

how r u?

The issue I found occurs when you click on "info" button in the history page, on one record of an operation made on a large domain (with 1k+ records), nothing happens.

When you do the same action on a record of an operation made on a domain with few records the app show properly de data.

¿Can you help me please?

Thank you very much.

Best regards!!

**Comment by ngoduykhanh** [comment]
The linked PR solves this problem by recording only changes in the history detail.
