### ISSUE TITLE
Module not found: 'werkzeug.middleware'

### ISSUE THREAD

**Issue by ntinti** [ngoduykhanh/PowerDNS-Admin#593]
Can't start latest version (80b6ca19ac6c3c9b70f72da916888bf2faf2d287) because module is missing - I've  tried with install "flaskbb-plugin-proxyfix (1.0)  - Werkzeug ProxyFix" - but doesn't help

```
  File "/usr/local/www/PowerDNS-Admin/powerdnsadmin/__init__.py", line 2, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.middleware'
```

**Comment by ngoduykhanh** [comment]
How did you install the application? Did you install the packages in requirements.txt file?

**Comment by ntinti** [comment]
Hi

Thanks! - I solved it - there was a conflict with the "Werkzeug" install in the base OS
