### ISSUE TITLE
Missing Import

### ISSUE THREAD

**Issue by ntinti** [ngoduykhanh/PowerDNS-Admin#596]
In powerdnsadmin/models/user.py:
`import pyotp`
is missing.

`ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
...
powerdnsadmin/models/user.py", line 86, in verify_totp
    def verify_totp(self, token):
NameError: name 'pyotp' is not defined`

**Comment by ngoduykhanh** [comment]
Nice catch! I missed it in the code refactoring. Fixed it with the above commit.

**Comment by nfantone** [comment]
@ngoduykhanh `user.py` is also missing an `import traceback`.

**Comment by ngoduykhanh** [comment]
Added it. Thanks @nfantone
