### ISSUE TITLE
Can't apply changes - loginKey 'priority' not an Integer or not present

### ISSUE THREAD

**Issue by marnovdm** [ngoduykhanh/PowerDNS-Admin#6]
Running powerdns 3.4.1-4+deb8u3 on Debian 8 and latest version for PowerDNS-Admin console. I can login but when trying to apply changes (add record) I get this error: loginKey 'priority' not an Integer or not present. I noticed something about 'priority' in https://doc.powerdns.com/md/authoritative/upgrading/ but that's only in 3.4.2. Any idea what's going on? Logs show:

[INFO] 10.168.100.2 - - [20/Jan/2016 17:16:38] "POST /domain/mydomain.io/apply HTTP/1.1" 200 -
[ERROR] Cannot apply record changes.
[DEBUG] Key 'priority' not an Integer or not present

Thanks in advance, it looks like a really nice web ui so I hope we can use it!

EDIT: Exact frontend error: '{ "msg": "Key 'priority' not an Integer or not present", "status": "error" }'

**Comment by sirantd** [comment]
Have same problem with all frontends i checked.

Looks like all using modern api, and all now work when i installed powedns 3.4.7 from jessie-backports

Add to /etc/apt/sources.list
deb http://http.debian.net/debian jessie-backports main

apt-get update
apt-get install -t jessie-backports pdns-server (and all other backends, etc)

restart pdns service

**Comment by marnovdm** [comment]
@sirantd thanks, that seems to work! I thought I checked the backports version but I guess I didn't :)
