### ISSUE TITLE
Cannot scroll horizontally

### ISSUE THREAD

**Issue by mlaurense** [ngoduykhanh/PowerDNS-Admin#602]
Long records (e.g. DKIM TXT records aren't wrapped (or have their extraneous content hidden using text-overflow: ellipsis). The content grows too wide (wider than the viewport), and thus there is no way to get to the Save button. Horizontal scrolling is disabled. I can use the tab key to get to the next field and eventually the button, but then there is no sane way to get to the Apply button, because it is to far to the left...

![Schermafbeelding 2019-12-12 om 20 18 56](https://user-images.githubusercontent.com/16759472/70742960-039c7b80-1d1f-11ea-88d3-a81c29a51555.png)

**Comment by ngoduykhanh** [comment]
The previous changes with comment feature broke it. Fixed in the above commit.
