### ISSUE TITLE
Production docker image improvements

### ISSUE THREAD

**Issue by chrisss404** [ngoduykhanh/PowerDNS-Admin#606]
I have two issues with the official docker image

* it is rather big (~327 MB)
* it is not versioned (has only latest tag)

Do you have plans to improve this situation?

In order to reduce the image size you can

* use a smaller base image (e.g.: alpine)
* make use of multi-stage builds to
  * get rid of dev dependencies
  * get rid of build artifacts
  * reduce number of layers

Some examples:

https://hub.docker.com/r/uip9av6y/powerdns-admin (~40MB)
https://hub.docker.com/r/chrisss404/powerdns (~41MB)
https://hub.docker.com/r/aescanero/powerdns-admin (~84MB)
https://hub.docker.com/r/aaronsfoley/pdns-admin (~115MB)

I would be happy to contribute, so please let me know what you think.

**Comment by ngoduykhanh** [comment]
Hi @chrisss404 ,

Thanks for your comment.
Yes, I noticed the size. Unfortunately, I still working on the code refactoring/bug fixes and some other features. I planed to improve the Docker image, docs and add K8s stuff but it is not gonna be soon. 

And yes, You are welcome to contribute to the existing Dockerfile :-).

**Comment by chrisss404** [comment]
@ngoduykhanh added first draft, let me know what you think.

**Comment by ngoduykhanh** [comment]
Hi @chrisss404 .

I've tried your Dockerfile version. It works great. Do you have any further changes?
There is another Dockerfile used for testing purposes. Do you think we should switch it to the same version as production one or just leave it as it is?

**Comment by chrisss404** [comment]
Hi @ngoduykhanh,

No, at the moment I have no further changes regarding the image size.

I have seen the `docker-test` directory but haven't looked at it in detail so I don't know what kind of tests you want to do with it. In case your use case is to connect to powerdns authoritative server and create / update / ... some domains manually for integration testing, I would suggest not to use two separate Dockerfiles, but use the Dockerfile that is used for the production docker image later on. Since in my opinion it is not desirable to keep these two Dockerfiles in sync, however it is really up to your preferences.

For the above use case you can update your `docker-compose-test.yml` as follows (not tested) and remove the whole `docker-test` directory:

    version: "2.1"

    services:

      powerdns-admin:
        build:
          context: .
          dockerfile: docker/Dockerfile
        image: powerdns-admin-test
        container_name: powerdns-admin-test
        ports:
          - "9191:80/tcp"
        networks:
          - default
        depends_on:
          - pdns-server

      pdns-server:
        image: chrisss404/powerdns:4.2.1-authoritative
        depends_on:
          - pdns-server-db
        environment:
          - AUTHORITATIVE_API=yes
          - AUTHORITATIVE_API_KEY=changeme
          - AUTHORITATIVE_DB_HOST=pdns-server-db
          - AUTHORITATIVE_WEBSERVER=yes
          - AUTHORITATIVE_WEBSERVER_PASSWORD=changeme
        networks:
          - default
        ports:
          - "5053:53/tcp"
          - "5053:53/udp"
          - "8081:8081/tcp"

      pdns-server-db:
        image: postgres:12.1-alpine
        environment:
          - POSTGRES_DB=pdns
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_PASSWORD=pdns
          - POSTGRES_USER=pdns
        networks:
          - default

    networks:
      default:

**Comment by ngoduykhanh** [comment]
The `docker-test` is used for running the API unit tests. Basically, it uses the SQLite for a simple DB and runs `pytest` command instead of gunicorn things.

btw, I've merged your PR.
Thanks for your contribution :).

**Comment by chrisss404** [comment]
Oh I see. The above solution wouldn't work for this use case because the production docker image does not contain `pytest`.

Thanks for merging and your great work!
