### ISSUE TITLE
Since refactoring config.py seems to not be valid

### ISSUE THREAD

**Issue by splog123** [ngoduykhanh/PowerDNS-Admin#611]
The refactoring code committed on Dec 2 seems to have broken some stuff:

- ./app is gone
- ./config.py is no longer read

I have a valid ./config.py but SQLAlchemy now wants to connect to MariaDB on localhost which I assume is the hard-coded default.

Is there some docs on what this changes, as every install doc I know out there is now broken and I can't find a way to do a new install.

If it's relevant, docker is not an option.

**Comment by ngoduykhanh** [comment]
Hi,

After refactoring:

- `app` has been renamed to `powerdnsadmin`
- `config.py` is not used anymore. Instead, you can pass any config file using `FLASK_CONF` environment variable

If you look at the guide to [install on Ubuntu](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian) for example, you will see:

```
export FLASK_CONF=../configs/development.py
```

development.py file is similar to your config.py.
If you dont set `FLASK_CONF`, the default config file will be used, it is `powerdnsadmin/default_config.py`

**Comment by splog123** [comment]
Makes sense thanks.

Just my luck, that wiki page is probably the only one I didn't read before creating the issue....
