### ISSUE TITLE
Templates no longer apply correctly on zone creation

### ISSUE THREAD

**Issue by splog123** [ngoduykhanh/PowerDNS-Admin#613]
With latest git on Ubuntu-18.04.3 and pdns 4.1.1-1 I find records in templates no longer apply.

I find only one log entry in journalctl:

Dec 19 14:05:59 powerdnsadmin gunicorn[12843]: [2019-12-19 14:05:59,207] [record.py:288] ERROR - Cannot apply record changes with deleting rrsets step. PDNS error: No SOA found for domain 'example.com.'

**What did I do?**
I have a template named "forward" with the following content:
@   NS   Active    3600   ns1.example.com
and create a zone "example.com" with these settings:
Type="Master"
Template="forward"
SOA-EDIT-API="DEFAULT"

**What happened?**
The zone was created in pdns with the default SOA from pdns.conf
The NS record in the template was not applied
One error was logged to the journal, quoted above

**What did I expect to happen?**
NS record in the template should be applied to the new zone.

**Additional info:**
A similar issue was reported some time ago and recently closed saying the code to call API methods for record changes had changed:
https://github.com/ngoduykhanh/PowerDNS-Admin/issues/338

I believe it is significant that pdns reports no SOA found. Either it is deleted during the rrset update throught he API or the API is called before the SOA has been created,

**Comment by ngoduykhanh** [comment]
Thanks for reporting the issue in detail. I can reproduce it now. The issue happens when we have SOA record enabled in the list of records that allowed to edit. I am gonna do some debug and submit the patch if I find the solution for it.

**Comment by ngoduykhanh** [comment]
The issue should be fixed in the linked commit now.

**Comment by splog123** [comment]
Confirmed working.
