### ISSUE TITLE
Apache/WSGI conf broken

### ISSUE THREAD

**Issue by blakkheimgw** [ngoduykhanh/PowerDNS-Admin#615]
Since I updated the code from the repo, my WSGI conf doesn't seem valid anymore. From the Apache logs :
```
[Thu Dec 19 15:05:47.995776 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906] mod_wsgi (pid=17359): Failed to exec Python script file '/appli/PowerDNS-Admin/powerdnsadmin.wsgi'.
[Thu Dec 19 15:05:47.995930 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906] mod_wsgi (pid=17359): Exception occurred processing WSGI script '/appli/PowerDNS-Admin/powerdnsadmin.wsgi'.
[Thu Dec 19 15:05:47.996097 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906] Traceback (most recent call last):
[Thu Dec 19 15:05:47.996133 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906]   File "/appli/PowerDNS-Admin/powerdnsadmin.wsgi", line 5, in <module>
[Thu Dec 19 15:05:47.996140 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906]     from app import app as application
[Thu Dec 19 15:05:47.996162 2019] [wsgi:error] [pid 17359] [remote 172.30.84.29:56906] ImportError: cannot import name 'app'
```

This conf was taken from the wiki. Is it valid with the new version ?

Regards.

**Comment by ngoduykhanh** [comment]
The app name has been renamed from `app` to `powerdnsadmin` already. So, the WSGI needs to be updated as well.

The old one
```
#!/usr/bin/env python3
import sys
sys.path.insert(0, '/srv/vhosts/superawesomedns.foo.bar')

from app import app as application
```

The import section needs to changed to `from powerdnsadmin import create_app`. You need `application = create_app()` as well I guess.

and don't forget to set the `FLASK_CONF` environment variable point to your config file.

p/s: since the WIKI is open and contributed by several public contributors, it might be outdated as time go.

**Comment by blakkheimgw** [comment]
Thank you for the help.

After changing the line, I've got the following error :

```
[Thu Dec 19 16:06:00.372771 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470] mod_wsgi (pid=13187): Failed to exec Python script file '/appli/PowerDNS-Admin/powerdnsadmin.wsgi'.
[Thu Dec 19 16:06:00.372841 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470] mod_wsgi (pid=13187): Exception occurred processing WSGI script '/appli/PowerDNS-Admin/powerdnsadmin.wsgi'.
[Thu Dec 19 16:06:00.373192 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470] Traceback (most recent call last):
[Thu Dec 19 16:06:00.373225 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470]   File "/appli/PowerDNS-Admin/powerdnsadmin.wsgi", line 5, in <module>
[Thu Dec 19 16:06:00.373247 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470]     from powerdnsadmin import create_app
[Thu Dec 19 16:06:00.373259 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470]   File "/appli/PowerDNS-Admin/powerdnsadmin/__init__.py", line 3, in <module>
[Thu Dec 19 16:06:00.373264 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470]     from flask import Flask
[Thu Dec 19 16:06:00.373282 2019] [wsgi:error] [pid 13187] [remote 172.30.84.29:39470] ImportError: cannot import name 'Flask'
```

Regards.

**Comment by ngoduykhanh** [comment]
Have you installed the package from requirements.txt again?

**Comment by blakkheimgw** [comment]
Yes, I followed the installation procedure as I couldn't find explicit procedure to upgrade. 

Starting the testing daemon with _run.py_ on :9191 port worked. So, it really seems related to the WSGI process.

**Comment by blakkheimgw** [comment]
Hello,

Removing the PowerDNS-Admin and reinstallating from scratch by cloning the repo finally did the trick.

What is the recommandend procedure to update ? Reinstalling from scratch as I did ? Is there a database upgrade needed ?

Thank you.

Regards.

**Comment by ngoduykhanh** [comment]
For now, in order to update, you have to pull the lasted code or release. And update the dependencies:
- Install python libs using pip
- Regenerate the assets
- Upgrade the schema
