### ISSUE TITLE
Apply Changes

### ISSUE THREAD

**Issue by ppcharli** [ngoduykhanh/PowerDNS-Admin#618]
When there are many records (tested with 730), after pressing "Apply changes" the message "Applied changes successfully" does not appear  but the changes do apply.

**Comment by ngoduykhanh** [comment]
Hi,

Is it an intermittent issue or always happen?
I've just tried with applying on a domain that has 1000 records and it quite fast. The popup was shown.

**Comment by ppcharli** [comment]
Always happen

**Comment by ppcharli** [comment]
The domain has option "Auto PTR creation" set

**Comment by ppcharli** [comment]
With the latest version this does not happen anymore.
Thanks
