### ISSUE TITLE
Domain Records UI Issue

### ISSUE THREAD

**Issue by CageU** [ngoduykhanh/PowerDNS-Admin#620]
When adding a very long TXT record such as a DKIM key the Data field does not wrap. It pushes the Edit and Delete buttons off the right hand side of the page and they cannot be accessed without removing the record.

**Comment by ngoduykhanh** [comment]
Hi,
Are you using the latest version of PDA? This issue was reported and fixed already. Following is my example
![Screen Shot 2019-12-20 at 10 05 59 PM](https://user-images.githubusercontent.com/6447444/71263726-134a3e80-2375-11ea-89e8-82d551d6824a.png)

**Comment by CageU** [comment]
I believe I am using the latest version. I’m running it via docker-compose. This morning I ran a git pull to grab the latest code. I then ran docker-compose down and docker-compose up to restart the container. Is there something else I need to do to get it up to date?

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ngoduykhanh** [comment]
If you are using the default `docker-compose.yaml` file from the repo. It is using the image from Docker Hub and should work as expected.
If you run the code without docker, you need to build the assets files.

Please try to use your browser to inspect the cell that has DKMI record and check if `class="length-break"` is there.

**Comment by CageU** [comment]
I believe I am using the default docker-compose.yml from the repo. At least I didn’t change anything other than adding my database connection string to that file.

When I inspect that cell this is the code my browser shows me.

[cid:image001.png@01D5B70F.C30784E0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CageU** [comment]
I figured it out. I had to do a docker-compose pull to make it grab the latest image. It seems to be working great now. I’m still not sure I have everything set up correctly but at least this worked. Docker is pretty new to me so still learning how to run all this. Thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ngoduykhanh** [comment]
Oh right, the image needs to be pulled as well
