### ISSUE TITLE
Timeout of PDA - Large number of zones

### ISSUE THREAD

**Issue by maxok** [ngoduykhanh/PowerDNS-Admin#625]
Hi,

I am running PDA with around 57,000 domains and 300,000 records in total. It has been running well with couple of records, but as soon as I imported the above numbers, I am unable to reach the server and nginx shows 502 Bad Gateway.

I did try indicating BG_DOMAIN_UPDATES = True in default_config.py, restarted, but it never helped.

Log at powerdns-admin.local.error.log shows - *1 upstream prematurely closed connection while reading response header from upstream.

I tried increasing timeouts for nginx for proxy, but it never helped, maybe I should somehow increase gunicorn timeout time?

Best Regards,

Malkhaz

**Comment by maxok** [comment]
We checked the database and seems like we also had to import the domain data into powerdns-admin database. After doing so, dashboard loading is slow a bit, but it does work.

**Comment by PHUGeckonet** [comment]
> We checked the database and seems like we also had to import the domain data into powerdns-admin database. After doing so, dashboard loading is slow a bit, but it does work.

Hi, I have the same issue how did you manage to import data powerdns-admin database?

**Comment by Metrax** [comment]
Did you activated bg_domain_updates in the Basic-Settings and activated the cron job for this?
I didn't check, but maybe the basic settings overrides the config-file setting.
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/update_zones.py

**Comment by PHUGeckonet** [comment]
> Did you activated bg_domain_updates in the Basic-Settings and activated the cron job for this? I didn't check, but maybe the basic settings overrides the config-file setting. https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/update_zones.py

It helps. Thank you :).
