### ISSUE TITLE
Error when applying new changes - Reverse DNS

### ISSUE THREAD

**Issue by BrightSkyz** [ngoduykhanh/PowerDNS-Admin#631]
I have found a bug where if you have pretty_ipv6_ptr enabled in settings -> basic, you encounter the "Error when applying new changes" error when trying to save a reverse DNS zone with an @ record (needed for NS records.) I can't have it enabled as it doesn't seem to let me add the @ NS records for the reverse DNS zone.

**Comment by ngoduykhanh** [comment]
Thanks for reporting the issue. It has been fixed in the referenced commit above.
