### ISSUE TITLE
"." Not auto-added to reverse DNS when saving

### ISSUE THREAD

**Issue by BrightSkyz** [ngoduykhanh/PowerDNS-Admin#632]
On regular zones, when you make a record such as a CNAME, a "." character is appended automatically, this behavior is not consistent with reverse DNS zones and you just encounter an error when trying to save.

**Comment by ngoduykhanh** [comment]
Can you give me your example to reproduce it? It does work for me. Actually we have the code to add the dot for a few record types.
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/models/record.py#L171-L174

**Comment by BrightSkyz** [comment]
The problem record type is PTR, it should also auto add the "." since the data is a domain/subdomain.

**Comment by ngoduykhanh** [comment]
Ok, then it should be an easy fix. I added PTR record type to the list. Please check the referenced commit.
