### ISSUE TITLE
API key not working

### ISSUE THREAD

**Issue by varsh-thaker** [ngoduykhanh/PowerDNS-Admin#651]
I have a PDNS Authoritative Server, Recursor server and Admin on the same server. For some reason when I log in to the Admin portal, I am unable to update the API key for the Authoritative server.

Url for PDNS_Server: http://127.0.0.1:8081/ (I confirmed it is listening on the port and even tried using the API key via terminal with the stock example in PDNS doc and it works).
Server version 4.2.1.

The only thing it does is it refreshes itself when I click update and does nothing.
There is literally nothing in the logs.

I don't know what else to do, can anyone please help?

**Comment by ngoduykhanh** [comment]
If the PDNS API URL, KEY or VERSION setting is missing, you will be redirected to the PDNS setting page automatically, [code](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/routes/dashboard.py#L142-L144). I think the database hasn't been updated for some reason. Can you double-check the database data after clicking the "update" button?

```
mysql> select * from setting where name like "%pdns%";
+----+--------------+------------------------+
| id | name         | value                  |
+----+--------------+------------------------+
| 47 | pdns_api_url | http://127.0.0.1:8081/ |
| 48 | pdns_api_key | changeme               |
| 49 | pdns_version | 4.1.7                  |
+----+--------------+------------------------+
```

**Comment by varsh-thaker** [comment]
Thank you @ngoduykhanh for replying back to me. I checked the database, here is the result:

mysql> select * from setting where name like "%pdns%";
+----+--------------+------------------------+
| id | name         | value                  |
+----+--------------+------------------------+
|  1 | pdns_api_url | http://127.0.0.1:8081/ |
|  2 | pdns_api_key | apikeytry              |
|  3 | pdns_version | 4.2.1                  |
+----+--------------+------------------------+
3 rows in set (0.01 sec)

All of the values are correct so the database is updating. If there is anything else to do please let me know.

**Comment by ngoduykhanh** [comment]
If the database was updated, are you able to access the dashboard page and see the domain list?

**Comment by varsh-thaker** [comment]
Yes, I can access the dashboard page and see the domain list. I am uploading the image in the link for it.
[https://postimg.cc/dDdKw6k1](url)

I also went ahead and made a trial record to see if it is working.
[https://postimg.cc/64dsc6JR](url)

Here is my suspicion.
A random password generator generated my password for the MySQL database.
Password: c9b1B*VlMm%uJ0# (I am going to change it as this is still a test server).

Looking at code linked in the first reply and thinking about the second troubleshooting step, I think a '%' in the password, which is also an escape character in python, is causing a problem.

I tried to change the password to 'pdnsadmindbpass' to confirm if this was causing the issue, but still the same situation.

By the way if anyone is thinking about how I did the DB migration, I changed the line in migrations/env.py
`# As '%' is an escape symbol need to replace any '%' with '%%'
db_url_escaped = current_app.config.get('SQLALCHEMY_DATABASE_URI').replace('%', '%%')
config.set_main_option('sqlalchemy.url', db_url_escaped)`

I am still not able to get the API working but thought maybe this information might help.

**Comment by ngoduykhanh** [comment]
According to your screenshot, everything looks good. I don't really understand your issue here. If there is a problem with the MySQL DB password, you even won't able to login into the PDA.

**Comment by varsh-thaker** [comment]
I have a question. In the case where I am supplying the correct API key and it is storing in MySQL database, what should be the response of PowerDNS Admin?
Should it say that the API was correct or it was successful or something (a message)? Or it just refreshes and shows all fields in green?

**Comment by varsh-thaker** [comment]
In the end, I just reverted to a snapshot and did the final production server config again, and everything works fine. Sorry for not closing this issue early. Thank you for your support @ngoduykhanh
