### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by TheKingOfChaos** [ngoduykhanh/PowerDNS-Admin#658]
Hi is there a better documentation of the API 
the the read me under doc

i am looking for a way to delete a zone

**Comment by ngoduykhanh** [comment]
You can make HTTP `DELETE` request to `/pdnsadmin/zones/<string:domain_name>` to delete a zone.

It is not documented yet. Code is [here](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/routes/api.py#L191)

**Comment by TheKingOfChaos** [comment]
thanks work like a charme
