### ISSUE TITLE
Gravatar

### ISSUE THREAD

**Issue by jallakim** [ngoduykhanh/PowerDNS-Admin#66]
Hi,

Could Gravatar-support be added, as an alternative to uploading avatars?

**Comment by ivanfilippov** [comment]
@ngoduykhanh 

Can you review and assist if you can with this? I have it working here https://github.com/ivanfilippov/PowerDNS-Admin/commit/c22f3424f6b03e66b4b90c3c3a9659924b66cb86

But I feel like there should be a better way than injecting the local variable on user load. I tried to make it a local variable in the model but it doesn't stick around. There's an option to make a custom Jinja filter to do md5 hashes, but I'm not sure if that's a better solution.

**Comment by ngoduykhanh** [comment]
Hi @ivanfilippov ,

Honestly I don't like the idea of adding one more value in the model for this purpose. We better to use Jinja filter, it is more flexible.

Please take a look at my `gravatar` branch with commit 3edf9b01faac33bc5b6574256490f85e3f2c2253

Thanks.

**Comment by ivanfilippov** [comment]
@ngoduykhanh Nice, I like it!

If you'd like, I think you can simplify the code a bit since I don't think we need to check for SSL.  It should be ok and error-free to request gravatars over HTTPS even when PDNS-Admin is loaded over HTTP, as opposed to the other way around which would cause errors.

:+1:

**Comment by ngoduykhanh** [comment]
@ivanfilippov : do you mean forcing to load gravatar with HTTPS even PowerDNS-Admin is loaded over HTTP? If yes, I am ok with that too since we won't waste server resource to check if the connection is SECURE in every request :D

**Comment by ivanfilippov** [comment]
Yes that's what I meant!

**Comment by ngoduykhanh** [comment]
OK, removed the SSL check and added this enhancement into `master` branch. Thanks.
