### ISSUE TITLE
Issue with uWSGI example after code refactoring

### ISSUE THREAD

**Issue by florianbeer** [ngoduykhanh/PowerDNS-Admin#669]
After upgrading PowerDNS-Admin today from a codebase before the refactoring I can't start the application via uwsgi anymore. The [Wiki example](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/uWSGI-example) has `mount = /pdns=run.py` which I think should now be `mount = /pdns=powerdnsadmin:app` but my service refuses to start and gives the following error:
```
unable to load app 0 (mountpoint='/pdns') (callable not found or import error)
```

Does anyone have a pointer what the mount directive should look like with the new code structure? Or am I maybe searching for the wrong thing and this is connected with the additional FLASK_APP and FLASK_CONFIG environment variables that uwsgi needs to access but can't?

Thanks in advance!

**Comment by florianbeer** [comment]
If I leave `mount = /pdns=run.py` and change `callable` to `create_app` the application starts but the logfile gives me another error:
```
TypeError: create_app() takes from 0 to 1 positional arguments but 2 were given
```

**Comment by eht16** [comment]
Put the following glue code in a `run_uwsgi.py`:
```py
#!/usr/bin/env python3

from powerdnsadmin import create_app


# ----------------------------------------------------------------------
def main(*args, **kwargs):
    app = create_app()
    return app(*args, **kwargs)
```
And then use `mount = /pdns=run_uwsgi:main`.

**Comment by florianbeer** [comment]
Thank you very much @eht16 that worked perfectly :+1: 
Do you want to PR the changes or should I?

**Comment by eht16** [comment]
Feel free to do. Fine for me.

**Comment by eht16** [comment]
Please forget the script I posted, it doesn't work properly as on each request, the app is completely started again.

The proper way to start PDNSA using uwsgi is: `wsgi ... --mount /='powerdnsadmin:create_app()'`
No additional script is necessary, `create_app()` is already there.

**Comment by florianbeer** [comment]
Ah, that's one option I didn't try! :man_facepalming: 
Thanks for re-checking. I will amend the Wiki here so people are aware of the change.
