### ISSUE TITLE
Unable to login with OIDC when using uwsgi

### ISSUE THREAD

**Issue by eht16** [ngoduykhanh/PowerDNS-Admin#672]
I'm experiencing a strange problem with OIDC and a uwsgi deployment:

After `/oidc/login`, the redirekt to the provider and the following redirect back to PowerDNS-Admin, I get a 404 for `/oidc/authorized`.

This does happen with uwsgi.
This does *not* happen when starting with the debug Flask server or Gunicorn.

I'm still debugging what's happening but I assume it is related to the way how uwsgi starts the app.
It must be related to https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/services/oidc.py#L30 in some way. It seems the route doesn't get registered properly or in another thread/process or not soon enough. Still not sure what's happening.

This most probably affects also most of the other auth providers which work similarly.

**Comment by sshipway** [comment]
I don't know if this is related, but when creating the Microsoft SAML support for pdnsa I found that the system had to be running on an https URL for it to work.  However since this was done via an nginx proxy, the pdnsa was generating URLs that were http.  I needed to modify the service code to explicitly have `_scheme="https"` for things to work.

**Comment by eht16** [comment]
Unlikely, when using the builtin Flask debug server locally, pdnsa is running on http, redirects to the OIDC provider (KeyCloak in my case) and redirects back properly.
Only when using uwsgi or gunicorn with multiple workers and threads, it breaks.

I'm pretty much sure the OIDC (and probably similar for the other auth modules) code isn't properly initialized in all workers or some state is not shared as expected.

**Comment by eht16** [comment]
After more debugging, it's getting slowly a picture:

with Gunicorn and the Flask debug server, you will get a 404 if the requested URL is "/oidc/authorized". Beginning with the second request, the route is found and everything is fine.
This must be related to the initialization in `powerdnsadmin.index.register_modules()`.

With uwsgi, each request to "/oidc/authorized" ends in a 404 and the initialization code in `powerdnsadmin.index.register_modules()` is called everytime.

I see two problems here:
a) no matter which server you use, the very first call to "/oidc/authorized" everytime ends in a 404.
b) in uwsgi the module registration doesn't work as expected

**Comment by eht16** [comment]
Please scratch the whole uwsgi part, I just started uwsgi the wrong way. Sorry for the spam.

Still, issue a) should still be true: the first request doesn't seem to work right.
I'll continue debugging.

**Comment by ngoduykhanh** [comment]
@eht16,
Regarding your issue a), do you see it happens on other OAuth methods when running via uwsgi ?

**Comment by eht16** [comment]
Yes, it is the same for the other methods.
I opened #678 with a clean and more detailed description of the issue.
This one I spammed with my previous setup problems :).
