### ISSUE TITLE
Microsoft authentication has been broken since last release

### ISSUE THREAD

**Issue by sshipway** [ngoduykhanh/PowerDNS-Admin#673]
The Azure authentication no longer works in the live branch.  It seems that there has been major refactoring and azure.py is missing the function:

    def update_token(token):
        session['azure_token'] = token
        return token

also the last part of azure_authorized should have index.login as the parameter to url_for:

        return redirect(url_for('index.login', _external=True, _scheme='https'))

However this does not completely solve the issue on mysetup, and a successful login is still redirected back to the login screen with a "cannot create user" error.  If I can work out the cause I'll submit a PR

**Comment by sshipway** [comment]
Hmm things are working now.  I blame Azure and AAD.  But the above 2 changes are still required for the main branch.

**Comment by sshipway** [comment]
Submitted PR #674 with the above corrections

**Comment by ngoduykhanh** [comment]
The #674 PR has been merged. Closing the issue.
