### ISSUE TITLE
Comments are not supported on all pdns backends

### ISSUE THREAD

**Issue by sahoahfoa** [ngoduykhanh/PowerDNS-Admin#676]
I am unable to add new records with the v0.2.1 release since the [LMDB backend for pdns](https://doc.powerdns.com/authoritative/backends/lmdb.html) does not support comments. 

This is the error that appears in the log:
`[2020-03-06 07:19:48,490] [record.py:311] ERROR - Cannot apply record changes with adding rrsets step. PDNS error: Hosting backend does not support editing comments.`

For the time being I've edited models/record.py to remove the comments field from new_rrsets / del_rrsets in the apply method.

**Comment by ngoduykhanh** [comment]
The PR got merged. Closing the issue.
