### ISSUE TITLE
bug with auto resize and column size

### ISSUE THREAD

**Issue by hellEVIL-13** [ngoduykhanh/PowerDNS-Admin#688]
bug with auto resize and column size.
even when you set the size in the settings, nothing changes
see pic [https://hellevil.ru/asd.png](url)

**Comment by ngoduykhanh** [comment]
I don't understand the bug. Can you describe a bit more? Which setting are you referring to?

**Comment by hellEVIL-13** [comment]
![Screenshot_2020-03-30 sg noc - PowerDNS](https://user-images.githubusercontent.com/19870084/77899981-08f9e380-7286-11ea-8a5b-34a818e7d32c.png)
The first column is very narrow

**Comment by hellEVIL-13** [comment]
![Screenshot_2020-03-30 sg noc - PowerDNS(1)](https://user-images.githubusercontent.com/19870084/77900114-3b0b4580-7286-11ea-8156-ac72368d9773.png)
The first column is very narrow

**Comment by hellEVIL-13** [comment]
![asd](https://user-images.githubusercontent.com/19870084/77900357-9c331900-7286-11ea-92ef-adcc6bacc3d4.png)
names of records are transferred to the next line

**Comment by ngoduykhanh** [comment]
So it is about the datatable's column auto width, not the size in PDA's setting.
It seems like the text with the dash characters will have a line break automatically.
I don't have any idea for an adjustment atm. An option is to set the width for the first column, e.g. ` { "width": "20%", "targets": 0 }` in the `columnDefs` to make it look better.

**Comment by sshipway** [comment]
I'm having this issue as well, it seems that the table is giving more weight to the Data and Comment columns than to the Name.  Probably the root cause if the length-break class in the custom.css that sets width to 70% -- reduce this to something smaller (maybe 20%?) and it should fix things.  Alternatively add a new class for the Name column similar to this with a larger width as above, but even then the 70% in the length-break will outweigh it.

**Comment by sshipway** [comment]
Yes I've confirmed thatyou can fix this by updating the powerdnsadmin/static/custom/css/custom.css file to set

> .length-break {
>    word-break: break-all !important;
>    width: 30% !important;
>}

**Comment by hellEVIL-13** [comment]
this solution does not work for me :(

**Comment by hellEVIL-13** [comment]
I think the problem is here
./powerdnsadmin/static/node_modules/datatables.net-plugins/integration/jqueryui/dataTables.jqueryui.css

**Comment by sshipway** [comment]
Possibly we're on a different version?  I'm using the latest snapshot of the repo as of a couple of days ago.  I made the change above (to 30%) which fixed it for me (Firefox 75).  Glad to hear you have a working solution thoguh

**Comment by hellEVIL-13** [comment]
I also use the latest version with github

**Comment by hellEVIL-13** [comment]
the latest version corrected the situation thanks
