### ISSUE TITLE
default_domain_table_size

### ISSUE THREAD

**Issue by jallakim** [ngoduykhanh/PowerDNS-Admin#69]
Hi,

Should add ```default_domain_table_size``` that defines the default number of domains to show. Currently this can only be changed by manually adding ```pageLength``` to ```app/templates/dashboard.html```.

**Comment by jallakim** [comment]
(sorry for the spam -- just writing down all impressions/thoughts as I work through the software "for the first time").

**Comment by ngoduykhanh** [comment]
Thanks @jallakim  for your contribution. I merged your PR.

To whom the database was already created. Need to run migration script and insert more fields in the setting table.

```
powerdnsadmin=# INSERT INTO setting(name,value) values('login_ldap_first', 'True');
INSERT 0 1
powerdnsadmin=# INSERT INTO setting(name,value) values('default_record_table_size', '15');
INSERT 0 1
powerdnsadmin=# INSERT INTO setting(name,value) values('default_domain_table_size', '10');
powerdnsadmin=# select * from setting;
 id |           name            | value
----+---------------------------+-------
  1 | maintenance               | False
  2 | fullscreen_layout         | True
  3 | record_helper             | False
  9 | login_ldap_first          | True
 10 | default_record_table_size | 15
 11 | default_domain_table_size | 10
```
