### ISSUE TITLE
Docker can't connect to MySQL

### ISSUE THREAD

**Issue by righter83** [ngoduykhanh/PowerDNS-Admin#693]
I setup the whole stuff on a complete Debian 10 with the guide and everything works.
Now I would use the docker container instead, but it is not possible to connect to the DB with 127.0.0.1:

powerdns_admin | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, `"Can't connect to MySQL server on '127.0.0.1' (115)"`)

or with localhost
`powerdns_admin | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")`

My config (If I use mysql connect from console with these settings its working)
`      - SQLALCHEMY_DATABASE_URI=mysql://powerdnsadmin:XXX@localhost/powerdnsadmin
`

**Comment by ngoduykhanh** [comment]
If you are running PDA on docker, please change the MySQL host address. It not localhost or 127.0.0.1 anymore.

**Comment by righter83** [comment]
Aaa yeah had to change from localhost to the real server IP, and the MariaDB Server also configure to listen on that not on localhost.

Now it's running, thanks.
