### ISSUE TITLE
Connection issue through docker

### ISSUE THREAD

**Issue by fsalle** [ngoduykhanh/PowerDNS-Admin#697]
Hello,

On both Ubuntu 18 and Centos 7, the docker image is not able to connect to mysql database (pdns is working fine btw) whatever  socket, localhost tcp connection or extenal ip I put in the  SQLALCHEMY_DATABASE_URI variable.

Pretty sure I missed something simple. Any hint ?

Thank you,
Frédéric

root@pdns:~/PowerDNS-Admin# docker-compose up
Recreating powerdns_admin ...
Recreating powerdns_admin ... done
Attaching to powerdns_admin
powerdns_admin | Traceback (most recent call last):
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
powerdns_admin |     return fn()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
powerdns_admin |     return _ConnectionFairy._checkout(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
powerdns_admin |     fairy = _ConnectionRecord.checkout(pool)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
powerdns_admin |     rec = pool._do_get()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
powerdns_admin |     return self._create_connection()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
powerdns_admin |     return _ConnectionRecord(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
powerdns_admin |     self.__connect(first_connect_check=True)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
powerdns_admin |     connection = pool._invoke_creator(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
powerdns_admin |     return dialect.connect(*cargs, **cparams)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 482, in connect
powerdns_admin |     return self.dbapi.connect(*cargs, **cparams)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
powerdns_admin |     return Connection(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 179, in __init__
powerdns_admin |     super(Connection, self).__init__(*args, **kwargs2)
powerdns_admin | MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")
powerdns_admin |
powerdns_admin | The above exception was the direct cause of the following exception:
powerdns_admin |
powerdns_admin | Traceback (most recent call last):
powerdns_admin |   File "/usr/bin/flask", line 8, in <module>
powerdns_admin |     sys.exit(main())
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 966, in main
powerdns_admin |     cli.main(prog_name="python -m flask" if as_module else None)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 586, in main
powerdns_admin |     return super(FlaskGroup, self).main(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
powerdns_admin |     rv = self.invoke(ctx)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
powerdns_admin |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
powerdns_admin |     return _process_result(sub_ctx.command.invoke(sub_ctx))
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
powerdns_admin |     return ctx.invoke(self.callback, **ctx.params)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
powerdns_admin |     return callback(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
powerdns_admin |     return f(get_current_context(), *args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
powerdns_admin |     return __ctx.invoke(f, *args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
powerdns_admin |     return callback(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
powerdns_admin |     _upgrade(directory, revision, sql, tag, x_arg)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
powerdns_admin |     f(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
powerdns_admin |     command.upgrade(config, revision, sql=sql, tag=tag)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
powerdns_admin |     script.run_env()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
powerdns_admin |     util.load_python_file(self.dir, "env.py")
powerdns_admin |   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
powerdns_admin |     module = load_module_py(module_id, path)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
powerdns_admin |     spec.loader.exec_module(module)
powerdns_admin |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
powerdns_admin |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
powerdns_admin |   File "migrations/env.py", line 88, in <module>
powerdns_admin |     run_migrations_online()
powerdns_admin |   File "migrations/env.py", line 72, in run_migrations_online
powerdns_admin |     connection = engine.connect()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2209, in connect
powerdns_admin |     return self._connection_cls(self, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
powerdns_admin |     else engine.raw_connection()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
powerdns_admin |     return self._wrap_pool_connect(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
powerdns_admin |     Connection._handle_dbapi_exception_noconnection(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
powerdns_admin |     util.raise_from_cause(sqlalchemy_exception, exc_info)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
powerdns_admin |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
powerdns_admin |     raise value.with_traceback(tb)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
powerdns_admin |     return fn()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
powerdns_admin |     return _ConnectionFairy._checkout(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
powerdns_admin |     fairy = _ConnectionRecord.checkout(pool)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
powerdns_admin |     rec = pool._do_get()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
powerdns_admin |     return self._create_connection()
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
powerdns_admin |     return _ConnectionRecord(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
powerdns_admin |     self.__connect(first_connect_check=True)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
powerdns_admin |     connection = pool._invoke_creator(self)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
powerdns_admin |     return dialect.connect(*cargs, **cparams)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 482, in connect
powerdns_admin |     return self.dbapi.connect(*cargs, **cparams)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
powerdns_admin |     return Connection(*args, **kwargs)
powerdns_admin |   File "/usr/lib/python3.8/site-packages/MySQLdb/connections.py", line 179, in __init__
powerdns_admin |     super(Connection, self).__init__(*args, **kwargs2)
powerdns_admin | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")
powerdns_admin | (Background on this error at: http://sqlalche.me/e/e3q8)
powerdns_admin exited with code 1

root@pdns:~/PowerDNS-Admin# ls -l /run/mysqld/
total 4
-rw-rw---- 1 mysql mysql 5 Apr 13 17:26 mysqld.pid
srwxrwxrwx 1 mysql mysql 0 Apr 13 17:26 mysqld.sock

**Comment by righter83** [comment]
On what IP is your mysql server listening?
netstat -plantu -> search for 3306

what is your config SQLALCHEMY_DATABASE_URI

**Comment by fsalle** [comment]
I manage to make it work on Ubuntu with the external in IP SQLALCHEMY_DATABASE_URI.

Next issue :-)
The Web UI is most of the time stuck on fonts.googleapi.com.
As my system have no internet access (a proxy could be possible but I would prefer to avoid that), is there is parameter/trick to disable external requests ?

Thank you,
Frédéric

**Comment by righter83** [comment]
No not at the moment see [https://github.com/ngoduykhanh/PowerDNS-Admin/issues/680](url)

Or you deconfigure the request manually under templates/base.html
