### ISSUE TITLE
Requests: Global Search. and Optional PTR

### ISSUE THREAD

**Issue by msalemcentrilogic** [ngoduykhanh/PowerDNS-Admin#712]
Hello, 

thank you for this great tool and interface, I really appreciate your work. I have two requests, I do not know if they already exsit. 
1 - Global Search, where I enter a record or an IP and it shows all the results. 
2 - there is only one option for PTR, there are some records that I need to enter - exmaple 30 records, some I need auto PTR other I do not. is there an option for that  ? 

Thanks

**Comment by ngoduykhanh** [comment]
Hi,

> 1 - Global Search, where I enter a record or an IP and it shows all the results.
Yes, we already had it.

2 - there is only one option for PTR, there are some records that I need to enter - exmaple 30 records, some I need auto PTR other I do not. is there an option for that ?
No, we don't have that flexibility. You can try to enable auto-ptr then enter your records that need PRT. Once done, disable auto-ptr and do the rest of records :)

**Comment by msalemcentrilogic** [comment]
Hey there. 
the PTR Part I understand, I guess that something we have to work around. 

however the Global search is there to activate it ? 

Thanks

**Comment by ngoduykhanh** [comment]
You should see it under the Administrator's Global Search menu, in URL http://<domain>/admin/global-search

**Comment by msalemcentrilogic** [comment]
Sorry but I do not see that section or option anywhere ?

**Comment by ngoduykhanh** [comment]
Are you using an old version? This feature has been available since PR #599, v0.2

**Comment by msalemcentrilogic** [comment]
I used This guides to install my system:

**Comment by msalemcentrilogic** [comment]
How do I upgrade ? 

Thanks

**Comment by ngoduykhanh** [comment]
How did you get the source code? If you are running PDA directly on the host system, I guess you can do `git pull`  to get the latest code.

**Comment by msalemcentrilogic** [comment]
I will that .. 

thanks you sir.

**Comment by msalemcentrilogic** [comment]
Seems like git pull game me a bit of porblems, seems like the Python script is failing. 

I would rather build a new server, however you have like migration process to make this simpler.
