### ISSUE TITLE
OpenID Connect name claim issue

### ISSUE THREAD

**Issue by maximumG** [ngoduykhanh/PowerDNS-Admin#713]
First thanks for your work on this PowerDNS admin interface.

I setup OIDC login using the OpenID Connect OAuth tab with Keycloak (settings at the end) but ran into an issue regarding the name claim that is used create a new User in PDNS-Admin.

From the official OIDC specification, the `name` claim is the [full name of a user](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). However PDNS-Admin is using this claim as if it was the [firstname only](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/routes/index.py#L289). As a result the `User` is created with a wrong Firstname (full name in it) and Lastname (empty).

I would rather use the `given_name` and `family_name` claims instead of the name. I can create a pull request with the new code if you'd like ?

OIDC settings with keycloak to reproduce

* Scope: email
* API URL: http://my.kc.home:8080/auth/realms/master/protocol/openid-connect/
* Token URL: http://my.kc.home:8080/auth/realms/master/protocol/openid-connect/token
* Authorize URL: http://my.kc.home:8080/auth/realms/master/protocol/openid-connect/auth

**Comment by ngoduykhanh** [comment]
PR merged. Closing the issue.
