### ISSUE TITLE
Sorting of records

### ISSUE THREAD

**Issue by jallakim** [ngoduykhanh/PowerDNS-Admin#72]
Hi,

Sorting of records should probably take numbers into account. Specially for IPv4 PTR zones.

In the below example, I would expect the first page to be filled with 0-14 (and not 0,1,100-109,11,110).

![Sorting](http://files.jocke.no/b/dump_2016-07-04_18.58.47.png)

**Comment by jallakim** [comment]
Fixed in #73 by implementing the Natural Sort plugin for DataTables.

![Natural Sort](http://files.jocke.no/b/dump_2016-07-04_19.55.41.png)

**Comment by jallakim** [comment]
Only implemented on column 0 (name) and 4 (data) for the domain.html template.

**Comment by ngoduykhanh** [comment]
@jallakim : This is a great enhancement. Thank you for your contribution!
