### ISSUE TITLE
400 Oops! Bad requestCannot add this domain.You may return to the dashboard.

### ISSUE THREAD

**Issue by M33FT** [ngoduykhanh/PowerDNS-Admin#721]
Hi . . . 
Thanks for your great program.
I ran the program with the command **"docker run -d --restart=always -v powerdns-admin:/data -p 9191:80 ngoduykhanh/powerdns-admin:latest"** on the docker.
The inside of the panel shows this error when I want to create a domain: 
**"400 Oops! Bad requestCannot add this domain.You may return to the dashboard."**
I've seen the comments and I think there's a problem with the API settings
but I don't know how to fill these three parts:

+ PDNS API URL
+ PDNS API KEY
+ PDNS VERSION

can you help me, PLZ

**Comment by righter83** [comment]
That is the API config from your PowerDNS API.
First you have to configure that in your PDNS Config https://doc.powerdns.com/authoritative/http-api/index.html

after that you can fill in the fields with your config above

**Comment by M33FT** [comment]
> That is the API config from your PowerDNS API.
> First you have to configure that in your PDNS Config https://doc.powerdns.com/authoritative/http-api/index.html
> 
> after that you can fill in the fields with your config above

Thanks buddy for answering me.
I had previously installed it without Docker and I remember 
that the address "pdns.conf" was in "/etc/powerdns". 
Now in Docker, when I go into Container, where is the pdns.conf address?
Can you tell me exactly where?

**Comment by righter83** [comment]
It's still there!
In The docker container is only the panel, not the dns server itself.

**Comment by M33FT** [comment]
> It's still there!
> In The docker container is only the panel, not the dns server itself.

Ahaaaaa 
I just understood what you mean.
Do you mean I have to install Powerdns on my Host (which is Debian here). it's true?
No need to install Database (MariaDB, MYSQL)? And the database is in the Container itself.it's true ?
I thought everything (PowerDNS + GUI + Database) is all in Conatainer.
I'm sorry, this is the first time I've run this program in Docker, and I didn't know exactly what to do.

**Comment by righter83** [comment]
yes powerdns on debian.
mariadb also.

in the container there is only the panle and the small webserver, you should then also run an NGINX as proxy on your debian. but you don't have to

**Comment by M33FT** [comment]
Thank you for answering me very quickly.
Now I understand what you are saying. 
I had a problem, I will definitely come and ask you lol
Thank you.

**Comment by ngoduykhanh** [comment]
Please take a look at PowerDNS document to see how to set up their web API server and Key. For PDA, you can either use docker or install it directly on the host machine. [WIKI](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki)
