### ISSUE TITLE
" unterminated regular expression literal" after Installation

### ISSUE THREAD

**Issue by sourcenux** [ngoduykhanh/PowerDNS-Admin#722]
Hi,
i recently installed powerdns-admin from the git repository (using this guide: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian ).

After Installation all buttons, that are using Javascript do not work. 

My Webbrowser-Console shows up this messages:

![grafik](https://user-images.githubusercontent.com/29550035/81404822-ab836d00-9136-11ea-8156-c867071ac7b8.png)

Corresponding Lines from main.js:

```
this._config=config;this._dayOfMonthOrdinalParseLenient=new RegExp((this._dayOfMonthOrdinalParse.source||this._ordinalParse.source)+
'|'+/
\d{1,2}/.source);}
```

Solution (Removing the linebreak after '/'):

```
this._config=config;this._dayOfMonthOrdinalParseLenient=new RegExp((this._dayOfMonthOrdinalParse.source||this._ordinalParse.source)+
'|'+/\d{1,2}/.source);}
```

**Comment by sourcenux** [comment]
Browser: Firefox 76.0 (x64).

**Comment by sourcenux** [comment]
I used npm to generate static assets (instead of using yarn, because yarn did not work).

**Comment by ngoduykhanh** [comment]
Please use yarn to install the same package as we listed in [yarn.lock](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/yarn.lock).
