### ISSUE TITLE
MySQLdb._exceptions.OperationalError) (1045, "Access denied for user

### ISSUE THREAD

**Issue by felipe-costa-git-hub** [ngoduykhanh/PowerDNS-Admin#733]
Hello, I am having a problem in the operation of PowerDNS-Admin.
Perform the entire installation as information at https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7
The entire installation process was successful, however, after the command ./run.py I enter the page http://localhost:9191
I'm subjected to the error 
![error-powerdns](https://user-images.githubusercontent.com/62400103/81865339-25a35f80-9544-11ea-86c1-cb468f522a30.PNG)

**Comment by RoeiGanor** [comment]
Did you go through this guide?
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Prepare-MySQL-or-MariaDB-Database-for-PowerDNS-Admin

**Comment by felipe-costa-git-hub** [comment]
Yes, step by step.
The error says that the bank is unable to access the pds user.
Initially I believed it was just the user.
So, I created the user pds in the bunch in the same format as the guide shows, but without success..

**Comment by felipe-costa-git-hub** [comment]
Maybe it will help ....
In the installation process MariaDB-shared was not being found by yum.
So I had to remove what had already been installed from mariadb by yum and installed it again through the MariaDB repository.

**Comment by RoeiGanor** [comment]
Are you able to run these commands:
```
mysql -h localhost -u pda -p <your_password>
use powerdnsadmin;
```
I want to make sure that the problem is not with your SQL server.
Also, what is your connection string?

**Comment by felipe-costa-git-hub** [comment]
Remem bering that I created the user pda after all the installation, because the guide only informs that powerdnsadmin must be created.
Because of this I left the pda user without a password to access mysql.
Do I have to set a password for this user?
![Acess-MariaDB](https://user-images.githubusercontent.com/62400103/81873484-407cd080-9552-11ea-8985-d2c86d74d102.PNG)
![web-powerdns](https://user-images.githubusercontent.com/62400103/81873485-41156700-9552-11ea-809a-eb287a49a14f.PNG)
