### ISSUE TITLE
Fix: IndexError: list index out of range

### ISSUE THREAD

**Issue by trooster** [ngoduykhanh/PowerDNS-Admin#736]
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/0ef132a7be7a3c8b21809c1570a4e8a98a8343c2/powerdnsadmin/routes/domain.py#L109

Line 109:
`if r['comments'] else '',`
gives a "IndexError: list index out of range" error when there are two (or more) records with the same name, and not all records have a comment. This results in a 500 error for the user.

I solved this by changing line 109 to:
`if index < len(r['comments']) else '',`

It doesn't solve the bug as mentioned in the comments:
    # BUG: If we have multiple records with the same name
    # and each record has its own comment, the display of
    # [record-comment] may not consistent because PDNS API
    # returns the rrsets (records, comments) has different
    # order than its database records.
    # TODO:
    #   - Find a way to make it consistent, or
    #   - Only allow one comment for that case

But at least it prevents a fatal error.

If you want I can create a pull request for the change.

**Comment by ngoduykhanh** [comment]
Should be fixed since #739 got merged.
