### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by ymage** [ngoduykhanh/PowerDNS-Admin#746]
Since REMOTE_USER support, I can't logout.

**Comment by ngoduykhanh** [comment]
Do you mean the logout operation from web UI? Wha is the issue with it? Seems work for me.

**Comment by ymage** [comment]
1. I log in with **Remember Me** checked
1. I click on Logout link
1. I am automatically redirected to the /logout route
1. I am automatically redirected to the /login route
1. I am automatically redirected to the /dashboard being already logged in.

The session seems to be kept and not cleared.
The provided PR fixes the case.

**Comment by ngoduykhanh** [comment]
Thanks @ymage for the clarification and PR. I saw the issue now. Merged your PR.
