### ISSUE TITLE
BUG, powerdns-admin lost record when try to add duplicate record

### ISSUE THREAD

**Issue by pprietosanchez** [ngoduykhanh/PowerDNS-Admin#752]
When you try to add a duplicate record by a mistake (for example, add an A record with same name and IP that one existing yet), because the powerdns.admin show an error, and no log on history nothing, but, the first operation that the app does is delete the record, and then tries to create with the same IP twice, and the pdns API trows an error, and the result is that the first record is deleted, and no info on the history about it.

If you want to reproduce, yo can do:

Add an A record (like Name: test, IP 1.2.3.4)
apply the changes
Add another A record with te same values (Name: test, IP 1.2.3.4)
apply the changes

At this moment, powerdns-admin show you an error, cannot add duplicate entry, but the result is that the first record is deleted and there isn't info on log about this operation.

In addition, maybe is well option to record on history the failed operations too.

Thank you so much!

best regards!

**Comment by ngoduykhanh** [comment]
Thanks @pprietosanchez for the clear explanation about the bug. I can see the issue now. Since we are making 2 operations (DEL then ADD), if the ADD operation failed, it doesn't roll back the DEL operation. We need to adjust this flow.

**Comment by pprietosanchez** [comment]
In my oppinion isn't necessary do the deletion of the records, because de powerdns api do the required change when you request de changes.

**Comment by ngoduykhanh** [comment]
The reason why we want to split into 2 operations was to have the "diff" history and avoid sending too much data (the whole domain's records) to the PDNS API.

**Comment by pprietosanchez** [comment]
Ah! OK!

Thank you for the reply @ngoduykhanh

**Comment by karasz** [comment]
Hi @ngoduykhanh,
What are your thoughts about the way this issue should be solved. It seems to me that this issue is serious and needs to be solved. I would be willing to do some work on it but I would like to know your thoughts first.

**Comment by ngoduykhanh** [comment]
In my opinion, because we have 2 separate operations (del & add), if the second operation failed, we have to roll back the first one.
I've created a PR #761 to fix this. Not sure if it is an optimal solution. Please give it try and let me know if you have a better idea.

**Comment by pprietosanchez** [comment]
> In my opinion, because we have 2 separate operations (del & add), if the second operation failed, we have to roll back the first one.
> I've created a PR #761 to fix this. Not sure if it is an optimal solution. Please give it try and let me know if you have a better idea.

Your solution is valid enough and functional, but I think the better solution is to do all operations on only one API call, to do this we don't add a delete record operation on records that its change is add another value (for example, on an A record, add another IP).

With this solution we achieve to delegate on pdns the integrity of the domain records and the diff history is correct yet.

In addition, I think wold be very useful to save failed operations on history, because at troubleshoot time you can compare API calls on pdns logs with our history, or troubleshoot issues with external integrations with powerdns-admin api (jenkins, vra, etc...)

**Comment by ngoduykhanh** [comment]
In an "Apply" operation, there may be multiple types of records, including records with the same name, records to be added, records to be deleted. It not only "_records that its change is add another value_". I don't see an easy way to implement a generic function to take care of those cases.

**Comment by pprietosanchez** [comment]
I haven't seen that part of the source code yet, but I think that the procedure wold be like this (pseudocode):

- Create two arrays, one for rrset to be deleted with an API call to pdns with changetype DELETE (on this example we called it, ARRAY_DELETE ), and another one for rrset to be added/updated with an API call to pdns with changetype UPDATE (on this example we called it, ARRAY_UPDATE )

- look for new records, add to ARRAY_UPDATE

- look for actual records with new values, add these  to ARRAY_UPDATE

- look for records needed to be deleted completely, add these records to ARRAY_DELETE

- look for records with more than one value, needed to delete only some values, add the record with the values except those that want to remove to ARRAY_UPDATE **and add the record to ARRAY_DELETE**

- call API pdns with ARRAY_DELETE
- call API pdns with ARRAY_UPDATE

If the procedure were similar to this, the only one modification to do on it is to ommit the part that is on bold in the previous procedure, and make pdns do this part and treat it an atomical operation, explained:

- Create two arrays, one for rrset to be deleted with an API call to pdns with changetype DELETE (on this example we called it, ARRAY_DELETE ), and another one for rrset to be added/updated with an API call to pdns with changetype UPDATE (on this example we called it, ARRAY_UPDATE )

- look for new records, add to ARRAY_UPDATE

- look for actual records with new values, add to ARRAY_UPDATE

- look for records need to delete completely, add these records to ARRAY_DELETE

- look for records with more than one value, need to delete not only all values, add the record with the values except those that want to remove to ARRAY_UPDATE ** ̶a̶n̶d̶ ̶a̶d̶d̶ ̶t̶h̶e̶ ̶r̶e̶c̶o̶r̶d̶ ̶t̶o̶ ̶A̶R̶R̶A̶Y̶_̶D̶E̶L̶E̶T̶E̶**

- call API pdns with ARRAY_DELETE
- call API pdns with ARRAY_UPDATE


If i'm wrong and the procedure is more complex, tell me this and I will try to read source code for look another alternatives to this.

Thank you so much.

**Comment by Owais-cyber** [comment]
Adding any entry in A record after every time when apply its add again and again domain name whenever changes may apply by apply button.

**Comment by Owais-cyber** [comment]
for example if i add test its become results as test.example.com and after that when we add test2 than the results are as follow.
test.example.com.example.com
test2.example.com
