### ISSUE TITLE
Order record types whan add on domain

### ISSUE THREAD

**Issue by alexpablo** [ngoduykhanh/PowerDNS-Admin#754]
It´s possible to order ascendant record types when add new on domain?
![Records](https://user-images.githubusercontent.com/1921893/84562865-bba2f380-ad57-11ea-9039-b01b5c9e6526.png)

**Comment by ngoduykhanh** [comment]
Which python version are you using? We already had [this code piece](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/models/setting.py#L274-L277) to sort those record types. It looks good on my side.
![Screen Shot 2020-06-20 at 10 06 32](https://user-images.githubusercontent.com/6447444/85189965-fec41000-b2dd-11ea-93b2-c69c1ee4954a.png)

**Comment by alexpablo** [comment]
Python 3.8, works modifying the code:

		def get_forward_records_allow_to_edit(self):
			records = self.get('forward_records_allow_edit')
			f_records = literal_eval(records) if isinstance(records,
															str) else records
			r_name = [r for r in f_records if f_records[r]]
			# Sort alphabetically if python version is smaller than 3.9
			if sys.version_info[0] < 3 or (sys.version_info[0] == 3
										and sys.version_info[1] < 9):
				r_name.sort()
			return r_name
	
		def get_reverse_records_allow_to_edit(self):
			records = self.get('reverse_records_allow_edit')
			r_records = literal_eval(records) if isinstance(records,
															str) else records
			r_name = [r for r in r_records if r_records[r]]
			# Sort alphabetically if python version is smaller than 3.9
			if sys.version_info[0] < 3 or (sys.version_info[0] == 3
										and sys.version_info[1] < 9):
