### ISSUE TITLE
Default TTL

### ISSUE THREAD

**Issue by RoeiGanor** [ngoduykhanh/PowerDNS-Admin#755]
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/5eb2edee2c2faa47aa578d755fb80372fc05d507/powerdnsadmin/templates/domain.html#L246

When I changed the TTL option I noticed that no matter what I put in the TTL there will be always 1-hour selected by default.

I created a pull request to solve this issue by setting the default as your first ttl option.

https://github.com/ngoduykhanh/PowerDNS-Admin/pull/756

**Comment by ngoduykhanh** [comment]
Merged. Thanks for your contribution.
