### ISSUE TITLE
OpenID Auth0 URL Callback is HTTP and not HTTPS 

### ISSUE THREAD

**Issue by rom1pass** [ngoduykhanh/PowerDNS-Admin#759]
Hello,

I have installed PowerDNS-Admin web server using the following script : [how-to-install-powerdns-and-powerdns-admin-on-debian-buster-updated](https://hacksncloud.com/2020/01/02/how-to-install-powerdns-and-powerdns-admin-on-debian-buster-updated/)

Its using Nginx and a flask socket. 

We have configure the server to enable Auth0. The calls seems working but we are having an issue the URL callback given to Auth0 is HTTP but the server is used by nginx in HTTPS. 

Is there any place on the configuration where we should ask the server to use https ? 

Could you help me with that ? 

Here is my powerdns config : 

```
### BASIC APP CONFIG
SALT = '***'
SECRET_KEY = '***'
BIND_ADDRESS = '0.0.0.0'
PORT = 9191
HSTS_ENABLED = False

### DATABASE CONFIG
SQLA_DB_USER = '***'
SQLA_DB_PASSWORD = '***'
SQLA_DB_HOST = '127.0.0.1'
SQLA_DB_NAME = '***'
SQLALCHEMY_TRACK_MODIFICATIONS = True


### DATBASE - MySQL
SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME

### DATABSE - SQLite
# SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'pdns.db')

# SAML Authnetication
SAML_ENABLED = False
```

Here is my NGINX config for the HTTPS server : 
````
server {
  listen 80;

  server_name pdns.***com;
  return 301 https://pdns.***.com$request_uri;
}



server {
  listen 443;
  server_name               pdns.***.com;

  ssl on;
  ssl_certificate /etc/ssl/certs/***.pem; #path to certificate
  ssl_certificate_key /etc/ssl/private/***.key; #path to key

  index                     index.html index.htm index.php;
  root                      /opt/web/powerdns-admin;
  access_log                /var/log/nginx/powerdns-admin.local.access.log combined;
  error_log                 /var/log/nginx/powerdns-admin.local.error.log;

  client_max_body_size              10m;
  client_body_buffer_size           128k;
  proxy_redirect                    off;
  proxy_connect_timeout             90;
  proxy_send_timeout                90;
  proxy_read_timeout                90;
  proxy_buffers                     32 4k;
  proxy_buffer_size                 8k;
  proxy_set_header                  Host $host;
  proxy_set_header                  X-Real-IP $remote_addr;
  proxy_set_header                  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_headers_hash_bucket_size    64;

  location ~ ^/static/  {
    include  /etc/nginx/mime.types;
    root /opt/web/powerdns-admin/powerdnsadmin;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location / {
    proxy_pass            http://unix:/run/powerdns-admin/socket;
    proxy_read_timeout    120;
    proxy_connect_timeout 120;
    proxy_redirect        off;
  }
}
```

**Comment by maximumG** [comment]
Nginx must inform the flask WSGI app that it is available in HTTPS and not HTTP. Thus, you need to set an additional header _X-Forwarded-Proto_ in the nginx config.

Flask is already configured to read these headers and fix the callback URL accordingly : https://github.com/ngoduykhanh/PowerDNS-Admin/blob/0ef132a7be7a3c8b21809c1570a4e8a98a8343c2/powerdnsadmin/__init__.py#L33

**Comment by rom1pass** [comment]
Thanks its working now. 

We got a small issue because the 'preferred-name' was not define with our version of Auth0. 

Could maybe be a great idea to let people select their attribute names. 

I will close the ticket anyway.
