### ISSUE TITLE
Docker image improvements

### ISSUE THREAD

**Issue by PhilipSchmid** [ngoduykhanh/PowerDNS-Admin#783]
Hi @ngoduykhanh,

First of all, thank you very much for this awesome piece of software - it's very helpful!

To be honest, the (initial) configuration of a dockerized PowerDNS-Admin instance seems to be a bit limited (my personal opinion). That's the reason why I would like to ask you whether it would be for you, if I would try to further improve the Docker image setup with the following features and create a PR:

- Direct configuration of the PDNS connection using environment variables
- Direct configuration of a local admin user and adding the option to disable the signup functionality right away (also via environment variables)

This functionality is already present in our organisations' version of a dockerized PowerDNS-Admin: https://github.com/HSRNetwork/docker-powerdns-admin

Please don't get me wrong but before I put afford into such PR I would like to know if these changes are even welcomed and therefore at least get a change to be merged.

Regards,
Philip

**Comment by onedr0p** [comment]
These would be excellent.

**Comment by ngoduykhanh** [comment]
Hi @PhilipSchmid ,
Sorry for the late response. I didn't have much time for this project. Yes, your idea is really good. It will be helpful to automate the provisioning of our infrastructure. Please feel free to submit PR for your idea. Thank you.

**Comment by PhilipSchmid** [comment]
Hi @ngoduykhanh and @onedr0p 

@ngoduykhanh, to be honest I think @onedr0p is absolutely right. Do you think it would be a huge effort for you to implement this features via environment variables directly in the Python code itself? This would probably be the more future prove approach and also fulfill 3rd twelve-factor app rule ([Config](https://12factor.net/config)).

I'm sorry but since I'm not working for the old company anymore, I'm closing this issue for now. If someone wants the described features above, please consider to use https://github.com/HSRNetwork/docker-powerdns-admin.

Thanks & regards,
Philip
