### ISSUE TITLE
pda potentially can remove data if there is a dns syntax error in dns record

### ISSUE THREAD

**Issue by ha36d** [ngoduykhanh/PowerDNS-Admin#786]
Sometimes PDA removes some records, and re-add them in the same request to PowerDNS API (because of canceling an edit in the UI, etc).

The scenario that has caused the issue for me was:
The new_rrsets and del_rrsets are the same (containing some records) except one new record (to be added) in new_rrsets. The new record has a syntax (dns) problem, so PowerDNS rejected it:

Jul 10 14:35:44 *** run.py[2776]: [2020-07-10 14:35:44,583] [record.py:311] ERROR - Cannot apply record changes with adding rrsets step. PDNS error: Record ***.***.com./A '***.***.com.': Parsing record content (try 'pdnsutil check-zone'): while parsing IP address, expected digits at position 0 in '***.***.com.'

But because del_rrsets is not atomic, the whole data in del_rrsets is lost.

suggestion: If the new_rrsets cannot be executed, PDA can roll back del_rrsets.

**Comment by ngoduykhanh** [comment]
Yes, this is what I tried to solve in PR #761 . Feel free to test it out. 
Related issue: #752
