### ISSUE TITLE
Suggestion: Add the option to increment SOA serial on update

### ISSUE THREAD

**Issue by ivanfilippov** [ngoduykhanh/PowerDNS-Admin#8]
Setting kind to SOA-EDIT-API and content to INCEPTION-INCREMENT in the domainmetadata table in PDNS allows API edits to trigger an increment in the SOA serial.

This metadata entry can be enabled via the API by passing in the below JSON during domain creation. 
"soa_edit_api": "INCEPTION-INCREMENT"

This is also editable after domain creation.

Suggestion: add a check-box to allow the user to enable this option during domain creation, or add the ability to modify domain metadata.

**Comment by ngoduykhanh** [comment]
pushed commit a4df1e47fe92504006f9f487ebe1a181e37a3d2a to allow to set SOA-EDIT-API option during domain creation.

**Comment by ivanfilippov** [comment]
Thanks, I'm going to try this out!

**Comment by ivanfilippov** [comment]
This is working great, thanks for the addition!
