### ISSUE TITLE
Use IPv6 address in PTR records

### ISSUE THREAD

**Issue by jallakim** [ngoduykhanh/PowerDNS-Admin#80]
Hi,

Would be far more "user friendly" if IPv6 addresses could be used directly in the "Name" column for IPv6 PTR zones. I'm coming from the BIND-world, where static text-configuration files where used, and having a /32 IPv6 zone it was quite useful to have different sections in the configuration file for each /64 using ```$ORIGIN```.

This is not possible in PowerDNS (afaik, at least), so some kind of simplification would be preferred (since we can't use $ORIGIN or sort the list "as we please"). PTR-records could be made using the ```set-ptr``` feature of the PowerDNS API (as per #43), but even when that feature gets implemented into PowerDNS-Admin, it might be useful to set PTR's manually (e.g. ones that doesn't have forward records).

And even with the "auto PTR" function, you'd still benefit from showing the actual IPv6 address, rather than the cumbersome entries we have today (dotted string from hell).

The logic would happen server-side within PowerDNS-Admin, and the records would still be stored/sent normally (as dotted strings), but would be converted to/from this format before displaying/storing.

Make it an option to disable/enable (so that it can be introduced as a "experimental feature") that is disabled by default. First implementation might have no error-checks, and imply that the user knows what he is doing. Then at some point; do checks if the IPv6 address actually matches the zone we're editing.

**Comment by jallakim** [comment]
I plan to implement this at some point (unless someone beats me to it). Just made the issue to address the issue, and to keep track of it.

**Comment by jallakim** [comment]
Should work with PR #118.

**Comment by jallakim** [comment]
![Pretty IPv6 PTR](http://files.jocke.no/b/dump_2016-08-20_01.17.19.png)

```
root@ns1:~## dig @ns1.foo.bar -x fc00::1 +short
lol.foo.bar.
root@ns1:~## dig @ns1.foo.bar -x fc00::2 +short
kek.foo.bar.
```

**Comment by jallakim** [comment]
@ngoduykhanh *notify*

**Comment by jallakim** [comment]
The code does *no* form of error-checking regarding if the IPv6-address actually is a part of that ip6.arpa-domain. That's left as an exercise for the user (-:

**Comment by jallakim** [comment]
Also, it only works with `NEW_SCHEMA`. 4.0 is released, so I don't see a reason why new features should be implemented using the old method(s).

**Comment by jallakim** [comment]
I left out IPv4 on purpose. I'll probably look into that at some point, but IPv6 PTR's was by far first-priority.

**Comment by ngoduykhanh** [comment]
#118  has been merged.
