### ISSUE TITLE
Link API key to account/user

### ISSUE THREAD

**Issue by RoeiGanor** [ngoduykhanh/PowerDNS-Admin#803]
Currently, when creating a domain, you can link the domain to certain account and add users to ACL.
When you create an API key you grant access to domains.
Let's say i have a team working together and they have an account that has all of their domains, if I give them an API key and later add a domain to the account, I have to manually go and update they key so the team can work against the new domain.

I think it's a good idea to link the API  key to the domains that the account or user has, and this way, whenever account/user permissions are updated, their API key will be updated as well.

**Comment by jbe-dw** [comment]
@RoeiGanor isn't it fixed with your last PR ? This issue could be closed.
