### ISSUE TITLE
Unable to add domain

### ISSUE THREAD

**Issue by gnanasankar** [ngoduykhanh/PowerDNS-Admin#806]
Please help me to fix this issue..

requests.exceptions.ConnectionError: HTTPConnectionPool(host='*', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa125704d90>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by bryanpedini** [comment]
Please provide context...

- PowerDNS (Authoritative / Recursor) version
- PowerDNS-Admin version
- PowerDNS-Admin installation method (directly with Flask, with Apache as proxy, with Apache with Python module (can't recall the name), with Nginx as proxy, with Dockerfile, etc)
- What did you do that caused the error
- Which log file you extracted that error from

Thanks.
