### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by Caez83** [ngoduykhanh/PowerDNS-Admin#809]
Hello i's possible to had an advanced search feature.

The goal will be to find a record or an IP adresse in any zone 

Thanks

**Comment by ngoduykhanh** [comment]
Please use the "Global Search" feature for that.

**Comment by Caez83** [comment]
Thank you i have upgraded my instance and test this feature but we are limited in 100 records
It's possible to add an option for increase this limit ?
