### ISSUE TITLE
Typo in Default-OIDC-Claim for family_name

### ISSUE THREAD

**Issue by iceman91176** [ngoduykhanh/PowerDNS-Admin#812]
The default value for family_name OIDC claim has a trailing space.

https://github.com/ngoduykhanh/PowerDNS-Admin/blob/2044ce473720852ba653b44689699055ad6ab79b/powerdnsadmin/models/setting.py#L93

This leads to an error with OIDC-Login because whitespace is not allowed in key names.

`
  File "/app/powerdnsadmin/routes/index.py", line 290, in login
    oidc_familyname = me[Setting().get('oidc_oauth_last_name')]
KeyError: 'family_name '
`

It could be good idea to trim whitspace from claim-values before writing them to the database.

**Comment by ngoduykhanh** [comment]
Fixed it on the master branch. Thanks for pointing it out.

**Comment by git-noise** [comment]
Hello,

Is it possible the error is still present in the latest docker image? The code in the .py itself seems to be fixed, but the error still occurs, which let me think something is cached somewhere, maybe in a .pyc?

Best,
