### ISSUE TITLE
Hi, how update/check PowerDNS-Admin using Docker?

### ISSUE THREAD

**Issue by kmorales026** [ngoduykhanh/PowerDNS-Admin#826]
Hi, How Can I check what version of PowerDNS-Admin I have installed?, and How Can I update to lastest version?
I am using Docker version..

Thanks!

![image](https://user-images.githubusercontent.com/36080974/95679649-82f21a00-0b91-11eb-9487-b49398111398.png)

**Comment by ngoduykhanh** [comment]
You are using the `latest` tag which is build from `master` branch. In order to update it, just pull again.

**Comment by kmorales026** [comment]
Thanks Ngoduykhanh !, I suppose no need to show version on dashboard..?

**Comment by ngoduykhanh** [comment]
Yes, it would be nice to show the version (commit hash/tag) on the UI. I'll think about it. Thanks.

**Comment by kmorales026** [comment]
thanks bro!,
