### ISSUE TITLE
Feature: DNS Request

### ISSUE THREAD

**Issue by RoeiGanor** [ngoduykhanh/PowerDNS-Admin#827]
I started to design a feature that will give users the ability to request DNS record from domain that they don't own. I think this feature is somewhat big to implement and can be quite controversial so I think it will be a good idea to discuss about it first.

Currently you can only create record under your domain.
Let's say my company own b.a domain, this mean that my customer would receive domains like c.b.a.
Now, if one of my customers want a record on b.a, I either create a new domain with @ record or create the desire record for them on b.a (which they don't have access to). The first method is not a best practice and get you overwhelmed with domains real fast, and the second method is tedious and not self service.

How I see this feature working is by creating a new category of dns request, where a user can request their desired record and then the request will be pending to an approval at the domain owners dashboards (everyone that either on the account that manage it or has specific ACL on it).
Once the dns approved it will be added to the domain like any other record.

After this introduction I would like to hear your opinion about:
- Do you find this feature necessary?
- Will you use it / see a use case for it?
- Do you think this feature should also contain farther management of the approved records (like delete or modify)?

**Comment by terbolous** [comment]
It's not a bad feature, but I personally don't believe it belongs in PowerDNS-Admin.

You'd need to have some sort of user registrations for individual dns registrations and it doesn't suit the current data schema as far as I can see it.

You could fairly easily make a solution for this that talks to the PDNS-Admin

**Comment by ngoduykhanh** [comment]
Hi @RoeiGanor , Thank you for sharing your ideal. But I agree with @terbolous . I don't think there is a big demand for this feature. It is only suitable for some small use cases I think. IMO, we should avoid making the management workflow complicated.
