### ISSUE TITLE
API permission problem

### ISSUE THREAD

**Issue by Caez83** [ngoduykhanh/PowerDNS-Admin#856]
Hi,

An API user can list all zones even if only one domain is listed on the ACL
On the web interface the same user can see only his domain. 

A simple test :
curl -sSfL --stderr - --request GET --header 'Content-Type: application/json' --header 'X-API-Key: API_KEY' --data '' https://dnsadmin/api/v1/servers/localhost/zones

**Comment by RoeiGanor** [comment]
If you change the server from localhost to pdnsadmin then it should give you the correct domains, like it is written here:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/2917c47fd1c78194d3462687b3a31c17c42e308e/powerdnsadmin/routes/api.py#L960

**Comment by Caez83** [comment]
Thank you but i think it's a security issue because any user can use localhost and list any domains 
So I've added 
if server_id == 'pdnsadmin' or server_id == 'localhost':

**Comment by RoeiGanor** [comment]
Well, actually I don't think this is a security breach. Any unauthenticated user can dig/nslookup to a dns server and see what domains/records are configured there, let alone this is an authenticated api.
I think this is a misleading api, not a security problem.

**Comment by jbe-dw** [comment]
I guess that you're expecting this behaviour because you're distributing API keys to limit managers view over the API. It's reasonable to think that you may not want the see all domains on this endpoint because it's a bit disturbing and inconsistent with the idea that a user could list any domain and get an error trying to access it.

In my setup I have set PDNS as a frontend to use API keys to limit user actions to a list of allowed domain. The changes will be made through Terraform to allow them to create A and PTR records when they pop up virtual instances on the delegated domains, so it uses the server/localhost endpoint.

In my opinion it should be consistent accross the two endpoints. If there's no regression I think It's the way to go if it only requires a tiny change in the code.

**Comment by Caez83** [comment]
Yes, it's not a real security issue, but i would like the same view on web interface and on the API. 
It's more difficult to list and dig or nslookup each domain or they need to use an external service.

Some account are used to create acme records for wildcard letsencrypt domain and some script check all the domain right and give error if the domain is not allowed.
Generaly i'm creating an api access for each server which need to generate these entries. 
Before the last release, API and Web access gave the same view.

Generaly on a API view we can see only resources than we're authorized to see or to modify. 
So it's logic to permit Adminstrator or Operator to see any domain but an user don't need to see it. 

```
     if server_id == 'pdnsadmin':
        if g.apikey.role.name not in ['Administrator', 'Operator']:
            domain_obj_list = g.apikey.domains
        else:
            domain_obj_list = Domain.query.all()
        return json.dumps(domain_schema.dump(domain_obj_list)), 200
    else:
        resp = helper.forward_request()
        return resp.content, resp.status_code, resp.headers.items()
```

But if server is not 'pdnsadmin' user can list all domains 
We can see some restriction in the code:

```
@api_bp.route('/pdnsadmin/zones', methods=['GET'])
@api_basic_auth
def api_login_list_zones():
    if current_user.role.name not in ['Administrator', 'Operator']:
        domain_obj_list = get_user_domains()
    else:
        domain_obj_list = Domain.query.all()

    domain_obj_list = [] if domain_obj_list is None else domain_obj_list
    return json.dumps(domain_schema.dump(domain_obj_list)), 200
```
So i think their are missed checks on this release after the API changes.

**Comment by jbe-dw** [comment]
The API is in two parts:

* /pdnsadmin is for managing PDNSA 
* /servers is just proxying requests to the PDNS Server.

Furthermore, these are not the same endpoints:

* server/pdnsadmin/zones returns only zones allowed to the APIKey with their corresponding PDNS Admin id
* server/localhost/* forwards each subpath request to PDNS. 

We can filter the response of PDNS to allowed zones, that would we better thant changing the behavior. 

You can see it does not give the same amount of information:

**api/v1/servers/pdnsadmin/zones**

```json
[
  {
    "id": 1,
    "name": "test.com"
  },
  {
    "id": 2,
    "name": "test.fr"
  },
  {
    "id": 3,
    "name": "test.info"
  }
]
```

**api/v1/servers/localhost/zones**

```json
[ 
 {
    "account": "infra",
    "dnssec": false,
    "edited_serial": 2020120901,
    "id": "test.com.",
    "kind": "Master",
    "last_check": 0,
    "masters": [],
    "name": "dwadm.in.",
    "notified_serial": 2020120901,
    "serial": 2020120901,
    "url": "/api/v1/servers/localhost/zones/test.com."
  },
  {
    "account": "infra",
    "dnssec": false,
    "edited_serial": 2020120702,
    "id": "deverywa.re.",
    "kind": "Master",
    "last_check": 0,
    "masters": [],
    "name": "test.fr.",
    "notified_serial": 2020120702,
    "serial": 2020120702,
    "url": "/api/v1/servers/localhost/zones/test.fr."
  },
  {
    "account": "testing",
    "dnssec": false,
    "edited_serial": 2021010402,
    "id": "test.info.",
    "kind": "Master",
    "last_check": 0,
    "masters": [],
    "name": "test.info.",
    "notified_serial": 2021010402,
    "serial": 2021010402,
    "url": "/api/v1/servers/localhost/zones/test.info."
  }
]
```

**Comment by jbe-dw** [comment]
Provided patch can be used if @ngoduykhanh does not wish to include it.

**Comment by ngoduykhanh** [comment]
I agree with you guys. IMO, the result should be consistent with web UI and API. I merged the patch from @jbe-dw .
