### ISSUE TITLE
Feature Request: FreeIPA/Red Hat iDM authentication integration

### ISSUE THREAD

**Issue by alythemonk** [ngoduykhanh/PowerDNS-Admin#87]
Hello Gents,

Would you consider adding this as an authentication mechanism. I know that most mainstream browsers support this. I think that it would be a great advantage. It could also leverage the password and OTP/MFA capabilities of FreeIPA/iDM. Thanks for considering this. 

Cheers,

ASD.

**Comment by pschiffe** [comment]
You should be able to use ldap auth against FreeIPA.

**Comment by xbulat** [comment]
I confirm, with FreeIPA it works fine.

**Comment by ivanfilippov** [comment]
Seems like this is a non-issue. :smile:  I'm not familiar with FreeIPA, would anyone like to write some Wiki documentation for configuring authentication against it?

Githut doesn't let you do a PR on a Wiki document (as far as I know), but if you fork the project and write a Wiki article in your fork and let us know, either I or @ngoduykhanh can copy the content over to the main projects wiki.

**Comment by pschiffe** [comment]
There is nothing special to it, really. FreeIPA is a collection of services for identity management, where the main component is 389 directory server (ldap). Info about configuration against FreeIPA ldap can be found here https://www.freeipa.org/page/HowTo/LDAP

**Comment by ngoduykhanh** [comment]
@pschiffe : I have never used FreeIPA before. But as you said, FreeIPA is a collection of services for identity management and it has LDAP which PowerDNS-Admin supported already so I don't think it is neccessaray to have extra works, right?

**Comment by pschiffe** [comment]
@ngoduykhanh correct. I would rather focus on #114 which gives you single sign on functionality for in-house providers.

**Comment by ivanfilippov** [comment]
It seems like FreeIPA is already supported.

Closing this issue.
