### ISSUE TITLE
Feature: Show history for a user's zones

### ISSUE THREAD

**Issue by florianbeer** [ngoduykhanh/PowerDNS-Admin#872]
Hi, 
we as a manged service provider would love to have the feature to show our customers the history for their own zones.
At the moment only our admins can view the history for all zones.

Would it be relatively trivial to provide the history link to normal users as well and filter down the records to only those that the user has access to?

**Comment by jodygilbert** [comment]
I agree this would be a very useful feature. Looks like a new field will need to be added to the history table (need to include domain_id). What’s the process for adding fields to tables?

**Comment by jodygilbert** [comment]
I’ve created a PR for this feature: #890 

DNS changes are displayed for the domains the user has access to. They do not see login events as these are not related to a domain. 

There is a configuration option to enable this

**Comment by jodygilbert** [comment]
This is now available in the current version, there is an option under settings to enable the user role to see history of the domains they have access to.
