### ISSUE TITLE
powerdns admin hosting backend does not support editing records

### ISSUE THREAD

**Issue by hagenaarsp** [ngoduykhanh/PowerDNS-Admin#883]
HI guys,

don't know if this is an issue but this is a error is get

powerdns admin hosting backend does not support editing records
I am new to PowerDNS Admin as well to Powerdns 

can any body help

regards

Peter

**Comment by splog123** [comment]
You have not provided any real information that people can use to help you, so I am going to do the only thing I can, and guess.

There is something wrong with your PowerDNS server setup. Whatever method you are using to store data is apparently read-only nd will not allow edits. This makes the PowerDNSAdmin app pretty much useless.

You need to fix your PowerDNS server. How to do that is out of scope for this forum, there are many internet resources and howtos on this subject.
