### ISSUE TITLE
API: enhancement discussion renew API key ?

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [ngoduykhanh/PowerDNS-Admin#886]
Hi, 

API key code is not really clear for me : 

I.e.  We can create api key, affect roles / domains...   the api key is returned  the first time  in plain text (base64 encoded now).

Would it be possible to add a feature that renews the API key?   (instead of deleting / recreating it ?)

Also, I don't understand the point of giving hashed keys when we list all api keys ?
storing hashed password in database is a good thing (for security).. maybe applying it to api keys is also a good thing.
But What am I supposed do with bcrypt hashed api keys ?  
Am I missing something?

Thx for your help/support.
Great job !

**Comment by jodygilbert** [comment]
You can use the base encoded value directly in the X-API-KEY header, no need to encode again. The docs should be updated, it took me a while to work that out. 

I can’t comment on the API reset, not sure how much effort is required.

**Comment by jbe-dw** [comment]
Hello,
I have worked on the APIKey API recently, I can give you more insight about it, but I can't tell you about past design choices. The last changes are applied in the master version (there should be some difference in the last release version).

Currently, yes, you have to delete and recreate. If you look at the api, the design is to access the apikeys via their ids. Your analysis is correct: the key is generated by the server and output in clear text in the response (but base64 encoded in master branch) then only the hash is stored in the database. There is no way to decode the bcrypt hash.

BUT

With the bcrypt library you can check if the clear passphrase you have matches the given hash. This is why it's given in the response. This is also how the server validates your key while it is not stored in clear text.

In a secury point of view it's better. Your passwords are stored this way.

As for the b64 encoding, it was not encoded in the output, but, you need to do it in the header (it's not a technical requirement, just the app design). Someone add API Key support in the guy and just decided on his own to display the already base64 encoded key at creation, so I updated the API to do so and stay coherent (in master branch, not in 0.2.3 and lower).

So you can use the key, that you need to base64 decode to compare with the hash to validate that the key is correct. If you loose it you need to delete and recreate the key. I'm not sure that implementing an update function to regenerate a new key is worth it, even if it would be quite easy to do it.

**Comment by WhatshallIbreaktoday** [comment]
Crystal clear. Thanks for your explanations.
