### ISSUE TITLE
PowerDNS-admin 400 error

### ISSUE THREAD

**Issue by bensaidRayen** [ngoduykhanh/PowerDNS-Admin#891]
![image](https://user-images.githubusercontent.com/48916193/109413214-80f7ee80-79ac-11eb-9e7d-49fa6e33e699.png)
I have a problem when I want to create a domain name I have this error what to do ???
I just followed the commands which are written in the https://hub.docker.com/r/ngoduykhanh/powerdns-admin and then I am a beginner and I do not know how to do?

**Comment by hughesr67** [comment]
Hi, did you get this fixed? I seem to the have the same issue.

**Comment by bensaidRayen** [comment]
hii ! sorry i don't :( Sent from Android deviceLe 12 mars 2021 18:02, hughesr67 ***@***.***> a écrit :
Hi, did you get this fixed? I seem to the have the same issue.
