### ISSUE TITLE
How to replicate username/password from an server to another server automatically?

### ISSUE THREAD

**Issue by kmorales026** [ngoduykhanh/PowerDNS-Admin#895]
Hi, I have 2 Server with PowerDNS-Admin installed, how can I do to replicate Users and Password from an Server to another server automatically?,

**Comment by rytis** [comment]
What DB backend are you using?

**Comment by jbe-dw** [comment]
If the servers are clones (ie ha frontends):
Database replication
SQLITE file rsync

If the servers are not clones and intended to manage different DNS, the only option is dump and import. But consider using external auth like ldap or AD or oauth as a better solution.
