### ISSUE TITLE
Suggestion: dyndns2 support

### ISSUE THREAD

**Issue by ivanfilippov** [ngoduykhanh/PowerDNS-Admin#9]
I'd like to suggest adding 'dyndns2' protocol support. This will allow dynamic updates of DNS entries via third-party software (ddclient and many consumer routers).

I've created a branch [here](https://github.com/ivanfilippov/PowerDNS-Admin/tree/dyndns2_support) that adds this support. I've tested it with ddclient 3.8.1 using the 'dyndns2' protocol and it works well. I'll be rolling this out to replace a portion of my current custom Poweradmin + dynds2 setup to see how well it works with more use.

Current functionality mirrors the DynDNS RA-API described [here](https://help.dyn.com/remote-access-api/perform-update/) except for:
- Only 'Authorization:' header based authentication is supported. The RA-API supports both header and URL based authentication.
- Only one record can be updated per request. The RA-API allows up to 20 records per request.

The return codes have been reduced for simplicity, [here](https://help.dyn.com/remote-access-api/return-codes/) is the RA-API reference. The only return codes used by the new code are:
- noauth: user could not authenticate against the powerdns-admin database
- good: the record was updated successfully
- nochg: the current content of the record matches the proposed update
- 911: error

@ngoduykhanh please review the branch when you have a moment, and if it meets your intentions for this software let me know and I can submit a pull request.  I'd prefer not to maintain it separately from the mainline PowerDNS-Admin, but I will as long as I still have a need for it. :)

**Comment by ngoduykhanh** [comment]
Thanks @ivanfilippov for your suggestion. This feature is good and helpful. I've tried your code, there is a bug which I commented in the in your branch, you can review it again.

I also have some comments below

> Only 'Authorization:' header based authentication is supported. The RA-API supports both header and URL based authentication.

What is missing here? I see both of them work. Actually they are Basic Authentication which can work in URL based or header based.


> Only one record can be updated per request. The RA-API allows up to 20 records per request.
The return codes have been reduced for simplicity, here is the RA-API reference.

Yes, we can make some adjustment to achieve this :). I think you should move almost code in `dyndns_update` function from `view` to `model`. I suggest keeping our `view` short.


> The only return codes used by the new code are:
noauth: user could not authenticate against the powerdns-admin database
good: the record was updated successfully
nochg: the current content of the record matches the proposed update
911: error

You should also add HTTP response code. 401 for **noauth**, 503 for the **error** for example.

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh, I went back to the code you commented on [here](https://github.com/ivanfilippov/PowerDNS-Admin/commit/e6567da8b03509fa21944a08269b477c804ae741#commitcomment-16078694) and I cleaned it up a bit, but I'm not sure I understand what the bug is. To me it seems like if I loop through all the records and append them to the **records** list before applying (whether I modify the record or not), I wouldn't create duplicate records. I'm probably just misunderstanding the bug, can you clarify? The commit is [here](https://github.com/ivanfilippov/PowerDNS-Admin/commit/83b17f3116a8ec023073c51f09064b4fa11da3ed)

Good point about Basic Authentication, I had misunderstood how that worked.

Good point about the view and the model. I will investigate doing that.

As for the response codes (401 for noauth and 503 for error), I investigated that but my testing showed that the dyndns2 implementation in ddclient (I don't have anything else that speaks dyndns2 handy) doesn't support HTTP return codes. Example: if I return a 401 instead of noauth, the ddclient software exits without an error, but if I return a noauth, ddclient tells me that I the authorization information is bad

Test return HTTP 401:
![image](https://cloud.githubusercontent.com/assets/325998/13308569/9758713c-db31-11e5-8544-defc215f2dd5.png)

Test return 'noauth':
![image](https://cloud.githubusercontent.com/assets/325998/13308577/ace68890-db31-11e5-9f60-a9b3fe4f73cc.png)

**Comment by ngoduykhanh** [comment]
> Hi @ngoduykhanh, I went back to the code you commented on [here](https://github.com/ivanfilippov/PowerDNS-Admin/commit/e6567da8b03509fa21944a08269b477c804ae741#commitcomment-16078694) and I cleaned it up a bit, but I'm not sure I understand what the bug is. To me it seems like if I loop through all the records and append them to the **records** list before applying (whether I modify the record or not), I wouldn't create duplicate records. I'm probably just misunderstanding the bug, can you clarify? The commit is [here](https://github.com/ivanfilippov/PowerDNS-Admin/commit/83b17f3116a8ec023073c51f09064b4fa11da3ed)

Sorry @ivanfilippov , I was looking at a difference peace of code, please ignore my previous comment in the code diff. But I see another problem, let me show you with quoted code below.

```python
        for jr in jrecords:
            record = {
                        "name": jr['name'] ,
                        "type": jr['type'],
                        "content": jr['content'],
                        "disabled": jr['disabled'],
                        "ttl": jr['ttl'],
                    }
            if jr['type'] in app.config['RECORDS_ALLOW_EDIT']:
                if jr['name'] == hostname:
                    # found the hostname being requested for update
                    domain_name = domain.name
                    if jr['content'] == myip:
                        # content did not change, return 'nochg'
                        return render_template('dyndns.html', response='nochg')
                    else:
                        # content changed, change the record
                        record['content'] = myip
            records.append(record)
        try:
            r = Record()
            result = r.apply(domain_name, records)
            if result['status'] == 'ok':
                history = History(msg='DynDNS record changes to domain %s' % domain_name, detail=str(records), created_by=current_user.username)
                history.add()
                return render_template('dyndns.html', response='good')
            else:
                return render_template('dyndns.html', response='911')
        except:
            return render_template('dyndns.html', response='911')

````

Your code is trying to search the `hostname` in all zones which user own. If the first zone doesn't contain any records match the `hostname` you posted, `domain_name` variable will be empty and cause the exception in next step (in `result = r.apply(domain_name, records)`).

Also, It isn't good idea to do `apply` for every domain although it doesn't contains the records which you want to update.

> As for the response codes (401 for noauth and 503 for error), I investigated that but my testing showed that the dyndns2 implementation in ddclient (I don't have anything else that speaks dyndns2 handy) doesn't support HTTP return codes. Example: if I return a 401 instead of noauth, the ddclient software exits without an error, but if I return a noauth, ddclient tells me that I the authorization information is bad

Test return HTTP 401:
![image](https://cloud.githubusercontent.com/assets/325998/13308569/9758713c-db31-11e5-8544-defc215f2dd5.png)

Test return 'noauth':
![image](https://cloud.githubusercontent.com/assets/325998/13308577/ace68890-db31-11e5-9f60-a9b3fe4f73cc.png)

It looks like you misunderstand my idea :). 401 and 503 is http response code, not the response content. Will it be ok if you return **noauth** with http code `503`?

as example below, currently we are returning HTTP/1.0 200 OK, it will be better if we have **503** code instead.

```
~ >> curl  "http://khanh:a-wrong-pwd@localhost:9191/nic/update?hostname=a.example.net&myip=1.2.3.2"
badauth
~ >> curl  "http://khanh:a-wrong-pwd@localhost:9191/nic/update?hostname=a.example.net&myip=1.2.3.2" -I
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 7
Server: Werkzeug/0.11.3 Python/2.7.10
Date: Thu, 25 Feb 2016 08:45:52 GMT
```

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh!

Good point about the 501/403 error codes, I've made the change and tested against dhclient and it works.

I've fixed the issue with the update failing if the first found domain isn't the one the user is trying to update.

Please review my branch again. Once these issues are fixed, I will start working on moving the majority of this code into the model.

Also @ngoduykhanh, I want to thank you for patience and guidance as well as the assistance with this contribution!

**Comment by ngoduykhanh** [comment]
Hi @ivanfilippov ,

Your changes look good to me. Now it works as expected :+1: 

Thank you

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh!

I've pushed some changes to my branch to move the dyndns2 login into the model from the view. I've done some preliminary test and it seems to be working well, but I'll be doing more thorough testing over the next few weeks. Please review the code if you get a chance. :smile: 

The latest commit is here: https://github.com/ivanfilippov/PowerDNS-Admin/commit/6fda89a49f6709e0838a14137c1a2dc677e3a29a

**Comment by ngoduykhanh** [comment]
Thanks @ivanfilippov , you changes looks good except a issue with `priority` which I commented in [your link](https://github.com/ivanfilippov/PowerDNS-Admin/commit/6fda89a49f6709e0838a14137c1a2dc677e3a29a)

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh 

Thanks for your feedback! I've fixed the few issues you mentioned, added some extra logging. Also I missed some stuff in my previous testing and found that 'ddclient' does not understand the content of the response if it is not returned in an HTTP 200 response, so I reverted back to using 200 return codes for the dyndns parts of the code.

I'm going to test these changes in my environment for a few days, then submit a PR.

**Comment by ngoduykhanh** [comment]
Hi @ivanfilippov 

How was your test? is everything work fine?

**Comment by ngoduykhanh** [comment]
btw I synced the code to the `new_ui` to branch in commit 39648294b79ba538ec219a2c7f606a2ed029085e. It works as I expected. Let me know your about test.

**Comment by ivanfilippov** [comment]
Hi @ngoduykhanh 

My tests have been going well, I think this is good to go. :smile:

**Comment by ivanfilippov** [comment]
When do you think we should merge `new_ui` into master?

**Comment by ngoduykhanh** [comment]
@ivanfilippov : All good for me so far. I think we can merge it now. Do you still have something need to do with this branch?

**Comment by ivanfilippov** [comment]
No, I think all the functionality from the old ui is in `new_ui` and we can merge. :smile:

**Comment by ngoduykhanh** [comment]
@ivanfilippov : thank you for your confirmation. I've merged it. This issue can be closed also :)
