### ISSUE TITLE
"Account" terminology too close to "User" (as in "User Account"). Suggesting to rename to "Group" or similar

### ISSUE THREAD

**Issue by falz** [ngoduykhanh/PowerDNS-Admin#900]
This is a cosmetic issue. The term **Account** is a group of users. Since the word Account is commonly interchangeable with User (User Account), I would propose this gets renamed to something else to be less confusing.

My suggestions would be:

* User Group
* Group
* Customer (not happy with this one, but it may be what the original author had in mind)

Thoughts?

**Comment by jbe-dw** [comment]
Account is meant for the account field of a PowerDNS Zone and it is where it comes from. It's supposed to be the zone Manager. 
As PowerDNS itself doesn't offer RBAC via its API, it is done in PowerDNS Admin.

As you said it can be considered as a group of allowed user, but in fact it links users to a "PowerDNS" account (which is not a group). PowerDNSAdmin makes the translation.

Changing the terminology here would not stick to PowerDNS term anymore.
