### ISSUE TITLE
Delete does not work after Edit & Save

### ISSUE THREAD

**Issue by cseres3** [ngoduykhanh/PowerDNS-Admin#91]
If you click Edit for a record, then Save for the same record, but do not apply changes and then click Delete for the same record, the record goes into edit mode instead of delete confirmation.

Reproduced always, browser Firefox 47.0.

Expected result: A record deletable always independent of previous actions.

**Comment by ngoduykhanh** [comment]
It is a typo in custom js. Fixed in commit ddb8825852a61f5d59a2d52fa2269b8bbfc61426. Thank for reporting.
