### ISSUE TITLE
pdns or PowerDNS-Admin creates duplicate records

### ISSUE THREAD

**Issue by tingvold** [ngoduykhanh/PowerDNS-Admin#96]
Hi,

I've experienced several times now when using the PowerDNS-Admin GUI that random (at the moment I see no pattern) records are being duplicated. It happens when updating the zone, and it seems to be related to the same name+type tuple.

E.g. having these entries;

```
@ 3600 NS ns1.foo.bar.
@ 3600 NS ns2.foo.bar.
@ 3600 A 10.1.1.1
@ 3600 AAAA fe80::1
lol 3600 A 10.2.2.2
```

Applying changes to that zone (for whatever reason -- adding new, or changing existing records), you could suddenly end up with the following entries;

```
@ 3600 NS ns1.foo.bar.
@ 3600 NS ns2.foo.bar.
@ 3600 A 10.1.1.1
@ 3600 AAAA fe80::1
lol 3600 A 10.2.2.2
lol 3600 A 10.2.2.2
```

.. or ..

```
@ 3600 NS ns1.foo.bar.
@ 3600 NS ns2.foo.bar.
@ 3600 NS ns1.foo.bar.
@ 3600 NS ns2.foo.bar.
@ 3600 A 10.1.1.1
@ 3600 AAAA fe80::1
lol 3600 A 10.2.2.2
```

As mentioned, I'm not sure if it's caused by PowerDNS-Admin or the pdns API. I'll make an issue here to keep track of it, and if there are others who have similar experiences, feel free to chip in.

**Comment by DigiDaz** [comment]
I'm experiencing exactly this now with a postgres backend, then records will not save because it sees a duplicate and sure enough, there it is in the gui.

The same record just keeps reappearing.

**Comment by DigiDaz** [comment]
In fact, I just deleted both instances of it and realised, in my case it is duplicating the first record in the domain.

**Comment by DigiDaz** [comment]
It now seems to create multiple duplicates. Not a word on this in six months from the dev nor indeed a word on the previous one over two years ago!

**Comment by ngoduykhanh** [comment]
It seems related to the old way of applying records in PDA. Although I was not able to reproduce this issue on my side, I've made changes in the latest code to just send actual changes to the PDNS API to avoid unexpected behavior.
