### ISSUE TITLE
API Keys should be linkable to accounts

### ISSUE THREAD

**Issue by jbe-dw** [ngoduykhanh/PowerDNS-Admin#968]
Hello,

I really do not have free time to contribute now. I'm asking, so maybe one would be interested to code it.

I feel frustrated because API Keys are dissociated from accounts. In our enterprise, we are setting up accounts and set it to zones, then add users to the accounts so they are able to manage their domains. But these same users must have an API Key to use with terraform.

Therefore, adding a new zone with an account is not enough. We have to update the API Key then to allow access to the domain.
If we could allow an API key to be linked to accounts, they would not need to be frequently updated as well. We would keep the per domain access though, because if a team needs to share a domain it owns with another one, and given the fact that zones can only have one account, we may not want to have to create a third party "cross team" account.

- Is this idea good or bad ?
- Anyone feels the same about it ?
- Do anyone of the regular contributors can estimate how much effort is needed ?

Regards

**Comment by github-sys-admin** [comment]
the api doesnt even do anything for you its not working as advertised.

**Comment by RGanor** [comment]
Hey @jbe-dw ,
I think this feature is a good idea and can be very useful!
I don't think it will take much to implement such solution.

Let me know if it is still relevant so we can check out how to implement such solution.

**Comment by jbe-dw** [comment]
Hello,

Yes it is. I have written a terraform provider, and my Terraform code solves this instead (Associates zones to an account and computes the equivalent for the API Key).

Yet it would still be easier if the two could be linked somehow, because associating a zone to an account will grant the API Key automatically. There may be several options to do so, but just allowing a key to bind one or several accounts could be cool enough.

I can put some efforts to contribute to this on my evenings.

**Comment by RGanor** [comment]
It will be great if you'll manage to contribute that.
Just to make sure we are on the same page, the things that left to do are:

1) create a new column in api key to contain account_id
2) when changing account domains, look for api keys with the account id and update those as well
3) update the api key UI to choose account to be linked to

Have i forgot any thing?
Please let me know if i could help.

**Comment by jbe-dw** [comment]
1. If you want to allow a key to link to many accounts, you can't just add a field, you want to add a new association table.
2. Once the link is set, you have to retrieve the permission on each API call
3. You indeed need to update the ui to let the users associate the key to the account
4. Create a new endpoint on the API to manage this association
5. The keys that can be linkable must be of "User" type, so changing the key role shall unbind all accounts.

One may think is could be great to have a button to create a key bound to the account on the account edition page. (but it may be a future option because it will add requirements to the other points)

**Comment by jbe-dw** [comment]
I may need help for the UI because I'm not a front dev.

**Comment by RGanor** [comment]
I'll try to help where ever i can.
Also feel free to contact me at parotid.con.0h@icloud.com
