### ISSUE TITLE
Latest Docker Container Untagged

### ISSUE THREAD

**Issue by zhaofengli** [ngoduykhanh/PowerDNS-Admin#972]
The [`latest`](https://hub.docker.com/layers/ngoduykhanh/powerdns-admin/latest/images/sha256-74a4f29e815c9eb14dcba1fb8b794e2548e5df6408b15b557e05078d48902342?context=explore) tag of the official Docker image contains an unreleased version of powerdns-admin, which appears to be 32983635c6bc51d2ca74496aa9cb0cf834fe2563. If it's considered stable, could you tag a new release on GitHub? Thank you!

**Comment by RGanor** [comment]
A new image has been built and released lately.
https://hub.docker.com/r/ngoduykhanh/powerdns-admin

**Comment by zhaofengli** [comment]
Hi, thanks for that! However, my issue is about the opposite: The version isn't tagged _here on GitHub_. I maintain the powerdns-admin package on Nixpkgs and would be great if there is some official indication that the version is stable and ready.

**Comment by RGanor** [comment]
Thank you for the explanation,
Regarding the releases, @ngoduykhanh should tag a new version.

Thanks for the feedback :)
