### ISSUE TITLE
Allow for SSL connection from PowerDNS-Admin to database backend

### ISSUE THREAD

**Issue by albech** [ngoduykhanh/PowerDNS-Admin#976]
Been looking at the documentation and cannot locate anything regarding connecting PowerDNS-Admin with SSL to the database backend. According to SQLAlchemy it should be relatively simple. Many users will be running the database off the host, thus the need for encrypted connection.
Thanks for a great piece of software.
/Thomas

**Comment by steschuser** [comment]
Hello,

yeah, you should be able to add ?ssl=true to the connection string
SQLALCHEMY_DATABASE_URI=mysql://USER:PASS@HOST/DATABASE?ssl=true

Did you try that?
