### ISSUE TITLE
issue with MariaDB Database for PowerDNS Admin

### ISSUE THREAD

**Issue by awsmaythem** [ngoduykhanh/PowerDNS-Admin#977]
hello my issue is a docker container is created with volume (pda-data) and created powerdnsadmin in mariadb database  but nothing is stored in **mariadb**
how can web gui save users and passwords to mariadb database

my os : centos 7
mariadb v10.5
powerdns 4.1.14

**Comment by larslehmann-net** [comment]
Hello,

you need to set the environment variable `SQLALCHEMY_DATABASE_URI` with this `mysql://<mariadb_user>:<mariadb_password>@<mariadb_host>/<mariadb_batabase>`.

Example:
`SQLALCHEMY_DATABASE_URI=mysql://pda:changeme@host.docker.internal/pda`

You can see it also in the [docker-compose.yaml](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docker-compose.yml)

**Comment by awsmaythem** [comment]
thanks
