### ISSUE TITLE
[help / feature request] Importing existing pdns database

### ISSUE THREAD

**Issue by mirko** [ngoduykhanh/PowerDNS-Admin#978]
Hello,

I'm in the process of switching to powerdns-admin as frontend for my rather huge pdns-database which was previously maintained by another frontend.
Fortunately the previous frontend didn't mess with pdns' native layout, so I'm having a clean sql-dump which powerdns happily accepts.
However powerdns-admin seems to maintain a shadow copy of domains - and only creates such entries when creating new domains via its frtonend - hence my question: how to I import my pdns database into powerdns-admin?

I'd have expected some kind of "import" or "sync" button in powerdns-admin, if (amount of) domains/records fetched via pdns' API mismatches powerdns-admin's view - or at least a way of initially importing pdns' database into powerdns-admin, when powerdns-admin's database of domains is empty.

Am I overlooking something or what's the best-practice way when migrating to powerdns-admin?

**Comment by RoeiGanor** [comment]
There is a toggle in the setting of bg_domain_update
As far as i can tell, when it enabled every http get to the domain dashboard it fetch the domains from pdns. When it disabled, a sync button appear in the main dashboard to sync manually
