### ISSUE TITLE
The variable me doesn't include list from oidc userinfo

### ISSUE THREAD

**Issue by benshalev849** [ngoduykhanh/PowerDNS-Admin#983]
I am trying to sync with an sso service, in the userinfo i get from the oidc service there is a list named groups.

When I print the variable me it only prints info like 'Firstname = Ben, Lastname = test, email= example' (in json form).
The only thing out of the available variables that doesn't get printed is the groups variable which is the only variable that isn't a string but a list.

In this list the user has all the associated groups he is assigned to. when i get the info like so:

I need this groups list because when a user connects with oidc the ideal is that it will create an account (if not already existed) with his groups as the names and associate the user to those groups.

So let's say I have user A that the groups he is apart of are "test"
and we have user B that is apart of the groups "test, userB".

This will allow better management of accounts and thus both user A and user B will be able to watch edit and manage domains associated with account test without adding them into the test account manually.

The me variable is defined like so:
`me = json.loads(oidc.get('userinfo').text)`

I only get all the keys and values of keys without multiple values, aka a list.

Is there a way for me to take the data that i get from the oidc userinfo to include the list.

When i print all the values but groups are in the print(i print the value of `me` into a file.). In addition the type of `me` is dict.

The  code:
[github /powerdnsadmin/routes/index.py](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/39cddd3b348d49b6cc9e40bd1bb32229f8a0838f/powerdnsadmin/routes/index.py)

The pull that got merged that includes the adding of groups with oidc:
[Lord gaavs pull](https://github.com/ngoduykhanh/PowerDNS-Admin/pull/800)

**Comment by LordGaav** [comment]
This is hard to debug without knowing exactly (or redacted) what your OIDC token and userinfo responses were. If memory serves me, oidc.get('userinfo') makes a call to your IdP, so make sure that the response actually contains the groups field. At least in Keycloak it's possible to have different fields present in your access token and userinfo.

**Comment by benshalev849** [comment]
> This is hard to debug without knowing exactly (or redacted) what your OIDC token and userinfo responses were. If memory serves me, oidc.get('userinfo') makes a call to your IdP, so make sure that the response actually contains the groups field. At least in Keycloak it's possible to have different fields present in your access token and userinfo.

From what i saw now after a bit of more debugging the response doesn't even contain the groups section.
It only cotains the values that aren't a list.
When i print the response i get something like this:

```
{'sub': '<number>', 'mail': benshalev@gmail.com, 'FirstName': 'Ben', 'LastName': 'Shalev', displayName: 'epickill'}
```

When i print just the .get w/o the .text addition it prints
`<Response[200]>` 

In the sso the media that shows is:
```
'sub': '<number>'
 'mail': benshalev@gmail.com
'FirstName': 'Ben'
'LastName': 'Shalev'
'displayName: 'epickill'
'groups': ['github', 'gitlab', 'google']
```
(all values are examples obviously)

**Comment by LordGaav** [comment]
If the response does not contain the groups key, then I'm assuming that you didn't specify the correct OIDC scope for your IdP token/userinfo request. What scope to specify is hugely dependent on how your IdP is set up. There is no filtering in PowerDNS-Admin on the userinfo as far as a I know; it just uses what your IdP returns.

**Comment by benshalev849** [comment]
> If the response does not contain the groups key, then I'm assuming that you didn't specify the correct OIDC scope for your IdP token/userinfo request. What scope to specify is hugely dependent on how your IdP is set up. There is no filtering in PowerDNS-Admin on the userinfo as far as a I know; it just uses what your IdP returns.

Trying to play around with the supplied scopes to see if any of them supply me with the "groups" variable.

**Comment by benshalev849** [comment]
> > If the response does not contain the groups key, then I'm assuming that you didn't specify the correct OIDC scope for your IdP token/userinfo request. What scope to specify is hugely dependent on how your IdP is set up. There is no filtering in PowerDNS-Admin on the userinfo as far as a I know; it just uses what your IdP returns.
> 
> Trying to play around with the supplied scopes to see if any of them supply me with the "groups" variable.

For some reason no matter what i put in the scope area (even if just random letters) it still gives me the same response that i mentioned above.

**Comment by benshalev849** [comment]
> If the response does not contain the groups key, then I'm assuming that you didn't specify the correct OIDC scope for your IdP token/userinfo request. What scope to specify is hugely dependent on how your IdP is set up. There is no filtering in PowerDNS-Admin on the userinfo as far as a I know; it just uses what your IdP returns.

Figured out a part of the problem.
My IdP didn't allow every client the groups function.
They have enabled the groups function for me and now i get it.

The problem now is that in `the handle_account` function there is a part that it lowers the characters `c for c in account_name.lower()` gives an error:
`'list' objet has no attribute 'lower'`

I will try to figure this problem out on my own by editing and modifiying the code and hopefully it will work at the end!

Ty for your assistance and i hope i will be able to resolve this on my own :D
