### ISSUE TITLE
Domain Template Records

### ISSUE THREAD

**Issue by awsmaythem** [ngoduykhanh/PowerDNS-Admin#984]
Hello
Is there a variable to set in data like ns1.[domain-name] on template for after create new domain it will set on name of domian name?
https://ibb.co/yf9JcbN

**Comment by awsmaythem** [comment]
i tried 
{{ domain.name }}
DOMAIN-NAME
is there i variable to set to domain name

**Comment by RGanor** [comment]
This feature has been added in #960
