### ISSUE TITLE
History information detail unreadable on large changes

### ISSUE THREAD

**Issue by michielvisser** [ngoduykhanh/PowerDNS-Admin#99]
I just added a bunch of records to a domain. When I view the change history details for that edit, it is completely unreadable for humans:

![image](https://cloud.githubusercontent.com/assets/15341393/17393671/87190674-5a25-11e6-88df-440fcc0a864d.png)

System is based on CentOS 7, PowerDNS 3.4.8, latest commit of PowerDNS-admin.

**Comment by ngoduykhanh** [comment]
They are printed in python's json format. Just a matter of displaying.

**Comment by ivanfilippov** [comment]
@ngoduykhanh Are you thinking something like `pprint` (https://docs.python.org/2/library/pprint.html)?

**Comment by jallakim** [comment]
Something like #121?

![Pretty history](http://files.jocke.no/b/dump_2016-08-21_16.25.41.png)
